/*!   GeneXus C# 16_0_0-127771 on 2/27/2020 9:34:48.4
*/
gx.evt.autoSkip = false;
gx.define('br_encountercheckbr_procedurewc', true, function (CmpContext) {
   this.ServerClass =  "br_encountercheckbr_procedurewc" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.setCmpContext(CmpContext);
   this.ReadonlyForm = true;
   this.hasEnterEvent = false;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV65Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.AV51IsAuthorized_Display=gx.fn.getControlValue("vISAUTHORIZED_DISPLAY") ;
      this.AV8BR_EncounterID=gx.fn.getIntegerValue("vBR_ENCOUNTERID",',') ;
      this.AV8BR_EncounterID=gx.fn.getIntegerValue("vBR_ENCOUNTERID",',') ;
      this.AV65Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.AV51IsAuthorized_Display=gx.fn.getControlValue("vISAUTHORIZED_DISPLAY") ;
   };
   this.e11432_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEPAGE", false, null, true, true);
   };
   this.e12432_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", false, null, true, true);
   };
   this.e13432_client=function()
   {
      return this.executeServerEvent("DDO_BR_PROCEDUREID.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e14432_client=function()
   {
      return this.executeServerEvent("DDO_BR_PROCEDURE_PXRADIOTHERAPY.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e15432_client=function()
   {
      return this.executeServerEvent("DDO_BR_PROCEDURE_PXSURGERY.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e19432_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e20432_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,21,22,23,25,27,29,30,32,33];
   this.GXLastCtrlId =33;
   this.GridContainer = new gx.grid.grid(this, 2,"WbpLvl2",12,"Grid","Grid","GridContainer",this.CmpContext,this.IsMasterPage,"br_encountercheckbr_procedurewc",[],false,1,false,true,0,false,false,false,"",0,"px",0,"px","澧炲姞绌虹櫧琛?,true,false,false,null,null,false,"",false,[1,1,1,1],false,0,true,false);
   var GridContainer = this.GridContainer;
   GridContainer.addBitmap("&Display","vDISPLAY",13,0,"px",17,"px",null,"","","ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addSingleLineEdit(139,14,"BR_PROCEDUREID","","","BR_ProcedureID","int",0,"px",18,18,"right",null,[],139,"BR_ProcedureID",true,0,false,false,"Attribute",1,"WWColumn hidden-xs hidden-sm");
   GridContainer.addComboBox(143,15,"BR_PROCEDURE_PXRADIOTHERAPY","","BR_Procedure_PXRadiotherapy","svchar",null,0,true,false,0,"px","WWColumn");
   GridContainer.addComboBox(141,16,"BR_PROCEDURE_PXSURGERY","","BR_Procedure_PXSurgery","svchar",null,0,true,false,0,"px","WWColumn");
   this.GridContainer.emptyText = "";
   this.setGrid(GridContainer);
   this.GRIDPAGINATIONBARContainer = gx.uc.getNew(this, 20, 13, "DVelop_DVPaginationBar", this.CmpContext + "GRIDPAGINATIONBARContainer", "Gridpaginationbar", "GRIDPAGINATIONBAR");
   var GRIDPAGINATIONBARContainer = this.GRIDPAGINATIONBARContainer;
   GRIDPAGINATIONBARContainer.setProp("Enabled", "Enabled", true, "boolean");
   GRIDPAGINATIONBARContainer.setProp("Class", "Class", "PaginationBar", "str");
   GRIDPAGINATIONBARContainer.setProp("ShowFirst", "Showfirst", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowPrevious", "Showprevious", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowNext", "Shownext", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowLast", "Showlast", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("PagesToShow", "Pagestoshow", 5, "num");
   GRIDPAGINATIONBARContainer.setProp("PagingButtonsPosition", "Pagingbuttonsposition", "Right", "str");
   GRIDPAGINATIONBARContainer.setProp("PagingCaptionPosition", "Pagingcaptionposition", "Left", "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridClass", "Emptygridclass", "PaginationBarEmptyGrid", "str");
   GRIDPAGINATIONBARContainer.setProp("SelectedPage", "Selectedpage", "", "char");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageSelector", "Rowsperpageselector", true, "bool");
   GRIDPAGINATIONBARContainer.setDynProp("RowsPerPageSelectedValue", "Rowsperpageselectedvalue", 10, "num");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageOptions", "Rowsperpageoptions", "5:WWP_Rows5,10:WWP_Rows10,20:WWP_Rows20,50:WWP_Rows50", "str");
   GRIDPAGINATIONBARContainer.setProp("First", "First", "First", "str");
   GRIDPAGINATIONBARContainer.setProp("Previous", "Previous", "WWP_PagingPreviousCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Next", "Next", "WWP_PagingNextCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Last", "Last", "Last", "str");
   GRIDPAGINATIONBARContainer.setProp("Caption", "Caption", "<CURRENT_PAGE>椤?<TOTAL_PAGES>椤?璁板綍锛?TOTAL_RECORDS>鏉?, "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridCaption", "Emptygridcaption", "WWP_PagingEmptyGridCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageCaption", "Rowsperpagecaption", "WWP_PagingRowsPerPage", "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV42GridCurrentPage', "vGRIDCURRENTPAGE", 'SetCurrentPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV42GridCurrentPage=UC.GetCurrentPage();gx.fn.setControlValue("vGRIDCURRENTPAGE",UC.ParentObject.AV42GridCurrentPage); });
   GRIDPAGINATIONBARContainer.setProp("PageCount", "Pagecount", '', "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV44GridRecordCount', "vGRIDRECORDCOUNT", 'SetRecordCount');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV44GridRecordCount=UC.GetRecordCount();gx.fn.setControlValue("vGRIDRECORDCOUNT",UC.ParentObject.AV44GridRecordCount); });
   GRIDPAGINATIONBARContainer.addV2CFunction('AV43GridPageSize', "vGRIDPAGESIZE", 'SetPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV43GridPageSize=UC.GetPage();gx.fn.setControlValue("vGRIDPAGESIZE",UC.ParentObject.AV43GridPageSize); });
   GRIDPAGINATIONBARContainer.setProp("Visible", "Visible", true, "bool");
   GRIDPAGINATIONBARContainer.setC2ShowFunction(function(UC) { UC.show(); });
   GRIDPAGINATIONBARContainer.addEventHandler("ChangePage", this.e11432_client);
   GRIDPAGINATIONBARContainer.addEventHandler("ChangeRowsPerPage", this.e12432_client);
   this.setUserControl(GRIDPAGINATIONBARContainer);
   this.DDO_BR_PROCEDUREIDContainer = gx.uc.getNew(this, 24, 13, "BootstrapDropDownOptions", this.CmpContext + "DDO_BR_PROCEDUREIDContainer", "Ddo_br_procedureid", "DDO_BR_PROCEDUREID");
   var DDO_BR_PROCEDUREIDContainer = this.DDO_BR_PROCEDUREIDContainer;
   DDO_BR_PROCEDUREIDContainer.setProp("Class", "Class", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_PROCEDUREIDContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_PROCEDUREIDContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_PROCEDUREIDContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_PROCEDUREIDContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_PROCEDUREIDContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_PROCEDUREIDContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_PROCEDUREIDContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_PROCEDUREIDContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_PROCEDUREIDContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_PROCEDUREIDContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_PROCEDUREIDContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_PROCEDUREIDContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_PROCEDUREIDContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_PROCEDUREIDContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_PROCEDUREIDContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_PROCEDUREIDContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_PROCEDUREIDContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_PROCEDUREIDContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_PROCEDUREIDContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_PROCEDUREIDContainer.addV2CFunction('AV39DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_PROCEDUREIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV39DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV39DDO_TitleSettingsIcons); });
   DDO_BR_PROCEDUREIDContainer.addV2CFunction('AV17BR_ProcedureIDTitleFilterData', "vBR_PROCEDUREIDTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_PROCEDUREIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV17BR_ProcedureIDTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_PROCEDUREIDTITLEFILTERDATA",UC.ParentObject.AV17BR_ProcedureIDTitleFilterData); });
   DDO_BR_PROCEDUREIDContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_PROCEDUREIDContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_PROCEDUREIDContainer.addEventHandler("OnOptionClicked", this.e13432_client);
   this.setUserControl(DDO_BR_PROCEDUREIDContainer);
   this.DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer = gx.uc.getNew(this, 26, 25, "BootstrapDropDownOptions", this.CmpContext + "DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer", "Ddo_br_procedure_pxradiotherapy", "DDO_BR_PROCEDURE_PXRADIOTHERAPY");
   var DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer = this.DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer;
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("Class", "Class", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.addV2CFunction('AV39DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.addC2VFunction(function(UC) { UC.ParentObject.AV39DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV39DDO_TitleSettingsIcons); });
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.addV2CFunction('AV25BR_Procedure_PXRadiotherapyTitleFilterData', "vBR_PROCEDURE_PXRADIOTHERAPYTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25BR_Procedure_PXRadiotherapyTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_PROCEDURE_PXRADIOTHERAPYTITLEFILTERDATA",UC.ParentObject.AV25BR_Procedure_PXRadiotherapyTitleFilterData); });
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.addEventHandler("OnOptionClicked", this.e14432_client);
   this.setUserControl(DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer);
   this.DDO_BR_PROCEDURE_PXSURGERYContainer = gx.uc.getNew(this, 28, 25, "BootstrapDropDownOptions", this.CmpContext + "DDO_BR_PROCEDURE_PXSURGERYContainer", "Ddo_br_procedure_pxsurgery", "DDO_BR_PROCEDURE_PXSURGERY");
   var DDO_BR_PROCEDURE_PXSURGERYContainer = this.DDO_BR_PROCEDURE_PXSURGERYContainer;
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("Class", "Class", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_PROCEDURE_PXSURGERYContainer.addV2CFunction('AV39DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_PROCEDURE_PXSURGERYContainer.addC2VFunction(function(UC) { UC.ParentObject.AV39DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV39DDO_TitleSettingsIcons); });
   DDO_BR_PROCEDURE_PXSURGERYContainer.addV2CFunction('AV21BR_Procedure_PXSurgeryTitleFilterData', "vBR_PROCEDURE_PXSURGERYTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_PROCEDURE_PXSURGERYContainer.addC2VFunction(function(UC) { UC.ParentObject.AV21BR_Procedure_PXSurgeryTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_PROCEDURE_PXSURGERYTITLEFILTERDATA",UC.ParentObject.AV21BR_Procedure_PXSurgeryTitleFilterData); });
   DDO_BR_PROCEDURE_PXSURGERYContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_PROCEDURE_PXSURGERYContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_PROCEDURE_PXSURGERYContainer.addEventHandler("OnOptionClicked", this.e15432_client);
   this.setUserControl(DDO_BR_PROCEDURE_PXSURGERYContainer);
   this.WORKWITHPLUSUTILITIES1Container = gx.uc.getNew(this, 31, 25, "DVelop_WorkWithPlusUtilities", this.CmpContext + "WORKWITHPLUSUTILITIES1Container", "Workwithplusutilities1", "WORKWITHPLUSUTILITIES1");
   var WORKWITHPLUSUTILITIES1Container = this.WORKWITHPLUSUTILITIES1Container;
   WORKWITHPLUSUTILITIES1Container.setProp("Class", "Class", "", "char");
   WORKWITHPLUSUTILITIES1Container.setProp("Enabled", "Enabled", true, "boolean");
   WORKWITHPLUSUTILITIES1Container.setProp("Width", "Width", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Height", "Height", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Visible", "Visible", true, "bool");
   WORKWITHPLUSUTILITIES1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(WORKWITHPLUSUTILITIES1Container);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEGRIDHEADER",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"GRIDTABLEWITHPAGINATIONBAR",grid:0};
   GXValidFnc[10]={ id: 10, fld:"",grid:0};
   GXValidFnc[11]={ id: 11, fld:"",grid:0};
   GXValidFnc[13]={ id:13 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDISPLAY",gxz:"ZV49Display",gxold:"OV49Display",gxvar:"AV49Display",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV49Display=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV49Display=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vDISPLAY",row || gx.fn.currentGridRowImpl(12),gx.O.AV49Display,gx.O.AV64Display_GXI)},c2v:function(){gx.O.AV64Display_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV49Display=this.val()},val:function(row){return gx.fn.getGridControlValue("vDISPLAY",row || gx.fn.currentGridRowImpl(12))},val_GXI:function(row){return gx.fn.getGridControlValue("vDISPLAY_GXI",row || gx.fn.currentGridRowImpl(12))}, gxvar_GXI:'AV64Display_GXI',nac:gx.falseFn};
   GXValidFnc[14]={ id:14 ,lvl:2,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_PROCEDUREID",gxz:"Z139BR_ProcedureID",gxold:"O139BR_ProcedureID",gxvar:"A139BR_ProcedureID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A139BR_ProcedureID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z139BR_ProcedureID=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("BR_PROCEDUREID",row || gx.fn.currentGridRowImpl(12),gx.O.A139BR_ProcedureID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A139BR_ProcedureID=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("BR_PROCEDUREID",row || gx.fn.currentGridRowImpl(12),',')},nac:gx.falseFn};
   GXValidFnc[15]={ id:15 ,lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_PROCEDURE_PXRADIOTHERAPY",gxz:"Z143BR_Procedure_PXRadiotherapy",gxold:"O143BR_Procedure_PXRadiotherapy",gxvar:"A143BR_Procedure_PXRadiotherapy",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.A143BR_Procedure_PXRadiotherapy=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z143BR_Procedure_PXRadiotherapy=Value},v2c:function(row){gx.fn.setGridComboBoxValue("BR_PROCEDURE_PXRADIOTHERAPY",row || gx.fn.currentGridRowImpl(12),gx.O.A143BR_Procedure_PXRadiotherapy);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A143BR_Procedure_PXRadiotherapy=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_PROCEDURE_PXRADIOTHERAPY",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn};
   GXValidFnc[16]={ id:16 ,lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_PROCEDURE_PXSURGERY",gxz:"Z141BR_Procedure_PXSurgery",gxold:"O141BR_Procedure_PXSurgery",gxvar:"A141BR_Procedure_PXSurgery",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.A141BR_Procedure_PXSurgery=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z141BR_Procedure_PXSurgery=Value},v2c:function(row){gx.fn.setGridComboBoxValue("BR_PROCEDURE_PXSURGERY",row || gx.fn.currentGridRowImpl(12),gx.O.A141BR_Procedure_PXSurgery);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A141BR_Procedure_PXSurgery=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_PROCEDURE_PXSURGERY",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn};
   GXValidFnc[17]={ id: 17, fld:"",grid:0};
   GXValidFnc[18]={ id: 18, fld:"",grid:0};
   GXValidFnc[19]={ id: 19, fld:"HTML_GRIDPAGINATIONBAR",grid:0};
   GXValidFnc[21]={ id: 21, fld:"",grid:0};
   GXValidFnc[22]={ id: 22, fld:"",grid:0};
   GXValidFnc[23]={ id: 23, fld:"HTML_BOTTOMAUXILIARCONTROLS",grid:0};
   GXValidFnc[25]={ id:25 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_PROCEDUREIDTITLECONTROLIDTOREPLACE",gxz:"ZV18ddo_BR_ProcedureIDTitleControlIdToReplace",gxold:"OV18ddo_BR_ProcedureIDTitleControlIdToReplace",gxvar:"AV18ddo_BR_ProcedureIDTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV18ddo_BR_ProcedureIDTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV18ddo_BR_ProcedureIDTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_PROCEDUREIDTITLECONTROLIDTOREPLACE",gx.O.AV18ddo_BR_ProcedureIDTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV18ddo_BR_ProcedureIDTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_PROCEDUREIDTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[27]={ id:27 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_PROCEDURE_PXRADIOTHERAPYTITLECONTROLIDTOREPLACE",gxz:"ZV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace",gxold:"OV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace",gxvar:"AV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_PROCEDURE_PXRADIOTHERAPYTITLECONTROLIDTOREPLACE",gx.O.AV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_PROCEDURE_PXRADIOTHERAPYTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[29]={ id:29 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_PROCEDURE_PXSURGERYTITLECONTROLIDTOREPLACE",gxz:"ZV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace",gxold:"OV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace",gxvar:"AV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_PROCEDURE_PXSURGERYTITLECONTROLIDTOREPLACE",gx.O.AV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_PROCEDURE_PXSURGERYTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[30]={ id:30 ,lvl:0,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_ENCOUNTERID",gxz:"Z19BR_EncounterID",gxold:"O19BR_EncounterID",gxvar:"A19BR_EncounterID",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.A19BR_EncounterID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z19BR_EncounterID=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("BR_ENCOUNTERID",gx.O.A19BR_EncounterID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A19BR_EncounterID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("BR_ENCOUNTERID",',')},nac:gx.falseFn};
   this.declareDomainHdlr( 30 , function() {
   });
   GXValidFnc[32]={ id:32 ,lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDBY",gxz:"ZV14OrderedBy",gxold:"OV14OrderedBy",gxvar:"AV14OrderedBy",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV14OrderedBy=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV14OrderedBy=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDBY",gx.O.AV14OrderedBy,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV14OrderedBy=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vORDEREDBY",',')},nac:gx.falseFn};
   GXValidFnc[33]={ id:33 ,lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDDSC",gxz:"ZV15OrderedDsc",gxold:"OV15OrderedDsc",gxvar:"AV15OrderedDsc",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV15OrderedDsc=gx.lang.booleanValue(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV15OrderedDsc=gx.lang.booleanValue(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDDSC",gx.O.AV15OrderedDsc,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV15OrderedDsc=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getControlValue("vORDEREDDSC")},nac:gx.falseFn};
   this.ZV49Display = "" ;
   this.OV49Display = "" ;
   this.Z139BR_ProcedureID = 0 ;
   this.O139BR_ProcedureID = 0 ;
   this.Z143BR_Procedure_PXRadiotherapy = "" ;
   this.O143BR_Procedure_PXRadiotherapy = "" ;
   this.Z141BR_Procedure_PXSurgery = "" ;
   this.O141BR_Procedure_PXSurgery = "" ;
   this.AV18ddo_BR_ProcedureIDTitleControlIdToReplace = "" ;
   this.ZV18ddo_BR_ProcedureIDTitleControlIdToReplace = "" ;
   this.OV18ddo_BR_ProcedureIDTitleControlIdToReplace = "" ;
   this.AV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace = "" ;
   this.ZV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace = "" ;
   this.OV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace = "" ;
   this.AV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace = "" ;
   this.ZV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace = "" ;
   this.OV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace = "" ;
   this.A19BR_EncounterID = 0 ;
   this.Z19BR_EncounterID = 0 ;
   this.O19BR_EncounterID = 0 ;
   this.AV14OrderedBy = 0 ;
   this.ZV14OrderedBy = 0 ;
   this.OV14OrderedBy = 0 ;
   this.AV15OrderedDsc = false ;
   this.ZV15OrderedDsc = false ;
   this.OV15OrderedDsc = false ;
   this.AV42GridCurrentPage = 0 ;
   this.AV39DDO_TitleSettingsIcons = {Default:"",Default_GXI:"",Filtered:"",Filtered_GXI:"",SortedASC:"",SortedASC_GXI:"",SortedDSC:"",SortedDSC_GXI:"",FilteredSortedASC:"",FilteredSortedASC_GXI:"",FilteredSortedDSC:"",FilteredSortedDSC_GXI:"",OptionSortASC:"",OptionSortASC_GXI:"",OptionSortDSC:"",OptionSortDSC_GXI:"",OptionApplyFilter:"",OptionApplyFilter_GXI:"",OptionFilteringData:"",OptionFilteringData_GXI:"",OptionCleanFilters:"",OptionCleanFilters_GXI:"",SelectedOption:"",SelectedOption_GXI:"",MultiselOption:"",MultiselOption_GXI:"",MultiselSelOption:"",MultiselSelOption_GXI:""} ;
   this.AV18ddo_BR_ProcedureIDTitleControlIdToReplace = "" ;
   this.AV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace = "" ;
   this.AV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace = "" ;
   this.A19BR_EncounterID = 0 ;
   this.AV14OrderedBy = 0 ;
   this.AV15OrderedDsc = false ;
   this.AV8BR_EncounterID = 0 ;
   this.AV49Display = "" ;
   this.A139BR_ProcedureID = 0 ;
   this.A143BR_Procedure_PXRadiotherapy = "" ;
   this.A141BR_Procedure_PXSurgery = "" ;
   this.AV65Pgmname = "" ;
   this.AV51IsAuthorized_Display = false ;
   this.Events = {"e11432_client": ["GRIDPAGINATIONBAR.CHANGEPAGE", true] ,"e12432_client": ["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", true] ,"e13432_client": ["DDO_BR_PROCEDUREID.ONOPTIONCLICKED", true] ,"e14432_client": ["DDO_BR_PROCEDURE_PXRADIOTHERAPY.ONOPTIONCLICKED", true] ,"e15432_client": ["DDO_BR_PROCEDURE_PXSURGERY.ONOPTIONCLICKED", true] ,"e19432_client": ["ENTER", true] ,"e20432_client": ["CANCEL", true]};
   this.EvtParms["REFRESH"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV51IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'sPrefix'},{av:'AV18ddo_BR_ProcedureIDTitleControlIdToReplace',fld:'vDDO_BR_PROCEDUREIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace',fld:'vDDO_BR_PROCEDURE_PXRADIOTHERAPYTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace',fld:'vDDO_BR_PROCEDURE_PXSURGERYTITLECONTROLIDTOREPLACE',pic:''},{ctrl:'GRID',prop:'Rows'},{av:'AV65Pgmname',fld:'vPGMNAME',pic:''},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''}],[{av:'AV17BR_ProcedureIDTitleFilterData',fld:'vBR_PROCEDUREIDTITLEFILTERDATA',pic:''},{av:'AV25BR_Procedure_PXRadiotherapyTitleFilterData',fld:'vBR_PROCEDURE_PXRADIOTHERAPYTITLEFILTERDATA',pic:''},{av:'AV21BR_Procedure_PXSurgeryTitleFilterData',fld:'vBR_PROCEDURE_PXSURGERYTITLEFILTERDATA',pic:''},{ctrl:'BR_PROCEDUREID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PROCEDUREID","Title")',ctrl:'BR_PROCEDUREID',prop:'Title'},{ctrl:'BR_PROCEDURE_PXRADIOTHERAPY'},{ctrl:'BR_PROCEDURE_PXSURGERY'},{av:'AV42GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV43GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV44GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'AV51IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'gx.fn.getCtrlProperty("vDISPLAY","Visible")',ctrl:'vDISPLAY',prop:'Visible'}]];
   this.EvtParms["START"] = [[{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV65Pgmname',fld:'vPGMNAME',pic:''},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'}],[{ctrl:'GRID',prop:'Rows'},{av:'this.DDO_BR_PROCEDUREIDContainer.TitleControlIdToReplace',ctrl:'DDO_BR_PROCEDUREID',prop:'TitleControlIdToReplace'},{av:'AV18ddo_BR_ProcedureIDTitleControlIdToReplace',fld:'vDDO_BR_PROCEDUREIDTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_PROCEDUREIDTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_PROCEDUREIDTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.TitleControlIdToReplace',ctrl:'DDO_BR_PROCEDURE_PXRADIOTHERAPY',prop:'TitleControlIdToReplace'},{av:'AV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace',fld:'vDDO_BR_PROCEDURE_PXRADIOTHERAPYTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_PROCEDURE_PXRADIOTHERAPYTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_PROCEDURE_PXRADIOTHERAPYTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_PROCEDURE_PXSURGERYContainer.TitleControlIdToReplace',ctrl:'DDO_BR_PROCEDURE_PXSURGERY',prop:'TitleControlIdToReplace'},{av:'AV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace',fld:'vDDO_BR_PROCEDURE_PXSURGERYTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_PROCEDURE_PXSURGERYTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_PROCEDURE_PXSURGERYTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'gx.fn.getCtrlProperty("BR_ENCOUNTERID","Visible")',ctrl:'BR_ENCOUNTERID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vORDEREDBY","Visible")',ctrl:'vORDEREDBY',prop:'Visible'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'gx.fn.getCtrlProperty("vORDEREDDSC","Visible")',ctrl:'vORDEREDDSC',prop:'Visible'},{av:'AV39DDO_TitleSettingsIcons',fld:'vDDO_TITLESETTINGSICONS',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''}]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_ProcedureIDTitleControlIdToReplace',fld:'vDDO_BR_PROCEDUREIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace',fld:'vDDO_BR_PROCEDURE_PXRADIOTHERAPYTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace',fld:'vDDO_BR_PROCEDURE_PXSURGERYTITLECONTROLIDTOREPLACE',pic:''},{av:'AV65Pgmname',fld:'vPGMNAME',pic:''},{av:'AV51IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'sPrefix'},{av:'this.GRIDPAGINATIONBARContainer.SelectedPage',ctrl:'GRIDPAGINATIONBAR',prop:'SelectedPage'}],[]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_ProcedureIDTitleControlIdToReplace',fld:'vDDO_BR_PROCEDUREIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace',fld:'vDDO_BR_PROCEDURE_PXRADIOTHERAPYTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace',fld:'vDDO_BR_PROCEDURE_PXSURGERYTITLECONTROLIDTOREPLACE',pic:''},{av:'AV65Pgmname',fld:'vPGMNAME',pic:''},{av:'AV51IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'sPrefix'},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}],[{ctrl:'GRID',prop:'Rows'}]];
   this.EvtParms["DDO_BR_PROCEDUREID.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_ProcedureIDTitleControlIdToReplace',fld:'vDDO_BR_PROCEDUREIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace',fld:'vDDO_BR_PROCEDURE_PXRADIOTHERAPYTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace',fld:'vDDO_BR_PROCEDURE_PXSURGERYTITLECONTROLIDTOREPLACE',pic:''},{av:'AV65Pgmname',fld:'vPGMNAME',pic:''},{av:'AV51IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'sPrefix'},{av:'this.DDO_BR_PROCEDUREIDContainer.ActiveEventKey',ctrl:'DDO_BR_PROCEDUREID',prop:'ActiveEventKey'}],[{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_PROCEDUREIDContainer.SortedStatus',ctrl:'DDO_BR_PROCEDUREID',prop:'SortedStatus'},{av:'AV17BR_ProcedureIDTitleFilterData',fld:'vBR_PROCEDUREIDTITLEFILTERDATA',pic:''},{av:'AV25BR_Procedure_PXRadiotherapyTitleFilterData',fld:'vBR_PROCEDURE_PXRADIOTHERAPYTITLEFILTERDATA',pic:''},{av:'AV21BR_Procedure_PXSurgeryTitleFilterData',fld:'vBR_PROCEDURE_PXSURGERYTITLEFILTERDATA',pic:''},{ctrl:'BR_PROCEDUREID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PROCEDUREID","Title")',ctrl:'BR_PROCEDUREID',prop:'Title'},{ctrl:'BR_PROCEDURE_PXRADIOTHERAPY'},{ctrl:'BR_PROCEDURE_PXSURGERY'},{av:'AV42GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV43GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV44GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'AV51IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'gx.fn.getCtrlProperty("vDISPLAY","Visible")',ctrl:'vDISPLAY',prop:'Visible'}]];
   this.EvtParms["DDO_BR_PROCEDURE_PXRADIOTHERAPY.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_ProcedureIDTitleControlIdToReplace',fld:'vDDO_BR_PROCEDUREIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace',fld:'vDDO_BR_PROCEDURE_PXRADIOTHERAPYTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace',fld:'vDDO_BR_PROCEDURE_PXSURGERYTITLECONTROLIDTOREPLACE',pic:''},{av:'AV65Pgmname',fld:'vPGMNAME',pic:''},{av:'AV51IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'sPrefix'},{av:'this.DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.ActiveEventKey',ctrl:'DDO_BR_PROCEDURE_PXRADIOTHERAPY',prop:'ActiveEventKey'}],[{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_PROCEDURE_PXRADIOTHERAPYContainer.SortedStatus',ctrl:'DDO_BR_PROCEDURE_PXRADIOTHERAPY',prop:'SortedStatus'},{av:'AV17BR_ProcedureIDTitleFilterData',fld:'vBR_PROCEDUREIDTITLEFILTERDATA',pic:''},{av:'AV25BR_Procedure_PXRadiotherapyTitleFilterData',fld:'vBR_PROCEDURE_PXRADIOTHERAPYTITLEFILTERDATA',pic:''},{av:'AV21BR_Procedure_PXSurgeryTitleFilterData',fld:'vBR_PROCEDURE_PXSURGERYTITLEFILTERDATA',pic:''},{ctrl:'BR_PROCEDUREID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PROCEDUREID","Title")',ctrl:'BR_PROCEDUREID',prop:'Title'},{ctrl:'BR_PROCEDURE_PXRADIOTHERAPY'},{ctrl:'BR_PROCEDURE_PXSURGERY'},{av:'AV42GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV43GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV44GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'AV51IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'gx.fn.getCtrlProperty("vDISPLAY","Visible")',ctrl:'vDISPLAY',prop:'Visible'}]];
   this.EvtParms["DDO_BR_PROCEDURE_PXSURGERY.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_ProcedureIDTitleControlIdToReplace',fld:'vDDO_BR_PROCEDUREIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV26ddo_BR_Procedure_PXRadiotherapyTitleControlIdToReplace',fld:'vDDO_BR_PROCEDURE_PXRADIOTHERAPYTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_BR_Procedure_PXSurgeryTitleControlIdToReplace',fld:'vDDO_BR_PROCEDURE_PXSURGERYTITLECONTROLIDTOREPLACE',pic:''},{av:'AV65Pgmname',fld:'vPGMNAME',pic:''},{av:'AV51IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'sPrefix'},{av:'this.DDO_BR_PROCEDURE_PXSURGERYContainer.ActiveEventKey',ctrl:'DDO_BR_PROCEDURE_PXSURGERY',prop:'ActiveEventKey'}],[{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_PROCEDURE_PXSURGERYContainer.SortedStatus',ctrl:'DDO_BR_PROCEDURE_PXSURGERY',prop:'SortedStatus'},{av:'AV17BR_ProcedureIDTitleFilterData',fld:'vBR_PROCEDUREIDTITLEFILTERDATA',pic:''},{av:'AV25BR_Procedure_PXRadiotherapyTitleFilterData',fld:'vBR_PROCEDURE_PXRADIOTHERAPYTITLEFILTERDATA',pic:''},{av:'AV21BR_Procedure_PXSurgeryTitleFilterData',fld:'vBR_PROCEDURE_PXSURGERYTITLEFILTERDATA',pic:''},{ctrl:'BR_PROCEDUREID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PROCEDUREID","Title")',ctrl:'BR_PROCEDUREID',prop:'Title'},{ctrl:'BR_PROCEDURE_PXRADIOTHERAPY'},{ctrl:'BR_PROCEDURE_PXSURGERY'},{av:'AV42GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV43GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV44GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'AV51IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'gx.fn.getCtrlProperty("vDISPLAY","Visible")',ctrl:'vDISPLAY',prop:'Visible'}]];
   this.EvtParms["GRID.LOAD"] = [[{av:'AV51IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'A139BR_ProcedureID',fld:'BR_PROCEDUREID',pic:'ZZZZZZZZZZZZZZZZZZ'}],[{av:'AV49Display',fld:'vDISPLAY',pic:''},{av:'gx.fn.getCtrlProperty("vDISPLAY","Tooltiptext")',ctrl:'vDISPLAY',prop:'Tooltiptext'},{av:'gx.fn.getCtrlProperty("vDISPLAY","Link")',ctrl:'vDISPLAY',prop:'Link'}]];
   this.setVCMap("AV65Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV51IsAuthorized_Display", "vISAUTHORIZED_DISPLAY", 0, "boolean", 4, 0);
   this.setVCMap("AV8BR_EncounterID", "vBR_ENCOUNTERID", 0, "int", 18, 0);
   this.setVCMap("AV8BR_EncounterID", "vBR_ENCOUNTERID", 0, "int", 18, 0);
   this.setVCMap("AV65Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV51IsAuthorized_Display", "vISAUTHORIZED_DISPLAY", 0, "boolean", 4, 0);
   this.setVCMap("AV8BR_EncounterID", "vBR_ENCOUNTERID", 0, "int", 18, 0);
   this.setVCMap("AV65Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV51IsAuthorized_Display", "vISAUTHORIZED_DISPLAY", 0, "boolean", 4, 0);
   GridContainer.addRefreshingVar(this.GXValidFnc[32]);
   GridContainer.addRefreshingVar(this.GXValidFnc[33]);
   GridContainer.addRefreshingVar({rfrVar:"AV8BR_EncounterID"});
   GridContainer.addRefreshingVar(this.GXValidFnc[25]);
   GridContainer.addRefreshingVar(this.GXValidFnc[27]);
   GridContainer.addRefreshingVar(this.GXValidFnc[29]);
   GridContainer.addRefreshingVar({rfrVar:"AV65Pgmname"});
   GridContainer.addRefreshingVar({rfrVar:"AV51IsAuthorized_Display"});
   this.Initialize( );
});
