/*!   GeneXus C# 16_0_0-127771 on 2/27/2020 9:36:48.86
*/
gx.evt.autoSkip = false;
gx.define('br_encounterupdatebr_labwc', true, function (CmpContext) {
   this.ServerClass =  "br_encounterupdatebr_labwc" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.setCmpContext(CmpContext);
   this.ReadonlyForm = true;
   this.hasEnterEvent = false;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV89Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.AV64IsAuthorized_Display=gx.fn.getControlValue("vISAUTHORIZED_DISPLAY") ;
      this.AV62IsAuthorized_Delete=gx.fn.getControlValue("vISAUTHORIZED_DELETE") ;
      this.AV8BR_EncounterID=gx.fn.getIntegerValue("vBR_ENCOUNTERID",',') ;
      this.AV8BR_EncounterID=gx.fn.getIntegerValue("vBR_ENCOUNTERID",',') ;
      this.AV89Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.AV64IsAuthorized_Display=gx.fn.getControlValue("vISAUTHORIZED_DISPLAY") ;
      this.AV62IsAuthorized_Delete=gx.fn.getControlValue("vISAUTHORIZED_DELETE") ;
   };
   this.e11262_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEPAGE", false, null, true, true);
   };
   this.e12262_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", false, null, true, true);
   };
   this.e13262_client=function()
   {
      return this.executeServerEvent("DDO_BR_LABID.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e14262_client=function()
   {
      return this.executeServerEvent("DDO_BR_LAB_TESTNAME.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e15262_client=function()
   {
      return this.executeServerEvent("DDO_BR_LAB_SPECIMENSOURCE.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e16262_client=function()
   {
      return this.executeServerEvent("DDO_BR_LAB_SPECIMENDATE.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e17262_client=function()
   {
      return this.executeServerEvent("DDO_BR_LAB_ABNIND.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e18262_client=function()
   {
      return this.executeServerEvent("'DOINSERT'", false, null, false, false);
   };
   this.e22262_client=function()
   {
      return this.executeServerEvent("VBACK.CLICK", true, arguments[0], false, false);
   };
   this.e23262_client=function()
   {
      return this.executeServerEvent("VDELETE.CLICK", true, arguments[0], false, false);
   };
   this.e24262_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e25262_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,35,36,37,38,39,41,42,43,45,47,49,51,53,54,56,57];
   this.GXLastCtrlId =57;
   this.GridContainer = new gx.grid.grid(this, 2,"WbpLvl2",28,"Grid","Grid","GridContainer",this.CmpContext,this.IsMasterPage,"br_encounterupdatebr_labwc",[],false,1,false,true,0,false,false,false,"",0,"px",0,"px","澧炲姞绌虹櫧琛?,true,false,false,null,null,false,"",false,[1,1,1,1],false,0,true,false);
   var GridContainer = this.GridContainer;
   GridContainer.addBitmap("&Display","vDISPLAY",29,0,"px",17,"px",null,"","","ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addBitmap("&Back","vBACK",30,0,"px",17,"px","e22262_client","","","ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addBitmap("&Delete","vDELETE",31,0,"px",17,"px","e23262_client","","","DeleteAttribute ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addSingleLineEdit(101,32,"BR_LABID","","","BR_LabID","int",0,"px",18,18,"right",null,[],101,"BR_LabID",true,0,false,false,"Attribute",1,"WWColumn");
   GridContainer.addSingleLineEdit(104,33,"BR_LAB_TESTNAME","","","BR_Lab_TestName","svchar",0,"px",40,40,"left",null,[],104,"BR_Lab_TestName",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(106,34,"BR_LAB_SPECIMENSOURCE","","","BR_Lab_SpecimenSource","svchar",0,"px",100,80,"left",null,[],106,"BR_Lab_SpecimenSource",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(105,35,"BR_LAB_SPECIMENDATE","","","BR_Lab_SpecimenDate","dtime",0,"px",19,19,"right",null,[],105,"BR_Lab_SpecimenDate",true,8,false,false,"Attribute",1,"WWColumn hidden-xs hidden-sm");
   GridContainer.addSingleLineEdit(112,36,"BR_LAB_ABNIND","","","BR_Lab_AbnInd","svchar",0,"px",100,80,"left",null,[],112,"BR_Lab_AbnInd",true,0,false,false,"Attribute",1,"WWColumn hidden-xs hidden-sm");
   this.GridContainer.emptyText = "";
   this.setGrid(GridContainer);
   this.DVPANEL_TABLEHEADERContainer = gx.uc.getNew(this, 10, 0, "BootstrapPanel", this.CmpContext + "DVPANEL_TABLEHEADERContainer", "Dvpanel_tableheader", "DVPANEL_TABLEHEADER");
   var DVPANEL_TABLEHEADERContainer = this.DVPANEL_TABLEHEADERContainer;
   DVPANEL_TABLEHEADERContainer.setProp("Class", "Class", "", "char");
   DVPANEL_TABLEHEADERContainer.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_TABLEHEADERContainer.setProp("Width", "Width", "100%", "str");
   DVPANEL_TABLEHEADERContainer.setProp("Height", "Height", "100", "str");
   DVPANEL_TABLEHEADERContainer.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Cls", "Cls", "PanelNoHeader", "str");
   DVPANEL_TABLEHEADERContainer.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Title", "Title", "閫夐」", "str");
   DVPANEL_TABLEHEADERContainer.setProp("Collapsible", "Collapsible", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("IconPosition", "Iconposition", "left", "str");
   DVPANEL_TABLEHEADERContainer.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Visible", "Visible", true, "bool");
   DVPANEL_TABLEHEADERContainer.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_TABLEHEADERContainer);
   this.GRIDPAGINATIONBARContainer = gx.uc.getNew(this, 40, 29, "DVelop_DVPaginationBar", this.CmpContext + "GRIDPAGINATIONBARContainer", "Gridpaginationbar", "GRIDPAGINATIONBAR");
   var GRIDPAGINATIONBARContainer = this.GRIDPAGINATIONBARContainer;
   GRIDPAGINATIONBARContainer.setProp("Enabled", "Enabled", true, "boolean");
   GRIDPAGINATIONBARContainer.setProp("Class", "Class", "PaginationBar", "str");
   GRIDPAGINATIONBARContainer.setProp("ShowFirst", "Showfirst", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowPrevious", "Showprevious", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowNext", "Shownext", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowLast", "Showlast", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("PagesToShow", "Pagestoshow", 5, "num");
   GRIDPAGINATIONBARContainer.setProp("PagingButtonsPosition", "Pagingbuttonsposition", "Right", "str");
   GRIDPAGINATIONBARContainer.setProp("PagingCaptionPosition", "Pagingcaptionposition", "Left", "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridClass", "Emptygridclass", "PaginationBarEmptyGrid", "str");
   GRIDPAGINATIONBARContainer.setProp("SelectedPage", "Selectedpage", "", "char");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageSelector", "Rowsperpageselector", true, "bool");
   GRIDPAGINATIONBARContainer.setDynProp("RowsPerPageSelectedValue", "Rowsperpageselectedvalue", 10, "num");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageOptions", "Rowsperpageoptions", "5:WWP_Rows5,10:WWP_Rows10,20:WWP_Rows20,50:WWP_Rows50", "str");
   GRIDPAGINATIONBARContainer.setProp("First", "First", "First", "str");
   GRIDPAGINATIONBARContainer.setProp("Previous", "Previous", "WWP_PagingPreviousCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Next", "Next", "WWP_PagingNextCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Last", "Last", "Last", "str");
   GRIDPAGINATIONBARContainer.setProp("Caption", "Caption", "<CURRENT_PAGE>椤?<TOTAL_PAGES>椤?璁板綍锛?TOTAL_RECORDS>鏉?, "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridCaption", "Emptygridcaption", "WWP_PagingEmptyGridCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageCaption", "Rowsperpagecaption", "WWP_PagingRowsPerPage", "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV56GridCurrentPage', "vGRIDCURRENTPAGE", 'SetCurrentPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV56GridCurrentPage=UC.GetCurrentPage();gx.fn.setControlValue("vGRIDCURRENTPAGE",UC.ParentObject.AV56GridCurrentPage); });
   GRIDPAGINATIONBARContainer.setProp("PageCount", "Pagecount", '', "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV58GridRecordCount', "vGRIDRECORDCOUNT", 'SetRecordCount');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV58GridRecordCount=UC.GetRecordCount();gx.fn.setControlValue("vGRIDRECORDCOUNT",UC.ParentObject.AV58GridRecordCount); });
   GRIDPAGINATIONBARContainer.addV2CFunction('AV57GridPageSize', "vGRIDPAGESIZE", 'SetPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV57GridPageSize=UC.GetPage();gx.fn.setControlValue("vGRIDPAGESIZE",UC.ParentObject.AV57GridPageSize); });
   GRIDPAGINATIONBARContainer.setProp("Visible", "Visible", true, "bool");
   GRIDPAGINATIONBARContainer.setC2ShowFunction(function(UC) { UC.show(); });
   GRIDPAGINATIONBARContainer.addEventHandler("ChangePage", this.e11262_client);
   GRIDPAGINATIONBARContainer.addEventHandler("ChangeRowsPerPage", this.e12262_client);
   this.setUserControl(GRIDPAGINATIONBARContainer);
   this.DDO_BR_LABIDContainer = gx.uc.getNew(this, 44, 29, "BootstrapDropDownOptions", this.CmpContext + "DDO_BR_LABIDContainer", "Ddo_br_labid", "DDO_BR_LABID");
   var DDO_BR_LABIDContainer = this.DDO_BR_LABIDContainer;
   DDO_BR_LABIDContainer.setProp("Class", "Class", "", "char");
   DDO_BR_LABIDContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_LABIDContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_LABIDContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_LABIDContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_LABIDContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_LABIDContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_LABIDContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_LABIDContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_LABIDContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_LABIDContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_LABIDContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_LABIDContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_LABIDContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_LABIDContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_LABIDContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_LABIDContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_LABIDContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_LABIDContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_LABIDContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_LABIDContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_LABIDContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_LABIDContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_LABIDContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_LABIDContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_LABIDContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_LABIDContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_LABIDContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_LABIDContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_LABIDContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_LABIDContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_LABIDContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_LABIDContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_LABIDContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_LABIDContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_LABIDContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_LABIDContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_LABIDContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_LABIDContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_LABIDContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_LABIDContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_LABIDContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_LABIDContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_LABIDContainer.addV2CFunction('AV53DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_LABIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV53DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV53DDO_TitleSettingsIcons); });
   DDO_BR_LABIDContainer.addV2CFunction('AV17BR_LabIDTitleFilterData', "vBR_LABIDTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_LABIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV17BR_LabIDTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_LABIDTITLEFILTERDATA",UC.ParentObject.AV17BR_LabIDTitleFilterData); });
   DDO_BR_LABIDContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_LABIDContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_LABIDContainer.addEventHandler("OnOptionClicked", this.e13262_client);
   this.setUserControl(DDO_BR_LABIDContainer);
   this.DDO_BR_LAB_TESTNAMEContainer = gx.uc.getNew(this, 46, 45, "BootstrapDropDownOptions", this.CmpContext + "DDO_BR_LAB_TESTNAMEContainer", "Ddo_br_lab_testname", "DDO_BR_LAB_TESTNAME");
   var DDO_BR_LAB_TESTNAMEContainer = this.DDO_BR_LAB_TESTNAMEContainer;
   DDO_BR_LAB_TESTNAMEContainer.setProp("Class", "Class", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_LAB_TESTNAMEContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_LAB_TESTNAMEContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_LAB_TESTNAMEContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_LAB_TESTNAMEContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_LAB_TESTNAMEContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_LAB_TESTNAMEContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_LAB_TESTNAMEContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_LAB_TESTNAMEContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_LAB_TESTNAMEContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_LAB_TESTNAMEContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_LAB_TESTNAMEContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_LAB_TESTNAMEContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_LAB_TESTNAMEContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_LAB_TESTNAMEContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_LAB_TESTNAMEContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_LAB_TESTNAMEContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_LAB_TESTNAMEContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_LAB_TESTNAMEContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_LAB_TESTNAMEContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_LAB_TESTNAMEContainer.addV2CFunction('AV53DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_LAB_TESTNAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV53DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV53DDO_TitleSettingsIcons); });
   DDO_BR_LAB_TESTNAMEContainer.addV2CFunction('AV23BR_Lab_TestNameTitleFilterData', "vBR_LAB_TESTNAMETITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_LAB_TESTNAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV23BR_Lab_TestNameTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_LAB_TESTNAMETITLEFILTERDATA",UC.ParentObject.AV23BR_Lab_TestNameTitleFilterData); });
   DDO_BR_LAB_TESTNAMEContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_LAB_TESTNAMEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_LAB_TESTNAMEContainer.addEventHandler("OnOptionClicked", this.e14262_client);
   this.setUserControl(DDO_BR_LAB_TESTNAMEContainer);
   this.DDO_BR_LAB_SPECIMENSOURCEContainer = gx.uc.getNew(this, 48, 45, "BootstrapDropDownOptions", this.CmpContext + "DDO_BR_LAB_SPECIMENSOURCEContainer", "Ddo_br_lab_specimensource", "DDO_BR_LAB_SPECIMENSOURCE");
   var DDO_BR_LAB_SPECIMENSOURCEContainer = this.DDO_BR_LAB_SPECIMENSOURCEContainer;
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("Class", "Class", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_LAB_SPECIMENSOURCEContainer.addV2CFunction('AV53DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_LAB_SPECIMENSOURCEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV53DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV53DDO_TitleSettingsIcons); });
   DDO_BR_LAB_SPECIMENSOURCEContainer.addV2CFunction('AV27BR_Lab_SpecimenSourceTitleFilterData', "vBR_LAB_SPECIMENSOURCETITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_LAB_SPECIMENSOURCEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV27BR_Lab_SpecimenSourceTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_LAB_SPECIMENSOURCETITLEFILTERDATA",UC.ParentObject.AV27BR_Lab_SpecimenSourceTitleFilterData); });
   DDO_BR_LAB_SPECIMENSOURCEContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_LAB_SPECIMENSOURCEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_LAB_SPECIMENSOURCEContainer.addEventHandler("OnOptionClicked", this.e15262_client);
   this.setUserControl(DDO_BR_LAB_SPECIMENSOURCEContainer);
   this.DDO_BR_LAB_SPECIMENDATEContainer = gx.uc.getNew(this, 50, 45, "BootstrapDropDownOptions", this.CmpContext + "DDO_BR_LAB_SPECIMENDATEContainer", "Ddo_br_lab_specimendate", "DDO_BR_LAB_SPECIMENDATE");
   var DDO_BR_LAB_SPECIMENDATEContainer = this.DDO_BR_LAB_SPECIMENDATEContainer;
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("Class", "Class", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_LAB_SPECIMENDATEContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_LAB_SPECIMENDATEContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_LAB_SPECIMENDATEContainer.addV2CFunction('AV53DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_LAB_SPECIMENDATEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV53DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV53DDO_TitleSettingsIcons); });
   DDO_BR_LAB_SPECIMENDATEContainer.addV2CFunction('AV25BR_Lab_SpecimenDateTitleFilterData', "vBR_LAB_SPECIMENDATETITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_LAB_SPECIMENDATEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25BR_Lab_SpecimenDateTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_LAB_SPECIMENDATETITLEFILTERDATA",UC.ParentObject.AV25BR_Lab_SpecimenDateTitleFilterData); });
   DDO_BR_LAB_SPECIMENDATEContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_LAB_SPECIMENDATEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_LAB_SPECIMENDATEContainer.addEventHandler("OnOptionClicked", this.e16262_client);
   this.setUserControl(DDO_BR_LAB_SPECIMENDATEContainer);
   this.DDO_BR_LAB_ABNINDContainer = gx.uc.getNew(this, 52, 45, "BootstrapDropDownOptions", this.CmpContext + "DDO_BR_LAB_ABNINDContainer", "Ddo_br_lab_abnind", "DDO_BR_LAB_ABNIND");
   var DDO_BR_LAB_ABNINDContainer = this.DDO_BR_LAB_ABNINDContainer;
   DDO_BR_LAB_ABNINDContainer.setProp("Class", "Class", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_LAB_ABNINDContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_LAB_ABNINDContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_LAB_ABNINDContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_LAB_ABNINDContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_LAB_ABNINDContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_LAB_ABNINDContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_LAB_ABNINDContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_LAB_ABNINDContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_LAB_ABNINDContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_LAB_ABNINDContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_LAB_ABNINDContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_LAB_ABNINDContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_LAB_ABNINDContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_LAB_ABNINDContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_LAB_ABNINDContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_LAB_ABNINDContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_LAB_ABNINDContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_LAB_ABNINDContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_LAB_ABNINDContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_LAB_ABNINDContainer.addV2CFunction('AV53DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_LAB_ABNINDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV53DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV53DDO_TitleSettingsIcons); });
   DDO_BR_LAB_ABNINDContainer.addV2CFunction('AV39BR_Lab_AbnIndTitleFilterData', "vBR_LAB_ABNINDTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_LAB_ABNINDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV39BR_Lab_AbnIndTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_LAB_ABNINDTITLEFILTERDATA",UC.ParentObject.AV39BR_Lab_AbnIndTitleFilterData); });
   DDO_BR_LAB_ABNINDContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_LAB_ABNINDContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_LAB_ABNINDContainer.addEventHandler("OnOptionClicked", this.e17262_client);
   this.setUserControl(DDO_BR_LAB_ABNINDContainer);
   this.WORKWITHPLUSUTILITIES1Container = gx.uc.getNew(this, 55, 45, "DVelop_WorkWithPlusUtilities", this.CmpContext + "WORKWITHPLUSUTILITIES1Container", "Workwithplusutilities1", "WORKWITHPLUSUTILITIES1");
   var WORKWITHPLUSUTILITIES1Container = this.WORKWITHPLUSUTILITIES1Container;
   WORKWITHPLUSUTILITIES1Container.setProp("Class", "Class", "", "char");
   WORKWITHPLUSUTILITIES1Container.setProp("Enabled", "Enabled", true, "boolean");
   WORKWITHPLUSUTILITIES1Container.setProp("Width", "Width", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Height", "Height", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Visible", "Visible", true, "bool");
   WORKWITHPLUSUTILITIES1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(WORKWITHPLUSUTILITIES1Container);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEGRIDHEADER",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"HTML_DVPANEL_TABLEHEADER",grid:0};
   GXValidFnc[12]={ id: 12, fld:"LAYOUT_TABLEHEADER",grid:0};
   GXValidFnc[13]={ id: 13, fld:"",grid:0};
   GXValidFnc[14]={ id: 14, fld:"TABLEHEADER",grid:0};
   GXValidFnc[15]={ id: 15, fld:"",grid:0};
   GXValidFnc[16]={ id: 16, fld:"",grid:0};
   GXValidFnc[17]={ id: 17, fld:"TABLEACTIONS",grid:0};
   GXValidFnc[18]={ id: 18, fld:"",grid:0};
   GXValidFnc[19]={ id: 19, fld:"",grid:0};
   GXValidFnc[20]={ id: 20, fld:"",grid:0};
   GXValidFnc[21]={ id: 21, fld:"",grid:0};
   GXValidFnc[22]={ id: 22, fld:"BTNINSERT",grid:0};
   GXValidFnc[23]={ id: 23, fld:"",grid:0};
   GXValidFnc[24]={ id: 24, fld:"",grid:0};
   GXValidFnc[25]={ id: 25, fld:"GRIDTABLEWITHPAGINATIONBAR",grid:0};
   GXValidFnc[26]={ id: 26, fld:"",grid:0};
   GXValidFnc[27]={ id: 27, fld:"",grid:0};
   GXValidFnc[29]={ id:29 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDISPLAY",gxz:"ZV63Display",gxold:"OV63Display",gxvar:"AV63Display",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV63Display=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV63Display=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vDISPLAY",row || gx.fn.currentGridRowImpl(28),gx.O.AV63Display,gx.O.AV86Display_GXI)},c2v:function(){gx.O.AV86Display_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV63Display=this.val()},val:function(row){return gx.fn.getGridControlValue("vDISPLAY",row || gx.fn.currentGridRowImpl(28))},val_GXI:function(row){return gx.fn.getGridControlValue("vDISPLAY_GXI",row || gx.fn.currentGridRowImpl(28))}, gxvar_GXI:'AV86Display_GXI',nac:gx.falseFn};
   GXValidFnc[30]={ id:30 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vBACK",gxz:"ZV80back",gxold:"OV80back",gxvar:"AV80back",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV80back=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV80back=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vBACK",row || gx.fn.currentGridRowImpl(28),gx.O.AV80back,gx.O.AV87Back_GXI)},c2v:function(){gx.O.AV87Back_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV80back=this.val()},val:function(row){return gx.fn.getGridControlValue("vBACK",row || gx.fn.currentGridRowImpl(28))},val_GXI:function(row){return gx.fn.getGridControlValue("vBACK_GXI",row || gx.fn.currentGridRowImpl(28))}, gxvar_GXI:'AV87Back_GXI',nac:gx.falseFn,evt:"e22262_client"};
   GXValidFnc[31]={ id:31 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDELETE",gxz:"ZV61Delete",gxold:"OV61Delete",gxvar:"AV61Delete",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV61Delete=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV61Delete=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vDELETE",row || gx.fn.currentGridRowImpl(28),gx.O.AV61Delete,gx.O.AV88Delete_GXI)},c2v:function(){gx.O.AV88Delete_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV61Delete=this.val()},val:function(row){return gx.fn.getGridControlValue("vDELETE",row || gx.fn.currentGridRowImpl(28))},val_GXI:function(row){return gx.fn.getGridControlValue("vDELETE_GXI",row || gx.fn.currentGridRowImpl(28))}, gxvar_GXI:'AV88Delete_GXI',nac:gx.falseFn,evt:"e23262_client"};
   GXValidFnc[32]={ id:32 ,lvl:2,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_LABID",gxz:"Z101BR_LabID",gxold:"O101BR_LabID",gxvar:"A101BR_LabID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A101BR_LabID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z101BR_LabID=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("BR_LABID",row || gx.fn.currentGridRowImpl(28),gx.O.A101BR_LabID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A101BR_LabID=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("BR_LABID",row || gx.fn.currentGridRowImpl(28),',')},nac:gx.falseFn};
   GXValidFnc[33]={ id:33 ,lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_LAB_TESTNAME",gxz:"Z104BR_Lab_TestName",gxold:"O104BR_Lab_TestName",gxvar:"A104BR_Lab_TestName",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A104BR_Lab_TestName=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z104BR_Lab_TestName=Value},v2c:function(row){gx.fn.setGridControlValue("BR_LAB_TESTNAME",row || gx.fn.currentGridRowImpl(28),gx.O.A104BR_Lab_TestName,0)},c2v:function(){if(this.val()!==undefined)gx.O.A104BR_Lab_TestName=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_LAB_TESTNAME",row || gx.fn.currentGridRowImpl(28))},nac:gx.falseFn};
   GXValidFnc[34]={ id:34 ,lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_LAB_SPECIMENSOURCE",gxz:"Z106BR_Lab_SpecimenSource",gxold:"O106BR_Lab_SpecimenSource",gxvar:"A106BR_Lab_SpecimenSource",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A106BR_Lab_SpecimenSource=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z106BR_Lab_SpecimenSource=Value},v2c:function(row){gx.fn.setGridControlValue("BR_LAB_SPECIMENSOURCE",row || gx.fn.currentGridRowImpl(28),gx.O.A106BR_Lab_SpecimenSource,0)},c2v:function(){if(this.val()!==undefined)gx.O.A106BR_Lab_SpecimenSource=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_LAB_SPECIMENSOURCE",row || gx.fn.currentGridRowImpl(28))},nac:gx.falseFn};
   GXValidFnc[35]={ id:35 ,lvl:2,type:"dtime",len:10,dec:8,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_LAB_SPECIMENDATE",gxz:"Z105BR_Lab_SpecimenDate",gxold:"O105BR_Lab_SpecimenDate",gxvar:"A105BR_Lab_SpecimenDate",dp:{f:0,st:true,wn:false,mf:false,pic:"99/99/9999 99:99:99",dec:8},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.A105BR_Lab_SpecimenDate=gx.fn.toDatetimeValue(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z105BR_Lab_SpecimenDate=gx.fn.toDatetimeValue(Value)},v2c:function(row){gx.fn.setGridControlValue("BR_LAB_SPECIMENDATE",row || gx.fn.currentGridRowImpl(28),gx.O.A105BR_Lab_SpecimenDate,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A105BR_Lab_SpecimenDate=gx.fn.toDatetimeValue(this.val())},val:function(row){return gx.fn.getGridDateTimeValue("BR_LAB_SPECIMENDATE",row || gx.fn.currentGridRowImpl(28))},nac:gx.falseFn};
   GXValidFnc[36]={ id:36 ,lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_LAB_ABNIND",gxz:"Z112BR_Lab_AbnInd",gxold:"O112BR_Lab_AbnInd",gxvar:"A112BR_Lab_AbnInd",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A112BR_Lab_AbnInd=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z112BR_Lab_AbnInd=Value},v2c:function(row){gx.fn.setGridControlValue("BR_LAB_ABNIND",row || gx.fn.currentGridRowImpl(28),gx.O.A112BR_Lab_AbnInd,0)},c2v:function(){if(this.val()!==undefined)gx.O.A112BR_Lab_AbnInd=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_LAB_ABNIND",row || gx.fn.currentGridRowImpl(28))},nac:gx.falseFn};
   GXValidFnc[37]={ id: 37, fld:"",grid:0};
   GXValidFnc[38]={ id: 38, fld:"",grid:0};
   GXValidFnc[39]={ id: 39, fld:"HTML_GRIDPAGINATIONBAR",grid:0};
   GXValidFnc[41]={ id: 41, fld:"",grid:0};
   GXValidFnc[42]={ id: 42, fld:"",grid:0};
   GXValidFnc[43]={ id: 43, fld:"HTML_BOTTOMAUXILIARCONTROLS",grid:0};
   GXValidFnc[45]={ id:45 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_LABIDTITLECONTROLIDTOREPLACE",gxz:"ZV18ddo_BR_LabIDTitleControlIdToReplace",gxold:"OV18ddo_BR_LabIDTitleControlIdToReplace",gxvar:"AV18ddo_BR_LabIDTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV18ddo_BR_LabIDTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV18ddo_BR_LabIDTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_LABIDTITLECONTROLIDTOREPLACE",gx.O.AV18ddo_BR_LabIDTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV18ddo_BR_LabIDTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_LABIDTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[47]={ id:47 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_LAB_TESTNAMETITLECONTROLIDTOREPLACE",gxz:"ZV24ddo_BR_Lab_TestNameTitleControlIdToReplace",gxold:"OV24ddo_BR_Lab_TestNameTitleControlIdToReplace",gxvar:"AV24ddo_BR_Lab_TestNameTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV24ddo_BR_Lab_TestNameTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV24ddo_BR_Lab_TestNameTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_LAB_TESTNAMETITLECONTROLIDTOREPLACE",gx.O.AV24ddo_BR_Lab_TestNameTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV24ddo_BR_Lab_TestNameTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_LAB_TESTNAMETITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[49]={ id:49 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_LAB_SPECIMENSOURCETITLECONTROLIDTOREPLACE",gxz:"ZV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace",gxold:"OV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace",gxvar:"AV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_LAB_SPECIMENSOURCETITLECONTROLIDTOREPLACE",gx.O.AV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_LAB_SPECIMENSOURCETITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[51]={ id:51 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_LAB_SPECIMENDATETITLECONTROLIDTOREPLACE",gxz:"ZV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace",gxold:"OV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace",gxvar:"AV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_LAB_SPECIMENDATETITLECONTROLIDTOREPLACE",gx.O.AV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_LAB_SPECIMENDATETITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[53]={ id:53 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_LAB_ABNINDTITLECONTROLIDTOREPLACE",gxz:"ZV40ddo_BR_Lab_AbnIndTitleControlIdToReplace",gxold:"OV40ddo_BR_Lab_AbnIndTitleControlIdToReplace",gxvar:"AV40ddo_BR_Lab_AbnIndTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV40ddo_BR_Lab_AbnIndTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV40ddo_BR_Lab_AbnIndTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_LAB_ABNINDTITLECONTROLIDTOREPLACE",gx.O.AV40ddo_BR_Lab_AbnIndTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV40ddo_BR_Lab_AbnIndTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_LAB_ABNINDTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[54]={ id:54 ,lvl:0,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_ENCOUNTERID",gxz:"Z19BR_EncounterID",gxold:"O19BR_EncounterID",gxvar:"A19BR_EncounterID",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.A19BR_EncounterID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z19BR_EncounterID=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("BR_ENCOUNTERID",gx.O.A19BR_EncounterID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A19BR_EncounterID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("BR_ENCOUNTERID",',')},nac:gx.falseFn};
   this.declareDomainHdlr( 54 , function() {
   });
   GXValidFnc[56]={ id:56 ,lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDBY",gxz:"ZV14OrderedBy",gxold:"OV14OrderedBy",gxvar:"AV14OrderedBy",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV14OrderedBy=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV14OrderedBy=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDBY",gx.O.AV14OrderedBy,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV14OrderedBy=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vORDEREDBY",',')},nac:gx.falseFn};
   GXValidFnc[57]={ id:57 ,lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDDSC",gxz:"ZV15OrderedDsc",gxold:"OV15OrderedDsc",gxvar:"AV15OrderedDsc",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV15OrderedDsc=gx.lang.booleanValue(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV15OrderedDsc=gx.lang.booleanValue(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDDSC",gx.O.AV15OrderedDsc,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV15OrderedDsc=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getControlValue("vORDEREDDSC")},nac:gx.falseFn};
   this.ZV63Display = "" ;
   this.OV63Display = "" ;
   this.ZV80back = "" ;
   this.OV80back = "" ;
   this.ZV61Delete = "" ;
   this.OV61Delete = "" ;
   this.Z101BR_LabID = 0 ;
   this.O101BR_LabID = 0 ;
   this.Z104BR_Lab_TestName = "" ;
   this.O104BR_Lab_TestName = "" ;
   this.Z106BR_Lab_SpecimenSource = "" ;
   this.O106BR_Lab_SpecimenSource = "" ;
   this.Z105BR_Lab_SpecimenDate = gx.date.nullDate() ;
   this.O105BR_Lab_SpecimenDate = gx.date.nullDate() ;
   this.Z112BR_Lab_AbnInd = "" ;
   this.O112BR_Lab_AbnInd = "" ;
   this.AV18ddo_BR_LabIDTitleControlIdToReplace = "" ;
   this.ZV18ddo_BR_LabIDTitleControlIdToReplace = "" ;
   this.OV18ddo_BR_LabIDTitleControlIdToReplace = "" ;
   this.AV24ddo_BR_Lab_TestNameTitleControlIdToReplace = "" ;
   this.ZV24ddo_BR_Lab_TestNameTitleControlIdToReplace = "" ;
   this.OV24ddo_BR_Lab_TestNameTitleControlIdToReplace = "" ;
   this.AV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace = "" ;
   this.ZV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace = "" ;
   this.OV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace = "" ;
   this.AV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace = "" ;
   this.ZV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace = "" ;
   this.OV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace = "" ;
   this.AV40ddo_BR_Lab_AbnIndTitleControlIdToReplace = "" ;
   this.ZV40ddo_BR_Lab_AbnIndTitleControlIdToReplace = "" ;
   this.OV40ddo_BR_Lab_AbnIndTitleControlIdToReplace = "" ;
   this.A19BR_EncounterID = 0 ;
   this.Z19BR_EncounterID = 0 ;
   this.O19BR_EncounterID = 0 ;
   this.AV14OrderedBy = 0 ;
   this.ZV14OrderedBy = 0 ;
   this.OV14OrderedBy = 0 ;
   this.AV15OrderedDsc = false ;
   this.ZV15OrderedDsc = false ;
   this.OV15OrderedDsc = false ;
   this.AV56GridCurrentPage = 0 ;
   this.AV53DDO_TitleSettingsIcons = {Default:"",Default_GXI:"",Filtered:"",Filtered_GXI:"",SortedASC:"",SortedASC_GXI:"",SortedDSC:"",SortedDSC_GXI:"",FilteredSortedASC:"",FilteredSortedASC_GXI:"",FilteredSortedDSC:"",FilteredSortedDSC_GXI:"",OptionSortASC:"",OptionSortASC_GXI:"",OptionSortDSC:"",OptionSortDSC_GXI:"",OptionApplyFilter:"",OptionApplyFilter_GXI:"",OptionFilteringData:"",OptionFilteringData_GXI:"",OptionCleanFilters:"",OptionCleanFilters_GXI:"",SelectedOption:"",SelectedOption_GXI:"",MultiselOption:"",MultiselOption_GXI:"",MultiselSelOption:"",MultiselSelOption_GXI:""} ;
   this.AV18ddo_BR_LabIDTitleControlIdToReplace = "" ;
   this.AV24ddo_BR_Lab_TestNameTitleControlIdToReplace = "" ;
   this.AV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace = "" ;
   this.AV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace = "" ;
   this.AV40ddo_BR_Lab_AbnIndTitleControlIdToReplace = "" ;
   this.A19BR_EncounterID = 0 ;
   this.AV14OrderedBy = 0 ;
   this.AV15OrderedDsc = false ;
   this.AV8BR_EncounterID = 0 ;
   this.AV63Display = "" ;
   this.AV80back = "" ;
   this.AV61Delete = "" ;
   this.A101BR_LabID = 0 ;
   this.A104BR_Lab_TestName = "" ;
   this.A106BR_Lab_SpecimenSource = "" ;
   this.A105BR_Lab_SpecimenDate = gx.date.nullDate() ;
   this.A112BR_Lab_AbnInd = "" ;
   this.AV89Pgmname = "" ;
   this.AV64IsAuthorized_Display = false ;
   this.AV62IsAuthorized_Delete = false ;
   this.Events = {"e11262_client": ["GRIDPAGINATIONBAR.CHANGEPAGE", true] ,"e12262_client": ["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", true] ,"e13262_client": ["DDO_BR_LABID.ONOPTIONCLICKED", true] ,"e14262_client": ["DDO_BR_LAB_TESTNAME.ONOPTIONCLICKED", true] ,"e15262_client": ["DDO_BR_LAB_SPECIMENSOURCE.ONOPTIONCLICKED", true] ,"e16262_client": ["DDO_BR_LAB_SPECIMENDATE.ONOPTIONCLICKED", true] ,"e17262_client": ["DDO_BR_LAB_ABNIND.ONOPTIONCLICKED", true] ,"e18262_client": ["'DOINSERT'", true] ,"e22262_client": ["VBACK.CLICK", true] ,"e23262_client": ["VDELETE.CLICK", true] ,"e24262_client": ["ENTER", true] ,"e25262_client": ["CANCEL", true]};
   this.EvtParms["REFRESH"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV64IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'AV62IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'AV18ddo_BR_LabIDTitleControlIdToReplace',fld:'vDDO_BR_LABIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_BR_Lab_TestNameTitleControlIdToReplace',fld:'vDDO_BR_LAB_TESTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENSOURCETITLECONTROLIDTOREPLACE',pic:''},{av:'AV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENDATETITLECONTROLIDTOREPLACE',pic:''},{av:'AV40ddo_BR_Lab_AbnIndTitleControlIdToReplace',fld:'vDDO_BR_LAB_ABNINDTITLECONTROLIDTOREPLACE',pic:''},{ctrl:'GRID',prop:'Rows'},{av:'AV89Pgmname',fld:'vPGMNAME',pic:''},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''}],[{av:'AV17BR_LabIDTitleFilterData',fld:'vBR_LABIDTITLEFILTERDATA',pic:''},{av:'AV23BR_Lab_TestNameTitleFilterData',fld:'vBR_LAB_TESTNAMETITLEFILTERDATA',pic:''},{av:'AV27BR_Lab_SpecimenSourceTitleFilterData',fld:'vBR_LAB_SPECIMENSOURCETITLEFILTERDATA',pic:''},{av:'AV25BR_Lab_SpecimenDateTitleFilterData',fld:'vBR_LAB_SPECIMENDATETITLEFILTERDATA',pic:''},{av:'AV39BR_Lab_AbnIndTitleFilterData',fld:'vBR_LAB_ABNINDTITLEFILTERDATA',pic:''},{ctrl:'BR_LABID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_LABID","Title")',ctrl:'BR_LABID',prop:'Title'},{ctrl:'BR_LAB_TESTNAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_TESTNAME","Title")',ctrl:'BR_LAB_TESTNAME',prop:'Title'},{ctrl:'BR_LAB_SPECIMENSOURCE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_SPECIMENSOURCE","Title")',ctrl:'BR_LAB_SPECIMENSOURCE',prop:'Title'},{ctrl:'BR_LAB_SPECIMENDATE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_SPECIMENDATE","Title")',ctrl:'BR_LAB_SPECIMENDATE',prop:'Title'},{ctrl:'BR_LAB_ABNIND',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_ABNIND","Title")',ctrl:'BR_LAB_ABNIND',prop:'Title'},{av:'AV56GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV57GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV58GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'AV64IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'gx.fn.getCtrlProperty("vDISPLAY","Visible")',ctrl:'vDISPLAY',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vBACK","Visible")',ctrl:'vBACK',prop:'Visible'},{av:'AV62IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{ctrl:'BTNINSERT',prop:'Visible'}]];
   this.EvtParms["START"] = [[{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV89Pgmname',fld:'vPGMNAME',pic:''},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'}],[{ctrl:'GRID',prop:'Rows'},{av:'this.DDO_BR_LABIDContainer.TitleControlIdToReplace',ctrl:'DDO_BR_LABID',prop:'TitleControlIdToReplace'},{av:'AV18ddo_BR_LabIDTitleControlIdToReplace',fld:'vDDO_BR_LABIDTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_LABIDTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_LABIDTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_LAB_TESTNAMEContainer.TitleControlIdToReplace',ctrl:'DDO_BR_LAB_TESTNAME',prop:'TitleControlIdToReplace'},{av:'AV24ddo_BR_Lab_TestNameTitleControlIdToReplace',fld:'vDDO_BR_LAB_TESTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_LAB_TESTNAMETITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_LAB_TESTNAMETITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_LAB_SPECIMENSOURCEContainer.TitleControlIdToReplace',ctrl:'DDO_BR_LAB_SPECIMENSOURCE',prop:'TitleControlIdToReplace'},{av:'AV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENSOURCETITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_LAB_SPECIMENSOURCETITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_LAB_SPECIMENSOURCETITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_LAB_SPECIMENDATEContainer.TitleControlIdToReplace',ctrl:'DDO_BR_LAB_SPECIMENDATE',prop:'TitleControlIdToReplace'},{av:'AV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENDATETITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_LAB_SPECIMENDATETITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_LAB_SPECIMENDATETITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_LAB_ABNINDContainer.TitleControlIdToReplace',ctrl:'DDO_BR_LAB_ABNIND',prop:'TitleControlIdToReplace'},{av:'AV40ddo_BR_Lab_AbnIndTitleControlIdToReplace',fld:'vDDO_BR_LAB_ABNINDTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_LAB_ABNINDTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_LAB_ABNINDTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'gx.fn.getCtrlProperty("BR_ENCOUNTERID","Visible")',ctrl:'BR_ENCOUNTERID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vORDEREDBY","Visible")',ctrl:'vORDEREDBY',prop:'Visible'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'gx.fn.getCtrlProperty("vORDEREDDSC","Visible")',ctrl:'vORDEREDDSC',prop:'Visible'},{av:'AV53DDO_TitleSettingsIcons',fld:'vDDO_TITLESETTINGSICONS',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''}]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_LabIDTitleControlIdToReplace',fld:'vDDO_BR_LABIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_BR_Lab_TestNameTitleControlIdToReplace',fld:'vDDO_BR_LAB_TESTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENSOURCETITLECONTROLIDTOREPLACE',pic:''},{av:'AV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENDATETITLECONTROLIDTOREPLACE',pic:''},{av:'AV40ddo_BR_Lab_AbnIndTitleControlIdToReplace',fld:'vDDO_BR_LAB_ABNINDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV89Pgmname',fld:'vPGMNAME',pic:''},{av:'AV64IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'AV62IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'this.GRIDPAGINATIONBARContainer.SelectedPage',ctrl:'GRIDPAGINATIONBAR',prop:'SelectedPage'}],[]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_LabIDTitleControlIdToReplace',fld:'vDDO_BR_LABIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_BR_Lab_TestNameTitleControlIdToReplace',fld:'vDDO_BR_LAB_TESTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENSOURCETITLECONTROLIDTOREPLACE',pic:''},{av:'AV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENDATETITLECONTROLIDTOREPLACE',pic:''},{av:'AV40ddo_BR_Lab_AbnIndTitleControlIdToReplace',fld:'vDDO_BR_LAB_ABNINDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV89Pgmname',fld:'vPGMNAME',pic:''},{av:'AV64IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'AV62IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}],[{ctrl:'GRID',prop:'Rows'}]];
   this.EvtParms["DDO_BR_LABID.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_LabIDTitleControlIdToReplace',fld:'vDDO_BR_LABIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_BR_Lab_TestNameTitleControlIdToReplace',fld:'vDDO_BR_LAB_TESTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENSOURCETITLECONTROLIDTOREPLACE',pic:''},{av:'AV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENDATETITLECONTROLIDTOREPLACE',pic:''},{av:'AV40ddo_BR_Lab_AbnIndTitleControlIdToReplace',fld:'vDDO_BR_LAB_ABNINDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV89Pgmname',fld:'vPGMNAME',pic:''},{av:'AV64IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'AV62IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'this.DDO_BR_LABIDContainer.ActiveEventKey',ctrl:'DDO_BR_LABID',prop:'ActiveEventKey'}],[{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_LABIDContainer.SortedStatus',ctrl:'DDO_BR_LABID',prop:'SortedStatus'},{av:'AV17BR_LabIDTitleFilterData',fld:'vBR_LABIDTITLEFILTERDATA',pic:''},{av:'AV23BR_Lab_TestNameTitleFilterData',fld:'vBR_LAB_TESTNAMETITLEFILTERDATA',pic:''},{av:'AV27BR_Lab_SpecimenSourceTitleFilterData',fld:'vBR_LAB_SPECIMENSOURCETITLEFILTERDATA',pic:''},{av:'AV25BR_Lab_SpecimenDateTitleFilterData',fld:'vBR_LAB_SPECIMENDATETITLEFILTERDATA',pic:''},{av:'AV39BR_Lab_AbnIndTitleFilterData',fld:'vBR_LAB_ABNINDTITLEFILTERDATA',pic:''},{ctrl:'BR_LABID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_LABID","Title")',ctrl:'BR_LABID',prop:'Title'},{ctrl:'BR_LAB_TESTNAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_TESTNAME","Title")',ctrl:'BR_LAB_TESTNAME',prop:'Title'},{ctrl:'BR_LAB_SPECIMENSOURCE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_SPECIMENSOURCE","Title")',ctrl:'BR_LAB_SPECIMENSOURCE',prop:'Title'},{ctrl:'BR_LAB_SPECIMENDATE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_SPECIMENDATE","Title")',ctrl:'BR_LAB_SPECIMENDATE',prop:'Title'},{ctrl:'BR_LAB_ABNIND',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_ABNIND","Title")',ctrl:'BR_LAB_ABNIND',prop:'Title'},{av:'AV56GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV57GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV58GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'AV64IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'gx.fn.getCtrlProperty("vDISPLAY","Visible")',ctrl:'vDISPLAY',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vBACK","Visible")',ctrl:'vBACK',prop:'Visible'},{av:'AV62IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{ctrl:'BTNINSERT',prop:'Visible'}]];
   this.EvtParms["DDO_BR_LAB_TESTNAME.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_LabIDTitleControlIdToReplace',fld:'vDDO_BR_LABIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_BR_Lab_TestNameTitleControlIdToReplace',fld:'vDDO_BR_LAB_TESTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENSOURCETITLECONTROLIDTOREPLACE',pic:''},{av:'AV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENDATETITLECONTROLIDTOREPLACE',pic:''},{av:'AV40ddo_BR_Lab_AbnIndTitleControlIdToReplace',fld:'vDDO_BR_LAB_ABNINDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV89Pgmname',fld:'vPGMNAME',pic:''},{av:'AV64IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'AV62IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'this.DDO_BR_LAB_TESTNAMEContainer.ActiveEventKey',ctrl:'DDO_BR_LAB_TESTNAME',prop:'ActiveEventKey'}],[{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_LAB_TESTNAMEContainer.SortedStatus',ctrl:'DDO_BR_LAB_TESTNAME',prop:'SortedStatus'},{av:'AV17BR_LabIDTitleFilterData',fld:'vBR_LABIDTITLEFILTERDATA',pic:''},{av:'AV23BR_Lab_TestNameTitleFilterData',fld:'vBR_LAB_TESTNAMETITLEFILTERDATA',pic:''},{av:'AV27BR_Lab_SpecimenSourceTitleFilterData',fld:'vBR_LAB_SPECIMENSOURCETITLEFILTERDATA',pic:''},{av:'AV25BR_Lab_SpecimenDateTitleFilterData',fld:'vBR_LAB_SPECIMENDATETITLEFILTERDATA',pic:''},{av:'AV39BR_Lab_AbnIndTitleFilterData',fld:'vBR_LAB_ABNINDTITLEFILTERDATA',pic:''},{ctrl:'BR_LABID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_LABID","Title")',ctrl:'BR_LABID',prop:'Title'},{ctrl:'BR_LAB_TESTNAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_TESTNAME","Title")',ctrl:'BR_LAB_TESTNAME',prop:'Title'},{ctrl:'BR_LAB_SPECIMENSOURCE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_SPECIMENSOURCE","Title")',ctrl:'BR_LAB_SPECIMENSOURCE',prop:'Title'},{ctrl:'BR_LAB_SPECIMENDATE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_SPECIMENDATE","Title")',ctrl:'BR_LAB_SPECIMENDATE',prop:'Title'},{ctrl:'BR_LAB_ABNIND',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_ABNIND","Title")',ctrl:'BR_LAB_ABNIND',prop:'Title'},{av:'AV56GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV57GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV58GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'AV64IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'gx.fn.getCtrlProperty("vDISPLAY","Visible")',ctrl:'vDISPLAY',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vBACK","Visible")',ctrl:'vBACK',prop:'Visible'},{av:'AV62IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{ctrl:'BTNINSERT',prop:'Visible'}]];
   this.EvtParms["DDO_BR_LAB_SPECIMENSOURCE.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_LabIDTitleControlIdToReplace',fld:'vDDO_BR_LABIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_BR_Lab_TestNameTitleControlIdToReplace',fld:'vDDO_BR_LAB_TESTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENSOURCETITLECONTROLIDTOREPLACE',pic:''},{av:'AV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENDATETITLECONTROLIDTOREPLACE',pic:''},{av:'AV40ddo_BR_Lab_AbnIndTitleControlIdToReplace',fld:'vDDO_BR_LAB_ABNINDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV89Pgmname',fld:'vPGMNAME',pic:''},{av:'AV64IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'AV62IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'this.DDO_BR_LAB_SPECIMENSOURCEContainer.ActiveEventKey',ctrl:'DDO_BR_LAB_SPECIMENSOURCE',prop:'ActiveEventKey'}],[{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_LAB_SPECIMENSOURCEContainer.SortedStatus',ctrl:'DDO_BR_LAB_SPECIMENSOURCE',prop:'SortedStatus'},{av:'AV17BR_LabIDTitleFilterData',fld:'vBR_LABIDTITLEFILTERDATA',pic:''},{av:'AV23BR_Lab_TestNameTitleFilterData',fld:'vBR_LAB_TESTNAMETITLEFILTERDATA',pic:''},{av:'AV27BR_Lab_SpecimenSourceTitleFilterData',fld:'vBR_LAB_SPECIMENSOURCETITLEFILTERDATA',pic:''},{av:'AV25BR_Lab_SpecimenDateTitleFilterData',fld:'vBR_LAB_SPECIMENDATETITLEFILTERDATA',pic:''},{av:'AV39BR_Lab_AbnIndTitleFilterData',fld:'vBR_LAB_ABNINDTITLEFILTERDATA',pic:''},{ctrl:'BR_LABID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_LABID","Title")',ctrl:'BR_LABID',prop:'Title'},{ctrl:'BR_LAB_TESTNAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_TESTNAME","Title")',ctrl:'BR_LAB_TESTNAME',prop:'Title'},{ctrl:'BR_LAB_SPECIMENSOURCE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_SPECIMENSOURCE","Title")',ctrl:'BR_LAB_SPECIMENSOURCE',prop:'Title'},{ctrl:'BR_LAB_SPECIMENDATE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_SPECIMENDATE","Title")',ctrl:'BR_LAB_SPECIMENDATE',prop:'Title'},{ctrl:'BR_LAB_ABNIND',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_ABNIND","Title")',ctrl:'BR_LAB_ABNIND',prop:'Title'},{av:'AV56GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV57GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV58GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'AV64IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'gx.fn.getCtrlProperty("vDISPLAY","Visible")',ctrl:'vDISPLAY',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vBACK","Visible")',ctrl:'vBACK',prop:'Visible'},{av:'AV62IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{ctrl:'BTNINSERT',prop:'Visible'}]];
   this.EvtParms["DDO_BR_LAB_SPECIMENDATE.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_LabIDTitleControlIdToReplace',fld:'vDDO_BR_LABIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_BR_Lab_TestNameTitleControlIdToReplace',fld:'vDDO_BR_LAB_TESTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENSOURCETITLECONTROLIDTOREPLACE',pic:''},{av:'AV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENDATETITLECONTROLIDTOREPLACE',pic:''},{av:'AV40ddo_BR_Lab_AbnIndTitleControlIdToReplace',fld:'vDDO_BR_LAB_ABNINDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV89Pgmname',fld:'vPGMNAME',pic:''},{av:'AV64IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'AV62IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'this.DDO_BR_LAB_SPECIMENDATEContainer.ActiveEventKey',ctrl:'DDO_BR_LAB_SPECIMENDATE',prop:'ActiveEventKey'}],[{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_LAB_SPECIMENDATEContainer.SortedStatus',ctrl:'DDO_BR_LAB_SPECIMENDATE',prop:'SortedStatus'},{av:'AV17BR_LabIDTitleFilterData',fld:'vBR_LABIDTITLEFILTERDATA',pic:''},{av:'AV23BR_Lab_TestNameTitleFilterData',fld:'vBR_LAB_TESTNAMETITLEFILTERDATA',pic:''},{av:'AV27BR_Lab_SpecimenSourceTitleFilterData',fld:'vBR_LAB_SPECIMENSOURCETITLEFILTERDATA',pic:''},{av:'AV25BR_Lab_SpecimenDateTitleFilterData',fld:'vBR_LAB_SPECIMENDATETITLEFILTERDATA',pic:''},{av:'AV39BR_Lab_AbnIndTitleFilterData',fld:'vBR_LAB_ABNINDTITLEFILTERDATA',pic:''},{ctrl:'BR_LABID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_LABID","Title")',ctrl:'BR_LABID',prop:'Title'},{ctrl:'BR_LAB_TESTNAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_TESTNAME","Title")',ctrl:'BR_LAB_TESTNAME',prop:'Title'},{ctrl:'BR_LAB_SPECIMENSOURCE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_SPECIMENSOURCE","Title")',ctrl:'BR_LAB_SPECIMENSOURCE',prop:'Title'},{ctrl:'BR_LAB_SPECIMENDATE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_SPECIMENDATE","Title")',ctrl:'BR_LAB_SPECIMENDATE',prop:'Title'},{ctrl:'BR_LAB_ABNIND',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_ABNIND","Title")',ctrl:'BR_LAB_ABNIND',prop:'Title'},{av:'AV56GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV57GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV58GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'AV64IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'gx.fn.getCtrlProperty("vDISPLAY","Visible")',ctrl:'vDISPLAY',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vBACK","Visible")',ctrl:'vBACK',prop:'Visible'},{av:'AV62IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{ctrl:'BTNINSERT',prop:'Visible'}]];
   this.EvtParms["DDO_BR_LAB_ABNIND.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_LabIDTitleControlIdToReplace',fld:'vDDO_BR_LABIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_BR_Lab_TestNameTitleControlIdToReplace',fld:'vDDO_BR_LAB_TESTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_BR_Lab_SpecimenSourceTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENSOURCETITLECONTROLIDTOREPLACE',pic:''},{av:'AV26ddo_BR_Lab_SpecimenDateTitleControlIdToReplace',fld:'vDDO_BR_LAB_SPECIMENDATETITLECONTROLIDTOREPLACE',pic:''},{av:'AV40ddo_BR_Lab_AbnIndTitleControlIdToReplace',fld:'vDDO_BR_LAB_ABNINDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV89Pgmname',fld:'vPGMNAME',pic:''},{av:'AV64IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'AV62IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'this.DDO_BR_LAB_ABNINDContainer.ActiveEventKey',ctrl:'DDO_BR_LAB_ABNIND',prop:'ActiveEventKey'}],[{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_LAB_ABNINDContainer.SortedStatus',ctrl:'DDO_BR_LAB_ABNIND',prop:'SortedStatus'},{av:'AV17BR_LabIDTitleFilterData',fld:'vBR_LABIDTITLEFILTERDATA',pic:''},{av:'AV23BR_Lab_TestNameTitleFilterData',fld:'vBR_LAB_TESTNAMETITLEFILTERDATA',pic:''},{av:'AV27BR_Lab_SpecimenSourceTitleFilterData',fld:'vBR_LAB_SPECIMENSOURCETITLEFILTERDATA',pic:''},{av:'AV25BR_Lab_SpecimenDateTitleFilterData',fld:'vBR_LAB_SPECIMENDATETITLEFILTERDATA',pic:''},{av:'AV39BR_Lab_AbnIndTitleFilterData',fld:'vBR_LAB_ABNINDTITLEFILTERDATA',pic:''},{ctrl:'BR_LABID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_LABID","Title")',ctrl:'BR_LABID',prop:'Title'},{ctrl:'BR_LAB_TESTNAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_TESTNAME","Title")',ctrl:'BR_LAB_TESTNAME',prop:'Title'},{ctrl:'BR_LAB_SPECIMENSOURCE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_SPECIMENSOURCE","Title")',ctrl:'BR_LAB_SPECIMENSOURCE',prop:'Title'},{ctrl:'BR_LAB_SPECIMENDATE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_SPECIMENDATE","Title")',ctrl:'BR_LAB_SPECIMENDATE',prop:'Title'},{ctrl:'BR_LAB_ABNIND',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_LAB_ABNIND","Title")',ctrl:'BR_LAB_ABNIND',prop:'Title'},{av:'AV56GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV57GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV58GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'AV64IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'gx.fn.getCtrlProperty("vDISPLAY","Visible")',ctrl:'vDISPLAY',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vBACK","Visible")',ctrl:'vBACK',prop:'Visible'},{av:'AV62IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{ctrl:'BTNINSERT',prop:'Visible'}]];
   this.EvtParms["GRID.LOAD"] = [[{av:'AV64IsAuthorized_Display',fld:'vISAUTHORIZED_DISPLAY',pic:''},{av:'A101BR_LabID',fld:'BR_LABID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true},{av:'AV62IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''}],[{av:'AV63Display',fld:'vDISPLAY',pic:''},{av:'gx.fn.getCtrlProperty("vDISPLAY","Tooltiptext")',ctrl:'vDISPLAY',prop:'Tooltiptext'},{av:'gx.fn.getCtrlProperty("vDISPLAY","Link")',ctrl:'vDISPLAY',prop:'Link'},{av:'AV80back',fld:'vBACK',pic:''},{av:'gx.fn.getCtrlProperty("vBACK","Tooltiptext")',ctrl:'vBACK',prop:'Tooltiptext'},{av:'AV61Delete',fld:'vDELETE',pic:''},{av:'gx.fn.getCtrlProperty("vDELETE","Tooltiptext")',ctrl:'vDELETE',prop:'Tooltiptext'},{av:'gx.fn.getCtrlProperty("vDELETE","Link")',ctrl:'vDELETE',prop:'Link'}]];
   this.EvtParms["'DOINSERT'"] = [[{av:'A101BR_LabID',fld:'BR_LABID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true},{av:'AV8BR_EncounterID',fld:'vBR_ENCOUNTERID',pic:'ZZZZZZZZZZZZZZZZZZ'}],[]];
   this.EvtParms["VBACK.CLICK"] = [[{av:'A101BR_LabID',fld:'BR_LABID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true}],[]];
   this.EvtParms["VDELETE.CLICK"] = [[{av:'A101BR_LabID',fld:'BR_LABID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true}],[]];
   this.setVCMap("AV89Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV64IsAuthorized_Display", "vISAUTHORIZED_DISPLAY", 0, "boolean", 4, 0);
   this.setVCMap("AV62IsAuthorized_Delete", "vISAUTHORIZED_DELETE", 0, "boolean", 4, 0);
   this.setVCMap("AV8BR_EncounterID", "vBR_ENCOUNTERID", 0, "int", 18, 0);
   this.setVCMap("AV8BR_EncounterID", "vBR_ENCOUNTERID", 0, "int", 18, 0);
   this.setVCMap("AV89Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV64IsAuthorized_Display", "vISAUTHORIZED_DISPLAY", 0, "boolean", 4, 0);
   this.setVCMap("AV62IsAuthorized_Delete", "vISAUTHORIZED_DELETE", 0, "boolean", 4, 0);
   this.setVCMap("AV8BR_EncounterID", "vBR_ENCOUNTERID", 0, "int", 18, 0);
   this.setVCMap("AV89Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV64IsAuthorized_Display", "vISAUTHORIZED_DISPLAY", 0, "boolean", 4, 0);
   this.setVCMap("AV62IsAuthorized_Delete", "vISAUTHORIZED_DELETE", 0, "boolean", 4, 0);
   GridContainer.addRefreshingVar(this.GXValidFnc[56]);
   GridContainer.addRefreshingVar(this.GXValidFnc[57]);
   GridContainer.addRefreshingVar({rfrVar:"AV8BR_EncounterID"});
   GridContainer.addRefreshingVar(this.GXValidFnc[45]);
   GridContainer.addRefreshingVar(this.GXValidFnc[47]);
   GridContainer.addRefreshingVar(this.GXValidFnc[49]);
   GridContainer.addRefreshingVar(this.GXValidFnc[51]);
   GridContainer.addRefreshingVar(this.GXValidFnc[53]);
   GridContainer.addRefreshingVar({rfrVar:"AV89Pgmname"});
   GridContainer.addRefreshingVar({rfrVar:"AV64IsAuthorized_Display"});
   GridContainer.addRefreshingVar({rfrVar:"AV62IsAuthorized_Delete"});
   this.Initialize( );
});
