/*!   GeneXus C# 16_0_0-127771 on 2/27/2020 9:39:36.14
*/
gx.evt.autoSkip = false;
gx.define('br_informationww', false, function () {
   this.ServerClass =  "br_informationww" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.hasEnterEvent = false;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV6WWPContext=gx.fn.getControlValue("vWWPCONTEXT") ;
      this.AV154Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.AV142IsAuthorized_PatientReTenant=gx.fn.getControlValue("vISAUTHORIZED_PATIENTRETENANT") ;
      this.AV140IsAuthorized_Patient_Entity=gx.fn.getControlValue("vISAUTHORIZED_PATIENT_ENTITY") ;
      this.AV125tTemNum=gx.fn.getIntegerValue("vTTEMNUM",',') ;
      this.AV6WWPContext=gx.fn.getControlValue("vWWPCONTEXT") ;
      this.AV154Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.AV142IsAuthorized_PatientReTenant=gx.fn.getControlValue("vISAUTHORIZED_PATIENTRETENANT") ;
      this.AV140IsAuthorized_Patient_Entity=gx.fn.getControlValue("vISAUTHORIZED_PATIENT_ENTITY") ;
   };
   this.e191g2_client=function()
   {
      this.clearMessages();
      this.call("br_informationoperate.aspx", [2, this.A85BR_Information_ID]);
      this.refreshOutputs([]);
      return gx.$.Deferred().resolve();
   };
   this.e111g2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEPAGE", false, null, true, true);
   };
   this.e121g2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", false, null, true, true);
   };
   this.e131g2_client=function()
   {
      return this.executeServerEvent("DDO_BR_INFORMATION_PATIENTNO.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e141g2_client=function()
   {
      return this.executeServerEvent("'DOINSERT'", false, null, false, false);
   };
   this.e181g2_client=function()
   {
      return this.executeServerEvent("'DOADD'", true, arguments[0], false, false);
   };
   this.e201g2_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e211g2_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,33,34,35,36,37,38,39,40,41,42,44,45,46,48,50,51];
   this.GXLastCtrlId =51;
   this.GridContainer = new gx.grid.grid(this, 2,"WbpLvl2",32,"Grid","Grid","GridContainer",this.CmpContext,this.IsMasterPage,"br_informationww",[],false,1,false,true,0,false,false,false,"",0,"px",0,"px","澧炲姞绌虹櫧琛?,true,false,false,null,null,false,"",false,[1,1,1,1],false,0,true,false);
   var GridContainer = this.GridContainer;
   GridContainer.addBitmap("&Myupdate","vMYUPDATE",33,0,"px",17,"px","e191g2_client","","","ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addBitmap("&Patientretenant","vPATIENTRETENANT",34,0,"px",17,"px",null,"","","ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addBitmap("&Patient_entity","vPATIENT_ENTITY",35,0,"px",17,"px",null,"","","ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addSingleLineEdit(85,36,"BR_INFORMATION_ID","ID","","BR_Information_ID","int",0,"px",18,18,"right",null,[],85,"BR_Information_ID",false,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(36,37,"BR_INFORMATION_PATIENTNO","","","BR_Information_PatientNo","svchar",410,"px",2000,80,"left",null,[],36,"BR_Information_PatientNo",true,0,false,false,"Attribute",1,"WWColumn");
   GridContainer.addSingleLineEdit(100,38,"BR_INFORMATION_BIRTHDATE","鎮ｈ€呭嚭鐢熸棩鏈?,"","BR_Information_BirthDate","date",102,"px",10,10,"right",null,[],100,"BR_Information_BirthDate",false,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(95,39,"BR_INFORMATION_CRTDATE","鍒涘缓鏃ユ湡","","BR_Information_CrtDate","dtime",0,"px",19,19,"right",null,[],95,"BR_Information_CrtDate",false,8,false,false,"Attribute",1,"WWColumn");
   this.GridContainer.emptyText = "";
   this.setGrid(GridContainer);
   this.DVPANEL_TABLEHEADERContainer = gx.uc.getNew(this, 10, 0, "BootstrapPanel", "DVPANEL_TABLEHEADERContainer", "Dvpanel_tableheader", "DVPANEL_TABLEHEADER");
   var DVPANEL_TABLEHEADERContainer = this.DVPANEL_TABLEHEADERContainer;
   DVPANEL_TABLEHEADERContainer.setProp("Class", "Class", "", "char");
   DVPANEL_TABLEHEADERContainer.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_TABLEHEADERContainer.setProp("Width", "Width", "100%", "str");
   DVPANEL_TABLEHEADERContainer.setProp("Height", "Height", "100", "str");
   DVPANEL_TABLEHEADERContainer.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Cls", "Cls", "PanelNoHeader", "str");
   DVPANEL_TABLEHEADERContainer.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Title", "Title", "閫夐」", "str");
   DVPANEL_TABLEHEADERContainer.setProp("Collapsible", "Collapsible", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("IconPosition", "Iconposition", "left", "str");
   DVPANEL_TABLEHEADERContainer.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Visible", "Visible", true, "bool");
   DVPANEL_TABLEHEADERContainer.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_TABLEHEADERContainer);
   this.GRIDPAGINATIONBARContainer = gx.uc.getNew(this, 43, 26, "DVelop_DVPaginationBar", "GRIDPAGINATIONBARContainer", "Gridpaginationbar", "GRIDPAGINATIONBAR");
   var GRIDPAGINATIONBARContainer = this.GRIDPAGINATIONBARContainer;
   GRIDPAGINATIONBARContainer.setProp("Enabled", "Enabled", true, "boolean");
   GRIDPAGINATIONBARContainer.setProp("Class", "Class", "PaginationBar", "str");
   GRIDPAGINATIONBARContainer.setProp("ShowFirst", "Showfirst", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowPrevious", "Showprevious", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowNext", "Shownext", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowLast", "Showlast", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("PagesToShow", "Pagestoshow", 5, "num");
   GRIDPAGINATIONBARContainer.setProp("PagingButtonsPosition", "Pagingbuttonsposition", "Right", "str");
   GRIDPAGINATIONBARContainer.setProp("PagingCaptionPosition", "Pagingcaptionposition", "Left", "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridClass", "Emptygridclass", "PaginationBarEmptyGrid", "str");
   GRIDPAGINATIONBARContainer.setProp("SelectedPage", "Selectedpage", "", "char");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageSelector", "Rowsperpageselector", true, "bool");
   GRIDPAGINATIONBARContainer.setDynProp("RowsPerPageSelectedValue", "Rowsperpageselectedvalue", 10, "num");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageOptions", "Rowsperpageoptions", "5:WWP_Rows5,10:WWP_Rows10,20:WWP_Rows20,50:WWP_Rows50", "str");
   GRIDPAGINATIONBARContainer.setProp("First", "First", "First", "str");
   GRIDPAGINATIONBARContainer.setProp("Previous", "Previous", "WWP_PagingPreviousCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Next", "Next", "WWP_PagingNextCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Last", "Last", "Last", "str");
   GRIDPAGINATIONBARContainer.setProp("Caption", "Caption", "<CURRENT_PAGE>椤?<TOTAL_PAGES>椤?璁板綍锛?TOTAL_RECORDS>鏉?, "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridCaption", "Emptygridcaption", "WWP_PagingEmptyGridCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageCaption", "Rowsperpagecaption", "WWP_PagingRowsPerPage", "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV93GridCurrentPage', "vGRIDCURRENTPAGE", 'SetCurrentPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV93GridCurrentPage=UC.GetCurrentPage();gx.fn.setControlValue("vGRIDCURRENTPAGE",UC.ParentObject.AV93GridCurrentPage); });
   GRIDPAGINATIONBARContainer.setProp("PageCount", "Pagecount", '', "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV95GridRecordCount', "vGRIDRECORDCOUNT", 'SetRecordCount');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV95GridRecordCount=UC.GetRecordCount();gx.fn.setControlValue("vGRIDRECORDCOUNT",UC.ParentObject.AV95GridRecordCount); });
   GRIDPAGINATIONBARContainer.addV2CFunction('AV94GridPageSize', "vGRIDPAGESIZE", 'SetPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV94GridPageSize=UC.GetPage();gx.fn.setControlValue("vGRIDPAGESIZE",UC.ParentObject.AV94GridPageSize); });
   GRIDPAGINATIONBARContainer.setProp("Visible", "Visible", true, "bool");
   GRIDPAGINATIONBARContainer.setC2ShowFunction(function(UC) { UC.show(); });
   GRIDPAGINATIONBARContainer.addEventHandler("ChangePage", this.e111g2_client);
   GRIDPAGINATIONBARContainer.addEventHandler("ChangeRowsPerPage", this.e121g2_client);
   this.setUserControl(GRIDPAGINATIONBARContainer);
   this.DDO_BR_INFORMATION_PATIENTNOContainer = gx.uc.getNew(this, 47, 26, "BootstrapDropDownOptions", "DDO_BR_INFORMATION_PATIENTNOContainer", "Ddo_br_information_patientno", "DDO_BR_INFORMATION_PATIENTNO");
   var DDO_BR_INFORMATION_PATIENTNOContainer = this.DDO_BR_INFORMATION_PATIENTNOContainer;
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("Class", "Class", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_INFORMATION_PATIENTNOContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_INFORMATION_PATIENTNOContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_INFORMATION_PATIENTNOContainer.addV2CFunction('AV91DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_INFORMATION_PATIENTNOContainer.addC2VFunction(function(UC) { UC.ParentObject.AV91DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV91DDO_TitleSettingsIcons); });
   DDO_BR_INFORMATION_PATIENTNOContainer.addV2CFunction('AV49BR_Information_PatientNoTitleFilterData', "vBR_INFORMATION_PATIENTNOTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_INFORMATION_PATIENTNOContainer.addC2VFunction(function(UC) { UC.ParentObject.AV49BR_Information_PatientNoTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_INFORMATION_PATIENTNOTITLEFILTERDATA",UC.ParentObject.AV49BR_Information_PatientNoTitleFilterData); });
   DDO_BR_INFORMATION_PATIENTNOContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_INFORMATION_PATIENTNOContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_INFORMATION_PATIENTNOContainer.addEventHandler("OnOptionClicked", this.e131g2_client);
   this.setUserControl(DDO_BR_INFORMATION_PATIENTNOContainer);
   this.WORKWITHPLUSUTILITIES1Container = gx.uc.getNew(this, 49, 26, "DVelop_WorkWithPlusUtilities", "WORKWITHPLUSUTILITIES1Container", "Workwithplusutilities1", "WORKWITHPLUSUTILITIES1");
   var WORKWITHPLUSUTILITIES1Container = this.WORKWITHPLUSUTILITIES1Container;
   WORKWITHPLUSUTILITIES1Container.setProp("Class", "Class", "", "char");
   WORKWITHPLUSUTILITIES1Container.setProp("Enabled", "Enabled", true, "boolean");
   WORKWITHPLUSUTILITIES1Container.setProp("Width", "Width", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Height", "Height", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Visible", "Visible", true, "bool");
   WORKWITHPLUSUTILITIES1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(WORKWITHPLUSUTILITIES1Container);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEMAIN",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"HTML_DVPANEL_TABLEHEADER",grid:0};
   GXValidFnc[12]={ id: 12, fld:"LAYOUT_TABLEHEADER",grid:0};
   GXValidFnc[13]={ id: 13, fld:"",grid:0};
   GXValidFnc[14]={ id: 14, fld:"TABLEHEADER",grid:0};
   GXValidFnc[15]={ id: 15, fld:"",grid:0};
   GXValidFnc[16]={ id: 16, fld:"",grid:0};
   GXValidFnc[17]={ id: 17, fld:"TABLEACTIONS",grid:0};
   GXValidFnc[18]={ id: 18, fld:"",grid:0};
   GXValidFnc[19]={ id: 19, fld:"",grid:0};
   GXValidFnc[20]={ id: 20, fld:"",grid:0};
   GXValidFnc[21]={ id: 21, fld:"",grid:0};
   GXValidFnc[22]={ id: 22, fld:"BTNINSERT",grid:0};
   GXValidFnc[23]={ id: 23, fld:"",grid:0};
   GXValidFnc[24]={ id: 24, fld:"",grid:0};
   GXValidFnc[25]={ id: 25, fld:"",grid:0};
   GXValidFnc[26]={ id:26 ,lvl:0,type:"svchar",len:2000,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vBR_INFORMATION_PATIENTNO",gxz:"ZV17BR_Information_PatientNo",gxold:"OV17BR_Information_PatientNo",gxvar:"AV17BR_Information_PatientNo",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV17BR_Information_PatientNo=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV17BR_Information_PatientNo=Value},v2c:function(){gx.fn.setControlValue("vBR_INFORMATION_PATIENTNO",gx.O.AV17BR_Information_PatientNo,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV17BR_Information_PatientNo=this.val()},val:function(){return gx.fn.getControlValue("vBR_INFORMATION_PATIENTNO")},nac:gx.falseFn};
   GXValidFnc[27]={ id: 27, fld:"",grid:0};
   GXValidFnc[28]={ id: 28, fld:"",grid:0};
   GXValidFnc[29]={ id: 29, fld:"GRIDTABLEWITHPAGINATIONBAR",grid:0};
   GXValidFnc[30]={ id: 30, fld:"",grid:0};
   GXValidFnc[31]={ id: 31, fld:"",grid:0};
   GXValidFnc[33]={ id:33 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:32,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vMYUPDATE",gxz:"ZV126myupdate",gxold:"OV126myupdate",gxvar:"AV126myupdate",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV126myupdate=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV126myupdate=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vMYUPDATE",row || gx.fn.currentGridRowImpl(32),gx.O.AV126myupdate,gx.O.AV151Myupdate_GXI)},c2v:function(){gx.O.AV151Myupdate_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV126myupdate=this.val()},val:function(row){return gx.fn.getGridControlValue("vMYUPDATE",row || gx.fn.currentGridRowImpl(32))},val_GXI:function(row){return gx.fn.getGridControlValue("vMYUPDATE_GXI",row || gx.fn.currentGridRowImpl(32))}, gxvar_GXI:'AV151Myupdate_GXI',nac:gx.falseFn,evt:"e191g2_client"};
   GXValidFnc[34]={ id:34 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:32,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vPATIENTRETENANT",gxz:"ZV141PatientReTenant",gxold:"OV141PatientReTenant",gxvar:"AV141PatientReTenant",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV141PatientReTenant=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV141PatientReTenant=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vPATIENTRETENANT",row || gx.fn.currentGridRowImpl(32),gx.O.AV141PatientReTenant,gx.O.AV152Patientretenant_GXI)},c2v:function(){gx.O.AV152Patientretenant_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV141PatientReTenant=this.val()},val:function(row){return gx.fn.getGridControlValue("vPATIENTRETENANT",row || gx.fn.currentGridRowImpl(32))},val_GXI:function(row){return gx.fn.getGridControlValue("vPATIENTRETENANT_GXI",row || gx.fn.currentGridRowImpl(32))}, gxvar_GXI:'AV152Patientretenant_GXI',nac:gx.falseFn};
   GXValidFnc[35]={ id:35 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:32,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vPATIENT_ENTITY",gxz:"ZV139Patient_Entity",gxold:"OV139Patient_Entity",gxvar:"AV139Patient_Entity",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV139Patient_Entity=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV139Patient_Entity=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vPATIENT_ENTITY",row || gx.fn.currentGridRowImpl(32),gx.O.AV139Patient_Entity,gx.O.AV153Patient_entity_GXI)},c2v:function(){gx.O.AV153Patient_entity_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV139Patient_Entity=this.val()},val:function(row){return gx.fn.getGridControlValue("vPATIENT_ENTITY",row || gx.fn.currentGridRowImpl(32))},val_GXI:function(row){return gx.fn.getGridControlValue("vPATIENT_ENTITY_GXI",row || gx.fn.currentGridRowImpl(32))}, gxvar_GXI:'AV153Patient_entity_GXI',nac:gx.falseFn};
   GXValidFnc[36]={ id:36 ,lvl:2,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,isacc:0,grid:32,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_INFORMATION_ID",gxz:"Z85BR_Information_ID",gxold:"O85BR_Information_ID",gxvar:"A85BR_Information_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A85BR_Information_ID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z85BR_Information_ID=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("BR_INFORMATION_ID",row || gx.fn.currentGridRowImpl(32),gx.O.A85BR_Information_ID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A85BR_Information_ID=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("BR_INFORMATION_ID",row || gx.fn.currentGridRowImpl(32),',')},nac:gx.falseFn};
   GXValidFnc[37]={ id:37 ,lvl:2,type:"svchar",len:2000,dec:0,sign:false,ro:1,isacc:0,grid:32,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_INFORMATION_PATIENTNO",gxz:"Z36BR_Information_PatientNo",gxold:"O36BR_Information_PatientNo",gxvar:"A36BR_Information_PatientNo",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A36BR_Information_PatientNo=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z36BR_Information_PatientNo=Value},v2c:function(row){gx.fn.setGridControlValue("BR_INFORMATION_PATIENTNO",row || gx.fn.currentGridRowImpl(32),gx.O.A36BR_Information_PatientNo,0)},c2v:function(){if(this.val()!==undefined)gx.O.A36BR_Information_PatientNo=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_INFORMATION_PATIENTNO",row || gx.fn.currentGridRowImpl(32))},nac:gx.falseFn};
   GXValidFnc[38]={ id:38 ,lvl:2,type:"date",len:10,dec:0,sign:false,ro:1,isacc:0,grid:32,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_INFORMATION_BIRTHDATE",gxz:"Z100BR_Information_BirthDate",gxold:"O100BR_Information_BirthDate",gxvar:"A100BR_Information_BirthDate",dp:{f:0,st:false,wn:false,mf:false,pic:"99/99/9999",dec:0},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.A100BR_Information_BirthDate=gx.fn.toDatetimeValue(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z100BR_Information_BirthDate=gx.fn.toDatetimeValue(Value)},v2c:function(row){gx.fn.setGridControlValue("BR_INFORMATION_BIRTHDATE",row || gx.fn.currentGridRowImpl(32),gx.O.A100BR_Information_BirthDate,0)},c2v:function(){if(this.val()!==undefined)gx.O.A100BR_Information_BirthDate=gx.fn.toDatetimeValue(this.val())},val:function(row){return gx.fn.getGridDateTimeValue("BR_INFORMATION_BIRTHDATE",row || gx.fn.currentGridRowImpl(32))},nac:gx.falseFn};
   GXValidFnc[39]={ id:39 ,lvl:2,type:"dtime",len:10,dec:8,sign:false,ro:1,isacc:0,grid:32,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_INFORMATION_CRTDATE",gxz:"Z95BR_Information_CrtDate",gxold:"O95BR_Information_CrtDate",gxvar:"A95BR_Information_CrtDate",dp:{f:0,st:true,wn:false,mf:false,pic:"99/99/9999 99:99:99",dec:8},ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.A95BR_Information_CrtDate=gx.fn.toDatetimeValue(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z95BR_Information_CrtDate=gx.fn.toDatetimeValue(Value)},v2c:function(row){gx.fn.setGridControlValue("BR_INFORMATION_CRTDATE",row || gx.fn.currentGridRowImpl(32),gx.O.A95BR_Information_CrtDate,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A95BR_Information_CrtDate=gx.fn.toDatetimeValue(this.val())},val:function(row){return gx.fn.getGridDateTimeValue("BR_INFORMATION_CRTDATE",row || gx.fn.currentGridRowImpl(32))},nac:gx.falseFn};
   GXValidFnc[40]={ id: 40, fld:"",grid:0};
   GXValidFnc[41]={ id: 41, fld:"",grid:0};
   GXValidFnc[42]={ id: 42, fld:"HTML_GRIDPAGINATIONBAR",grid:0};
   GXValidFnc[44]={ id: 44, fld:"",grid:0};
   GXValidFnc[45]={ id: 45, fld:"",grid:0};
   GXValidFnc[46]={ id: 46, fld:"HTML_BOTTOMAUXILIARCONTROLS",grid:0};
   GXValidFnc[48]={ id:48 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_INFORMATION_PATIENTNOTITLECONTROLIDTOREPLACE",gxz:"ZV52ddo_BR_Information_PatientNoTitleControlIdToReplace",gxold:"OV52ddo_BR_Information_PatientNoTitleControlIdToReplace",gxvar:"AV52ddo_BR_Information_PatientNoTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV52ddo_BR_Information_PatientNoTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV52ddo_BR_Information_PatientNoTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_INFORMATION_PATIENTNOTITLECONTROLIDTOREPLACE",gx.O.AV52ddo_BR_Information_PatientNoTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV52ddo_BR_Information_PatientNoTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_INFORMATION_PATIENTNOTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[50]={ id:50 ,lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDBY",gxz:"ZV13OrderedBy",gxold:"OV13OrderedBy",gxvar:"AV13OrderedBy",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV13OrderedBy=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV13OrderedBy=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDBY",gx.O.AV13OrderedBy,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV13OrderedBy=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vORDEREDBY",',')},nac:gx.falseFn};
   GXValidFnc[51]={ id:51 ,lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDDSC",gxz:"ZV14OrderedDsc",gxold:"OV14OrderedDsc",gxvar:"AV14OrderedDsc",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV14OrderedDsc=gx.lang.booleanValue(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV14OrderedDsc=gx.lang.booleanValue(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDDSC",gx.O.AV14OrderedDsc,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV14OrderedDsc=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getControlValue("vORDEREDDSC")},nac:gx.falseFn};
   this.AV17BR_Information_PatientNo = "" ;
   this.ZV17BR_Information_PatientNo = "" ;
   this.OV17BR_Information_PatientNo = "" ;
   this.ZV126myupdate = "" ;
   this.OV126myupdate = "" ;
   this.ZV141PatientReTenant = "" ;
   this.OV141PatientReTenant = "" ;
   this.ZV139Patient_Entity = "" ;
   this.OV139Patient_Entity = "" ;
   this.Z85BR_Information_ID = 0 ;
   this.O85BR_Information_ID = 0 ;
   this.Z36BR_Information_PatientNo = "" ;
   this.O36BR_Information_PatientNo = "" ;
   this.Z100BR_Information_BirthDate = gx.date.nullDate() ;
   this.O100BR_Information_BirthDate = gx.date.nullDate() ;
   this.Z95BR_Information_CrtDate = gx.date.nullDate() ;
   this.O95BR_Information_CrtDate = gx.date.nullDate() ;
   this.AV52ddo_BR_Information_PatientNoTitleControlIdToReplace = "" ;
   this.ZV52ddo_BR_Information_PatientNoTitleControlIdToReplace = "" ;
   this.OV52ddo_BR_Information_PatientNoTitleControlIdToReplace = "" ;
   this.AV13OrderedBy = 0 ;
   this.ZV13OrderedBy = 0 ;
   this.OV13OrderedBy = 0 ;
   this.AV14OrderedDsc = false ;
   this.ZV14OrderedDsc = false ;
   this.OV14OrderedDsc = false ;
   this.AV17BR_Information_PatientNo = "" ;
   this.AV93GridCurrentPage = 0 ;
   this.AV91DDO_TitleSettingsIcons = {Default:"",Default_GXI:"",Filtered:"",Filtered_GXI:"",SortedASC:"",SortedASC_GXI:"",SortedDSC:"",SortedDSC_GXI:"",FilteredSortedASC:"",FilteredSortedASC_GXI:"",FilteredSortedDSC:"",FilteredSortedDSC_GXI:"",OptionSortASC:"",OptionSortASC_GXI:"",OptionSortDSC:"",OptionSortDSC_GXI:"",OptionApplyFilter:"",OptionApplyFilter_GXI:"",OptionFilteringData:"",OptionFilteringData_GXI:"",OptionCleanFilters:"",OptionCleanFilters_GXI:"",SelectedOption:"",SelectedOption_GXI:"",MultiselOption:"",MultiselOption_GXI:"",MultiselSelOption:"",MultiselSelOption_GXI:""} ;
   this.AV52ddo_BR_Information_PatientNoTitleControlIdToReplace = "" ;
   this.AV13OrderedBy = 0 ;
   this.AV14OrderedDsc = false ;
   this.AV126myupdate = "" ;
   this.AV141PatientReTenant = "" ;
   this.AV139Patient_Entity = "" ;
   this.A85BR_Information_ID = 0 ;
   this.A36BR_Information_PatientNo = "" ;
   this.A100BR_Information_BirthDate = gx.date.nullDate() ;
   this.A95BR_Information_CrtDate = gx.date.nullDate() ;
   this.AV6WWPContext = {UserId:0,UserGUID:"",UserName:"",UserType:0,UserDisplayName:"",UserProviderID:0,UserProviderName:"",currentTNum:0,ClientIP:""} ;
   this.AV154Pgmname = "" ;
   this.AV142IsAuthorized_PatientReTenant = false ;
   this.AV140IsAuthorized_Patient_Entity = false ;
   this.AV125tTemNum = 0 ;
   this.Events = {"e111g2_client": ["GRIDPAGINATIONBAR.CHANGEPAGE", true] ,"e121g2_client": ["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", true] ,"e131g2_client": ["DDO_BR_INFORMATION_PATIENTNO.ONOPTIONCLICKED", true] ,"e141g2_client": ["'DOINSERT'", true] ,"e181g2_client": ["'DOADD'", true] ,"e201g2_client": ["ENTER", true] ,"e211g2_client": ["CANCEL", true] ,"e191g2_client": ["VMYUPDATE.CLICK", false]};
   this.EvtParms["REFRESH"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'AV142IsAuthorized_PatientReTenant',fld:'vISAUTHORIZED_PATIENTRETENANT',pic:''},{av:'AV140IsAuthorized_Patient_Entity',fld:'vISAUTHORIZED_PATIENT_ENTITY',pic:''},{av:'AV6WWPContext',fld:'vWWPCONTEXT',pic:''},{av:'AV52ddo_BR_Information_PatientNoTitleControlIdToReplace',fld:'vDDO_BR_INFORMATION_PATIENTNOTITLECONTROLIDTOREPLACE',pic:''},{ctrl:'GRID',prop:'Rows'},{av:'AV17BR_Information_PatientNo',fld:'vBR_INFORMATION_PATIENTNO',pic:''},{av:'AV154Pgmname',fld:'vPGMNAME',pic:''},{av:'AV13OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV14OrderedDsc',fld:'vORDEREDDSC',pic:''}],[{av:'AV49BR_Information_PatientNoTitleFilterData',fld:'vBR_INFORMATION_PATIENTNOTITLEFILTERDATA',pic:''},{av:'AV6WWPContext',fld:'vWWPCONTEXT',pic:''},{ctrl:'BR_INFORMATION_PATIENTNO',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_INFORMATION_PATIENTNO","Title")',ctrl:'BR_INFORMATION_PATIENTNO',prop:'Title'},{av:'AV93GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV94GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV95GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'gx.fn.getCtrlProperty("vMYUPDATE","Visible")',ctrl:'vMYUPDATE',prop:'Visible'},{av:'AV142IsAuthorized_PatientReTenant',fld:'vISAUTHORIZED_PATIENTRETENANT',pic:''},{av:'gx.fn.getCtrlProperty("vPATIENTRETENANT","Visible")',ctrl:'vPATIENTRETENANT',prop:'Visible'},{av:'AV140IsAuthorized_Patient_Entity',fld:'vISAUTHORIZED_PATIENT_ENTITY',pic:''},{av:'gx.fn.getCtrlProperty("vPATIENT_ENTITY","Visible")',ctrl:'vPATIENT_ENTITY',prop:'Visible'},{ctrl:'BTNINSERT',prop:'Visible'}]];
   this.EvtParms["START"] = [[{av:'AV13OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV154Pgmname',fld:'vPGMNAME',pic:''}],[{ctrl:'GRID',prop:'Rows'},{av:'this.DDO_BR_INFORMATION_PATIENTNOContainer.TitleControlIdToReplace',ctrl:'DDO_BR_INFORMATION_PATIENTNO',prop:'TitleControlIdToReplace'},{av:'AV52ddo_BR_Information_PatientNoTitleControlIdToReplace',fld:'vDDO_BR_INFORMATION_PATIENTNOTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_INFORMATION_PATIENTNOTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_INFORMATION_PATIENTNOTITLECONTROLIDTOREPLACE',prop:'Visible'},{ctrl:'FORM',prop:'Caption'},{av:'gx.fn.getCtrlProperty("vORDEREDBY","Visible")',ctrl:'vORDEREDBY',prop:'Visible'},{av:'AV13OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'gx.fn.getCtrlProperty("vORDEREDDSC","Visible")',ctrl:'vORDEREDDSC',prop:'Visible'},{av:'AV91DDO_TitleSettingsIcons',fld:'vDDO_TITLESETTINGSICONS',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'},{av:'AV14OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV17BR_Information_PatientNo',fld:'vBR_INFORMATION_PATIENTNO',pic:''}]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV17BR_Information_PatientNo',fld:'vBR_INFORMATION_PATIENTNO',pic:''},{av:'AV13OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV14OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV6WWPContext',fld:'vWWPCONTEXT',pic:''},{av:'AV52ddo_BR_Information_PatientNoTitleControlIdToReplace',fld:'vDDO_BR_INFORMATION_PATIENTNOTITLECONTROLIDTOREPLACE',pic:''},{av:'AV154Pgmname',fld:'vPGMNAME',pic:''},{av:'AV142IsAuthorized_PatientReTenant',fld:'vISAUTHORIZED_PATIENTRETENANT',pic:''},{av:'AV140IsAuthorized_Patient_Entity',fld:'vISAUTHORIZED_PATIENT_ENTITY',pic:''},{av:'this.GRIDPAGINATIONBARContainer.SelectedPage',ctrl:'GRIDPAGINATIONBAR',prop:'SelectedPage'}],[]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV17BR_Information_PatientNo',fld:'vBR_INFORMATION_PATIENTNO',pic:''},{av:'AV13OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV14OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV6WWPContext',fld:'vWWPCONTEXT',pic:''},{av:'AV52ddo_BR_Information_PatientNoTitleControlIdToReplace',fld:'vDDO_BR_INFORMATION_PATIENTNOTITLECONTROLIDTOREPLACE',pic:''},{av:'AV154Pgmname',fld:'vPGMNAME',pic:''},{av:'AV142IsAuthorized_PatientReTenant',fld:'vISAUTHORIZED_PATIENTRETENANT',pic:''},{av:'AV140IsAuthorized_Patient_Entity',fld:'vISAUTHORIZED_PATIENT_ENTITY',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}],[{ctrl:'GRID',prop:'Rows'}]];
   this.EvtParms["DDO_BR_INFORMATION_PATIENTNO.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV17BR_Information_PatientNo',fld:'vBR_INFORMATION_PATIENTNO',pic:''},{av:'AV13OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV14OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV6WWPContext',fld:'vWWPCONTEXT',pic:''},{av:'AV52ddo_BR_Information_PatientNoTitleControlIdToReplace',fld:'vDDO_BR_INFORMATION_PATIENTNOTITLECONTROLIDTOREPLACE',pic:''},{av:'AV154Pgmname',fld:'vPGMNAME',pic:''},{av:'AV142IsAuthorized_PatientReTenant',fld:'vISAUTHORIZED_PATIENTRETENANT',pic:''},{av:'AV140IsAuthorized_Patient_Entity',fld:'vISAUTHORIZED_PATIENT_ENTITY',pic:''},{av:'this.DDO_BR_INFORMATION_PATIENTNOContainer.ActiveEventKey',ctrl:'DDO_BR_INFORMATION_PATIENTNO',prop:'ActiveEventKey'}],[{av:'AV13OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV14OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_INFORMATION_PATIENTNOContainer.SortedStatus',ctrl:'DDO_BR_INFORMATION_PATIENTNO',prop:'SortedStatus'},{av:'AV49BR_Information_PatientNoTitleFilterData',fld:'vBR_INFORMATION_PATIENTNOTITLEFILTERDATA',pic:''},{av:'AV6WWPContext',fld:'vWWPCONTEXT',pic:''},{ctrl:'BR_INFORMATION_PATIENTNO',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_INFORMATION_PATIENTNO","Title")',ctrl:'BR_INFORMATION_PATIENTNO',prop:'Title'},{av:'AV93GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV94GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV95GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'gx.fn.getCtrlProperty("vMYUPDATE","Visible")',ctrl:'vMYUPDATE',prop:'Visible'},{av:'AV142IsAuthorized_PatientReTenant',fld:'vISAUTHORIZED_PATIENTRETENANT',pic:''},{av:'gx.fn.getCtrlProperty("vPATIENTRETENANT","Visible")',ctrl:'vPATIENTRETENANT',prop:'Visible'},{av:'AV140IsAuthorized_Patient_Entity',fld:'vISAUTHORIZED_PATIENT_ENTITY',pic:''},{av:'gx.fn.getCtrlProperty("vPATIENT_ENTITY","Visible")',ctrl:'vPATIENT_ENTITY',prop:'Visible'},{ctrl:'BTNINSERT',prop:'Visible'}]];
   this.EvtParms["GRID.LOAD"] = [[{av:'AV142IsAuthorized_PatientReTenant',fld:'vISAUTHORIZED_PATIENTRETENANT',pic:''},{av:'A85BR_Information_ID',fld:'BR_INFORMATION_ID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true},{av:'AV140IsAuthorized_Patient_Entity',fld:'vISAUTHORIZED_PATIENT_ENTITY',pic:''}],[{av:'AV126myupdate',fld:'vMYUPDATE',pic:''},{av:'gx.fn.getCtrlProperty("vMYUPDATE","Tooltiptext")',ctrl:'vMYUPDATE',prop:'Tooltiptext'},{av:'AV141PatientReTenant',fld:'vPATIENTRETENANT',pic:''},{av:'gx.fn.getCtrlProperty("vPATIENTRETENANT","Tooltiptext")',ctrl:'vPATIENTRETENANT',prop:'Tooltiptext'},{av:'gx.fn.getCtrlProperty("vPATIENTRETENANT","Link")',ctrl:'vPATIENTRETENANT',prop:'Link'},{av:'AV139Patient_Entity',fld:'vPATIENT_ENTITY',pic:''},{av:'gx.fn.getCtrlProperty("vPATIENT_ENTITY","Tooltiptext")',ctrl:'vPATIENT_ENTITY',prop:'Tooltiptext'},{av:'gx.fn.getCtrlProperty("vPATIENT_ENTITY","Link")',ctrl:'vPATIENT_ENTITY',prop:'Link'},{av:'gx.fn.getCtrlProperty("BR_INFORMATION_PATIENTNO","Link")',ctrl:'BR_INFORMATION_PATIENTNO',prop:'Link'}]];
   this.EvtParms["'DOINSERT'"] = [[{av:'A85BR_Information_ID',fld:'BR_INFORMATION_ID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true},{av:'AV125tTemNum',fld:'vTTEMNUM',pic:'ZZZZZZZZZZZZZZZZZ9'}],[]];
   this.EvtParms["'DOADD'"] = [[{av:'A85BR_Information_ID',fld:'BR_INFORMATION_ID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true}],[]];
   this.EvtParms["VMYUPDATE.CLICK"] = [[{av:'A85BR_Information_ID',fld:'BR_INFORMATION_ID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true}],[]];
   this.setVCMap("AV6WWPContext", "vWWPCONTEXT", 0, "WWPBaseObjects\WWPContext", 0, 0);
   this.setVCMap("AV154Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV142IsAuthorized_PatientReTenant", "vISAUTHORIZED_PATIENTRETENANT", 0, "boolean", 4, 0);
   this.setVCMap("AV140IsAuthorized_Patient_Entity", "vISAUTHORIZED_PATIENT_ENTITY", 0, "boolean", 4, 0);
   this.setVCMap("AV125tTemNum", "vTTEMNUM", 0, "int", 18, 0);
   this.setVCMap("AV6WWPContext", "vWWPCONTEXT", 0, "WWPBaseObjects\WWPContext", 0, 0);
   this.setVCMap("AV154Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV142IsAuthorized_PatientReTenant", "vISAUTHORIZED_PATIENTRETENANT", 0, "boolean", 4, 0);
   this.setVCMap("AV140IsAuthorized_Patient_Entity", "vISAUTHORIZED_PATIENT_ENTITY", 0, "boolean", 4, 0);
   this.setVCMap("AV6WWPContext", "vWWPCONTEXT", 0, "WWPBaseObjects\WWPContext", 0, 0);
   this.setVCMap("AV154Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV142IsAuthorized_PatientReTenant", "vISAUTHORIZED_PATIENTRETENANT", 0, "boolean", 4, 0);
   this.setVCMap("AV140IsAuthorized_Patient_Entity", "vISAUTHORIZED_PATIENT_ENTITY", 0, "boolean", 4, 0);
   GridContainer.addRefreshingVar(this.GXValidFnc[26]);
   GridContainer.addRefreshingVar(this.GXValidFnc[50]);
   GridContainer.addRefreshingVar(this.GXValidFnc[51]);
   GridContainer.addRefreshingVar({rfrVar:"AV6WWPContext"});
   GridContainer.addRefreshingVar(this.GXValidFnc[48]);
   GridContainer.addRefreshingVar({rfrVar:"AV154Pgmname"});
   GridContainer.addRefreshingVar({rfrVar:"AV142IsAuthorized_PatientReTenant"});
   GridContainer.addRefreshingVar({rfrVar:"AV140IsAuthorized_Patient_Entity"});
   this.Initialize( );
});
gx.createParentObj(br_informationww);
