/*!   GeneXus C# 16_0_0-127771 on 2/27/2020 9:44:55.72
*/
gx.evt.autoSkip = false;
gx.define('br_medication_schemeprompt', false, function () {
   this.ServerClass =  "br_medication_schemeprompt" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.hasEnterEvent = true;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV8InOutBR_Medication_SchemeID=gx.fn.getIntegerValue("vINOUTBR_MEDICATION_SCHEMEID",',') ;
   };
   this.e115r2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEPAGE", false, null, true, true);
   };
   this.e125r2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", false, null, true, true);
   };
   this.e135r2_client=function()
   {
      return this.executeServerEvent("DDO_BR_MEDICATION_SCHEMEID.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e145r2_client=function()
   {
      return this.executeServerEvent("DDO_BR_MEDICATIONID.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e155r2_client=function()
   {
      return this.executeServerEvent("DDO_BR_MEDICATION_CHEM_NAME.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e165r2_client=function()
   {
      return this.executeServerEvent("DDO_BR_MEDICATION_CHEM_CYCLE.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e175r2_client=function()
   {
      return this.executeServerEvent("DDO_BR_MEDICATION_CHEM_LINE.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e185r2_client=function()
   {
      return this.executeServerEvent("DDO_BR_MEDICATION_CHEM_DETAIL.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e225r2_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e235r2_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,24,25,26,28,30,32,34,36,38,40,41];
   this.GXLastCtrlId =41;
   this.GridContainer = new gx.grid.grid(this, 2,"WbpLvl2",12,"Grid","Grid","GridContainer",this.CmpContext,this.IsMasterPage,"br_medication_schemeprompt",[],false,1,false,true,0,false,false,false,"",0,"px",0,"px","澧炲姞绌虹櫧琛?,true,false,false,null,null,false,"",false,[1,1,1,1],false,0,true,false);
   var GridContainer = this.GridContainer;
   GridContainer.addBitmap("&Select","vSELECT",13,0,"px",17,"px","e225r2_client","","","SelectAttribute ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addSingleLineEdit(296,14,"BR_MEDICATION_SCHEMEID","","","BR_Medication_SchemeID","int",0,"px",18,18,"right",null,[],296,"BR_Medication_SchemeID",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(119,15,"BR_MEDICATIONID","","","BR_MedicationID","int",0,"px",18,18,"right",null,[],119,"BR_MedicationID",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(305,16,"BR_MEDICATION_CHEM_NAME","","","BR_Medication_Chem_Name","svchar",0,"px",100,80,"left",null,[],305,"BR_Medication_Chem_Name",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(306,17,"BR_MEDICATION_CHEM_CYCLE","","","BR_Medication_Chem_Cycle","decimal",0,"px",15,15,"right",null,[],306,"BR_Medication_Chem_Cycle",true,5,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(307,18,"BR_MEDICATION_CHEM_LINE","","","BR_Medication_Chem_Line","svchar",0,"px",40,40,"left",null,[],307,"BR_Medication_Chem_Line",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(313,19,"BR_MEDICATION_CHEM_DETAIL","","","BR_Medication_Chem_Detail","svchar",0,"px",100,80,"left",null,[],313,"BR_Medication_Chem_Detail",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   this.GridContainer.emptyText = "";
   this.setGrid(GridContainer);
   this.GRIDPAGINATIONBARContainer = gx.uc.getNew(this, 23, 13, "DVelop_DVPaginationBar", "GRIDPAGINATIONBARContainer", "Gridpaginationbar", "GRIDPAGINATIONBAR");
   var GRIDPAGINATIONBARContainer = this.GRIDPAGINATIONBARContainer;
   GRIDPAGINATIONBARContainer.setProp("Enabled", "Enabled", true, "boolean");
   GRIDPAGINATIONBARContainer.setProp("Class", "Class", "PaginationBar", "str");
   GRIDPAGINATIONBARContainer.setProp("ShowFirst", "Showfirst", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowPrevious", "Showprevious", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowNext", "Shownext", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowLast", "Showlast", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("PagesToShow", "Pagestoshow", 5, "num");
   GRIDPAGINATIONBARContainer.setProp("PagingButtonsPosition", "Pagingbuttonsposition", "Right", "str");
   GRIDPAGINATIONBARContainer.setProp("PagingCaptionPosition", "Pagingcaptionposition", "Left", "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridClass", "Emptygridclass", "PaginationBarEmptyGrid", "str");
   GRIDPAGINATIONBARContainer.setProp("SelectedPage", "Selectedpage", "", "char");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageSelector", "Rowsperpageselector", true, "bool");
   GRIDPAGINATIONBARContainer.setDynProp("RowsPerPageSelectedValue", "Rowsperpageselectedvalue", 10, "num");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageOptions", "Rowsperpageoptions", "5:WWP_Rows5,10:WWP_Rows10,20:WWP_Rows20,50:WWP_Rows50", "str");
   GRIDPAGINATIONBARContainer.setProp("First", "First", "First", "str");
   GRIDPAGINATIONBARContainer.setProp("Previous", "Previous", "WWP_PagingPreviousCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Next", "Next", "WWP_PagingNextCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Last", "Last", "Last", "str");
   GRIDPAGINATIONBARContainer.setProp("Caption", "Caption", "<CURRENT_PAGE>椤?<TOTAL_PAGES>椤?璁板綍锛?TOTAL_RECORDS>鏉?, "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridCaption", "Emptygridcaption", "WWP_PagingEmptyGridCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageCaption", "Rowsperpagecaption", "WWP_PagingRowsPerPage", "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV27GridCurrentPage', "vGRIDCURRENTPAGE", 'SetCurrentPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV27GridCurrentPage=UC.GetCurrentPage();gx.fn.setControlValue("vGRIDCURRENTPAGE",UC.ParentObject.AV27GridCurrentPage); });
   GRIDPAGINATIONBARContainer.setProp("PageCount", "Pagecount", '', "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV29GridRecordCount', "vGRIDRECORDCOUNT", 'SetRecordCount');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV29GridRecordCount=UC.GetRecordCount();gx.fn.setControlValue("vGRIDRECORDCOUNT",UC.ParentObject.AV29GridRecordCount); });
   GRIDPAGINATIONBARContainer.addV2CFunction('AV28GridPageSize', "vGRIDPAGESIZE", 'SetPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV28GridPageSize=UC.GetPage();gx.fn.setControlValue("vGRIDPAGESIZE",UC.ParentObject.AV28GridPageSize); });
   GRIDPAGINATIONBARContainer.setProp("Visible", "Visible", true, "bool");
   GRIDPAGINATIONBARContainer.setC2ShowFunction(function(UC) { UC.show(); });
   GRIDPAGINATIONBARContainer.addEventHandler("ChangePage", this.e115r2_client);
   GRIDPAGINATIONBARContainer.addEventHandler("ChangeRowsPerPage", this.e125r2_client);
   this.setUserControl(GRIDPAGINATIONBARContainer);
   this.DDO_BR_MEDICATION_SCHEMEIDContainer = gx.uc.getNew(this, 27, 13, "BootstrapDropDownOptions", "DDO_BR_MEDICATION_SCHEMEIDContainer", "Ddo_br_medication_schemeid", "DDO_BR_MEDICATION_SCHEMEID");
   var DDO_BR_MEDICATION_SCHEMEIDContainer = this.DDO_BR_MEDICATION_SCHEMEIDContainer;
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("Class", "Class", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_MEDICATION_SCHEMEIDContainer.addV2CFunction('AV25DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_MEDICATION_SCHEMEIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV25DDO_TitleSettingsIcons); });
   DDO_BR_MEDICATION_SCHEMEIDContainer.addV2CFunction('AV13BR_Medication_SchemeIDTitleFilterData', "vBR_MEDICATION_SCHEMEIDTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_MEDICATION_SCHEMEIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV13BR_Medication_SchemeIDTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_MEDICATION_SCHEMEIDTITLEFILTERDATA",UC.ParentObject.AV13BR_Medication_SchemeIDTitleFilterData); });
   DDO_BR_MEDICATION_SCHEMEIDContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_MEDICATION_SCHEMEIDContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_MEDICATION_SCHEMEIDContainer.addEventHandler("OnOptionClicked", this.e135r2_client);
   this.setUserControl(DDO_BR_MEDICATION_SCHEMEIDContainer);
   this.DDO_BR_MEDICATIONIDContainer = gx.uc.getNew(this, 29, 28, "BootstrapDropDownOptions", "DDO_BR_MEDICATIONIDContainer", "Ddo_br_medicationid", "DDO_BR_MEDICATIONID");
   var DDO_BR_MEDICATIONIDContainer = this.DDO_BR_MEDICATIONIDContainer;
   DDO_BR_MEDICATIONIDContainer.setProp("Class", "Class", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_MEDICATIONIDContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_MEDICATIONIDContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_MEDICATIONIDContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_MEDICATIONIDContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_MEDICATIONIDContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_MEDICATIONIDContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_MEDICATIONIDContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_MEDICATIONIDContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_MEDICATIONIDContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_MEDICATIONIDContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_MEDICATIONIDContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_MEDICATIONIDContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_MEDICATIONIDContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_MEDICATIONIDContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_MEDICATIONIDContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_MEDICATIONIDContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_MEDICATIONIDContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_MEDICATIONIDContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_MEDICATIONIDContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_MEDICATIONIDContainer.addV2CFunction('AV25DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_MEDICATIONIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV25DDO_TitleSettingsIcons); });
   DDO_BR_MEDICATIONIDContainer.addV2CFunction('AV15BR_MedicationIDTitleFilterData', "vBR_MEDICATIONIDTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_MEDICATIONIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV15BR_MedicationIDTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_MEDICATIONIDTITLEFILTERDATA",UC.ParentObject.AV15BR_MedicationIDTitleFilterData); });
   DDO_BR_MEDICATIONIDContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_MEDICATIONIDContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_MEDICATIONIDContainer.addEventHandler("OnOptionClicked", this.e145r2_client);
   this.setUserControl(DDO_BR_MEDICATIONIDContainer);
   this.DDO_BR_MEDICATION_CHEM_NAMEContainer = gx.uc.getNew(this, 31, 28, "BootstrapDropDownOptions", "DDO_BR_MEDICATION_CHEM_NAMEContainer", "Ddo_br_medication_chem_name", "DDO_BR_MEDICATION_CHEM_NAME");
   var DDO_BR_MEDICATION_CHEM_NAMEContainer = this.DDO_BR_MEDICATION_CHEM_NAMEContainer;
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("Class", "Class", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.addV2CFunction('AV25DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_MEDICATION_CHEM_NAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV25DDO_TitleSettingsIcons); });
   DDO_BR_MEDICATION_CHEM_NAMEContainer.addV2CFunction('AV32BR_Medication_Chem_NameTitleFilterData', "vBR_MEDICATION_CHEM_NAMETITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_MEDICATION_CHEM_NAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV32BR_Medication_Chem_NameTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_MEDICATION_CHEM_NAMETITLEFILTERDATA",UC.ParentObject.AV32BR_Medication_Chem_NameTitleFilterData); });
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_MEDICATION_CHEM_NAMEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_MEDICATION_CHEM_NAMEContainer.addEventHandler("OnOptionClicked", this.e155r2_client);
   this.setUserControl(DDO_BR_MEDICATION_CHEM_NAMEContainer);
   this.DDO_BR_MEDICATION_CHEM_CYCLEContainer = gx.uc.getNew(this, 33, 28, "BootstrapDropDownOptions", "DDO_BR_MEDICATION_CHEM_CYCLEContainer", "Ddo_br_medication_chem_cycle", "DDO_BR_MEDICATION_CHEM_CYCLE");
   var DDO_BR_MEDICATION_CHEM_CYCLEContainer = this.DDO_BR_MEDICATION_CHEM_CYCLEContainer;
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("Class", "Class", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.addV2CFunction('AV25DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV25DDO_TitleSettingsIcons); });
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.addV2CFunction('AV34BR_Medication_Chem_CycleTitleFilterData', "vBR_MEDICATION_CHEM_CYCLETITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV34BR_Medication_Chem_CycleTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_MEDICATION_CHEM_CYCLETITLEFILTERDATA",UC.ParentObject.AV34BR_Medication_Chem_CycleTitleFilterData); });
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_MEDICATION_CHEM_CYCLEContainer.addEventHandler("OnOptionClicked", this.e165r2_client);
   this.setUserControl(DDO_BR_MEDICATION_CHEM_CYCLEContainer);
   this.DDO_BR_MEDICATION_CHEM_LINEContainer = gx.uc.getNew(this, 35, 28, "BootstrapDropDownOptions", "DDO_BR_MEDICATION_CHEM_LINEContainer", "Ddo_br_medication_chem_line", "DDO_BR_MEDICATION_CHEM_LINE");
   var DDO_BR_MEDICATION_CHEM_LINEContainer = this.DDO_BR_MEDICATION_CHEM_LINEContainer;
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("Class", "Class", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_MEDICATION_CHEM_LINEContainer.addV2CFunction('AV25DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_MEDICATION_CHEM_LINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV25DDO_TitleSettingsIcons); });
   DDO_BR_MEDICATION_CHEM_LINEContainer.addV2CFunction('AV36BR_Medication_Chem_LineTitleFilterData', "vBR_MEDICATION_CHEM_LINETITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_MEDICATION_CHEM_LINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV36BR_Medication_Chem_LineTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_MEDICATION_CHEM_LINETITLEFILTERDATA",UC.ParentObject.AV36BR_Medication_Chem_LineTitleFilterData); });
   DDO_BR_MEDICATION_CHEM_LINEContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_MEDICATION_CHEM_LINEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_MEDICATION_CHEM_LINEContainer.addEventHandler("OnOptionClicked", this.e175r2_client);
   this.setUserControl(DDO_BR_MEDICATION_CHEM_LINEContainer);
   this.DDO_BR_MEDICATION_CHEM_DETAILContainer = gx.uc.getNew(this, 37, 28, "BootstrapDropDownOptions", "DDO_BR_MEDICATION_CHEM_DETAILContainer", "Ddo_br_medication_chem_detail", "DDO_BR_MEDICATION_CHEM_DETAIL");
   var DDO_BR_MEDICATION_CHEM_DETAILContainer = this.DDO_BR_MEDICATION_CHEM_DETAILContainer;
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("Class", "Class", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.addV2CFunction('AV25DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_MEDICATION_CHEM_DETAILContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV25DDO_TitleSettingsIcons); });
   DDO_BR_MEDICATION_CHEM_DETAILContainer.addV2CFunction('AV40BR_Medication_Chem_DetailTitleFilterData', "vBR_MEDICATION_CHEM_DETAILTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_MEDICATION_CHEM_DETAILContainer.addC2VFunction(function(UC) { UC.ParentObject.AV40BR_Medication_Chem_DetailTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_MEDICATION_CHEM_DETAILTITLEFILTERDATA",UC.ParentObject.AV40BR_Medication_Chem_DetailTitleFilterData); });
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_MEDICATION_CHEM_DETAILContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_MEDICATION_CHEM_DETAILContainer.addEventHandler("OnOptionClicked", this.e185r2_client);
   this.setUserControl(DDO_BR_MEDICATION_CHEM_DETAILContainer);
   this.WORKWITHPLUSUTILITIES1Container = gx.uc.getNew(this, 39, 28, "DVelop_WorkWithPlusUtilities", "WORKWITHPLUSUTILITIES1Container", "Workwithplusutilities1", "WORKWITHPLUSUTILITIES1");
   var WORKWITHPLUSUTILITIES1Container = this.WORKWITHPLUSUTILITIES1Container;
   WORKWITHPLUSUTILITIES1Container.setProp("Class", "Class", "", "char");
   WORKWITHPLUSUTILITIES1Container.setProp("Enabled", "Enabled", true, "boolean");
   WORKWITHPLUSUTILITIES1Container.setProp("Width", "Width", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Height", "Height", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Visible", "Visible", true, "bool");
   WORKWITHPLUSUTILITIES1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(WORKWITHPLUSUTILITIES1Container);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEMAIN",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"GRIDTABLEWITHPAGINATIONBAR",grid:0};
   GXValidFnc[10]={ id: 10, fld:"",grid:0};
   GXValidFnc[11]={ id: 11, fld:"",grid:0};
   GXValidFnc[13]={ id:13 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vSELECT",gxz:"ZV30Select",gxold:"OV30Select",gxvar:"AV30Select",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV30Select=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV30Select=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vSELECT",row || gx.fn.currentGridRowImpl(12),gx.O.AV30Select,gx.O.AV45Select_GXI)},c2v:function(){gx.O.AV45Select_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV30Select=this.val()},val:function(row){return gx.fn.getGridControlValue("vSELECT",row || gx.fn.currentGridRowImpl(12))},val_GXI:function(row){return gx.fn.getGridControlValue("vSELECT_GXI",row || gx.fn.currentGridRowImpl(12))}, gxvar_GXI:'AV45Select_GXI',nac:gx.falseFn,evt:"e225r2_client",std:"ENTER"};
   GXValidFnc[14]={ id:14 ,lvl:2,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_MEDICATION_SCHEMEID",gxz:"Z296BR_Medication_SchemeID",gxold:"O296BR_Medication_SchemeID",gxvar:"A296BR_Medication_SchemeID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A296BR_Medication_SchemeID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z296BR_Medication_SchemeID=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("BR_MEDICATION_SCHEMEID",row || gx.fn.currentGridRowImpl(12),gx.O.A296BR_Medication_SchemeID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A296BR_Medication_SchemeID=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("BR_MEDICATION_SCHEMEID",row || gx.fn.currentGridRowImpl(12),',')},nac:gx.falseFn};
   GXValidFnc[15]={ id:15 ,lvl:2,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_MEDICATIONID",gxz:"Z119BR_MedicationID",gxold:"O119BR_MedicationID",gxvar:"A119BR_MedicationID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A119BR_MedicationID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z119BR_MedicationID=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("BR_MEDICATIONID",row || gx.fn.currentGridRowImpl(12),gx.O.A119BR_MedicationID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A119BR_MedicationID=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("BR_MEDICATIONID",row || gx.fn.currentGridRowImpl(12),',')},nac:gx.falseFn};
   GXValidFnc[16]={ id:16 ,lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_MEDICATION_CHEM_NAME",gxz:"Z305BR_Medication_Chem_Name",gxold:"O305BR_Medication_Chem_Name",gxvar:"A305BR_Medication_Chem_Name",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A305BR_Medication_Chem_Name=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z305BR_Medication_Chem_Name=Value},v2c:function(row){gx.fn.setGridControlValue("BR_MEDICATION_CHEM_NAME",row || gx.fn.currentGridRowImpl(12),gx.O.A305BR_Medication_Chem_Name,0)},c2v:function(){if(this.val()!==undefined)gx.O.A305BR_Medication_Chem_Name=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_MEDICATION_CHEM_NAME",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn};
   GXValidFnc[17]={ id:17 ,lvl:2,type:"decimal",len:15,dec:5,sign:false,pic:"ZZZZZZZZZ.ZZZZZ",ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_MEDICATION_CHEM_CYCLE",gxz:"Z306BR_Medication_Chem_Cycle",gxold:"O306BR_Medication_Chem_Cycle",gxvar:"A306BR_Medication_Chem_Cycle",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.A306BR_Medication_Chem_Cycle=gx.fn.toDecimalValue(Value,',','.')},v2z:function(Value){if(Value!==undefined)gx.O.Z306BR_Medication_Chem_Cycle=gx.fn.toDecimalValue(Value,',','.')},v2c:function(row){gx.fn.setGridDecimalValue("BR_MEDICATION_CHEM_CYCLE",row || gx.fn.currentGridRowImpl(12),gx.O.A306BR_Medication_Chem_Cycle,5,'.');if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A306BR_Medication_Chem_Cycle=this.val()},val:function(row){return gx.fn.getGridDecimalValue("BR_MEDICATION_CHEM_CYCLE",row || gx.fn.currentGridRowImpl(12),',','.')},nac:gx.falseFn};
   GXValidFnc[18]={ id:18 ,lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_MEDICATION_CHEM_LINE",gxz:"Z307BR_Medication_Chem_Line",gxold:"O307BR_Medication_Chem_Line",gxvar:"A307BR_Medication_Chem_Line",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A307BR_Medication_Chem_Line=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z307BR_Medication_Chem_Line=Value},v2c:function(row){gx.fn.setGridControlValue("BR_MEDICATION_CHEM_LINE",row || gx.fn.currentGridRowImpl(12),gx.O.A307BR_Medication_Chem_Line,0)},c2v:function(){if(this.val()!==undefined)gx.O.A307BR_Medication_Chem_Line=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_MEDICATION_CHEM_LINE",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn};
   GXValidFnc[19]={ id:19 ,lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_MEDICATION_CHEM_DETAIL",gxz:"Z313BR_Medication_Chem_Detail",gxold:"O313BR_Medication_Chem_Detail",gxvar:"A313BR_Medication_Chem_Detail",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A313BR_Medication_Chem_Detail=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z313BR_Medication_Chem_Detail=Value},v2c:function(row){gx.fn.setGridControlValue("BR_MEDICATION_CHEM_DETAIL",row || gx.fn.currentGridRowImpl(12),gx.O.A313BR_Medication_Chem_Detail,0)},c2v:function(){if(this.val()!==undefined)gx.O.A313BR_Medication_Chem_Detail=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_MEDICATION_CHEM_DETAIL",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn};
   GXValidFnc[20]={ id: 20, fld:"",grid:0};
   GXValidFnc[21]={ id: 21, fld:"",grid:0};
   GXValidFnc[22]={ id: 22, fld:"HTML_GRIDPAGINATIONBAR",grid:0};
   GXValidFnc[24]={ id: 24, fld:"",grid:0};
   GXValidFnc[25]={ id: 25, fld:"",grid:0};
   GXValidFnc[26]={ id: 26, fld:"HTML_BOTTOMAUXILIARCONTROLS",grid:0};
   GXValidFnc[28]={ id:28 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_MEDICATION_SCHEMEIDTITLECONTROLIDTOREPLACE",gxz:"ZV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace",gxold:"OV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace",gxvar:"AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_MEDICATION_SCHEMEIDTITLECONTROLIDTOREPLACE",gx.O.AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_MEDICATION_SCHEMEIDTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[30]={ id:30 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_MEDICATIONIDTITLECONTROLIDTOREPLACE",gxz:"ZV16ddo_BR_MedicationIDTitleControlIdToReplace",gxold:"OV16ddo_BR_MedicationIDTitleControlIdToReplace",gxvar:"AV16ddo_BR_MedicationIDTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV16ddo_BR_MedicationIDTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV16ddo_BR_MedicationIDTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_MEDICATIONIDTITLECONTROLIDTOREPLACE",gx.O.AV16ddo_BR_MedicationIDTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV16ddo_BR_MedicationIDTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_MEDICATIONIDTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[32]={ id:32 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_MEDICATION_CHEM_NAMETITLECONTROLIDTOREPLACE",gxz:"ZV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace",gxold:"OV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace",gxvar:"AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_MEDICATION_CHEM_NAMETITLECONTROLIDTOREPLACE",gx.O.AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_MEDICATION_CHEM_NAMETITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[34]={ id:34 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_MEDICATION_CHEM_CYCLETITLECONTROLIDTOREPLACE",gxz:"ZV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace",gxold:"OV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace",gxvar:"AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_MEDICATION_CHEM_CYCLETITLECONTROLIDTOREPLACE",gx.O.AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_MEDICATION_CHEM_CYCLETITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[36]={ id:36 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_MEDICATION_CHEM_LINETITLECONTROLIDTOREPLACE",gxz:"ZV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace",gxold:"OV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace",gxvar:"AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_MEDICATION_CHEM_LINETITLECONTROLIDTOREPLACE",gx.O.AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_MEDICATION_CHEM_LINETITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[38]={ id:38 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_MEDICATION_CHEM_DETAILTITLECONTROLIDTOREPLACE",gxz:"ZV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace",gxold:"OV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace",gxvar:"AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_MEDICATION_CHEM_DETAILTITLECONTROLIDTOREPLACE",gx.O.AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_MEDICATION_CHEM_DETAILTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[40]={ id:40 ,lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDBY",gxz:"ZV11OrderedBy",gxold:"OV11OrderedBy",gxvar:"AV11OrderedBy",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV11OrderedBy=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV11OrderedBy=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDBY",gx.O.AV11OrderedBy,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV11OrderedBy=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vORDEREDBY",',')},nac:gx.falseFn};
   GXValidFnc[41]={ id:41 ,lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDDSC",gxz:"ZV12OrderedDsc",gxold:"OV12OrderedDsc",gxvar:"AV12OrderedDsc",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV12OrderedDsc=gx.lang.booleanValue(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV12OrderedDsc=gx.lang.booleanValue(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDDSC",gx.O.AV12OrderedDsc,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV12OrderedDsc=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getControlValue("vORDEREDDSC")},nac:gx.falseFn};
   this.ZV30Select = "" ;
   this.OV30Select = "" ;
   this.Z296BR_Medication_SchemeID = 0 ;
   this.O296BR_Medication_SchemeID = 0 ;
   this.Z119BR_MedicationID = 0 ;
   this.O119BR_MedicationID = 0 ;
   this.Z305BR_Medication_Chem_Name = "" ;
   this.O305BR_Medication_Chem_Name = "" ;
   this.Z306BR_Medication_Chem_Cycle = 0 ;
   this.O306BR_Medication_Chem_Cycle = 0 ;
   this.Z307BR_Medication_Chem_Line = "" ;
   this.O307BR_Medication_Chem_Line = "" ;
   this.Z313BR_Medication_Chem_Detail = "" ;
   this.O313BR_Medication_Chem_Detail = "" ;
   this.AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace = "" ;
   this.ZV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace = "" ;
   this.OV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace = "" ;
   this.AV16ddo_BR_MedicationIDTitleControlIdToReplace = "" ;
   this.ZV16ddo_BR_MedicationIDTitleControlIdToReplace = "" ;
   this.OV16ddo_BR_MedicationIDTitleControlIdToReplace = "" ;
   this.AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace = "" ;
   this.ZV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace = "" ;
   this.OV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace = "" ;
   this.AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace = "" ;
   this.ZV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace = "" ;
   this.OV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace = "" ;
   this.AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace = "" ;
   this.ZV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace = "" ;
   this.OV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace = "" ;
   this.AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace = "" ;
   this.ZV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace = "" ;
   this.OV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace = "" ;
   this.AV11OrderedBy = 0 ;
   this.ZV11OrderedBy = 0 ;
   this.OV11OrderedBy = 0 ;
   this.AV12OrderedDsc = false ;
   this.ZV12OrderedDsc = false ;
   this.OV12OrderedDsc = false ;
   this.AV27GridCurrentPage = 0 ;
   this.AV25DDO_TitleSettingsIcons = {Default:"",Default_GXI:"",Filtered:"",Filtered_GXI:"",SortedASC:"",SortedASC_GXI:"",SortedDSC:"",SortedDSC_GXI:"",FilteredSortedASC:"",FilteredSortedASC_GXI:"",FilteredSortedDSC:"",FilteredSortedDSC_GXI:"",OptionSortASC:"",OptionSortASC_GXI:"",OptionSortDSC:"",OptionSortDSC_GXI:"",OptionApplyFilter:"",OptionApplyFilter_GXI:"",OptionFilteringData:"",OptionFilteringData_GXI:"",OptionCleanFilters:"",OptionCleanFilters_GXI:"",SelectedOption:"",SelectedOption_GXI:"",MultiselOption:"",MultiselOption_GXI:"",MultiselSelOption:"",MultiselSelOption_GXI:""} ;
   this.AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace = "" ;
   this.AV16ddo_BR_MedicationIDTitleControlIdToReplace = "" ;
   this.AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace = "" ;
   this.AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace = "" ;
   this.AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace = "" ;
   this.AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace = "" ;
   this.AV11OrderedBy = 0 ;
   this.AV12OrderedDsc = false ;
   this.AV8InOutBR_Medication_SchemeID = 0 ;
   this.AV30Select = "" ;
   this.A296BR_Medication_SchemeID = 0 ;
   this.A119BR_MedicationID = 0 ;
   this.A305BR_Medication_Chem_Name = "" ;
   this.A306BR_Medication_Chem_Cycle = 0 ;
   this.A307BR_Medication_Chem_Line = "" ;
   this.A313BR_Medication_Chem_Detail = "" ;
   this.Events = {"e115r2_client": ["GRIDPAGINATIONBAR.CHANGEPAGE", true] ,"e125r2_client": ["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", true] ,"e135r2_client": ["DDO_BR_MEDICATION_SCHEMEID.ONOPTIONCLICKED", true] ,"e145r2_client": ["DDO_BR_MEDICATIONID.ONOPTIONCLICKED", true] ,"e155r2_client": ["DDO_BR_MEDICATION_CHEM_NAME.ONOPTIONCLICKED", true] ,"e165r2_client": ["DDO_BR_MEDICATION_CHEM_CYCLE.ONOPTIONCLICKED", true] ,"e175r2_client": ["DDO_BR_MEDICATION_CHEM_LINE.ONOPTIONCLICKED", true] ,"e185r2_client": ["DDO_BR_MEDICATION_CHEM_DETAIL.ONOPTIONCLICKED", true] ,"e225r2_client": ["ENTER", true] ,"e235r2_client": ["CANCEL", true]};
   this.EvtParms["REFRESH"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_SCHEMEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicationIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATIONIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_CYCLETITLECONTROLIDTOREPLACE',pic:''},{av:'AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_LINETITLECONTROLIDTOREPLACE',pic:''},{av:'AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_DETAILTITLECONTROLIDTOREPLACE',pic:''},{ctrl:'GRID',prop:'Rows'}],[{av:'AV13BR_Medication_SchemeIDTitleFilterData',fld:'vBR_MEDICATION_SCHEMEIDTITLEFILTERDATA',pic:''},{av:'AV15BR_MedicationIDTitleFilterData',fld:'vBR_MEDICATIONIDTITLEFILTERDATA',pic:''},{av:'AV32BR_Medication_Chem_NameTitleFilterData',fld:'vBR_MEDICATION_CHEM_NAMETITLEFILTERDATA',pic:''},{av:'AV34BR_Medication_Chem_CycleTitleFilterData',fld:'vBR_MEDICATION_CHEM_CYCLETITLEFILTERDATA',pic:''},{av:'AV36BR_Medication_Chem_LineTitleFilterData',fld:'vBR_MEDICATION_CHEM_LINETITLEFILTERDATA',pic:''},{av:'AV40BR_Medication_Chem_DetailTitleFilterData',fld:'vBR_MEDICATION_CHEM_DETAILTITLEFILTERDATA',pic:''},{ctrl:'BR_MEDICATION_SCHEMEID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_SCHEMEID","Title")',ctrl:'BR_MEDICATION_SCHEMEID',prop:'Title'},{ctrl:'BR_MEDICATIONID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATIONID","Title")',ctrl:'BR_MEDICATIONID',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_NAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_NAME","Title")',ctrl:'BR_MEDICATION_CHEM_NAME',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_CYCLE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_CYCLE","Title")',ctrl:'BR_MEDICATION_CHEM_CYCLE',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_LINE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_LINE","Title")',ctrl:'BR_MEDICATION_CHEM_LINE',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_DETAIL',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_DETAIL","Title")',ctrl:'BR_MEDICATION_CHEM_DETAIL',prop:'Title'},{av:'AV27GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV28GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV29GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["START"] = [[{av:'AV44Pgmname',fld:'vPGMNAME',pic:''},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'}],[{av:'gx.fn.getCtrlProperty("TABLEMAIN","Height")',ctrl:'TABLEMAIN',prop:'Height'},{ctrl:'GRID',prop:'Rows'},{av:'this.DDO_BR_MEDICATION_SCHEMEIDContainer.TitleControlIdToReplace',ctrl:'DDO_BR_MEDICATION_SCHEMEID',prop:'TitleControlIdToReplace'},{av:'AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_SCHEMEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_MEDICATION_SCHEMEIDTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_MEDICATION_SCHEMEIDTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_MEDICATIONIDContainer.TitleControlIdToReplace',ctrl:'DDO_BR_MEDICATIONID',prop:'TitleControlIdToReplace'},{av:'AV16ddo_BR_MedicationIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATIONIDTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_MEDICATIONIDTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_MEDICATIONIDTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_MEDICATION_CHEM_NAMEContainer.TitleControlIdToReplace',ctrl:'DDO_BR_MEDICATION_CHEM_NAME',prop:'TitleControlIdToReplace'},{av:'AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_MEDICATION_CHEM_NAMETITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_MEDICATION_CHEM_NAMETITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_MEDICATION_CHEM_CYCLEContainer.TitleControlIdToReplace',ctrl:'DDO_BR_MEDICATION_CHEM_CYCLE',prop:'TitleControlIdToReplace'},{av:'AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_CYCLETITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_MEDICATION_CHEM_CYCLETITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_MEDICATION_CHEM_CYCLETITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_MEDICATION_CHEM_LINEContainer.TitleControlIdToReplace',ctrl:'DDO_BR_MEDICATION_CHEM_LINE',prop:'TitleControlIdToReplace'},{av:'AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_LINETITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_MEDICATION_CHEM_LINETITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_MEDICATION_CHEM_LINETITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_MEDICATION_CHEM_DETAILContainer.TitleControlIdToReplace',ctrl:'DDO_BR_MEDICATION_CHEM_DETAIL',prop:'TitleControlIdToReplace'},{av:'AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_DETAILTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_MEDICATION_CHEM_DETAILTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_MEDICATION_CHEM_DETAILTITLECONTROLIDTOREPLACE',prop:'Visible'},{ctrl:'FORM',prop:'Caption'},{av:'gx.fn.getCtrlProperty("vORDEREDBY","Visible")',ctrl:'vORDEREDBY',prop:'Visible'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'gx.fn.getCtrlProperty("vORDEREDDSC","Visible")',ctrl:'vORDEREDDSC',prop:'Visible'},{av:'AV25DDO_TitleSettingsIcons',fld:'vDDO_TITLESETTINGSICONS',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_SCHEMEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicationIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATIONIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_CYCLETITLECONTROLIDTOREPLACE',pic:''},{av:'AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_LINETITLECONTROLIDTOREPLACE',pic:''},{av:'AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_DETAILTITLECONTROLIDTOREPLACE',pic:''},{av:'this.GRIDPAGINATIONBARContainer.SelectedPage',ctrl:'GRIDPAGINATIONBAR',prop:'SelectedPage'}],[]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_SCHEMEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicationIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATIONIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_CYCLETITLECONTROLIDTOREPLACE',pic:''},{av:'AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_LINETITLECONTROLIDTOREPLACE',pic:''},{av:'AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_DETAILTITLECONTROLIDTOREPLACE',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}],[{ctrl:'GRID',prop:'Rows'}]];
   this.EvtParms["DDO_BR_MEDICATION_SCHEMEID.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_SCHEMEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicationIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATIONIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_CYCLETITLECONTROLIDTOREPLACE',pic:''},{av:'AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_LINETITLECONTROLIDTOREPLACE',pic:''},{av:'AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_DETAILTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_BR_MEDICATION_SCHEMEIDContainer.ActiveEventKey',ctrl:'DDO_BR_MEDICATION_SCHEMEID',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_MEDICATION_SCHEMEIDContainer.SortedStatus',ctrl:'DDO_BR_MEDICATION_SCHEMEID',prop:'SortedStatus'},{av:'AV13BR_Medication_SchemeIDTitleFilterData',fld:'vBR_MEDICATION_SCHEMEIDTITLEFILTERDATA',pic:''},{av:'AV15BR_MedicationIDTitleFilterData',fld:'vBR_MEDICATIONIDTITLEFILTERDATA',pic:''},{av:'AV32BR_Medication_Chem_NameTitleFilterData',fld:'vBR_MEDICATION_CHEM_NAMETITLEFILTERDATA',pic:''},{av:'AV34BR_Medication_Chem_CycleTitleFilterData',fld:'vBR_MEDICATION_CHEM_CYCLETITLEFILTERDATA',pic:''},{av:'AV36BR_Medication_Chem_LineTitleFilterData',fld:'vBR_MEDICATION_CHEM_LINETITLEFILTERDATA',pic:''},{av:'AV40BR_Medication_Chem_DetailTitleFilterData',fld:'vBR_MEDICATION_CHEM_DETAILTITLEFILTERDATA',pic:''},{ctrl:'BR_MEDICATION_SCHEMEID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_SCHEMEID","Title")',ctrl:'BR_MEDICATION_SCHEMEID',prop:'Title'},{ctrl:'BR_MEDICATIONID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATIONID","Title")',ctrl:'BR_MEDICATIONID',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_NAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_NAME","Title")',ctrl:'BR_MEDICATION_CHEM_NAME',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_CYCLE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_CYCLE","Title")',ctrl:'BR_MEDICATION_CHEM_CYCLE',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_LINE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_LINE","Title")',ctrl:'BR_MEDICATION_CHEM_LINE',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_DETAIL',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_DETAIL","Title")',ctrl:'BR_MEDICATION_CHEM_DETAIL',prop:'Title'},{av:'AV27GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV28GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV29GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_BR_MEDICATIONID.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_SCHEMEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicationIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATIONIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_CYCLETITLECONTROLIDTOREPLACE',pic:''},{av:'AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_LINETITLECONTROLIDTOREPLACE',pic:''},{av:'AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_DETAILTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_BR_MEDICATIONIDContainer.ActiveEventKey',ctrl:'DDO_BR_MEDICATIONID',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_MEDICATIONIDContainer.SortedStatus',ctrl:'DDO_BR_MEDICATIONID',prop:'SortedStatus'},{av:'AV13BR_Medication_SchemeIDTitleFilterData',fld:'vBR_MEDICATION_SCHEMEIDTITLEFILTERDATA',pic:''},{av:'AV15BR_MedicationIDTitleFilterData',fld:'vBR_MEDICATIONIDTITLEFILTERDATA',pic:''},{av:'AV32BR_Medication_Chem_NameTitleFilterData',fld:'vBR_MEDICATION_CHEM_NAMETITLEFILTERDATA',pic:''},{av:'AV34BR_Medication_Chem_CycleTitleFilterData',fld:'vBR_MEDICATION_CHEM_CYCLETITLEFILTERDATA',pic:''},{av:'AV36BR_Medication_Chem_LineTitleFilterData',fld:'vBR_MEDICATION_CHEM_LINETITLEFILTERDATA',pic:''},{av:'AV40BR_Medication_Chem_DetailTitleFilterData',fld:'vBR_MEDICATION_CHEM_DETAILTITLEFILTERDATA',pic:''},{ctrl:'BR_MEDICATION_SCHEMEID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_SCHEMEID","Title")',ctrl:'BR_MEDICATION_SCHEMEID',prop:'Title'},{ctrl:'BR_MEDICATIONID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATIONID","Title")',ctrl:'BR_MEDICATIONID',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_NAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_NAME","Title")',ctrl:'BR_MEDICATION_CHEM_NAME',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_CYCLE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_CYCLE","Title")',ctrl:'BR_MEDICATION_CHEM_CYCLE',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_LINE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_LINE","Title")',ctrl:'BR_MEDICATION_CHEM_LINE',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_DETAIL',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_DETAIL","Title")',ctrl:'BR_MEDICATION_CHEM_DETAIL',prop:'Title'},{av:'AV27GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV28GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV29GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_BR_MEDICATION_CHEM_NAME.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_SCHEMEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicationIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATIONIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_CYCLETITLECONTROLIDTOREPLACE',pic:''},{av:'AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_LINETITLECONTROLIDTOREPLACE',pic:''},{av:'AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_DETAILTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_BR_MEDICATION_CHEM_NAMEContainer.ActiveEventKey',ctrl:'DDO_BR_MEDICATION_CHEM_NAME',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_MEDICATION_CHEM_NAMEContainer.SortedStatus',ctrl:'DDO_BR_MEDICATION_CHEM_NAME',prop:'SortedStatus'},{av:'AV13BR_Medication_SchemeIDTitleFilterData',fld:'vBR_MEDICATION_SCHEMEIDTITLEFILTERDATA',pic:''},{av:'AV15BR_MedicationIDTitleFilterData',fld:'vBR_MEDICATIONIDTITLEFILTERDATA',pic:''},{av:'AV32BR_Medication_Chem_NameTitleFilterData',fld:'vBR_MEDICATION_CHEM_NAMETITLEFILTERDATA',pic:''},{av:'AV34BR_Medication_Chem_CycleTitleFilterData',fld:'vBR_MEDICATION_CHEM_CYCLETITLEFILTERDATA',pic:''},{av:'AV36BR_Medication_Chem_LineTitleFilterData',fld:'vBR_MEDICATION_CHEM_LINETITLEFILTERDATA',pic:''},{av:'AV40BR_Medication_Chem_DetailTitleFilterData',fld:'vBR_MEDICATION_CHEM_DETAILTITLEFILTERDATA',pic:''},{ctrl:'BR_MEDICATION_SCHEMEID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_SCHEMEID","Title")',ctrl:'BR_MEDICATION_SCHEMEID',prop:'Title'},{ctrl:'BR_MEDICATIONID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATIONID","Title")',ctrl:'BR_MEDICATIONID',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_NAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_NAME","Title")',ctrl:'BR_MEDICATION_CHEM_NAME',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_CYCLE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_CYCLE","Title")',ctrl:'BR_MEDICATION_CHEM_CYCLE',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_LINE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_LINE","Title")',ctrl:'BR_MEDICATION_CHEM_LINE',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_DETAIL',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_DETAIL","Title")',ctrl:'BR_MEDICATION_CHEM_DETAIL',prop:'Title'},{av:'AV27GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV28GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV29GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_BR_MEDICATION_CHEM_CYCLE.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_SCHEMEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicationIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATIONIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_CYCLETITLECONTROLIDTOREPLACE',pic:''},{av:'AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_LINETITLECONTROLIDTOREPLACE',pic:''},{av:'AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_DETAILTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_BR_MEDICATION_CHEM_CYCLEContainer.ActiveEventKey',ctrl:'DDO_BR_MEDICATION_CHEM_CYCLE',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_MEDICATION_CHEM_CYCLEContainer.SortedStatus',ctrl:'DDO_BR_MEDICATION_CHEM_CYCLE',prop:'SortedStatus'},{av:'AV13BR_Medication_SchemeIDTitleFilterData',fld:'vBR_MEDICATION_SCHEMEIDTITLEFILTERDATA',pic:''},{av:'AV15BR_MedicationIDTitleFilterData',fld:'vBR_MEDICATIONIDTITLEFILTERDATA',pic:''},{av:'AV32BR_Medication_Chem_NameTitleFilterData',fld:'vBR_MEDICATION_CHEM_NAMETITLEFILTERDATA',pic:''},{av:'AV34BR_Medication_Chem_CycleTitleFilterData',fld:'vBR_MEDICATION_CHEM_CYCLETITLEFILTERDATA',pic:''},{av:'AV36BR_Medication_Chem_LineTitleFilterData',fld:'vBR_MEDICATION_CHEM_LINETITLEFILTERDATA',pic:''},{av:'AV40BR_Medication_Chem_DetailTitleFilterData',fld:'vBR_MEDICATION_CHEM_DETAILTITLEFILTERDATA',pic:''},{ctrl:'BR_MEDICATION_SCHEMEID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_SCHEMEID","Title")',ctrl:'BR_MEDICATION_SCHEMEID',prop:'Title'},{ctrl:'BR_MEDICATIONID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATIONID","Title")',ctrl:'BR_MEDICATIONID',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_NAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_NAME","Title")',ctrl:'BR_MEDICATION_CHEM_NAME',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_CYCLE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_CYCLE","Title")',ctrl:'BR_MEDICATION_CHEM_CYCLE',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_LINE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_LINE","Title")',ctrl:'BR_MEDICATION_CHEM_LINE',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_DETAIL',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_DETAIL","Title")',ctrl:'BR_MEDICATION_CHEM_DETAIL',prop:'Title'},{av:'AV27GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV28GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV29GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_BR_MEDICATION_CHEM_LINE.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_SCHEMEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicationIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATIONIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_CYCLETITLECONTROLIDTOREPLACE',pic:''},{av:'AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_LINETITLECONTROLIDTOREPLACE',pic:''},{av:'AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_DETAILTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_BR_MEDICATION_CHEM_LINEContainer.ActiveEventKey',ctrl:'DDO_BR_MEDICATION_CHEM_LINE',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_MEDICATION_CHEM_LINEContainer.SortedStatus',ctrl:'DDO_BR_MEDICATION_CHEM_LINE',prop:'SortedStatus'},{av:'AV13BR_Medication_SchemeIDTitleFilterData',fld:'vBR_MEDICATION_SCHEMEIDTITLEFILTERDATA',pic:''},{av:'AV15BR_MedicationIDTitleFilterData',fld:'vBR_MEDICATIONIDTITLEFILTERDATA',pic:''},{av:'AV32BR_Medication_Chem_NameTitleFilterData',fld:'vBR_MEDICATION_CHEM_NAMETITLEFILTERDATA',pic:''},{av:'AV34BR_Medication_Chem_CycleTitleFilterData',fld:'vBR_MEDICATION_CHEM_CYCLETITLEFILTERDATA',pic:''},{av:'AV36BR_Medication_Chem_LineTitleFilterData',fld:'vBR_MEDICATION_CHEM_LINETITLEFILTERDATA',pic:''},{av:'AV40BR_Medication_Chem_DetailTitleFilterData',fld:'vBR_MEDICATION_CHEM_DETAILTITLEFILTERDATA',pic:''},{ctrl:'BR_MEDICATION_SCHEMEID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_SCHEMEID","Title")',ctrl:'BR_MEDICATION_SCHEMEID',prop:'Title'},{ctrl:'BR_MEDICATIONID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATIONID","Title")',ctrl:'BR_MEDICATIONID',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_NAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_NAME","Title")',ctrl:'BR_MEDICATION_CHEM_NAME',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_CYCLE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_CYCLE","Title")',ctrl:'BR_MEDICATION_CHEM_CYCLE',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_LINE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_LINE","Title")',ctrl:'BR_MEDICATION_CHEM_LINE',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_DETAIL',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_DETAIL","Title")',ctrl:'BR_MEDICATION_CHEM_DETAIL',prop:'Title'},{av:'AV27GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV28GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV29GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_BR_MEDICATION_CHEM_DETAIL.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_Medication_SchemeIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_SCHEMEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicationIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICATIONIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV33ddo_BR_Medication_Chem_NameTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV35ddo_BR_Medication_Chem_CycleTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_CYCLETITLECONTROLIDTOREPLACE',pic:''},{av:'AV37ddo_BR_Medication_Chem_LineTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_LINETITLECONTROLIDTOREPLACE',pic:''},{av:'AV41ddo_BR_Medication_Chem_DetailTitleControlIdToReplace',fld:'vDDO_BR_MEDICATION_CHEM_DETAILTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_BR_MEDICATION_CHEM_DETAILContainer.ActiveEventKey',ctrl:'DDO_BR_MEDICATION_CHEM_DETAIL',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_MEDICATION_CHEM_DETAILContainer.SortedStatus',ctrl:'DDO_BR_MEDICATION_CHEM_DETAIL',prop:'SortedStatus'},{av:'AV13BR_Medication_SchemeIDTitleFilterData',fld:'vBR_MEDICATION_SCHEMEIDTITLEFILTERDATA',pic:''},{av:'AV15BR_MedicationIDTitleFilterData',fld:'vBR_MEDICATIONIDTITLEFILTERDATA',pic:''},{av:'AV32BR_Medication_Chem_NameTitleFilterData',fld:'vBR_MEDICATION_CHEM_NAMETITLEFILTERDATA',pic:''},{av:'AV34BR_Medication_Chem_CycleTitleFilterData',fld:'vBR_MEDICATION_CHEM_CYCLETITLEFILTERDATA',pic:''},{av:'AV36BR_Medication_Chem_LineTitleFilterData',fld:'vBR_MEDICATION_CHEM_LINETITLEFILTERDATA',pic:''},{av:'AV40BR_Medication_Chem_DetailTitleFilterData',fld:'vBR_MEDICATION_CHEM_DETAILTITLEFILTERDATA',pic:''},{ctrl:'BR_MEDICATION_SCHEMEID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_SCHEMEID","Title")',ctrl:'BR_MEDICATION_SCHEMEID',prop:'Title'},{ctrl:'BR_MEDICATIONID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATIONID","Title")',ctrl:'BR_MEDICATIONID',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_NAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_NAME","Title")',ctrl:'BR_MEDICATION_CHEM_NAME',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_CYCLE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_CYCLE","Title")',ctrl:'BR_MEDICATION_CHEM_CYCLE',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_LINE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_LINE","Title")',ctrl:'BR_MEDICATION_CHEM_LINE',prop:'Title'},{ctrl:'BR_MEDICATION_CHEM_DETAIL',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICATION_CHEM_DETAIL","Title")',ctrl:'BR_MEDICATION_CHEM_DETAIL',prop:'Title'},{av:'AV27GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV28GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV29GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["GRID.LOAD"] = [[],[{av:'AV30Select',fld:'vSELECT',pic:''},{av:'gx.fn.getCtrlProperty("vSELECT","Tooltiptext")',ctrl:'vSELECT',prop:'Tooltiptext'}]];
   this.EvtParms["ENTER"] = [[{av:'A296BR_Medication_SchemeID',fld:'BR_MEDICATION_SCHEMEID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true}],[{av:'AV8InOutBR_Medication_SchemeID',fld:'vINOUTBR_MEDICATION_SCHEMEID',pic:'ZZZZZZZZZZZZZZZZZZ'}]];
   this.EnterCtrl = ["vSELECT"];
   this.setVCMap("AV8InOutBR_Medication_SchemeID", "vINOUTBR_MEDICATION_SCHEMEID", 0, "int", 18, 0);
   GridContainer.addRefreshingVar(this.GXValidFnc[40]);
   GridContainer.addRefreshingVar(this.GXValidFnc[41]);
   GridContainer.addRefreshingVar(this.GXValidFnc[28]);
   GridContainer.addRefreshingVar(this.GXValidFnc[30]);
   GridContainer.addRefreshingVar(this.GXValidFnc[32]);
   GridContainer.addRefreshingVar(this.GXValidFnc[34]);
   GridContainer.addRefreshingVar(this.GXValidFnc[36]);
   GridContainer.addRefreshingVar(this.GXValidFnc[38]);
   this.Initialize( );
});
gx.createParentObj(br_medication_schemeprompt);
