/*!   GeneXus C# 16_0_0-127771 on 2/27/2020 9:38:16.52
*/
gx.evt.autoSkip = false;
gx.define('br_pathologybr_pathology_diagwc', true, function (CmpContext) {
   this.ServerClass =  "br_pathologybr_pathology_diagwc" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.setCmpContext(CmpContext);
   this.ReadonlyForm = true;
   this.hasEnterEvent = false;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV45Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.AV32IsAuthorized_Update=gx.fn.getControlValue("vISAUTHORIZED_UPDATE") ;
      this.AV34IsAuthorized_Delete=gx.fn.getControlValue("vISAUTHORIZED_DELETE") ;
      this.AV8BR_PathologyID=gx.fn.getIntegerValue("vBR_PATHOLOGYID",',') ;
      this.AV8BR_PathologyID=gx.fn.getIntegerValue("vBR_PATHOLOGYID",',') ;
      this.AV45Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.AV32IsAuthorized_Update=gx.fn.getControlValue("vISAUTHORIZED_UPDATE") ;
      this.AV34IsAuthorized_Delete=gx.fn.getControlValue("vISAUTHORIZED_DELETE") ;
   };
   this.e195f2_client=function()
   {
      this.clearMessages();
      this.call("br_pathology_diagupdate.aspx", [this.A276BR_Pathology_DiagID]);
      this.refreshOutputs([]);
      return gx.$.Deferred().resolve();
   };
   this.e205f2_client=function()
   {
      this.clearMessages();
      this.call("br_pathology_diagdelete.aspx", [this.A276BR_Pathology_DiagID]);
      this.refreshOutputs([]);
      return gx.$.Deferred().resolve();
   };
   this.e115f2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEPAGE", false, null, true, true);
   };
   this.e125f2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", false, null, true, true);
   };
   this.e135f2_client=function()
   {
      return this.executeServerEvent("DDO_BR_PATHOLOGY_DIAG_LOC.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e145f2_client=function()
   {
      return this.executeServerEvent("DDO_BR_PATHOLOGY_DIAG_ORGAN.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e155f2_client=function()
   {
      return this.executeServerEvent("'DOINSERT'", false, null, false, false);
   };
   this.e215f2_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e225f2_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,35,36,37,39,40,41,43,45,46,48,49];
   this.GXLastCtrlId =49;
   this.GridContainer = new gx.grid.grid(this, 2,"WbpLvl2",28,"Grid","Grid","GridContainer",this.CmpContext,this.IsMasterPage,"br_pathologybr_pathology_diagwc",[],false,1,false,true,0,false,false,false,"",0,"px",0,"px","澧炲姞绌虹櫧琛?,true,false,false,null,null,false,"",false,[1,1,1,1],false,0,true,false);
   var GridContainer = this.GridContainer;
   GridContainer.addBitmap("&Display","vDISPLAY",29,0,"px",17,"px",null,"","","ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addBitmap("&Update","vUPDATE",30,0,"px",17,"px","e195f2_client","","","ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addBitmap("&Delete","vDELETE",31,0,"px",17,"px","e205f2_client","","","DeleteAttribute ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addSingleLineEdit(276,32,"BR_PATHOLOGY_DIAGID","鐥呯悊瀛﹁瘖鏂富閿?,"","BR_Pathology_DiagID","int",0,"px",18,18,"right",null,[],276,"BR_Pathology_DiagID",false,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(277,33,"BR_PATHOLOGY_DIAG_LOC","","","BR_Pathology_Diag_Loc","svchar",0,"px",100,80,"left",null,[],277,"BR_Pathology_Diag_Loc",true,0,false,false,"Attribute",1,"WWColumn");
   GridContainer.addSingleLineEdit(278,34,"BR_PATHOLOGY_DIAG_ORGAN","","","BR_Pathology_Diag_Organ","svchar",0,"px",100,80,"left",null,[],278,"BR_Pathology_Diag_Organ",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   this.GridContainer.emptyText = "";
   this.setGrid(GridContainer);
   this.DVPANEL_TABLEHEADERContainer = gx.uc.getNew(this, 10, 0, "BootstrapPanel", this.CmpContext + "DVPANEL_TABLEHEADERContainer", "Dvpanel_tableheader", "DVPANEL_TABLEHEADER");
   var DVPANEL_TABLEHEADERContainer = this.DVPANEL_TABLEHEADERContainer;
   DVPANEL_TABLEHEADERContainer.setProp("Class", "Class", "", "char");
   DVPANEL_TABLEHEADERContainer.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_TABLEHEADERContainer.setProp("Width", "Width", "100%", "str");
   DVPANEL_TABLEHEADERContainer.setProp("Height", "Height", "100", "str");
   DVPANEL_TABLEHEADERContainer.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Cls", "Cls", "PanelNoHeader", "str");
   DVPANEL_TABLEHEADERContainer.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Title", "Title", "閫夐」", "str");
   DVPANEL_TABLEHEADERContainer.setProp("Collapsible", "Collapsible", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("IconPosition", "Iconposition", "left", "str");
   DVPANEL_TABLEHEADERContainer.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Visible", "Visible", true, "bool");
   DVPANEL_TABLEHEADERContainer.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_TABLEHEADERContainer);
   this.GRIDPAGINATIONBARContainer = gx.uc.getNew(this, 38, 29, "DVelop_DVPaginationBar", this.CmpContext + "GRIDPAGINATIONBARContainer", "Gridpaginationbar", "GRIDPAGINATIONBAR");
   var GRIDPAGINATIONBARContainer = this.GRIDPAGINATIONBARContainer;
   GRIDPAGINATIONBARContainer.setProp("Enabled", "Enabled", true, "boolean");
   GRIDPAGINATIONBARContainer.setProp("Class", "Class", "PaginationBar", "str");
   GRIDPAGINATIONBARContainer.setProp("ShowFirst", "Showfirst", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowPrevious", "Showprevious", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowNext", "Shownext", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowLast", "Showlast", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("PagesToShow", "Pagestoshow", 5, "num");
   GRIDPAGINATIONBARContainer.setProp("PagingButtonsPosition", "Pagingbuttonsposition", "Right", "str");
   GRIDPAGINATIONBARContainer.setProp("PagingCaptionPosition", "Pagingcaptionposition", "Left", "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridClass", "Emptygridclass", "PaginationBarEmptyGrid", "str");
   GRIDPAGINATIONBARContainer.setProp("SelectedPage", "Selectedpage", "", "char");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageSelector", "Rowsperpageselector", true, "bool");
   GRIDPAGINATIONBARContainer.setDynProp("RowsPerPageSelectedValue", "Rowsperpageselectedvalue", 10, "num");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageOptions", "Rowsperpageoptions", "5:WWP_Rows5,10:WWP_Rows10,20:WWP_Rows20,50:WWP_Rows50", "str");
   GRIDPAGINATIONBARContainer.setProp("First", "First", "First", "str");
   GRIDPAGINATIONBARContainer.setProp("Previous", "Previous", "WWP_PagingPreviousCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Next", "Next", "WWP_PagingNextCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Last", "Last", "Last", "str");
   GRIDPAGINATIONBARContainer.setProp("Caption", "Caption", "<CURRENT_PAGE>椤?<TOTAL_PAGES>椤?璁板綍锛?TOTAL_RECORDS>鏉?, "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridCaption", "Emptygridcaption", "WWP_PagingEmptyGridCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageCaption", "Rowsperpagecaption", "WWP_PagingRowsPerPage", "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV28GridCurrentPage', "vGRIDCURRENTPAGE", 'SetCurrentPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV28GridCurrentPage=UC.GetCurrentPage();gx.fn.setControlValue("vGRIDCURRENTPAGE",UC.ParentObject.AV28GridCurrentPage); });
   GRIDPAGINATIONBARContainer.setProp("PageCount", "Pagecount", '', "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV30GridRecordCount', "vGRIDRECORDCOUNT", 'SetRecordCount');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV30GridRecordCount=UC.GetRecordCount();gx.fn.setControlValue("vGRIDRECORDCOUNT",UC.ParentObject.AV30GridRecordCount); });
   GRIDPAGINATIONBARContainer.addV2CFunction('AV29GridPageSize', "vGRIDPAGESIZE", 'SetPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV29GridPageSize=UC.GetPage();gx.fn.setControlValue("vGRIDPAGESIZE",UC.ParentObject.AV29GridPageSize); });
   GRIDPAGINATIONBARContainer.setProp("Visible", "Visible", true, "bool");
   GRIDPAGINATIONBARContainer.setC2ShowFunction(function(UC) { UC.show(); });
   GRIDPAGINATIONBARContainer.addEventHandler("ChangePage", this.e115f2_client);
   GRIDPAGINATIONBARContainer.addEventHandler("ChangeRowsPerPage", this.e125f2_client);
   this.setUserControl(GRIDPAGINATIONBARContainer);
   this.DDO_BR_PATHOLOGY_DIAG_LOCContainer = gx.uc.getNew(this, 42, 29, "BootstrapDropDownOptions", this.CmpContext + "DDO_BR_PATHOLOGY_DIAG_LOCContainer", "Ddo_br_pathology_diag_loc", "DDO_BR_PATHOLOGY_DIAG_LOC");
   var DDO_BR_PATHOLOGY_DIAG_LOCContainer = this.DDO_BR_PATHOLOGY_DIAG_LOCContainer;
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("Class", "Class", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.addV2CFunction('AV25DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV25DDO_TitleSettingsIcons); });
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.addV2CFunction('AV17BR_Pathology_Diag_LocTitleFilterData', "vBR_PATHOLOGY_DIAG_LOCTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.addC2VFunction(function(UC) { UC.ParentObject.AV17BR_Pathology_Diag_LocTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_PATHOLOGY_DIAG_LOCTITLEFILTERDATA",UC.ParentObject.AV17BR_Pathology_Diag_LocTitleFilterData); });
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_PATHOLOGY_DIAG_LOCContainer.addEventHandler("OnOptionClicked", this.e135f2_client);
   this.setUserControl(DDO_BR_PATHOLOGY_DIAG_LOCContainer);
   this.DDO_BR_PATHOLOGY_DIAG_ORGANContainer = gx.uc.getNew(this, 44, 43, "BootstrapDropDownOptions", this.CmpContext + "DDO_BR_PATHOLOGY_DIAG_ORGANContainer", "Ddo_br_pathology_diag_organ", "DDO_BR_PATHOLOGY_DIAG_ORGAN");
   var DDO_BR_PATHOLOGY_DIAG_ORGANContainer = this.DDO_BR_PATHOLOGY_DIAG_ORGANContainer;
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("Class", "Class", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.addV2CFunction('AV25DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV25DDO_TitleSettingsIcons); });
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.addV2CFunction('AV19BR_Pathology_Diag_OrganTitleFilterData', "vBR_PATHOLOGY_DIAG_ORGANTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.addC2VFunction(function(UC) { UC.ParentObject.AV19BR_Pathology_Diag_OrganTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_PATHOLOGY_DIAG_ORGANTITLEFILTERDATA",UC.ParentObject.AV19BR_Pathology_Diag_OrganTitleFilterData); });
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_PATHOLOGY_DIAG_ORGANContainer.addEventHandler("OnOptionClicked", this.e145f2_client);
   this.setUserControl(DDO_BR_PATHOLOGY_DIAG_ORGANContainer);
   this.WORKWITHPLUSUTILITIES1Container = gx.uc.getNew(this, 47, 43, "DVelop_WorkWithPlusUtilities", this.CmpContext + "WORKWITHPLUSUTILITIES1Container", "Workwithplusutilities1", "WORKWITHPLUSUTILITIES1");
   var WORKWITHPLUSUTILITIES1Container = this.WORKWITHPLUSUTILITIES1Container;
   WORKWITHPLUSUTILITIES1Container.setProp("Class", "Class", "", "char");
   WORKWITHPLUSUTILITIES1Container.setProp("Enabled", "Enabled", true, "boolean");
   WORKWITHPLUSUTILITIES1Container.setProp("Width", "Width", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Height", "Height", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Visible", "Visible", true, "bool");
   WORKWITHPLUSUTILITIES1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(WORKWITHPLUSUTILITIES1Container);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEGRIDHEADER",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"HTML_DVPANEL_TABLEHEADER",grid:0};
   GXValidFnc[12]={ id: 12, fld:"LAYOUT_TABLEHEADER",grid:0};
   GXValidFnc[13]={ id: 13, fld:"",grid:0};
   GXValidFnc[14]={ id: 14, fld:"TABLEHEADER",grid:0};
   GXValidFnc[15]={ id: 15, fld:"",grid:0};
   GXValidFnc[16]={ id: 16, fld:"",grid:0};
   GXValidFnc[17]={ id: 17, fld:"TABLEACTIONS",grid:0};
   GXValidFnc[18]={ id: 18, fld:"",grid:0};
   GXValidFnc[19]={ id: 19, fld:"",grid:0};
   GXValidFnc[20]={ id: 20, fld:"",grid:0};
   GXValidFnc[21]={ id: 21, fld:"",grid:0};
   GXValidFnc[22]={ id: 22, fld:"BTNINSERT",grid:0};
   GXValidFnc[23]={ id: 23, fld:"",grid:0};
   GXValidFnc[24]={ id: 24, fld:"",grid:0};
   GXValidFnc[25]={ id: 25, fld:"GRIDTABLEWITHPAGINATIONBAR",grid:0};
   GXValidFnc[26]={ id: 26, fld:"",grid:0};
   GXValidFnc[27]={ id: 27, fld:"",grid:0};
   GXValidFnc[29]={ id:29 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDISPLAY",gxz:"ZV35Display",gxold:"OV35Display",gxvar:"AV35Display",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV35Display=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV35Display=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vDISPLAY",row || gx.fn.currentGridRowImpl(28),gx.O.AV35Display,gx.O.AV42Display_GXI)},c2v:function(){gx.O.AV42Display_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV35Display=this.val()},val:function(row){return gx.fn.getGridControlValue("vDISPLAY",row || gx.fn.currentGridRowImpl(28))},val_GXI:function(row){return gx.fn.getGridControlValue("vDISPLAY_GXI",row || gx.fn.currentGridRowImpl(28))}, gxvar_GXI:'AV42Display_GXI',nac:gx.falseFn};
   GXValidFnc[30]={ id:30 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vUPDATE",gxz:"ZV31Update",gxold:"OV31Update",gxvar:"AV31Update",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV31Update=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV31Update=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vUPDATE",row || gx.fn.currentGridRowImpl(28),gx.O.AV31Update,gx.O.AV43Update_GXI)},c2v:function(){gx.O.AV43Update_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV31Update=this.val()},val:function(row){return gx.fn.getGridControlValue("vUPDATE",row || gx.fn.currentGridRowImpl(28))},val_GXI:function(row){return gx.fn.getGridControlValue("vUPDATE_GXI",row || gx.fn.currentGridRowImpl(28))}, gxvar_GXI:'AV43Update_GXI',nac:gx.falseFn,evt:"e195f2_client"};
   GXValidFnc[31]={ id:31 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDELETE",gxz:"ZV33Delete",gxold:"OV33Delete",gxvar:"AV33Delete",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV33Delete=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV33Delete=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vDELETE",row || gx.fn.currentGridRowImpl(28),gx.O.AV33Delete,gx.O.AV44Delete_GXI)},c2v:function(){gx.O.AV44Delete_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV33Delete=this.val()},val:function(row){return gx.fn.getGridControlValue("vDELETE",row || gx.fn.currentGridRowImpl(28))},val_GXI:function(row){return gx.fn.getGridControlValue("vDELETE_GXI",row || gx.fn.currentGridRowImpl(28))}, gxvar_GXI:'AV44Delete_GXI',nac:gx.falseFn,evt:"e205f2_client"};
   GXValidFnc[32]={ id:32 ,lvl:2,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_PATHOLOGY_DIAGID",gxz:"Z276BR_Pathology_DiagID",gxold:"O276BR_Pathology_DiagID",gxvar:"A276BR_Pathology_DiagID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A276BR_Pathology_DiagID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z276BR_Pathology_DiagID=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("BR_PATHOLOGY_DIAGID",row || gx.fn.currentGridRowImpl(28),gx.O.A276BR_Pathology_DiagID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A276BR_Pathology_DiagID=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("BR_PATHOLOGY_DIAGID",row || gx.fn.currentGridRowImpl(28),',')},nac:gx.falseFn};
   GXValidFnc[33]={ id:33 ,lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_PATHOLOGY_DIAG_LOC",gxz:"Z277BR_Pathology_Diag_Loc",gxold:"O277BR_Pathology_Diag_Loc",gxvar:"A277BR_Pathology_Diag_Loc",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A277BR_Pathology_Diag_Loc=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z277BR_Pathology_Diag_Loc=Value},v2c:function(row){gx.fn.setGridControlValue("BR_PATHOLOGY_DIAG_LOC",row || gx.fn.currentGridRowImpl(28),gx.O.A277BR_Pathology_Diag_Loc,0)},c2v:function(){if(this.val()!==undefined)gx.O.A277BR_Pathology_Diag_Loc=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_PATHOLOGY_DIAG_LOC",row || gx.fn.currentGridRowImpl(28))},nac:gx.falseFn};
   GXValidFnc[34]={ id:34 ,lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_PATHOLOGY_DIAG_ORGAN",gxz:"Z278BR_Pathology_Diag_Organ",gxold:"O278BR_Pathology_Diag_Organ",gxvar:"A278BR_Pathology_Diag_Organ",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A278BR_Pathology_Diag_Organ=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z278BR_Pathology_Diag_Organ=Value},v2c:function(row){gx.fn.setGridControlValue("BR_PATHOLOGY_DIAG_ORGAN",row || gx.fn.currentGridRowImpl(28),gx.O.A278BR_Pathology_Diag_Organ,0)},c2v:function(){if(this.val()!==undefined)gx.O.A278BR_Pathology_Diag_Organ=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_PATHOLOGY_DIAG_ORGAN",row || gx.fn.currentGridRowImpl(28))},nac:gx.falseFn};
   GXValidFnc[35]={ id: 35, fld:"",grid:0};
   GXValidFnc[36]={ id: 36, fld:"",grid:0};
   GXValidFnc[37]={ id: 37, fld:"HTML_GRIDPAGINATIONBAR",grid:0};
   GXValidFnc[39]={ id: 39, fld:"",grid:0};
   GXValidFnc[40]={ id: 40, fld:"",grid:0};
   GXValidFnc[41]={ id: 41, fld:"HTML_BOTTOMAUXILIARCONTROLS",grid:0};
   GXValidFnc[43]={ id:43 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_PATHOLOGY_DIAG_LOCTITLECONTROLIDTOREPLACE",gxz:"ZV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace",gxold:"OV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace",gxvar:"AV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_PATHOLOGY_DIAG_LOCTITLECONTROLIDTOREPLACE",gx.O.AV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_PATHOLOGY_DIAG_LOCTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[45]={ id:45 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_PATHOLOGY_DIAG_ORGANTITLECONTROLIDTOREPLACE",gxz:"ZV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace",gxold:"OV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace",gxvar:"AV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_PATHOLOGY_DIAG_ORGANTITLECONTROLIDTOREPLACE",gx.O.AV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_PATHOLOGY_DIAG_ORGANTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[46]={ id:46 ,lvl:0,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_PATHOLOGYID",gxz:"Z226BR_PathologyID",gxold:"O226BR_PathologyID",gxvar:"A226BR_PathologyID",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.A226BR_PathologyID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z226BR_PathologyID=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("BR_PATHOLOGYID",gx.O.A226BR_PathologyID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A226BR_PathologyID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("BR_PATHOLOGYID",',')},nac:gx.falseFn};
   this.declareDomainHdlr( 46 , function() {
   });
   GXValidFnc[48]={ id:48 ,lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDBY",gxz:"ZV14OrderedBy",gxold:"OV14OrderedBy",gxvar:"AV14OrderedBy",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV14OrderedBy=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV14OrderedBy=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDBY",gx.O.AV14OrderedBy,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV14OrderedBy=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vORDEREDBY",',')},nac:gx.falseFn};
   GXValidFnc[49]={ id:49 ,lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDDSC",gxz:"ZV15OrderedDsc",gxold:"OV15OrderedDsc",gxvar:"AV15OrderedDsc",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV15OrderedDsc=gx.lang.booleanValue(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV15OrderedDsc=gx.lang.booleanValue(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDDSC",gx.O.AV15OrderedDsc,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV15OrderedDsc=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getControlValue("vORDEREDDSC")},nac:gx.falseFn};
   this.ZV35Display = "" ;
   this.OV35Display = "" ;
   this.ZV31Update = "" ;
   this.OV31Update = "" ;
   this.ZV33Delete = "" ;
   this.OV33Delete = "" ;
   this.Z276BR_Pathology_DiagID = 0 ;
   this.O276BR_Pathology_DiagID = 0 ;
   this.Z277BR_Pathology_Diag_Loc = "" ;
   this.O277BR_Pathology_Diag_Loc = "" ;
   this.Z278BR_Pathology_Diag_Organ = "" ;
   this.O278BR_Pathology_Diag_Organ = "" ;
   this.AV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace = "" ;
   this.ZV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace = "" ;
   this.OV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace = "" ;
   this.AV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace = "" ;
   this.ZV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace = "" ;
   this.OV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace = "" ;
   this.A226BR_PathologyID = 0 ;
   this.Z226BR_PathologyID = 0 ;
   this.O226BR_PathologyID = 0 ;
   this.AV14OrderedBy = 0 ;
   this.ZV14OrderedBy = 0 ;
   this.OV14OrderedBy = 0 ;
   this.AV15OrderedDsc = false ;
   this.ZV15OrderedDsc = false ;
   this.OV15OrderedDsc = false ;
   this.AV28GridCurrentPage = 0 ;
   this.AV25DDO_TitleSettingsIcons = {Default:"",Default_GXI:"",Filtered:"",Filtered_GXI:"",SortedASC:"",SortedASC_GXI:"",SortedDSC:"",SortedDSC_GXI:"",FilteredSortedASC:"",FilteredSortedASC_GXI:"",FilteredSortedDSC:"",FilteredSortedDSC_GXI:"",OptionSortASC:"",OptionSortASC_GXI:"",OptionSortDSC:"",OptionSortDSC_GXI:"",OptionApplyFilter:"",OptionApplyFilter_GXI:"",OptionFilteringData:"",OptionFilteringData_GXI:"",OptionCleanFilters:"",OptionCleanFilters_GXI:"",SelectedOption:"",SelectedOption_GXI:"",MultiselOption:"",MultiselOption_GXI:"",MultiselSelOption:"",MultiselSelOption_GXI:""} ;
   this.AV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace = "" ;
   this.AV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace = "" ;
   this.A226BR_PathologyID = 0 ;
   this.AV14OrderedBy = 0 ;
   this.AV15OrderedDsc = false ;
   this.AV8BR_PathologyID = 0 ;
   this.AV35Display = "" ;
   this.AV31Update = "" ;
   this.AV33Delete = "" ;
   this.A276BR_Pathology_DiagID = 0 ;
   this.A277BR_Pathology_Diag_Loc = "" ;
   this.A278BR_Pathology_Diag_Organ = "" ;
   this.AV45Pgmname = "" ;
   this.AV32IsAuthorized_Update = false ;
   this.AV34IsAuthorized_Delete = false ;
   this.Events = {"e115f2_client": ["GRIDPAGINATIONBAR.CHANGEPAGE", true] ,"e125f2_client": ["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", true] ,"e135f2_client": ["DDO_BR_PATHOLOGY_DIAG_LOC.ONOPTIONCLICKED", true] ,"e145f2_client": ["DDO_BR_PATHOLOGY_DIAG_ORGAN.ONOPTIONCLICKED", true] ,"e155f2_client": ["'DOINSERT'", true] ,"e215f2_client": ["ENTER", true] ,"e225f2_client": ["CANCEL", true] ,"e195f2_client": ["VUPDATE.CLICK", false] ,"e205f2_client": ["VDELETE.CLICK", false]};
   this.EvtParms["REFRESH"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'AV8BR_PathologyID',fld:'vBR_PATHOLOGYID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{av:'AV32IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'AV34IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'AV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{ctrl:'GRID',prop:'Rows'},{av:'AV45Pgmname',fld:'vPGMNAME',pic:''},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''}],[{av:'AV17BR_Pathology_Diag_LocTitleFilterData',fld:'vBR_PATHOLOGY_DIAG_LOCTITLEFILTERDATA',pic:''},{av:'AV19BR_Pathology_Diag_OrganTitleFilterData',fld:'vBR_PATHOLOGY_DIAG_ORGANTITLEFILTERDATA',pic:''},{ctrl:'BR_PATHOLOGY_DIAG_LOC',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_DIAG_LOC","Title")',ctrl:'BR_PATHOLOGY_DIAG_LOC',prop:'Title'},{ctrl:'BR_PATHOLOGY_DIAG_ORGAN',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_DIAG_ORGAN","Title")',ctrl:'BR_PATHOLOGY_DIAG_ORGAN',prop:'Title'},{av:'AV28GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV29GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV30GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'AV32IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'AV34IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{ctrl:'BTNINSERT',prop:'Visible'}]];
   this.EvtParms["START"] = [[{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV45Pgmname',fld:'vPGMNAME',pic:''},{av:'AV8BR_PathologyID',fld:'vBR_PATHOLOGYID',pic:'ZZZZZZZZZZZZZZZZZZ'}],[{ctrl:'GRID',prop:'Rows'},{av:'this.DDO_BR_PATHOLOGY_DIAG_LOCContainer.TitleControlIdToReplace',ctrl:'DDO_BR_PATHOLOGY_DIAG_LOC',prop:'TitleControlIdToReplace'},{av:'AV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_PATHOLOGY_DIAG_LOCTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_PATHOLOGY_DIAG_LOCTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_PATHOLOGY_DIAG_ORGANContainer.TitleControlIdToReplace',ctrl:'DDO_BR_PATHOLOGY_DIAG_ORGAN',prop:'TitleControlIdToReplace'},{av:'AV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_PATHOLOGY_DIAG_ORGANTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_PATHOLOGY_DIAG_ORGANTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGYID","Visible")',ctrl:'BR_PATHOLOGYID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vORDEREDBY","Visible")',ctrl:'vORDEREDBY',prop:'Visible'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'gx.fn.getCtrlProperty("vORDEREDDSC","Visible")',ctrl:'vORDEREDDSC',prop:'Visible'},{av:'AV25DDO_TitleSettingsIcons',fld:'vDDO_TITLESETTINGSICONS',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'},{av:'gx.fn.getCtrlProperty("TABLEHEADER","Visible")',ctrl:'TABLEHEADER',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''}]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_PathologyID',fld:'vBR_PATHOLOGYID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{av:'AV45Pgmname',fld:'vPGMNAME',pic:''},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{av:'AV32IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'AV34IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'this.GRIDPAGINATIONBARContainer.SelectedPage',ctrl:'GRIDPAGINATIONBAR',prop:'SelectedPage'}],[]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_PathologyID',fld:'vBR_PATHOLOGYID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{av:'AV45Pgmname',fld:'vPGMNAME',pic:''},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{av:'AV32IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'AV34IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}],[{ctrl:'GRID',prop:'Rows'}]];
   this.EvtParms["DDO_BR_PATHOLOGY_DIAG_LOC.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_PathologyID',fld:'vBR_PATHOLOGYID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{av:'AV45Pgmname',fld:'vPGMNAME',pic:''},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{av:'AV32IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'AV34IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'this.DDO_BR_PATHOLOGY_DIAG_LOCContainer.ActiveEventKey',ctrl:'DDO_BR_PATHOLOGY_DIAG_LOC',prop:'ActiveEventKey'}],[{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_PATHOLOGY_DIAG_LOCContainer.SortedStatus',ctrl:'DDO_BR_PATHOLOGY_DIAG_LOC',prop:'SortedStatus'},{av:'AV17BR_Pathology_Diag_LocTitleFilterData',fld:'vBR_PATHOLOGY_DIAG_LOCTITLEFILTERDATA',pic:''},{av:'AV19BR_Pathology_Diag_OrganTitleFilterData',fld:'vBR_PATHOLOGY_DIAG_ORGANTITLEFILTERDATA',pic:''},{ctrl:'BR_PATHOLOGY_DIAG_LOC',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_DIAG_LOC","Title")',ctrl:'BR_PATHOLOGY_DIAG_LOC',prop:'Title'},{ctrl:'BR_PATHOLOGY_DIAG_ORGAN',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_DIAG_ORGAN","Title")',ctrl:'BR_PATHOLOGY_DIAG_ORGAN',prop:'Title'},{av:'AV28GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV29GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV30GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'AV32IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'AV34IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{ctrl:'BTNINSERT',prop:'Visible'}]];
   this.EvtParms["DDO_BR_PATHOLOGY_DIAG_ORGAN.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_PathologyID',fld:'vBR_PATHOLOGYID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV18ddo_BR_Pathology_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_BR_Pathology_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{av:'AV45Pgmname',fld:'vPGMNAME',pic:''},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{av:'AV32IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'AV34IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'this.DDO_BR_PATHOLOGY_DIAG_ORGANContainer.ActiveEventKey',ctrl:'DDO_BR_PATHOLOGY_DIAG_ORGAN',prop:'ActiveEventKey'}],[{av:'AV14OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV15OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_PATHOLOGY_DIAG_ORGANContainer.SortedStatus',ctrl:'DDO_BR_PATHOLOGY_DIAG_ORGAN',prop:'SortedStatus'},{av:'AV17BR_Pathology_Diag_LocTitleFilterData',fld:'vBR_PATHOLOGY_DIAG_LOCTITLEFILTERDATA',pic:''},{av:'AV19BR_Pathology_Diag_OrganTitleFilterData',fld:'vBR_PATHOLOGY_DIAG_ORGANTITLEFILTERDATA',pic:''},{ctrl:'BR_PATHOLOGY_DIAG_LOC',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_DIAG_LOC","Title")',ctrl:'BR_PATHOLOGY_DIAG_LOC',prop:'Title'},{ctrl:'BR_PATHOLOGY_DIAG_ORGAN',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_DIAG_ORGAN","Title")',ctrl:'BR_PATHOLOGY_DIAG_ORGAN',prop:'Title'},{av:'AV28GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV29GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV30GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'AV32IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'AV34IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{ctrl:'BTNINSERT',prop:'Visible'}]];
   this.EvtParms["GRID.LOAD"] = [[{av:'A276BR_Pathology_DiagID',fld:'BR_PATHOLOGY_DIAGID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true},{av:'AV32IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'AV34IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''}],[{av:'AV35Display',fld:'vDISPLAY',pic:''},{av:'gx.fn.getCtrlProperty("vDISPLAY","Tooltiptext")',ctrl:'vDISPLAY',prop:'Tooltiptext'},{av:'gx.fn.getCtrlProperty("vDISPLAY","Link")',ctrl:'vDISPLAY',prop:'Link'},{av:'AV31Update',fld:'vUPDATE',pic:''},{av:'gx.fn.getCtrlProperty("vUPDATE","Tooltiptext")',ctrl:'vUPDATE',prop:'Tooltiptext'},{av:'gx.fn.getCtrlProperty("vUPDATE","Link")',ctrl:'vUPDATE',prop:'Link'},{av:'AV33Delete',fld:'vDELETE',pic:''},{av:'gx.fn.getCtrlProperty("vDELETE","Tooltiptext")',ctrl:'vDELETE',prop:'Tooltiptext'},{av:'gx.fn.getCtrlProperty("vDELETE","Link")',ctrl:'vDELETE',prop:'Link'}]];
   this.EvtParms["'DOINSERT'"] = [[{av:'A276BR_Pathology_DiagID',fld:'BR_PATHOLOGY_DIAGID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true},{av:'AV8BR_PathologyID',fld:'vBR_PATHOLOGYID',pic:'ZZZZZZZZZZZZZZZZZZ'}],[]];
   this.EvtParms["VUPDATE.CLICK"] = [[{av:'A276BR_Pathology_DiagID',fld:'BR_PATHOLOGY_DIAGID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true}],[]];
   this.EvtParms["VDELETE.CLICK"] = [[{av:'A276BR_Pathology_DiagID',fld:'BR_PATHOLOGY_DIAGID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true}],[]];
   this.setVCMap("AV45Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV32IsAuthorized_Update", "vISAUTHORIZED_UPDATE", 0, "boolean", 4, 0);
   this.setVCMap("AV34IsAuthorized_Delete", "vISAUTHORIZED_DELETE", 0, "boolean", 4, 0);
   this.setVCMap("AV8BR_PathologyID", "vBR_PATHOLOGYID", 0, "int", 18, 0);
   this.setVCMap("AV8BR_PathologyID", "vBR_PATHOLOGYID", 0, "int", 18, 0);
   this.setVCMap("AV45Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV32IsAuthorized_Update", "vISAUTHORIZED_UPDATE", 0, "boolean", 4, 0);
   this.setVCMap("AV34IsAuthorized_Delete", "vISAUTHORIZED_DELETE", 0, "boolean", 4, 0);
   this.setVCMap("AV8BR_PathologyID", "vBR_PATHOLOGYID", 0, "int", 18, 0);
   this.setVCMap("AV45Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV32IsAuthorized_Update", "vISAUTHORIZED_UPDATE", 0, "boolean", 4, 0);
   this.setVCMap("AV34IsAuthorized_Delete", "vISAUTHORIZED_DELETE", 0, "boolean", 4, 0);
   GridContainer.addRefreshingVar(this.GXValidFnc[48]);
   GridContainer.addRefreshingVar(this.GXValidFnc[49]);
   GridContainer.addRefreshingVar({rfrVar:"AV8BR_PathologyID"});
   GridContainer.addRefreshingVar(this.GXValidFnc[43]);
   GridContainer.addRefreshingVar(this.GXValidFnc[45]);
   GridContainer.addRefreshingVar({rfrVar:"AV45Pgmname"});
   GridContainer.addRefreshingVar({rfrVar:"AV31Update", rfrProp:"Visible", gxAttId:"Update"});
   GridContainer.addRefreshingVar({rfrVar:"AV33Delete", rfrProp:"Visible", gxAttId:"Delete"});
   GridContainer.addRefreshingVar({rfrVar:"AV32IsAuthorized_Update"});
   GridContainer.addRefreshingVar({rfrVar:"AV34IsAuthorized_Delete"});
   this.Initialize( );
});
