/*!   GeneXus C# 16_0_0-127771 on 2/27/2020 9:38:8.26
*/
gx.evt.autoSkip = false;
gx.define('br_pathologybr_pathology_specimenwc', true, function (CmpContext) {
   this.ServerClass =  "br_pathologybr_pathology_specimenwc" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.setCmpContext(CmpContext);
   this.ReadonlyForm = true;
   this.hasEnterEvent = false;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV38Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.AV25IsAuthorized_Update=gx.fn.getControlValue("vISAUTHORIZED_UPDATE") ;
      this.AV27IsAuthorized_Delete=gx.fn.getControlValue("vISAUTHORIZED_DELETE") ;
      this.AV8BR_PathologyID=gx.fn.getIntegerValue("vBR_PATHOLOGYID",',') ;
      this.AV8BR_PathologyID=gx.fn.getIntegerValue("vBR_PATHOLOGYID",',') ;
      this.AV38Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.AV25IsAuthorized_Update=gx.fn.getControlValue("vISAUTHORIZED_UPDATE") ;
      this.AV27IsAuthorized_Delete=gx.fn.getControlValue("vISAUTHORIZED_DELETE") ;
   };
   this.e185e2_client=function()
   {
      this.clearMessages();
      this.call("br_pathology_specimenupdate.aspx", [this.A274BR_Pathology_SpecimenID]);
      this.refreshOutputs([]);
      return gx.$.Deferred().resolve();
   };
   this.e195e2_client=function()
   {
      this.clearMessages();
      this.call("br_pathology_specimendelete.aspx", [this.A274BR_Pathology_SpecimenID]);
      this.refreshOutputs([]);
      return gx.$.Deferred().resolve();
   };
   this.e115e2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEPAGE", false, null, true, true);
   };
   this.e125e2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", false, null, true, true);
   };
   this.e135e2_client=function()
   {
      return this.executeServerEvent("DDO_BR_PATHOLOGY_SPECIMEN_NAME.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e145e2_client=function()
   {
      return this.executeServerEvent("'DOINSERT'", false, null, false, false);
   };
   this.e205e2_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e215e2_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,35,36,38,39,40,42,43,45];
   this.GXLastCtrlId =45;
   this.GridContainer = new gx.grid.grid(this, 2,"WbpLvl2",28,"Grid","Grid","GridContainer",this.CmpContext,this.IsMasterPage,"br_pathologybr_pathology_specimenwc",[],false,1,false,true,0,false,false,false,"",0,"px",0,"px","澧炲姞绌虹櫧琛?,true,false,false,null,null,false,"",false,[1,1,1,1],false,0,true,false);
   var GridContainer = this.GridContainer;
   GridContainer.addBitmap("&Display","vDISPLAY",29,0,"px",17,"px",null,"","","ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addBitmap("&Update","vUPDATE",30,0,"px",17,"px","e185e2_client","","","ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addBitmap("&Delete","vDELETE",31,0,"px",17,"px","e195e2_client","","","DeleteAttribute ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addSingleLineEdit(274,32,"BR_PATHOLOGY_SPECIMENID","鐥呯悊瀛﹂€佹缁勭粐涓婚敭","","BR_Pathology_SpecimenID","int",0,"px",18,18,"right",null,[],274,"BR_Pathology_SpecimenID",false,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(275,33,"BR_PATHOLOGY_SPECIMEN_NAME","","","BR_Pathology_Specimen_Name","svchar",0,"px",100,80,"left",null,[],275,"BR_Pathology_Specimen_Name",true,0,false,false,"Attribute",1,"WWColumn");
   this.GridContainer.emptyText = "";
   this.setGrid(GridContainer);
   this.DVPANEL_TABLEHEADERContainer = gx.uc.getNew(this, 10, 0, "BootstrapPanel", this.CmpContext + "DVPANEL_TABLEHEADERContainer", "Dvpanel_tableheader", "DVPANEL_TABLEHEADER");
   var DVPANEL_TABLEHEADERContainer = this.DVPANEL_TABLEHEADERContainer;
   DVPANEL_TABLEHEADERContainer.setProp("Class", "Class", "", "char");
   DVPANEL_TABLEHEADERContainer.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_TABLEHEADERContainer.setProp("Width", "Width", "100%", "str");
   DVPANEL_TABLEHEADERContainer.setProp("Height", "Height", "100", "str");
   DVPANEL_TABLEHEADERContainer.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Cls", "Cls", "PanelNoHeader", "str");
   DVPANEL_TABLEHEADERContainer.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Title", "Title", "閫夐」", "str");
   DVPANEL_TABLEHEADERContainer.setProp("Collapsible", "Collapsible", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("IconPosition", "Iconposition", "left", "str");
   DVPANEL_TABLEHEADERContainer.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Visible", "Visible", true, "bool");
   DVPANEL_TABLEHEADERContainer.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_TABLEHEADERContainer);
   this.GRIDPAGINATIONBARContainer = gx.uc.getNew(this, 37, 29, "DVelop_DVPaginationBar", this.CmpContext + "GRIDPAGINATIONBARContainer", "Gridpaginationbar", "GRIDPAGINATIONBAR");
   var GRIDPAGINATIONBARContainer = this.GRIDPAGINATIONBARContainer;
   GRIDPAGINATIONBARContainer.setProp("Enabled", "Enabled", true, "boolean");
   GRIDPAGINATIONBARContainer.setProp("Class", "Class", "PaginationBar", "str");
   GRIDPAGINATIONBARContainer.setProp("ShowFirst", "Showfirst", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowPrevious", "Showprevious", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowNext", "Shownext", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowLast", "Showlast", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("PagesToShow", "Pagestoshow", 5, "num");
   GRIDPAGINATIONBARContainer.setProp("PagingButtonsPosition", "Pagingbuttonsposition", "Right", "str");
   GRIDPAGINATIONBARContainer.setProp("PagingCaptionPosition", "Pagingcaptionposition", "Left", "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridClass", "Emptygridclass", "PaginationBarEmptyGrid", "str");
   GRIDPAGINATIONBARContainer.setProp("SelectedPage", "Selectedpage", "", "char");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageSelector", "Rowsperpageselector", true, "bool");
   GRIDPAGINATIONBARContainer.setDynProp("RowsPerPageSelectedValue", "Rowsperpageselectedvalue", 10, "num");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageOptions", "Rowsperpageoptions", "5:WWP_Rows5,10:WWP_Rows10,20:WWP_Rows20,50:WWP_Rows50", "str");
   GRIDPAGINATIONBARContainer.setProp("First", "First", "First", "str");
   GRIDPAGINATIONBARContainer.setProp("Previous", "Previous", "WWP_PagingPreviousCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Next", "Next", "WWP_PagingNextCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Last", "Last", "Last", "str");
   GRIDPAGINATIONBARContainer.setProp("Caption", "Caption", "<CURRENT_PAGE>椤?<TOTAL_PAGES>椤?璁板綍锛?TOTAL_RECORDS>鏉?, "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridCaption", "Emptygridcaption", "WWP_PagingEmptyGridCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageCaption", "Rowsperpagecaption", "WWP_PagingRowsPerPage", "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV21GridCurrentPage', "vGRIDCURRENTPAGE", 'SetCurrentPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV21GridCurrentPage=UC.GetCurrentPage();gx.fn.setControlValue("vGRIDCURRENTPAGE",UC.ParentObject.AV21GridCurrentPage); });
   GRIDPAGINATIONBARContainer.setProp("PageCount", "Pagecount", '', "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV23GridRecordCount', "vGRIDRECORDCOUNT", 'SetRecordCount');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV23GridRecordCount=UC.GetRecordCount();gx.fn.setControlValue("vGRIDRECORDCOUNT",UC.ParentObject.AV23GridRecordCount); });
   GRIDPAGINATIONBARContainer.addV2CFunction('AV22GridPageSize', "vGRIDPAGESIZE", 'SetPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV22GridPageSize=UC.GetPage();gx.fn.setControlValue("vGRIDPAGESIZE",UC.ParentObject.AV22GridPageSize); });
   GRIDPAGINATIONBARContainer.setProp("Visible", "Visible", true, "bool");
   GRIDPAGINATIONBARContainer.setC2ShowFunction(function(UC) { UC.show(); });
   GRIDPAGINATIONBARContainer.addEventHandler("ChangePage", this.e115e2_client);
   GRIDPAGINATIONBARContainer.addEventHandler("ChangeRowsPerPage", this.e125e2_client);
   this.setUserControl(GRIDPAGINATIONBARContainer);
   this.DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer = gx.uc.getNew(this, 41, 29, "BootstrapDropDownOptions", this.CmpContext + "DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer", "Ddo_br_pathology_specimen_name", "DDO_BR_PATHOLOGY_SPECIMEN_NAME");
   var DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer = this.DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer;
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("Class", "Class", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.addV2CFunction('AV18DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV18DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV18DDO_TitleSettingsIcons); });
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.addV2CFunction('AV16BR_Pathology_Specimen_NameTitleFilterData', "vBR_PATHOLOGY_SPECIMEN_NAMETITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV16BR_Pathology_Specimen_NameTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_PATHOLOGY_SPECIMEN_NAMETITLEFILTERDATA",UC.ParentObject.AV16BR_Pathology_Specimen_NameTitleFilterData); });
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.addEventHandler("OnOptionClicked", this.e135e2_client);
   this.setUserControl(DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer);
   this.WORKWITHPLUSUTILITIES1Container = gx.uc.getNew(this, 44, 42, "DVelop_WorkWithPlusUtilities", this.CmpContext + "WORKWITHPLUSUTILITIES1Container", "Workwithplusutilities1", "WORKWITHPLUSUTILITIES1");
   var WORKWITHPLUSUTILITIES1Container = this.WORKWITHPLUSUTILITIES1Container;
   WORKWITHPLUSUTILITIES1Container.setProp("Class", "Class", "", "char");
   WORKWITHPLUSUTILITIES1Container.setProp("Enabled", "Enabled", true, "boolean");
   WORKWITHPLUSUTILITIES1Container.setProp("Width", "Width", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Height", "Height", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Visible", "Visible", true, "bool");
   WORKWITHPLUSUTILITIES1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(WORKWITHPLUSUTILITIES1Container);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEGRIDHEADER",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"HTML_DVPANEL_TABLEHEADER",grid:0};
   GXValidFnc[12]={ id: 12, fld:"LAYOUT_TABLEHEADER",grid:0};
   GXValidFnc[13]={ id: 13, fld:"",grid:0};
   GXValidFnc[14]={ id: 14, fld:"TABLEHEADER",grid:0};
   GXValidFnc[15]={ id: 15, fld:"",grid:0};
   GXValidFnc[16]={ id: 16, fld:"",grid:0};
   GXValidFnc[17]={ id: 17, fld:"TABLEACTIONS",grid:0};
   GXValidFnc[18]={ id: 18, fld:"",grid:0};
   GXValidFnc[19]={ id: 19, fld:"",grid:0};
   GXValidFnc[20]={ id: 20, fld:"",grid:0};
   GXValidFnc[21]={ id: 21, fld:"",grid:0};
   GXValidFnc[22]={ id: 22, fld:"BTNINSERT",grid:0};
   GXValidFnc[23]={ id: 23, fld:"",grid:0};
   GXValidFnc[24]={ id: 24, fld:"",grid:0};
   GXValidFnc[25]={ id: 25, fld:"GRIDTABLEWITHPAGINATIONBAR",grid:0};
   GXValidFnc[26]={ id: 26, fld:"",grid:0};
   GXValidFnc[27]={ id: 27, fld:"",grid:0};
   GXValidFnc[29]={ id:29 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDISPLAY",gxz:"ZV28Display",gxold:"OV28Display",gxvar:"AV28Display",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV28Display=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV28Display=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vDISPLAY",row || gx.fn.currentGridRowImpl(28),gx.O.AV28Display,gx.O.AV35Display_GXI)},c2v:function(){gx.O.AV35Display_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV28Display=this.val()},val:function(row){return gx.fn.getGridControlValue("vDISPLAY",row || gx.fn.currentGridRowImpl(28))},val_GXI:function(row){return gx.fn.getGridControlValue("vDISPLAY_GXI",row || gx.fn.currentGridRowImpl(28))}, gxvar_GXI:'AV35Display_GXI',nac:gx.falseFn};
   GXValidFnc[30]={ id:30 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vUPDATE",gxz:"ZV24Update",gxold:"OV24Update",gxvar:"AV24Update",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV24Update=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV24Update=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vUPDATE",row || gx.fn.currentGridRowImpl(28),gx.O.AV24Update,gx.O.AV36Update_GXI)},c2v:function(){gx.O.AV36Update_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV24Update=this.val()},val:function(row){return gx.fn.getGridControlValue("vUPDATE",row || gx.fn.currentGridRowImpl(28))},val_GXI:function(row){return gx.fn.getGridControlValue("vUPDATE_GXI",row || gx.fn.currentGridRowImpl(28))}, gxvar_GXI:'AV36Update_GXI',nac:gx.falseFn,evt:"e185e2_client"};
   GXValidFnc[31]={ id:31 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDELETE",gxz:"ZV26Delete",gxold:"OV26Delete",gxvar:"AV26Delete",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV26Delete=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV26Delete=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vDELETE",row || gx.fn.currentGridRowImpl(28),gx.O.AV26Delete,gx.O.AV37Delete_GXI)},c2v:function(){gx.O.AV37Delete_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV26Delete=this.val()},val:function(row){return gx.fn.getGridControlValue("vDELETE",row || gx.fn.currentGridRowImpl(28))},val_GXI:function(row){return gx.fn.getGridControlValue("vDELETE_GXI",row || gx.fn.currentGridRowImpl(28))}, gxvar_GXI:'AV37Delete_GXI',nac:gx.falseFn,evt:"e195e2_client"};
   GXValidFnc[32]={ id:32 ,lvl:2,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_PATHOLOGY_SPECIMENID",gxz:"Z274BR_Pathology_SpecimenID",gxold:"O274BR_Pathology_SpecimenID",gxvar:"A274BR_Pathology_SpecimenID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A274BR_Pathology_SpecimenID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z274BR_Pathology_SpecimenID=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("BR_PATHOLOGY_SPECIMENID",row || gx.fn.currentGridRowImpl(28),gx.O.A274BR_Pathology_SpecimenID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A274BR_Pathology_SpecimenID=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("BR_PATHOLOGY_SPECIMENID",row || gx.fn.currentGridRowImpl(28),',')},nac:gx.falseFn};
   GXValidFnc[33]={ id:33 ,lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:28,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_PATHOLOGY_SPECIMEN_NAME",gxz:"Z275BR_Pathology_Specimen_Name",gxold:"O275BR_Pathology_Specimen_Name",gxvar:"A275BR_Pathology_Specimen_Name",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A275BR_Pathology_Specimen_Name=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z275BR_Pathology_Specimen_Name=Value},v2c:function(row){gx.fn.setGridControlValue("BR_PATHOLOGY_SPECIMEN_NAME",row || gx.fn.currentGridRowImpl(28),gx.O.A275BR_Pathology_Specimen_Name,0)},c2v:function(){if(this.val()!==undefined)gx.O.A275BR_Pathology_Specimen_Name=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_PATHOLOGY_SPECIMEN_NAME",row || gx.fn.currentGridRowImpl(28))},nac:gx.falseFn};
   GXValidFnc[34]={ id: 34, fld:"",grid:0};
   GXValidFnc[35]={ id: 35, fld:"",grid:0};
   GXValidFnc[36]={ id: 36, fld:"HTML_GRIDPAGINATIONBAR",grid:0};
   GXValidFnc[38]={ id: 38, fld:"",grid:0};
   GXValidFnc[39]={ id: 39, fld:"",grid:0};
   GXValidFnc[40]={ id: 40, fld:"HTML_BOTTOMAUXILIARCONTROLS",grid:0};
   GXValidFnc[42]={ id:42 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE",gxz:"ZV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace",gxold:"OV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace",gxvar:"AV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE",gx.O.AV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[43]={ id:43 ,lvl:0,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_PATHOLOGYID",gxz:"Z226BR_PathologyID",gxold:"O226BR_PathologyID",gxvar:"A226BR_PathologyID",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.A226BR_PathologyID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z226BR_PathologyID=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("BR_PATHOLOGYID",gx.O.A226BR_PathologyID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A226BR_PathologyID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("BR_PATHOLOGYID",',')},nac:gx.falseFn};
   this.declareDomainHdlr( 43 , function() {
   });
   GXValidFnc[45]={ id:45 ,lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDDSC",gxz:"ZV14OrderedDsc",gxold:"OV14OrderedDsc",gxvar:"AV14OrderedDsc",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV14OrderedDsc=gx.lang.booleanValue(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV14OrderedDsc=gx.lang.booleanValue(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDDSC",gx.O.AV14OrderedDsc,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV14OrderedDsc=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getControlValue("vORDEREDDSC")},nac:gx.falseFn};
   this.ZV28Display = "" ;
   this.OV28Display = "" ;
   this.ZV24Update = "" ;
   this.OV24Update = "" ;
   this.ZV26Delete = "" ;
   this.OV26Delete = "" ;
   this.Z274BR_Pathology_SpecimenID = 0 ;
   this.O274BR_Pathology_SpecimenID = 0 ;
   this.Z275BR_Pathology_Specimen_Name = "" ;
   this.O275BR_Pathology_Specimen_Name = "" ;
   this.AV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace = "" ;
   this.ZV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace = "" ;
   this.OV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace = "" ;
   this.A226BR_PathologyID = 0 ;
   this.Z226BR_PathologyID = 0 ;
   this.O226BR_PathologyID = 0 ;
   this.AV14OrderedDsc = false ;
   this.ZV14OrderedDsc = false ;
   this.OV14OrderedDsc = false ;
   this.AV21GridCurrentPage = 0 ;
   this.AV18DDO_TitleSettingsIcons = {Default:"",Default_GXI:"",Filtered:"",Filtered_GXI:"",SortedASC:"",SortedASC_GXI:"",SortedDSC:"",SortedDSC_GXI:"",FilteredSortedASC:"",FilteredSortedASC_GXI:"",FilteredSortedDSC:"",FilteredSortedDSC_GXI:"",OptionSortASC:"",OptionSortASC_GXI:"",OptionSortDSC:"",OptionSortDSC_GXI:"",OptionApplyFilter:"",OptionApplyFilter_GXI:"",OptionFilteringData:"",OptionFilteringData_GXI:"",OptionCleanFilters:"",OptionCleanFilters_GXI:"",SelectedOption:"",SelectedOption_GXI:"",MultiselOption:"",MultiselOption_GXI:"",MultiselSelOption:"",MultiselSelOption_GXI:""} ;
   this.AV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace = "" ;
   this.A226BR_PathologyID = 0 ;
   this.AV14OrderedDsc = false ;
   this.AV8BR_PathologyID = 0 ;
   this.AV28Display = "" ;
   this.AV24Update = "" ;
   this.AV26Delete = "" ;
   this.A274BR_Pathology_SpecimenID = 0 ;
   this.A275BR_Pathology_Specimen_Name = "" ;
   this.AV38Pgmname = "" ;
   this.AV25IsAuthorized_Update = false ;
   this.AV27IsAuthorized_Delete = false ;
   this.Events = {"e115e2_client": ["GRIDPAGINATIONBAR.CHANGEPAGE", true] ,"e125e2_client": ["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", true] ,"e135e2_client": ["DDO_BR_PATHOLOGY_SPECIMEN_NAME.ONOPTIONCLICKED", true] ,"e145e2_client": ["'DOINSERT'", true] ,"e205e2_client": ["ENTER", true] ,"e215e2_client": ["CANCEL", true] ,"e185e2_client": ["VUPDATE.CLICK", false] ,"e195e2_client": ["VDELETE.CLICK", false]};
   this.EvtParms["REFRESH"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'AV8BR_PathologyID',fld:'vBR_PATHOLOGYID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{av:'AV25IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'AV27IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'AV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE',pic:''},{ctrl:'GRID',prop:'Rows'},{av:'AV38Pgmname',fld:'vPGMNAME',pic:''},{av:'AV14OrderedDsc',fld:'vORDEREDDSC',pic:''}],[{av:'AV16BR_Pathology_Specimen_NameTitleFilterData',fld:'vBR_PATHOLOGY_SPECIMEN_NAMETITLEFILTERDATA',pic:''},{ctrl:'BR_PATHOLOGY_SPECIMEN_NAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_SPECIMEN_NAME","Title")',ctrl:'BR_PATHOLOGY_SPECIMEN_NAME',prop:'Title'},{av:'AV21GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV22GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV23GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'AV25IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'AV27IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{ctrl:'BTNINSERT',prop:'Visible'}]];
   this.EvtParms["START"] = [[{av:'AV38Pgmname',fld:'vPGMNAME',pic:''},{av:'AV8BR_PathologyID',fld:'vBR_PATHOLOGYID',pic:'ZZZZZZZZZZZZZZZZZZ'}],[{ctrl:'GRID',prop:'Rows'},{av:'this.DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.TitleControlIdToReplace',ctrl:'DDO_BR_PATHOLOGY_SPECIMEN_NAME',prop:'TitleControlIdToReplace'},{av:'AV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGYID","Visible")',ctrl:'BR_PATHOLOGYID',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vORDEREDDSC","Visible")',ctrl:'vORDEREDDSC',prop:'Visible'},{av:'AV18DDO_TitleSettingsIcons',fld:'vDDO_TITLESETTINGSICONS',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'},{av:'gx.fn.getCtrlProperty("TABLEHEADER","Visible")',ctrl:'TABLEHEADER',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{av:'AV14OrderedDsc',fld:'vORDEREDDSC',pic:''}]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_PathologyID',fld:'vBR_PATHOLOGYID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV38Pgmname',fld:'vPGMNAME',pic:''},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{av:'AV25IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'AV27IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'this.GRIDPAGINATIONBARContainer.SelectedPage',ctrl:'GRIDPAGINATIONBAR',prop:'SelectedPage'}],[]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_PathologyID',fld:'vBR_PATHOLOGYID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV38Pgmname',fld:'vPGMNAME',pic:''},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{av:'AV25IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'AV27IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}],[{ctrl:'GRID',prop:'Rows'}]];
   this.EvtParms["DDO_BR_PATHOLOGY_SPECIMEN_NAME.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV14OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV8BR_PathologyID',fld:'vBR_PATHOLOGYID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV17ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV38Pgmname',fld:'vPGMNAME',pic:''},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{av:'AV25IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'AV27IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'sPrefix'},{av:'this.DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.ActiveEventKey',ctrl:'DDO_BR_PATHOLOGY_SPECIMEN_NAME',prop:'ActiveEventKey'}],[{av:'AV14OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.SortedStatus',ctrl:'DDO_BR_PATHOLOGY_SPECIMEN_NAME',prop:'SortedStatus'},{av:'AV16BR_Pathology_Specimen_NameTitleFilterData',fld:'vBR_PATHOLOGY_SPECIMEN_NAMETITLEFILTERDATA',pic:''},{ctrl:'BR_PATHOLOGY_SPECIMEN_NAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_SPECIMEN_NAME","Title")',ctrl:'BR_PATHOLOGY_SPECIMEN_NAME',prop:'Title'},{av:'AV21GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV22GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV23GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'},{av:'AV25IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'gx.fn.getCtrlProperty("vUPDATE","Visible")',ctrl:'vUPDATE',prop:'Visible'},{av:'AV27IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''},{av:'gx.fn.getCtrlProperty("vDELETE","Visible")',ctrl:'vDELETE',prop:'Visible'},{ctrl:'BTNINSERT',prop:'Visible'}]];
   this.EvtParms["GRID.LOAD"] = [[{av:'A274BR_Pathology_SpecimenID',fld:'BR_PATHOLOGY_SPECIMENID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true},{av:'AV25IsAuthorized_Update',fld:'vISAUTHORIZED_UPDATE',pic:''},{av:'AV27IsAuthorized_Delete',fld:'vISAUTHORIZED_DELETE',pic:''}],[{av:'AV28Display',fld:'vDISPLAY',pic:''},{av:'gx.fn.getCtrlProperty("vDISPLAY","Tooltiptext")',ctrl:'vDISPLAY',prop:'Tooltiptext'},{av:'gx.fn.getCtrlProperty("vDISPLAY","Link")',ctrl:'vDISPLAY',prop:'Link'},{av:'AV24Update',fld:'vUPDATE',pic:''},{av:'gx.fn.getCtrlProperty("vUPDATE","Tooltiptext")',ctrl:'vUPDATE',prop:'Tooltiptext'},{av:'gx.fn.getCtrlProperty("vUPDATE","Link")',ctrl:'vUPDATE',prop:'Link'},{av:'AV26Delete',fld:'vDELETE',pic:''},{av:'gx.fn.getCtrlProperty("vDELETE","Tooltiptext")',ctrl:'vDELETE',prop:'Tooltiptext'},{av:'gx.fn.getCtrlProperty("vDELETE","Link")',ctrl:'vDELETE',prop:'Link'}]];
   this.EvtParms["'DOINSERT'"] = [[{av:'A274BR_Pathology_SpecimenID',fld:'BR_PATHOLOGY_SPECIMENID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true},{av:'AV8BR_PathologyID',fld:'vBR_PATHOLOGYID',pic:'ZZZZZZZZZZZZZZZZZZ'}],[]];
   this.EvtParms["VUPDATE.CLICK"] = [[{av:'A274BR_Pathology_SpecimenID',fld:'BR_PATHOLOGY_SPECIMENID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true}],[]];
   this.EvtParms["VDELETE.CLICK"] = [[{av:'A274BR_Pathology_SpecimenID',fld:'BR_PATHOLOGY_SPECIMENID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true}],[]];
   this.setVCMap("AV38Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV25IsAuthorized_Update", "vISAUTHORIZED_UPDATE", 0, "boolean", 4, 0);
   this.setVCMap("AV27IsAuthorized_Delete", "vISAUTHORIZED_DELETE", 0, "boolean", 4, 0);
   this.setVCMap("AV8BR_PathologyID", "vBR_PATHOLOGYID", 0, "int", 18, 0);
   this.setVCMap("AV8BR_PathologyID", "vBR_PATHOLOGYID", 0, "int", 18, 0);
   this.setVCMap("AV38Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV25IsAuthorized_Update", "vISAUTHORIZED_UPDATE", 0, "boolean", 4, 0);
   this.setVCMap("AV27IsAuthorized_Delete", "vISAUTHORIZED_DELETE", 0, "boolean", 4, 0);
   this.setVCMap("AV8BR_PathologyID", "vBR_PATHOLOGYID", 0, "int", 18, 0);
   this.setVCMap("AV38Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV25IsAuthorized_Update", "vISAUTHORIZED_UPDATE", 0, "boolean", 4, 0);
   this.setVCMap("AV27IsAuthorized_Delete", "vISAUTHORIZED_DELETE", 0, "boolean", 4, 0);
   GridContainer.addRefreshingVar(this.GXValidFnc[45]);
   GridContainer.addRefreshingVar({rfrVar:"AV8BR_PathologyID"});
   GridContainer.addRefreshingVar(this.GXValidFnc[42]);
   GridContainer.addRefreshingVar({rfrVar:"AV38Pgmname"});
   GridContainer.addRefreshingVar({rfrVar:"AV24Update", rfrProp:"Visible", gxAttId:"Update"});
   GridContainer.addRefreshingVar({rfrVar:"AV26Delete", rfrProp:"Visible", gxAttId:"Delete"});
   GridContainer.addRefreshingVar({rfrVar:"AV25IsAuthorized_Update"});
   GridContainer.addRefreshingVar({rfrVar:"AV27IsAuthorized_Delete"});
   this.Initialize( );
});
