/*!   GeneXus C# 16_0_0-127771 on 2/27/2020 12:3:11.51
*/
gx.evt.autoSkip = false;
gx.define('br_medicalimaging_diagprompt', false, function () {
   this.ServerClass =  "br_medicalimaging_diagprompt" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.hasEnterEvent = true;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV8InOutBR_MedicalImaging_DiagID=gx.fn.getIntegerValue("vINOUTBR_MEDICALIMAGING_DIAGID",',') ;
      this.AV9InOutBR_MedicalImaging_Diag_Loc=gx.fn.getControlValue("vINOUTBR_MEDICALIMAGING_DIAG_LOC") ;
   };
   this.e115n2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEPAGE", false, null, true, true);
   };
   this.e125n2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", false, null, true, true);
   };
   this.e135n2_client=function()
   {
      return this.executeServerEvent("DDO_BR_MEDICALIMAGING_DIAGID.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e145n2_client=function()
   {
      return this.executeServerEvent("DDO_BR_MEDICALIMAGINGID.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e155n2_client=function()
   {
      return this.executeServerEvent("DDO_BR_MEDICALIMAGING_DIAG_LOC.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e165n2_client=function()
   {
      return this.executeServerEvent("DDO_BR_MEDICALIMAGING_DIAG_ORGAN.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e175n2_client=function()
   {
      return this.executeServerEvent("DDO_BR_MEDICALIMAGING_DIAG_DIS.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e185n2_client=function()
   {
      return this.executeServerEvent("DDO_BR_MEDICALIMAGING_DIAG_NO.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e225n2_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e235n2_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,24,25,26,28,30,32,34,36,38,40,41];
   this.GXLastCtrlId =41;
   this.GridContainer = new gx.grid.grid(this, 2,"WbpLvl2",12,"Grid","Grid","GridContainer",this.CmpContext,this.IsMasterPage,"br_medicalimaging_diagprompt",[],false,1,false,true,0,false,false,false,"",0,"px",0,"px","澧炲姞绌虹櫧琛?,true,false,false,null,null,false,"",false,[1,1,1,1],false,0,true,false);
   var GridContainer = this.GridContainer;
   GridContainer.addBitmap("&Select","vSELECT",13,0,"px",17,"px","e225n2_client","","","SelectAttribute ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addSingleLineEdit(270,14,"BR_MEDICALIMAGING_DIAGID","","","BR_MedicalImaging_DiagID","int",0,"px",18,18,"right",null,[],270,"BR_MedicalImaging_DiagID",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(225,15,"BR_MEDICALIMAGINGID","","","BR_MedicalImagingID","int",0,"px",18,18,"right",null,[],225,"BR_MedicalImagingID",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(271,16,"BR_MEDICALIMAGING_DIAG_LOC","","","BR_MedicalImaging_Diag_Loc","svchar",0,"px",100,80,"left",null,[],271,"BR_MedicalImaging_Diag_Loc",true,0,false,false,"Attribute",1,"WWColumn");
   GridContainer.addSingleLineEdit(272,17,"BR_MEDICALIMAGING_DIAG_ORGAN","","","BR_MedicalImaging_Diag_Organ","svchar",0,"px",100,80,"left",null,[],272,"BR_MedicalImaging_Diag_Organ",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(273,18,"BR_MEDICALIMAGING_DIAG_DIS","","","BR_MedicalImaging_Diag_Dis","svchar",0,"px",100,80,"left",null,[],273,"BR_MedicalImaging_Diag_Dis",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(517,19,"BR_MEDICALIMAGING_DIAG_NO","","","BR_MedicalImaging_Diag_No","int",0,"px",18,18,"right",null,[],517,"BR_MedicalImaging_Diag_No",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   this.GridContainer.emptyText = "";
   this.setGrid(GridContainer);
   this.GRIDPAGINATIONBARContainer = gx.uc.getNew(this, 23, 13, "DVelop_DVPaginationBar", "GRIDPAGINATIONBARContainer", "Gridpaginationbar", "GRIDPAGINATIONBAR");
   var GRIDPAGINATIONBARContainer = this.GRIDPAGINATIONBARContainer;
   GRIDPAGINATIONBARContainer.setProp("Enabled", "Enabled", true, "boolean");
   GRIDPAGINATIONBARContainer.setProp("Class", "Class", "PaginationBar", "str");
   GRIDPAGINATIONBARContainer.setProp("ShowFirst", "Showfirst", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowPrevious", "Showprevious", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowNext", "Shownext", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowLast", "Showlast", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("PagesToShow", "Pagestoshow", 5, "num");
   GRIDPAGINATIONBARContainer.setProp("PagingButtonsPosition", "Pagingbuttonsposition", "Right", "str");
   GRIDPAGINATIONBARContainer.setProp("PagingCaptionPosition", "Pagingcaptionposition", "Left", "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridClass", "Emptygridclass", "PaginationBarEmptyGrid", "str");
   GRIDPAGINATIONBARContainer.setProp("SelectedPage", "Selectedpage", "", "char");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageSelector", "Rowsperpageselector", true, "bool");
   GRIDPAGINATIONBARContainer.setDynProp("RowsPerPageSelectedValue", "Rowsperpageselectedvalue", 10, "num");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageOptions", "Rowsperpageoptions", "5:WWP_Rows5,10:WWP_Rows10,20:WWP_Rows20,50:WWP_Rows50", "str");
   GRIDPAGINATIONBARContainer.setProp("First", "First", "First", "str");
   GRIDPAGINATIONBARContainer.setProp("Previous", "Previous", "WWP_PagingPreviousCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Next", "Next", "WWP_PagingNextCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Last", "Last", "Last", "str");
   GRIDPAGINATIONBARContainer.setProp("Caption", "Caption", "<CURRENT_PAGE>椤?<TOTAL_PAGES>椤?璁板綍锛?TOTAL_RECORDS>鏉?, "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridCaption", "Emptygridcaption", "WWP_PagingEmptyGridCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageCaption", "Rowsperpagecaption", "WWP_PagingRowsPerPage", "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV25GridCurrentPage', "vGRIDCURRENTPAGE", 'SetCurrentPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25GridCurrentPage=UC.GetCurrentPage();gx.fn.setControlValue("vGRIDCURRENTPAGE",UC.ParentObject.AV25GridCurrentPage); });
   GRIDPAGINATIONBARContainer.setProp("PageCount", "Pagecount", '', "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV27GridRecordCount', "vGRIDRECORDCOUNT", 'SetRecordCount');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV27GridRecordCount=UC.GetRecordCount();gx.fn.setControlValue("vGRIDRECORDCOUNT",UC.ParentObject.AV27GridRecordCount); });
   GRIDPAGINATIONBARContainer.addV2CFunction('AV26GridPageSize', "vGRIDPAGESIZE", 'SetPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV26GridPageSize=UC.GetPage();gx.fn.setControlValue("vGRIDPAGESIZE",UC.ParentObject.AV26GridPageSize); });
   GRIDPAGINATIONBARContainer.setProp("Visible", "Visible", true, "bool");
   GRIDPAGINATIONBARContainer.setC2ShowFunction(function(UC) { UC.show(); });
   GRIDPAGINATIONBARContainer.addEventHandler("ChangePage", this.e115n2_client);
   GRIDPAGINATIONBARContainer.addEventHandler("ChangeRowsPerPage", this.e125n2_client);
   this.setUserControl(GRIDPAGINATIONBARContainer);
   this.DDO_BR_MEDICALIMAGING_DIAGIDContainer = gx.uc.getNew(this, 27, 13, "BootstrapDropDownOptions", "DDO_BR_MEDICALIMAGING_DIAGIDContainer", "Ddo_br_medicalimaging_diagid", "DDO_BR_MEDICALIMAGING_DIAGID");
   var DDO_BR_MEDICALIMAGING_DIAGIDContainer = this.DDO_BR_MEDICALIMAGING_DIAGIDContainer;
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("Class", "Class", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.addV2CFunction('AV23DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV23DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV23DDO_TitleSettingsIcons); });
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.addV2CFunction('AV13BR_MedicalImaging_DiagIDTitleFilterData', "vBR_MEDICALIMAGING_DIAGIDTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV13BR_MedicalImaging_DiagIDTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_MEDICALIMAGING_DIAGIDTITLEFILTERDATA",UC.ParentObject.AV13BR_MedicalImaging_DiagIDTitleFilterData); });
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_MEDICALIMAGING_DIAGIDContainer.addEventHandler("OnOptionClicked", this.e135n2_client);
   this.setUserControl(DDO_BR_MEDICALIMAGING_DIAGIDContainer);
   this.DDO_BR_MEDICALIMAGINGIDContainer = gx.uc.getNew(this, 29, 28, "BootstrapDropDownOptions", "DDO_BR_MEDICALIMAGINGIDContainer", "Ddo_br_medicalimagingid", "DDO_BR_MEDICALIMAGINGID");
   var DDO_BR_MEDICALIMAGINGIDContainer = this.DDO_BR_MEDICALIMAGINGIDContainer;
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("Class", "Class", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_MEDICALIMAGINGIDContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_MEDICALIMAGINGIDContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_MEDICALIMAGINGIDContainer.addV2CFunction('AV23DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_MEDICALIMAGINGIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV23DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV23DDO_TitleSettingsIcons); });
   DDO_BR_MEDICALIMAGINGIDContainer.addV2CFunction('AV15BR_MedicalImagingIDTitleFilterData', "vBR_MEDICALIMAGINGIDTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_MEDICALIMAGINGIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV15BR_MedicalImagingIDTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_MEDICALIMAGINGIDTITLEFILTERDATA",UC.ParentObject.AV15BR_MedicalImagingIDTitleFilterData); });
   DDO_BR_MEDICALIMAGINGIDContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_MEDICALIMAGINGIDContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_MEDICALIMAGINGIDContainer.addEventHandler("OnOptionClicked", this.e145n2_client);
   this.setUserControl(DDO_BR_MEDICALIMAGINGIDContainer);
   this.DDO_BR_MEDICALIMAGING_DIAG_LOCContainer = gx.uc.getNew(this, 31, 28, "BootstrapDropDownOptions", "DDO_BR_MEDICALIMAGING_DIAG_LOCContainer", "Ddo_br_medicalimaging_diag_loc", "DDO_BR_MEDICALIMAGING_DIAG_LOC");
   var DDO_BR_MEDICALIMAGING_DIAG_LOCContainer = this.DDO_BR_MEDICALIMAGING_DIAG_LOCContainer;
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("Class", "Class", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.addV2CFunction('AV23DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.addC2VFunction(function(UC) { UC.ParentObject.AV23DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV23DDO_TitleSettingsIcons); });
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.addV2CFunction('AV17BR_MedicalImaging_Diag_LocTitleFilterData', "vBR_MEDICALIMAGING_DIAG_LOCTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.addC2VFunction(function(UC) { UC.ParentObject.AV17BR_MedicalImaging_Diag_LocTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_MEDICALIMAGING_DIAG_LOCTITLEFILTERDATA",UC.ParentObject.AV17BR_MedicalImaging_Diag_LocTitleFilterData); });
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.addEventHandler("OnOptionClicked", this.e155n2_client);
   this.setUserControl(DDO_BR_MEDICALIMAGING_DIAG_LOCContainer);
   this.DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer = gx.uc.getNew(this, 33, 28, "BootstrapDropDownOptions", "DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer", "Ddo_br_medicalimaging_diag_organ", "DDO_BR_MEDICALIMAGING_DIAG_ORGAN");
   var DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer = this.DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer;
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("Class", "Class", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.addV2CFunction('AV23DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.addC2VFunction(function(UC) { UC.ParentObject.AV23DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV23DDO_TitleSettingsIcons); });
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.addV2CFunction('AV19BR_MedicalImaging_Diag_OrganTitleFilterData', "vBR_MEDICALIMAGING_DIAG_ORGANTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.addC2VFunction(function(UC) { UC.ParentObject.AV19BR_MedicalImaging_Diag_OrganTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_MEDICALIMAGING_DIAG_ORGANTITLEFILTERDATA",UC.ParentObject.AV19BR_MedicalImaging_Diag_OrganTitleFilterData); });
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.addEventHandler("OnOptionClicked", this.e165n2_client);
   this.setUserControl(DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer);
   this.DDO_BR_MEDICALIMAGING_DIAG_DISContainer = gx.uc.getNew(this, 35, 28, "BootstrapDropDownOptions", "DDO_BR_MEDICALIMAGING_DIAG_DISContainer", "Ddo_br_medicalimaging_diag_dis", "DDO_BR_MEDICALIMAGING_DIAG_DIS");
   var DDO_BR_MEDICALIMAGING_DIAG_DISContainer = this.DDO_BR_MEDICALIMAGING_DIAG_DISContainer;
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("Class", "Class", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.addV2CFunction('AV23DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.addC2VFunction(function(UC) { UC.ParentObject.AV23DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV23DDO_TitleSettingsIcons); });
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.addV2CFunction('AV21BR_MedicalImaging_Diag_DisTitleFilterData', "vBR_MEDICALIMAGING_DIAG_DISTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.addC2VFunction(function(UC) { UC.ParentObject.AV21BR_MedicalImaging_Diag_DisTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_MEDICALIMAGING_DIAG_DISTITLEFILTERDATA",UC.ParentObject.AV21BR_MedicalImaging_Diag_DisTitleFilterData); });
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_MEDICALIMAGING_DIAG_DISContainer.addEventHandler("OnOptionClicked", this.e175n2_client);
   this.setUserControl(DDO_BR_MEDICALIMAGING_DIAG_DISContainer);
   this.DDO_BR_MEDICALIMAGING_DIAG_NOContainer = gx.uc.getNew(this, 37, 28, "BootstrapDropDownOptions", "DDO_BR_MEDICALIMAGING_DIAG_NOContainer", "Ddo_br_medicalimaging_diag_no", "DDO_BR_MEDICALIMAGING_DIAG_NO");
   var DDO_BR_MEDICALIMAGING_DIAG_NOContainer = this.DDO_BR_MEDICALIMAGING_DIAG_NOContainer;
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("Class", "Class", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.addV2CFunction('AV23DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.addC2VFunction(function(UC) { UC.ParentObject.AV23DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV23DDO_TitleSettingsIcons); });
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.addV2CFunction('AV29BR_MedicalImaging_Diag_NoTitleFilterData', "vBR_MEDICALIMAGING_DIAG_NOTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.addC2VFunction(function(UC) { UC.ParentObject.AV29BR_MedicalImaging_Diag_NoTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_MEDICALIMAGING_DIAG_NOTITLEFILTERDATA",UC.ParentObject.AV29BR_MedicalImaging_Diag_NoTitleFilterData); });
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_MEDICALIMAGING_DIAG_NOContainer.addEventHandler("OnOptionClicked", this.e185n2_client);
   this.setUserControl(DDO_BR_MEDICALIMAGING_DIAG_NOContainer);
   this.WORKWITHPLUSUTILITIES1Container = gx.uc.getNew(this, 39, 28, "DVelop_WorkWithPlusUtilities", "WORKWITHPLUSUTILITIES1Container", "Workwithplusutilities1", "WORKWITHPLUSUTILITIES1");
   var WORKWITHPLUSUTILITIES1Container = this.WORKWITHPLUSUTILITIES1Container;
   WORKWITHPLUSUTILITIES1Container.setProp("Class", "Class", "", "char");
   WORKWITHPLUSUTILITIES1Container.setProp("Enabled", "Enabled", true, "boolean");
   WORKWITHPLUSUTILITIES1Container.setProp("Width", "Width", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Height", "Height", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Visible", "Visible", true, "bool");
   WORKWITHPLUSUTILITIES1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(WORKWITHPLUSUTILITIES1Container);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEMAIN",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"GRIDTABLEWITHPAGINATIONBAR",grid:0};
   GXValidFnc[10]={ id: 10, fld:"",grid:0};
   GXValidFnc[11]={ id: 11, fld:"",grid:0};
   GXValidFnc[13]={ id:13 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vSELECT",gxz:"ZV28Select",gxold:"OV28Select",gxvar:"AV28Select",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV28Select=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV28Select=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vSELECT",row || gx.fn.currentGridRowImpl(12),gx.O.AV28Select,gx.O.AV34Select_GXI)},c2v:function(){gx.O.AV34Select_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV28Select=this.val()},val:function(row){return gx.fn.getGridControlValue("vSELECT",row || gx.fn.currentGridRowImpl(12))},val_GXI:function(row){return gx.fn.getGridControlValue("vSELECT_GXI",row || gx.fn.currentGridRowImpl(12))}, gxvar_GXI:'AV34Select_GXI',nac:gx.falseFn,evt:"e225n2_client",std:"ENTER"};
   GXValidFnc[14]={ id:14 ,lvl:2,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_MEDICALIMAGING_DIAGID",gxz:"Z270BR_MedicalImaging_DiagID",gxold:"O270BR_MedicalImaging_DiagID",gxvar:"A270BR_MedicalImaging_DiagID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A270BR_MedicalImaging_DiagID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z270BR_MedicalImaging_DiagID=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("BR_MEDICALIMAGING_DIAGID",row || gx.fn.currentGridRowImpl(12),gx.O.A270BR_MedicalImaging_DiagID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A270BR_MedicalImaging_DiagID=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("BR_MEDICALIMAGING_DIAGID",row || gx.fn.currentGridRowImpl(12),',')},nac:gx.falseFn};
   GXValidFnc[15]={ id:15 ,lvl:2,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_MEDICALIMAGINGID",gxz:"Z225BR_MedicalImagingID",gxold:"O225BR_MedicalImagingID",gxvar:"A225BR_MedicalImagingID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A225BR_MedicalImagingID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z225BR_MedicalImagingID=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("BR_MEDICALIMAGINGID",row || gx.fn.currentGridRowImpl(12),gx.O.A225BR_MedicalImagingID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A225BR_MedicalImagingID=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("BR_MEDICALIMAGINGID",row || gx.fn.currentGridRowImpl(12),',')},nac:gx.falseFn};
   GXValidFnc[16]={ id:16 ,lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_MEDICALIMAGING_DIAG_LOC",gxz:"Z271BR_MedicalImaging_Diag_Loc",gxold:"O271BR_MedicalImaging_Diag_Loc",gxvar:"A271BR_MedicalImaging_Diag_Loc",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A271BR_MedicalImaging_Diag_Loc=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z271BR_MedicalImaging_Diag_Loc=Value},v2c:function(row){gx.fn.setGridControlValue("BR_MEDICALIMAGING_DIAG_LOC",row || gx.fn.currentGridRowImpl(12),gx.O.A271BR_MedicalImaging_Diag_Loc,0)},c2v:function(){if(this.val()!==undefined)gx.O.A271BR_MedicalImaging_Diag_Loc=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_MEDICALIMAGING_DIAG_LOC",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn};
   GXValidFnc[17]={ id:17 ,lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_MEDICALIMAGING_DIAG_ORGAN",gxz:"Z272BR_MedicalImaging_Diag_Organ",gxold:"O272BR_MedicalImaging_Diag_Organ",gxvar:"A272BR_MedicalImaging_Diag_Organ",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A272BR_MedicalImaging_Diag_Organ=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z272BR_MedicalImaging_Diag_Organ=Value},v2c:function(row){gx.fn.setGridControlValue("BR_MEDICALIMAGING_DIAG_ORGAN",row || gx.fn.currentGridRowImpl(12),gx.O.A272BR_MedicalImaging_Diag_Organ,0)},c2v:function(){if(this.val()!==undefined)gx.O.A272BR_MedicalImaging_Diag_Organ=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_MEDICALIMAGING_DIAG_ORGAN",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn};
   GXValidFnc[18]={ id:18 ,lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_MEDICALIMAGING_DIAG_DIS",gxz:"Z273BR_MedicalImaging_Diag_Dis",gxold:"O273BR_MedicalImaging_Diag_Dis",gxvar:"A273BR_MedicalImaging_Diag_Dis",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A273BR_MedicalImaging_Diag_Dis=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z273BR_MedicalImaging_Diag_Dis=Value},v2c:function(row){gx.fn.setGridControlValue("BR_MEDICALIMAGING_DIAG_DIS",row || gx.fn.currentGridRowImpl(12),gx.O.A273BR_MedicalImaging_Diag_Dis,0)},c2v:function(){if(this.val()!==undefined)gx.O.A273BR_MedicalImaging_Diag_Dis=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_MEDICALIMAGING_DIAG_DIS",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn};
   GXValidFnc[19]={ id:19 ,lvl:2,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_MEDICALIMAGING_DIAG_NO",gxz:"Z517BR_MedicalImaging_Diag_No",gxold:"O517BR_MedicalImaging_Diag_No",gxvar:"A517BR_MedicalImaging_Diag_No",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A517BR_MedicalImaging_Diag_No=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z517BR_MedicalImaging_Diag_No=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("BR_MEDICALIMAGING_DIAG_NO",row || gx.fn.currentGridRowImpl(12),gx.O.A517BR_MedicalImaging_Diag_No,0)},c2v:function(){if(this.val()!==undefined)gx.O.A517BR_MedicalImaging_Diag_No=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("BR_MEDICALIMAGING_DIAG_NO",row || gx.fn.currentGridRowImpl(12),',')},nac:gx.falseFn};
   GXValidFnc[20]={ id: 20, fld:"",grid:0};
   GXValidFnc[21]={ id: 21, fld:"",grid:0};
   GXValidFnc[22]={ id: 22, fld:"HTML_GRIDPAGINATIONBAR",grid:0};
   GXValidFnc[24]={ id: 24, fld:"",grid:0};
   GXValidFnc[25]={ id: 25, fld:"",grid:0};
   GXValidFnc[26]={ id: 26, fld:"HTML_BOTTOMAUXILIARCONTROLS",grid:0};
   GXValidFnc[28]={ id:28 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_MEDICALIMAGING_DIAGIDTITLECONTROLIDTOREPLACE",gxz:"ZV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace",gxold:"OV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace",gxvar:"AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_MEDICALIMAGING_DIAGIDTITLECONTROLIDTOREPLACE",gx.O.AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_MEDICALIMAGING_DIAGIDTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[30]={ id:30 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_MEDICALIMAGINGIDTITLECONTROLIDTOREPLACE",gxz:"ZV16ddo_BR_MedicalImagingIDTitleControlIdToReplace",gxold:"OV16ddo_BR_MedicalImagingIDTitleControlIdToReplace",gxvar:"AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV16ddo_BR_MedicalImagingIDTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_MEDICALIMAGINGIDTITLECONTROLIDTOREPLACE",gx.O.AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_MEDICALIMAGINGIDTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[32]={ id:32 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_MEDICALIMAGING_DIAG_LOCTITLECONTROLIDTOREPLACE",gxz:"ZV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace",gxold:"OV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace",gxvar:"AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_MEDICALIMAGING_DIAG_LOCTITLECONTROLIDTOREPLACE",gx.O.AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_MEDICALIMAGING_DIAG_LOCTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[34]={ id:34 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_MEDICALIMAGING_DIAG_ORGANTITLECONTROLIDTOREPLACE",gxz:"ZV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace",gxold:"OV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace",gxvar:"AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_MEDICALIMAGING_DIAG_ORGANTITLECONTROLIDTOREPLACE",gx.O.AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_MEDICALIMAGING_DIAG_ORGANTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[36]={ id:36 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_MEDICALIMAGING_DIAG_DISTITLECONTROLIDTOREPLACE",gxz:"ZV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace",gxold:"OV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace",gxvar:"AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_MEDICALIMAGING_DIAG_DISTITLECONTROLIDTOREPLACE",gx.O.AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_MEDICALIMAGING_DIAG_DISTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[38]={ id:38 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_MEDICALIMAGING_DIAG_NOTITLECONTROLIDTOREPLACE",gxz:"ZV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace",gxold:"OV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace",gxvar:"AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_MEDICALIMAGING_DIAG_NOTITLECONTROLIDTOREPLACE",gx.O.AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_MEDICALIMAGING_DIAG_NOTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[40]={ id:40 ,lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDBY",gxz:"ZV11OrderedBy",gxold:"OV11OrderedBy",gxvar:"AV11OrderedBy",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV11OrderedBy=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV11OrderedBy=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDBY",gx.O.AV11OrderedBy,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV11OrderedBy=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vORDEREDBY",',')},nac:gx.falseFn};
   GXValidFnc[41]={ id:41 ,lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDDSC",gxz:"ZV12OrderedDsc",gxold:"OV12OrderedDsc",gxvar:"AV12OrderedDsc",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV12OrderedDsc=gx.lang.booleanValue(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV12OrderedDsc=gx.lang.booleanValue(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDDSC",gx.O.AV12OrderedDsc,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV12OrderedDsc=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getControlValue("vORDEREDDSC")},nac:gx.falseFn};
   this.ZV28Select = "" ;
   this.OV28Select = "" ;
   this.Z270BR_MedicalImaging_DiagID = 0 ;
   this.O270BR_MedicalImaging_DiagID = 0 ;
   this.Z225BR_MedicalImagingID = 0 ;
   this.O225BR_MedicalImagingID = 0 ;
   this.Z271BR_MedicalImaging_Diag_Loc = "" ;
   this.O271BR_MedicalImaging_Diag_Loc = "" ;
   this.Z272BR_MedicalImaging_Diag_Organ = "" ;
   this.O272BR_MedicalImaging_Diag_Organ = "" ;
   this.Z273BR_MedicalImaging_Diag_Dis = "" ;
   this.O273BR_MedicalImaging_Diag_Dis = "" ;
   this.Z517BR_MedicalImaging_Diag_No = 0 ;
   this.O517BR_MedicalImaging_Diag_No = 0 ;
   this.AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace = "" ;
   this.ZV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace = "" ;
   this.OV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace = "" ;
   this.AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace = "" ;
   this.ZV16ddo_BR_MedicalImagingIDTitleControlIdToReplace = "" ;
   this.OV16ddo_BR_MedicalImagingIDTitleControlIdToReplace = "" ;
   this.AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace = "" ;
   this.ZV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace = "" ;
   this.OV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace = "" ;
   this.AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace = "" ;
   this.ZV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace = "" ;
   this.OV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace = "" ;
   this.AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace = "" ;
   this.ZV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace = "" ;
   this.OV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace = "" ;
   this.AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace = "" ;
   this.ZV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace = "" ;
   this.OV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace = "" ;
   this.AV11OrderedBy = 0 ;
   this.ZV11OrderedBy = 0 ;
   this.OV11OrderedBy = 0 ;
   this.AV12OrderedDsc = false ;
   this.ZV12OrderedDsc = false ;
   this.OV12OrderedDsc = false ;
   this.AV25GridCurrentPage = 0 ;
   this.AV23DDO_TitleSettingsIcons = {Default:"",Default_GXI:"",Filtered:"",Filtered_GXI:"",SortedASC:"",SortedASC_GXI:"",SortedDSC:"",SortedDSC_GXI:"",FilteredSortedASC:"",FilteredSortedASC_GXI:"",FilteredSortedDSC:"",FilteredSortedDSC_GXI:"",OptionSortASC:"",OptionSortASC_GXI:"",OptionSortDSC:"",OptionSortDSC_GXI:"",OptionApplyFilter:"",OptionApplyFilter_GXI:"",OptionFilteringData:"",OptionFilteringData_GXI:"",OptionCleanFilters:"",OptionCleanFilters_GXI:"",SelectedOption:"",SelectedOption_GXI:"",MultiselOption:"",MultiselOption_GXI:"",MultiselSelOption:"",MultiselSelOption_GXI:""} ;
   this.AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace = "" ;
   this.AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace = "" ;
   this.AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace = "" ;
   this.AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace = "" ;
   this.AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace = "" ;
   this.AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace = "" ;
   this.AV11OrderedBy = 0 ;
   this.AV12OrderedDsc = false ;
   this.AV8InOutBR_MedicalImaging_DiagID = 0 ;
   this.AV9InOutBR_MedicalImaging_Diag_Loc = "" ;
   this.AV28Select = "" ;
   this.A270BR_MedicalImaging_DiagID = 0 ;
   this.A225BR_MedicalImagingID = 0 ;
   this.A271BR_MedicalImaging_Diag_Loc = "" ;
   this.A272BR_MedicalImaging_Diag_Organ = "" ;
   this.A273BR_MedicalImaging_Diag_Dis = "" ;
   this.A517BR_MedicalImaging_Diag_No = 0 ;
   this.Events = {"e115n2_client": ["GRIDPAGINATIONBAR.CHANGEPAGE", true] ,"e125n2_client": ["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", true] ,"e135n2_client": ["DDO_BR_MEDICALIMAGING_DIAGID.ONOPTIONCLICKED", true] ,"e145n2_client": ["DDO_BR_MEDICALIMAGINGID.ONOPTIONCLICKED", true] ,"e155n2_client": ["DDO_BR_MEDICALIMAGING_DIAG_LOC.ONOPTIONCLICKED", true] ,"e165n2_client": ["DDO_BR_MEDICALIMAGING_DIAG_ORGAN.ONOPTIONCLICKED", true] ,"e175n2_client": ["DDO_BR_MEDICALIMAGING_DIAG_DIS.ONOPTIONCLICKED", true] ,"e185n2_client": ["DDO_BR_MEDICALIMAGING_DIAG_NO.ONOPTIONCLICKED", true] ,"e225n2_client": ["ENTER", true] ,"e235n2_client": ["CANCEL", true]};
   this.EvtParms["REFRESH"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGINGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_DISTITLECONTROLIDTOREPLACE',pic:''},{av:'AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_NOTITLECONTROLIDTOREPLACE',pic:''},{ctrl:'GRID',prop:'Rows'}],[{av:'AV13BR_MedicalImaging_DiagIDTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAGIDTITLEFILTERDATA',pic:''},{av:'AV15BR_MedicalImagingIDTitleFilterData',fld:'vBR_MEDICALIMAGINGIDTITLEFILTERDATA',pic:''},{av:'AV17BR_MedicalImaging_Diag_LocTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_LOCTITLEFILTERDATA',pic:''},{av:'AV19BR_MedicalImaging_Diag_OrganTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_ORGANTITLEFILTERDATA',pic:''},{av:'AV21BR_MedicalImaging_Diag_DisTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_DISTITLEFILTERDATA',pic:''},{av:'AV29BR_MedicalImaging_Diag_NoTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_NOTITLEFILTERDATA',pic:''},{ctrl:'BR_MEDICALIMAGING_DIAGID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAGID","Title")',ctrl:'BR_MEDICALIMAGING_DIAGID',prop:'Title'},{ctrl:'BR_MEDICALIMAGINGID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGINGID","Title")',ctrl:'BR_MEDICALIMAGINGID',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_LOC',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_LOC","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_LOC',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_ORGAN',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_ORGAN","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_ORGAN',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_DIS',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_DIS","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_DIS',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_NO',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_NO","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_NO',prop:'Title'},{av:'AV25GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV26GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV27GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["START"] = [[{av:'AV33Pgmname',fld:'vPGMNAME',pic:''},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'}],[{av:'gx.fn.getCtrlProperty("TABLEMAIN","Height")',ctrl:'TABLEMAIN',prop:'Height'},{ctrl:'GRID',prop:'Rows'},{av:'this.DDO_BR_MEDICALIMAGING_DIAGIDContainer.TitleControlIdToReplace',ctrl:'DDO_BR_MEDICALIMAGING_DIAGID',prop:'TitleControlIdToReplace'},{av:'AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_MEDICALIMAGING_DIAGIDTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_MEDICALIMAGING_DIAGIDTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_MEDICALIMAGINGIDContainer.TitleControlIdToReplace',ctrl:'DDO_BR_MEDICALIMAGINGID',prop:'TitleControlIdToReplace'},{av:'AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGINGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_MEDICALIMAGINGIDTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_MEDICALIMAGINGIDTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.TitleControlIdToReplace',ctrl:'DDO_BR_MEDICALIMAGING_DIAG_LOC',prop:'TitleControlIdToReplace'},{av:'AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_MEDICALIMAGING_DIAG_LOCTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_MEDICALIMAGING_DIAG_LOCTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.TitleControlIdToReplace',ctrl:'DDO_BR_MEDICALIMAGING_DIAG_ORGAN',prop:'TitleControlIdToReplace'},{av:'AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_MEDICALIMAGING_DIAG_ORGANTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_MEDICALIMAGING_DIAG_ORGANTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_MEDICALIMAGING_DIAG_DISContainer.TitleControlIdToReplace',ctrl:'DDO_BR_MEDICALIMAGING_DIAG_DIS',prop:'TitleControlIdToReplace'},{av:'AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_DISTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_MEDICALIMAGING_DIAG_DISTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_MEDICALIMAGING_DIAG_DISTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_MEDICALIMAGING_DIAG_NOContainer.TitleControlIdToReplace',ctrl:'DDO_BR_MEDICALIMAGING_DIAG_NO',prop:'TitleControlIdToReplace'},{av:'AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_NOTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_MEDICALIMAGING_DIAG_NOTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_MEDICALIMAGING_DIAG_NOTITLECONTROLIDTOREPLACE',prop:'Visible'},{ctrl:'FORM',prop:'Caption'},{av:'gx.fn.getCtrlProperty("vORDEREDBY","Visible")',ctrl:'vORDEREDBY',prop:'Visible'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'gx.fn.getCtrlProperty("vORDEREDDSC","Visible")',ctrl:'vORDEREDDSC',prop:'Visible'},{av:'AV23DDO_TitleSettingsIcons',fld:'vDDO_TITLESETTINGSICONS',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGINGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_DISTITLECONTROLIDTOREPLACE',pic:''},{av:'AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_NOTITLECONTROLIDTOREPLACE',pic:''},{av:'this.GRIDPAGINATIONBARContainer.SelectedPage',ctrl:'GRIDPAGINATIONBAR',prop:'SelectedPage'}],[]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGINGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_DISTITLECONTROLIDTOREPLACE',pic:''},{av:'AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_NOTITLECONTROLIDTOREPLACE',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}],[{ctrl:'GRID',prop:'Rows'}]];
   this.EvtParms["DDO_BR_MEDICALIMAGING_DIAGID.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGINGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_DISTITLECONTROLIDTOREPLACE',pic:''},{av:'AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_NOTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_BR_MEDICALIMAGING_DIAGIDContainer.ActiveEventKey',ctrl:'DDO_BR_MEDICALIMAGING_DIAGID',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_MEDICALIMAGING_DIAGIDContainer.SortedStatus',ctrl:'DDO_BR_MEDICALIMAGING_DIAGID',prop:'SortedStatus'},{av:'AV13BR_MedicalImaging_DiagIDTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAGIDTITLEFILTERDATA',pic:''},{av:'AV15BR_MedicalImagingIDTitleFilterData',fld:'vBR_MEDICALIMAGINGIDTITLEFILTERDATA',pic:''},{av:'AV17BR_MedicalImaging_Diag_LocTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_LOCTITLEFILTERDATA',pic:''},{av:'AV19BR_MedicalImaging_Diag_OrganTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_ORGANTITLEFILTERDATA',pic:''},{av:'AV21BR_MedicalImaging_Diag_DisTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_DISTITLEFILTERDATA',pic:''},{av:'AV29BR_MedicalImaging_Diag_NoTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_NOTITLEFILTERDATA',pic:''},{ctrl:'BR_MEDICALIMAGING_DIAGID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAGID","Title")',ctrl:'BR_MEDICALIMAGING_DIAGID',prop:'Title'},{ctrl:'BR_MEDICALIMAGINGID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGINGID","Title")',ctrl:'BR_MEDICALIMAGINGID',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_LOC',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_LOC","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_LOC',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_ORGAN',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_ORGAN","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_ORGAN',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_DIS',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_DIS","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_DIS',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_NO',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_NO","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_NO',prop:'Title'},{av:'AV25GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV26GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV27GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_BR_MEDICALIMAGINGID.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGINGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_DISTITLECONTROLIDTOREPLACE',pic:''},{av:'AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_NOTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_BR_MEDICALIMAGINGIDContainer.ActiveEventKey',ctrl:'DDO_BR_MEDICALIMAGINGID',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_MEDICALIMAGINGIDContainer.SortedStatus',ctrl:'DDO_BR_MEDICALIMAGINGID',prop:'SortedStatus'},{av:'AV13BR_MedicalImaging_DiagIDTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAGIDTITLEFILTERDATA',pic:''},{av:'AV15BR_MedicalImagingIDTitleFilterData',fld:'vBR_MEDICALIMAGINGIDTITLEFILTERDATA',pic:''},{av:'AV17BR_MedicalImaging_Diag_LocTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_LOCTITLEFILTERDATA',pic:''},{av:'AV19BR_MedicalImaging_Diag_OrganTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_ORGANTITLEFILTERDATA',pic:''},{av:'AV21BR_MedicalImaging_Diag_DisTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_DISTITLEFILTERDATA',pic:''},{av:'AV29BR_MedicalImaging_Diag_NoTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_NOTITLEFILTERDATA',pic:''},{ctrl:'BR_MEDICALIMAGING_DIAGID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAGID","Title")',ctrl:'BR_MEDICALIMAGING_DIAGID',prop:'Title'},{ctrl:'BR_MEDICALIMAGINGID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGINGID","Title")',ctrl:'BR_MEDICALIMAGINGID',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_LOC',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_LOC","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_LOC',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_ORGAN',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_ORGAN","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_ORGAN',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_DIS',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_DIS","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_DIS',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_NO',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_NO","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_NO',prop:'Title'},{av:'AV25GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV26GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV27GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_BR_MEDICALIMAGING_DIAG_LOC.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGINGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_DISTITLECONTROLIDTOREPLACE',pic:''},{av:'AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_NOTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.ActiveEventKey',ctrl:'DDO_BR_MEDICALIMAGING_DIAG_LOC',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_MEDICALIMAGING_DIAG_LOCContainer.SortedStatus',ctrl:'DDO_BR_MEDICALIMAGING_DIAG_LOC',prop:'SortedStatus'},{av:'AV13BR_MedicalImaging_DiagIDTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAGIDTITLEFILTERDATA',pic:''},{av:'AV15BR_MedicalImagingIDTitleFilterData',fld:'vBR_MEDICALIMAGINGIDTITLEFILTERDATA',pic:''},{av:'AV17BR_MedicalImaging_Diag_LocTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_LOCTITLEFILTERDATA',pic:''},{av:'AV19BR_MedicalImaging_Diag_OrganTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_ORGANTITLEFILTERDATA',pic:''},{av:'AV21BR_MedicalImaging_Diag_DisTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_DISTITLEFILTERDATA',pic:''},{av:'AV29BR_MedicalImaging_Diag_NoTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_NOTITLEFILTERDATA',pic:''},{ctrl:'BR_MEDICALIMAGING_DIAGID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAGID","Title")',ctrl:'BR_MEDICALIMAGING_DIAGID',prop:'Title'},{ctrl:'BR_MEDICALIMAGINGID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGINGID","Title")',ctrl:'BR_MEDICALIMAGINGID',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_LOC',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_LOC","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_LOC',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_ORGAN',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_ORGAN","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_ORGAN',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_DIS',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_DIS","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_DIS',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_NO',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_NO","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_NO',prop:'Title'},{av:'AV25GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV26GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV27GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_BR_MEDICALIMAGING_DIAG_ORGAN.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGINGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_DISTITLECONTROLIDTOREPLACE',pic:''},{av:'AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_NOTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.ActiveEventKey',ctrl:'DDO_BR_MEDICALIMAGING_DIAG_ORGAN',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_MEDICALIMAGING_DIAG_ORGANContainer.SortedStatus',ctrl:'DDO_BR_MEDICALIMAGING_DIAG_ORGAN',prop:'SortedStatus'},{av:'AV13BR_MedicalImaging_DiagIDTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAGIDTITLEFILTERDATA',pic:''},{av:'AV15BR_MedicalImagingIDTitleFilterData',fld:'vBR_MEDICALIMAGINGIDTITLEFILTERDATA',pic:''},{av:'AV17BR_MedicalImaging_Diag_LocTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_LOCTITLEFILTERDATA',pic:''},{av:'AV19BR_MedicalImaging_Diag_OrganTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_ORGANTITLEFILTERDATA',pic:''},{av:'AV21BR_MedicalImaging_Diag_DisTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_DISTITLEFILTERDATA',pic:''},{av:'AV29BR_MedicalImaging_Diag_NoTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_NOTITLEFILTERDATA',pic:''},{ctrl:'BR_MEDICALIMAGING_DIAGID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAGID","Title")',ctrl:'BR_MEDICALIMAGING_DIAGID',prop:'Title'},{ctrl:'BR_MEDICALIMAGINGID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGINGID","Title")',ctrl:'BR_MEDICALIMAGINGID',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_LOC',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_LOC","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_LOC',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_ORGAN',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_ORGAN","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_ORGAN',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_DIS',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_DIS","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_DIS',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_NO',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_NO","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_NO',prop:'Title'},{av:'AV25GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV26GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV27GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_BR_MEDICALIMAGING_DIAG_DIS.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGINGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_DISTITLECONTROLIDTOREPLACE',pic:''},{av:'AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_NOTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_BR_MEDICALIMAGING_DIAG_DISContainer.ActiveEventKey',ctrl:'DDO_BR_MEDICALIMAGING_DIAG_DIS',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_MEDICALIMAGING_DIAG_DISContainer.SortedStatus',ctrl:'DDO_BR_MEDICALIMAGING_DIAG_DIS',prop:'SortedStatus'},{av:'AV13BR_MedicalImaging_DiagIDTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAGIDTITLEFILTERDATA',pic:''},{av:'AV15BR_MedicalImagingIDTitleFilterData',fld:'vBR_MEDICALIMAGINGIDTITLEFILTERDATA',pic:''},{av:'AV17BR_MedicalImaging_Diag_LocTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_LOCTITLEFILTERDATA',pic:''},{av:'AV19BR_MedicalImaging_Diag_OrganTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_ORGANTITLEFILTERDATA',pic:''},{av:'AV21BR_MedicalImaging_Diag_DisTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_DISTITLEFILTERDATA',pic:''},{av:'AV29BR_MedicalImaging_Diag_NoTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_NOTITLEFILTERDATA',pic:''},{ctrl:'BR_MEDICALIMAGING_DIAGID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAGID","Title")',ctrl:'BR_MEDICALIMAGING_DIAGID',prop:'Title'},{ctrl:'BR_MEDICALIMAGINGID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGINGID","Title")',ctrl:'BR_MEDICALIMAGINGID',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_LOC',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_LOC","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_LOC',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_ORGAN',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_ORGAN","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_ORGAN',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_DIS',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_DIS","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_DIS',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_NO',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_NO","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_NO',prop:'Title'},{av:'AV25GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV26GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV27GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_BR_MEDICALIMAGING_DIAG_NO.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_MedicalImaging_DiagIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_MedicalImagingIDTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGINGIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_BR_MedicalImaging_Diag_LocTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_LOCTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_BR_MedicalImaging_Diag_OrganTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_ORGANTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_BR_MedicalImaging_Diag_DisTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_DISTITLECONTROLIDTOREPLACE',pic:''},{av:'AV30ddo_BR_MedicalImaging_Diag_NoTitleControlIdToReplace',fld:'vDDO_BR_MEDICALIMAGING_DIAG_NOTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_BR_MEDICALIMAGING_DIAG_NOContainer.ActiveEventKey',ctrl:'DDO_BR_MEDICALIMAGING_DIAG_NO',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_MEDICALIMAGING_DIAG_NOContainer.SortedStatus',ctrl:'DDO_BR_MEDICALIMAGING_DIAG_NO',prop:'SortedStatus'},{av:'AV13BR_MedicalImaging_DiagIDTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAGIDTITLEFILTERDATA',pic:''},{av:'AV15BR_MedicalImagingIDTitleFilterData',fld:'vBR_MEDICALIMAGINGIDTITLEFILTERDATA',pic:''},{av:'AV17BR_MedicalImaging_Diag_LocTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_LOCTITLEFILTERDATA',pic:''},{av:'AV19BR_MedicalImaging_Diag_OrganTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_ORGANTITLEFILTERDATA',pic:''},{av:'AV21BR_MedicalImaging_Diag_DisTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_DISTITLEFILTERDATA',pic:''},{av:'AV29BR_MedicalImaging_Diag_NoTitleFilterData',fld:'vBR_MEDICALIMAGING_DIAG_NOTITLEFILTERDATA',pic:''},{ctrl:'BR_MEDICALIMAGING_DIAGID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAGID","Title")',ctrl:'BR_MEDICALIMAGING_DIAGID',prop:'Title'},{ctrl:'BR_MEDICALIMAGINGID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGINGID","Title")',ctrl:'BR_MEDICALIMAGINGID',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_LOC',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_LOC","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_LOC',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_ORGAN',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_ORGAN","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_ORGAN',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_DIS',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_DIS","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_DIS',prop:'Title'},{ctrl:'BR_MEDICALIMAGING_DIAG_NO',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_MEDICALIMAGING_DIAG_NO","Title")',ctrl:'BR_MEDICALIMAGING_DIAG_NO',prop:'Title'},{av:'AV25GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV26GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV27GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["GRID.LOAD"] = [[],[{av:'AV28Select',fld:'vSELECT',pic:''},{av:'gx.fn.getCtrlProperty("vSELECT","Tooltiptext")',ctrl:'vSELECT',prop:'Tooltiptext'}]];
   this.EvtParms["ENTER"] = [[{av:'A270BR_MedicalImaging_DiagID',fld:'BR_MEDICALIMAGING_DIAGID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true},{av:'A271BR_MedicalImaging_Diag_Loc',fld:'BR_MEDICALIMAGING_DIAG_LOC',pic:'',hsh:true}],[{av:'AV8InOutBR_MedicalImaging_DiagID',fld:'vINOUTBR_MEDICALIMAGING_DIAGID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV9InOutBR_MedicalImaging_Diag_Loc',fld:'vINOUTBR_MEDICALIMAGING_DIAG_LOC',pic:''}]];
   this.EnterCtrl = ["vSELECT"];
   this.setVCMap("AV8InOutBR_MedicalImaging_DiagID", "vINOUTBR_MEDICALIMAGING_DIAGID", 0, "int", 18, 0);
   this.setVCMap("AV9InOutBR_MedicalImaging_Diag_Loc", "vINOUTBR_MEDICALIMAGING_DIAG_LOC", 0, "svchar", 100, 0);
   GridContainer.addRefreshingVar(this.GXValidFnc[40]);
   GridContainer.addRefreshingVar(this.GXValidFnc[41]);
   GridContainer.addRefreshingVar(this.GXValidFnc[28]);
   GridContainer.addRefreshingVar(this.GXValidFnc[30]);
   GridContainer.addRefreshingVar(this.GXValidFnc[32]);
   GridContainer.addRefreshingVar(this.GXValidFnc[34]);
   GridContainer.addRefreshingVar(this.GXValidFnc[36]);
   GridContainer.addRefreshingVar(this.GXValidFnc[38]);
   this.Initialize( );
});
gx.createParentObj(br_medicalimaging_diagprompt);
