/*!   GeneXus C# 16_0_0-127771 on 2/27/2020 12:3:0.29
*/
gx.evt.autoSkip = false;
gx.define('br_pathology_specimenprompt', false, function () {
   this.ServerClass =  "br_pathology_specimenprompt" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.hasEnterEvent = true;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV8InOutBR_Pathology_SpecimenID=gx.fn.getIntegerValue("vINOUTBR_PATHOLOGY_SPECIMENID",',') ;
      this.AV9InOutBR_Pathology_Specimen_Name=gx.fn.getControlValue("vINOUTBR_PATHOLOGY_SPECIMEN_NAME") ;
   };
   this.e115o2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEPAGE", false, null, true, true);
   };
   this.e125o2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", false, null, true, true);
   };
   this.e135o2_client=function()
   {
      return this.executeServerEvent("DDO_BR_PATHOLOGY_SPECIMENID.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e145o2_client=function()
   {
      return this.executeServerEvent("DDO_BR_PATHOLOGYID.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e155o2_client=function()
   {
      return this.executeServerEvent("DDO_BR_PATHOLOGY_SPECIMEN_NAME.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e195o2_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e205o2_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,21,22,23,25,27,29,31,32];
   this.GXLastCtrlId =32;
   this.GridContainer = new gx.grid.grid(this, 2,"WbpLvl2",12,"Grid","Grid","GridContainer",this.CmpContext,this.IsMasterPage,"br_pathology_specimenprompt",[],false,1,false,true,0,false,false,false,"",0,"px",0,"px","澧炲姞绌虹櫧琛?,true,false,false,null,null,false,"",false,[1,1,1,1],false,0,true,false);
   var GridContainer = this.GridContainer;
   GridContainer.addBitmap("&Select","vSELECT",13,0,"px",17,"px","e195o2_client","","","SelectAttribute ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addSingleLineEdit(274,14,"BR_PATHOLOGY_SPECIMENID","","","BR_Pathology_SpecimenID","int",0,"px",18,18,"right",null,[],274,"BR_Pathology_SpecimenID",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(226,15,"BR_PATHOLOGYID","","","BR_PathologyID","int",0,"px",18,18,"right",null,[],226,"BR_PathologyID",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(275,16,"BR_PATHOLOGY_SPECIMEN_NAME","","","BR_Pathology_Specimen_Name","svchar",0,"px",100,80,"left",null,[],275,"BR_Pathology_Specimen_Name",true,0,false,false,"Attribute",1,"WWColumn");
   this.GridContainer.emptyText = "";
   this.setGrid(GridContainer);
   this.GRIDPAGINATIONBARContainer = gx.uc.getNew(this, 20, 13, "DVelop_DVPaginationBar", "GRIDPAGINATIONBARContainer", "Gridpaginationbar", "GRIDPAGINATIONBAR");
   var GRIDPAGINATIONBARContainer = this.GRIDPAGINATIONBARContainer;
   GRIDPAGINATIONBARContainer.setProp("Enabled", "Enabled", true, "boolean");
   GRIDPAGINATIONBARContainer.setProp("Class", "Class", "PaginationBar", "str");
   GRIDPAGINATIONBARContainer.setProp("ShowFirst", "Showfirst", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowPrevious", "Showprevious", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowNext", "Shownext", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowLast", "Showlast", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("PagesToShow", "Pagestoshow", 5, "num");
   GRIDPAGINATIONBARContainer.setProp("PagingButtonsPosition", "Pagingbuttonsposition", "Right", "str");
   GRIDPAGINATIONBARContainer.setProp("PagingCaptionPosition", "Pagingcaptionposition", "Left", "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridClass", "Emptygridclass", "PaginationBarEmptyGrid", "str");
   GRIDPAGINATIONBARContainer.setProp("SelectedPage", "Selectedpage", "", "char");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageSelector", "Rowsperpageselector", true, "bool");
   GRIDPAGINATIONBARContainer.setDynProp("RowsPerPageSelectedValue", "Rowsperpageselectedvalue", 10, "num");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageOptions", "Rowsperpageoptions", "5:WWP_Rows5,10:WWP_Rows10,20:WWP_Rows20,50:WWP_Rows50", "str");
   GRIDPAGINATIONBARContainer.setProp("First", "First", "First", "str");
   GRIDPAGINATIONBARContainer.setProp("Previous", "Previous", "WWP_PagingPreviousCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Next", "Next", "WWP_PagingNextCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Last", "Last", "Last", "str");
   GRIDPAGINATIONBARContainer.setProp("Caption", "Caption", "<CURRENT_PAGE>椤?<TOTAL_PAGES>椤?璁板綍锛?TOTAL_RECORDS>鏉?, "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridCaption", "Emptygridcaption", "WWP_PagingEmptyGridCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageCaption", "Rowsperpagecaption", "WWP_PagingRowsPerPage", "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV21GridCurrentPage', "vGRIDCURRENTPAGE", 'SetCurrentPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV21GridCurrentPage=UC.GetCurrentPage();gx.fn.setControlValue("vGRIDCURRENTPAGE",UC.ParentObject.AV21GridCurrentPage); });
   GRIDPAGINATIONBARContainer.setProp("PageCount", "Pagecount", '', "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV23GridRecordCount', "vGRIDRECORDCOUNT", 'SetRecordCount');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV23GridRecordCount=UC.GetRecordCount();gx.fn.setControlValue("vGRIDRECORDCOUNT",UC.ParentObject.AV23GridRecordCount); });
   GRIDPAGINATIONBARContainer.addV2CFunction('AV22GridPageSize', "vGRIDPAGESIZE", 'SetPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV22GridPageSize=UC.GetPage();gx.fn.setControlValue("vGRIDPAGESIZE",UC.ParentObject.AV22GridPageSize); });
   GRIDPAGINATIONBARContainer.setProp("Visible", "Visible", true, "bool");
   GRIDPAGINATIONBARContainer.setC2ShowFunction(function(UC) { UC.show(); });
   GRIDPAGINATIONBARContainer.addEventHandler("ChangePage", this.e115o2_client);
   GRIDPAGINATIONBARContainer.addEventHandler("ChangeRowsPerPage", this.e125o2_client);
   this.setUserControl(GRIDPAGINATIONBARContainer);
   this.DDO_BR_PATHOLOGY_SPECIMENIDContainer = gx.uc.getNew(this, 24, 13, "BootstrapDropDownOptions", "DDO_BR_PATHOLOGY_SPECIMENIDContainer", "Ddo_br_pathology_specimenid", "DDO_BR_PATHOLOGY_SPECIMENID");
   var DDO_BR_PATHOLOGY_SPECIMENIDContainer = this.DDO_BR_PATHOLOGY_SPECIMENIDContainer;
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("Class", "Class", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.addV2CFunction('AV19DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV19DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV19DDO_TitleSettingsIcons); });
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.addV2CFunction('AV13BR_Pathology_SpecimenIDTitleFilterData', "vBR_PATHOLOGY_SPECIMENIDTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV13BR_Pathology_SpecimenIDTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_PATHOLOGY_SPECIMENIDTITLEFILTERDATA",UC.ParentObject.AV13BR_Pathology_SpecimenIDTitleFilterData); });
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_PATHOLOGY_SPECIMENIDContainer.addEventHandler("OnOptionClicked", this.e135o2_client);
   this.setUserControl(DDO_BR_PATHOLOGY_SPECIMENIDContainer);
   this.DDO_BR_PATHOLOGYIDContainer = gx.uc.getNew(this, 26, 25, "BootstrapDropDownOptions", "DDO_BR_PATHOLOGYIDContainer", "Ddo_br_pathologyid", "DDO_BR_PATHOLOGYID");
   var DDO_BR_PATHOLOGYIDContainer = this.DDO_BR_PATHOLOGYIDContainer;
   DDO_BR_PATHOLOGYIDContainer.setProp("Class", "Class", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_PATHOLOGYIDContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_PATHOLOGYIDContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_PATHOLOGYIDContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_PATHOLOGYIDContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_PATHOLOGYIDContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_PATHOLOGYIDContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_PATHOLOGYIDContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_PATHOLOGYIDContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_PATHOLOGYIDContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_PATHOLOGYIDContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_PATHOLOGYIDContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_PATHOLOGYIDContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_PATHOLOGYIDContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_PATHOLOGYIDContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_PATHOLOGYIDContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_PATHOLOGYIDContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_PATHOLOGYIDContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_PATHOLOGYIDContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_PATHOLOGYIDContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_PATHOLOGYIDContainer.addV2CFunction('AV19DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_PATHOLOGYIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV19DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV19DDO_TitleSettingsIcons); });
   DDO_BR_PATHOLOGYIDContainer.addV2CFunction('AV15BR_PathologyIDTitleFilterData', "vBR_PATHOLOGYIDTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_PATHOLOGYIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV15BR_PathologyIDTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_PATHOLOGYIDTITLEFILTERDATA",UC.ParentObject.AV15BR_PathologyIDTitleFilterData); });
   DDO_BR_PATHOLOGYIDContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_PATHOLOGYIDContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_PATHOLOGYIDContainer.addEventHandler("OnOptionClicked", this.e145o2_client);
   this.setUserControl(DDO_BR_PATHOLOGYIDContainer);
   this.DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer = gx.uc.getNew(this, 28, 25, "BootstrapDropDownOptions", "DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer", "Ddo_br_pathology_specimen_name", "DDO_BR_PATHOLOGY_SPECIMEN_NAME");
   var DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer = this.DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer;
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("Class", "Class", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("Icon", "Icon", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("Caption", "Caption", "", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.addV2CFunction('AV19DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV19DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV19DDO_TitleSettingsIcons); });
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.addV2CFunction('AV17BR_Pathology_Specimen_NameTitleFilterData', "vBR_PATHOLOGY_SPECIMEN_NAMETITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV17BR_Pathology_Specimen_NameTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vBR_PATHOLOGY_SPECIMEN_NAMETITLEFILTERDATA",UC.ParentObject.AV17BR_Pathology_Specimen_NameTitleFilterData); });
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setProp("Visible", "Visible", true, "bool");
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.addEventHandler("OnOptionClicked", this.e155o2_client);
   this.setUserControl(DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer);
   this.WORKWITHPLUSUTILITIES1Container = gx.uc.getNew(this, 30, 25, "DVelop_WorkWithPlusUtilities", "WORKWITHPLUSUTILITIES1Container", "Workwithplusutilities1", "WORKWITHPLUSUTILITIES1");
   var WORKWITHPLUSUTILITIES1Container = this.WORKWITHPLUSUTILITIES1Container;
   WORKWITHPLUSUTILITIES1Container.setProp("Class", "Class", "", "char");
   WORKWITHPLUSUTILITIES1Container.setProp("Enabled", "Enabled", true, "boolean");
   WORKWITHPLUSUTILITIES1Container.setProp("Width", "Width", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Height", "Height", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Visible", "Visible", true, "bool");
   WORKWITHPLUSUTILITIES1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(WORKWITHPLUSUTILITIES1Container);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEMAIN",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"GRIDTABLEWITHPAGINATIONBAR",grid:0};
   GXValidFnc[10]={ id: 10, fld:"",grid:0};
   GXValidFnc[11]={ id: 11, fld:"",grid:0};
   GXValidFnc[13]={ id:13 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vSELECT",gxz:"ZV24Select",gxold:"OV24Select",gxvar:"AV24Select",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV24Select=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV24Select=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vSELECT",row || gx.fn.currentGridRowImpl(12),gx.O.AV24Select,gx.O.AV28Select_GXI)},c2v:function(){gx.O.AV28Select_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV24Select=this.val()},val:function(row){return gx.fn.getGridControlValue("vSELECT",row || gx.fn.currentGridRowImpl(12))},val_GXI:function(row){return gx.fn.getGridControlValue("vSELECT_GXI",row || gx.fn.currentGridRowImpl(12))}, gxvar_GXI:'AV28Select_GXI',nac:gx.falseFn,evt:"e195o2_client",std:"ENTER"};
   GXValidFnc[14]={ id:14 ,lvl:2,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_PATHOLOGY_SPECIMENID",gxz:"Z274BR_Pathology_SpecimenID",gxold:"O274BR_Pathology_SpecimenID",gxvar:"A274BR_Pathology_SpecimenID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A274BR_Pathology_SpecimenID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z274BR_Pathology_SpecimenID=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("BR_PATHOLOGY_SPECIMENID",row || gx.fn.currentGridRowImpl(12),gx.O.A274BR_Pathology_SpecimenID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A274BR_Pathology_SpecimenID=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("BR_PATHOLOGY_SPECIMENID",row || gx.fn.currentGridRowImpl(12),',')},nac:gx.falseFn};
   GXValidFnc[15]={ id:15 ,lvl:2,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_PATHOLOGYID",gxz:"Z226BR_PathologyID",gxold:"O226BR_PathologyID",gxvar:"A226BR_PathologyID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A226BR_PathologyID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z226BR_PathologyID=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("BR_PATHOLOGYID",row || gx.fn.currentGridRowImpl(12),gx.O.A226BR_PathologyID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A226BR_PathologyID=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("BR_PATHOLOGYID",row || gx.fn.currentGridRowImpl(12),',')},nac:gx.falseFn};
   GXValidFnc[16]={ id:16 ,lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"BR_PATHOLOGY_SPECIMEN_NAME",gxz:"Z275BR_Pathology_Specimen_Name",gxold:"O275BR_Pathology_Specimen_Name",gxvar:"A275BR_Pathology_Specimen_Name",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A275BR_Pathology_Specimen_Name=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z275BR_Pathology_Specimen_Name=Value},v2c:function(row){gx.fn.setGridControlValue("BR_PATHOLOGY_SPECIMEN_NAME",row || gx.fn.currentGridRowImpl(12),gx.O.A275BR_Pathology_Specimen_Name,0)},c2v:function(){if(this.val()!==undefined)gx.O.A275BR_Pathology_Specimen_Name=this.val()},val:function(row){return gx.fn.getGridControlValue("BR_PATHOLOGY_SPECIMEN_NAME",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn};
   GXValidFnc[17]={ id: 17, fld:"",grid:0};
   GXValidFnc[18]={ id: 18, fld:"",grid:0};
   GXValidFnc[19]={ id: 19, fld:"HTML_GRIDPAGINATIONBAR",grid:0};
   GXValidFnc[21]={ id: 21, fld:"",grid:0};
   GXValidFnc[22]={ id: 22, fld:"",grid:0};
   GXValidFnc[23]={ id: 23, fld:"HTML_BOTTOMAUXILIARCONTROLS",grid:0};
   GXValidFnc[25]={ id:25 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_PATHOLOGY_SPECIMENIDTITLECONTROLIDTOREPLACE",gxz:"ZV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace",gxold:"OV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace",gxvar:"AV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_PATHOLOGY_SPECIMENIDTITLECONTROLIDTOREPLACE",gx.O.AV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_PATHOLOGY_SPECIMENIDTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[27]={ id:27 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_PATHOLOGYIDTITLECONTROLIDTOREPLACE",gxz:"ZV16ddo_BR_PathologyIDTitleControlIdToReplace",gxold:"OV16ddo_BR_PathologyIDTitleControlIdToReplace",gxvar:"AV16ddo_BR_PathologyIDTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV16ddo_BR_PathologyIDTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV16ddo_BR_PathologyIDTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_PATHOLOGYIDTITLECONTROLIDTOREPLACE",gx.O.AV16ddo_BR_PathologyIDTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV16ddo_BR_PathologyIDTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_PATHOLOGYIDTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[29]={ id:29 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE",gxz:"ZV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace",gxold:"OV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace",gxvar:"AV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE",gx.O.AV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[31]={ id:31 ,lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDBY",gxz:"ZV11OrderedBy",gxold:"OV11OrderedBy",gxvar:"AV11OrderedBy",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV11OrderedBy=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV11OrderedBy=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDBY",gx.O.AV11OrderedBy,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV11OrderedBy=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vORDEREDBY",',')},nac:gx.falseFn};
   GXValidFnc[32]={ id:32 ,lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDDSC",gxz:"ZV12OrderedDsc",gxold:"OV12OrderedDsc",gxvar:"AV12OrderedDsc",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV12OrderedDsc=gx.lang.booleanValue(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV12OrderedDsc=gx.lang.booleanValue(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDDSC",gx.O.AV12OrderedDsc,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV12OrderedDsc=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getControlValue("vORDEREDDSC")},nac:gx.falseFn};
   this.ZV24Select = "" ;
   this.OV24Select = "" ;
   this.Z274BR_Pathology_SpecimenID = 0 ;
   this.O274BR_Pathology_SpecimenID = 0 ;
   this.Z226BR_PathologyID = 0 ;
   this.O226BR_PathologyID = 0 ;
   this.Z275BR_Pathology_Specimen_Name = "" ;
   this.O275BR_Pathology_Specimen_Name = "" ;
   this.AV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace = "" ;
   this.ZV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace = "" ;
   this.OV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace = "" ;
   this.AV16ddo_BR_PathologyIDTitleControlIdToReplace = "" ;
   this.ZV16ddo_BR_PathologyIDTitleControlIdToReplace = "" ;
   this.OV16ddo_BR_PathologyIDTitleControlIdToReplace = "" ;
   this.AV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace = "" ;
   this.ZV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace = "" ;
   this.OV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace = "" ;
   this.AV11OrderedBy = 0 ;
   this.ZV11OrderedBy = 0 ;
   this.OV11OrderedBy = 0 ;
   this.AV12OrderedDsc = false ;
   this.ZV12OrderedDsc = false ;
   this.OV12OrderedDsc = false ;
   this.AV21GridCurrentPage = 0 ;
   this.AV19DDO_TitleSettingsIcons = {Default:"",Default_GXI:"",Filtered:"",Filtered_GXI:"",SortedASC:"",SortedASC_GXI:"",SortedDSC:"",SortedDSC_GXI:"",FilteredSortedASC:"",FilteredSortedASC_GXI:"",FilteredSortedDSC:"",FilteredSortedDSC_GXI:"",OptionSortASC:"",OptionSortASC_GXI:"",OptionSortDSC:"",OptionSortDSC_GXI:"",OptionApplyFilter:"",OptionApplyFilter_GXI:"",OptionFilteringData:"",OptionFilteringData_GXI:"",OptionCleanFilters:"",OptionCleanFilters_GXI:"",SelectedOption:"",SelectedOption_GXI:"",MultiselOption:"",MultiselOption_GXI:"",MultiselSelOption:"",MultiselSelOption_GXI:""} ;
   this.AV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace = "" ;
   this.AV16ddo_BR_PathologyIDTitleControlIdToReplace = "" ;
   this.AV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace = "" ;
   this.AV11OrderedBy = 0 ;
   this.AV12OrderedDsc = false ;
   this.AV8InOutBR_Pathology_SpecimenID = 0 ;
   this.AV9InOutBR_Pathology_Specimen_Name = "" ;
   this.AV24Select = "" ;
   this.A274BR_Pathology_SpecimenID = 0 ;
   this.A226BR_PathologyID = 0 ;
   this.A275BR_Pathology_Specimen_Name = "" ;
   this.Events = {"e115o2_client": ["GRIDPAGINATIONBAR.CHANGEPAGE", true] ,"e125o2_client": ["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", true] ,"e135o2_client": ["DDO_BR_PATHOLOGY_SPECIMENID.ONOPTIONCLICKED", true] ,"e145o2_client": ["DDO_BR_PATHOLOGYID.ONOPTIONCLICKED", true] ,"e155o2_client": ["DDO_BR_PATHOLOGY_SPECIMEN_NAME.ONOPTIONCLICKED", true] ,"e195o2_client": ["ENTER", true] ,"e205o2_client": ["CANCEL", true]};
   this.EvtParms["REFRESH"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMENIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_PathologyIDTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGYIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE',pic:''},{ctrl:'GRID',prop:'Rows'}],[{av:'AV13BR_Pathology_SpecimenIDTitleFilterData',fld:'vBR_PATHOLOGY_SPECIMENIDTITLEFILTERDATA',pic:''},{av:'AV15BR_PathologyIDTitleFilterData',fld:'vBR_PATHOLOGYIDTITLEFILTERDATA',pic:''},{av:'AV17BR_Pathology_Specimen_NameTitleFilterData',fld:'vBR_PATHOLOGY_SPECIMEN_NAMETITLEFILTERDATA',pic:''},{ctrl:'BR_PATHOLOGY_SPECIMENID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_SPECIMENID","Title")',ctrl:'BR_PATHOLOGY_SPECIMENID',prop:'Title'},{ctrl:'BR_PATHOLOGYID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGYID","Title")',ctrl:'BR_PATHOLOGYID',prop:'Title'},{ctrl:'BR_PATHOLOGY_SPECIMEN_NAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_SPECIMEN_NAME","Title")',ctrl:'BR_PATHOLOGY_SPECIMEN_NAME',prop:'Title'},{av:'AV21GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV22GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV23GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["START"] = [[{av:'AV27Pgmname',fld:'vPGMNAME',pic:''},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'}],[{av:'gx.fn.getCtrlProperty("TABLEMAIN","Height")',ctrl:'TABLEMAIN',prop:'Height'},{ctrl:'GRID',prop:'Rows'},{av:'this.DDO_BR_PATHOLOGY_SPECIMENIDContainer.TitleControlIdToReplace',ctrl:'DDO_BR_PATHOLOGY_SPECIMENID',prop:'TitleControlIdToReplace'},{av:'AV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMENIDTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_PATHOLOGY_SPECIMENIDTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_PATHOLOGY_SPECIMENIDTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_PATHOLOGYIDContainer.TitleControlIdToReplace',ctrl:'DDO_BR_PATHOLOGYID',prop:'TitleControlIdToReplace'},{av:'AV16ddo_BR_PathologyIDTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGYIDTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_PATHOLOGYIDTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_PATHOLOGYIDTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.TitleControlIdToReplace',ctrl:'DDO_BR_PATHOLOGY_SPECIMEN_NAME',prop:'TitleControlIdToReplace'},{av:'AV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE',prop:'Visible'},{ctrl:'FORM',prop:'Caption'},{av:'gx.fn.getCtrlProperty("vORDEREDBY","Visible")',ctrl:'vORDEREDBY',prop:'Visible'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'gx.fn.getCtrlProperty("vORDEREDDSC","Visible")',ctrl:'vORDEREDDSC',prop:'Visible'},{av:'AV19DDO_TitleSettingsIcons',fld:'vDDO_TITLESETTINGSICONS',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMENIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_PathologyIDTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGYIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'this.GRIDPAGINATIONBARContainer.SelectedPage',ctrl:'GRIDPAGINATIONBAR',prop:'SelectedPage'}],[]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMENIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_PathologyIDTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGYIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}],[{ctrl:'GRID',prop:'Rows'}]];
   this.EvtParms["DDO_BR_PATHOLOGY_SPECIMENID.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMENIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_PathologyIDTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGYIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_BR_PATHOLOGY_SPECIMENIDContainer.ActiveEventKey',ctrl:'DDO_BR_PATHOLOGY_SPECIMENID',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_PATHOLOGY_SPECIMENIDContainer.SortedStatus',ctrl:'DDO_BR_PATHOLOGY_SPECIMENID',prop:'SortedStatus'},{av:'AV13BR_Pathology_SpecimenIDTitleFilterData',fld:'vBR_PATHOLOGY_SPECIMENIDTITLEFILTERDATA',pic:''},{av:'AV15BR_PathologyIDTitleFilterData',fld:'vBR_PATHOLOGYIDTITLEFILTERDATA',pic:''},{av:'AV17BR_Pathology_Specimen_NameTitleFilterData',fld:'vBR_PATHOLOGY_SPECIMEN_NAMETITLEFILTERDATA',pic:''},{ctrl:'BR_PATHOLOGY_SPECIMENID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_SPECIMENID","Title")',ctrl:'BR_PATHOLOGY_SPECIMENID',prop:'Title'},{ctrl:'BR_PATHOLOGYID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGYID","Title")',ctrl:'BR_PATHOLOGYID',prop:'Title'},{ctrl:'BR_PATHOLOGY_SPECIMEN_NAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_SPECIMEN_NAME","Title")',ctrl:'BR_PATHOLOGY_SPECIMEN_NAME',prop:'Title'},{av:'AV21GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV22GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV23GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_BR_PATHOLOGYID.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMENIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_PathologyIDTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGYIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_BR_PATHOLOGYIDContainer.ActiveEventKey',ctrl:'DDO_BR_PATHOLOGYID',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_PATHOLOGYIDContainer.SortedStatus',ctrl:'DDO_BR_PATHOLOGYID',prop:'SortedStatus'},{av:'AV13BR_Pathology_SpecimenIDTitleFilterData',fld:'vBR_PATHOLOGY_SPECIMENIDTITLEFILTERDATA',pic:''},{av:'AV15BR_PathologyIDTitleFilterData',fld:'vBR_PATHOLOGYIDTITLEFILTERDATA',pic:''},{av:'AV17BR_Pathology_Specimen_NameTitleFilterData',fld:'vBR_PATHOLOGY_SPECIMEN_NAMETITLEFILTERDATA',pic:''},{ctrl:'BR_PATHOLOGY_SPECIMENID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_SPECIMENID","Title")',ctrl:'BR_PATHOLOGY_SPECIMENID',prop:'Title'},{ctrl:'BR_PATHOLOGYID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGYID","Title")',ctrl:'BR_PATHOLOGYID',prop:'Title'},{ctrl:'BR_PATHOLOGY_SPECIMEN_NAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_SPECIMEN_NAME","Title")',ctrl:'BR_PATHOLOGY_SPECIMEN_NAME',prop:'Title'},{av:'AV21GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV22GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV23GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_BR_PATHOLOGY_SPECIMEN_NAME.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_BR_Pathology_SpecimenIDTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMENIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_BR_PathologyIDTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGYIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_BR_Pathology_Specimen_NameTitleControlIdToReplace',fld:'vDDO_BR_PATHOLOGY_SPECIMEN_NAMETITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.ActiveEventKey',ctrl:'DDO_BR_PATHOLOGY_SPECIMEN_NAME',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_BR_PATHOLOGY_SPECIMEN_NAMEContainer.SortedStatus',ctrl:'DDO_BR_PATHOLOGY_SPECIMEN_NAME',prop:'SortedStatus'},{av:'AV13BR_Pathology_SpecimenIDTitleFilterData',fld:'vBR_PATHOLOGY_SPECIMENIDTITLEFILTERDATA',pic:''},{av:'AV15BR_PathologyIDTitleFilterData',fld:'vBR_PATHOLOGYIDTITLEFILTERDATA',pic:''},{av:'AV17BR_Pathology_Specimen_NameTitleFilterData',fld:'vBR_PATHOLOGY_SPECIMEN_NAMETITLEFILTERDATA',pic:''},{ctrl:'BR_PATHOLOGY_SPECIMENID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_SPECIMENID","Title")',ctrl:'BR_PATHOLOGY_SPECIMENID',prop:'Title'},{ctrl:'BR_PATHOLOGYID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGYID","Title")',ctrl:'BR_PATHOLOGYID',prop:'Title'},{ctrl:'BR_PATHOLOGY_SPECIMEN_NAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("BR_PATHOLOGY_SPECIMEN_NAME","Title")',ctrl:'BR_PATHOLOGY_SPECIMEN_NAME',prop:'Title'},{av:'AV21GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV22GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV23GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["GRID.LOAD"] = [[],[{av:'AV24Select',fld:'vSELECT',pic:''},{av:'gx.fn.getCtrlProperty("vSELECT","Tooltiptext")',ctrl:'vSELECT',prop:'Tooltiptext'}]];
   this.EvtParms["ENTER"] = [[{av:'A274BR_Pathology_SpecimenID',fld:'BR_PATHOLOGY_SPECIMENID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true},{av:'A275BR_Pathology_Specimen_Name',fld:'BR_PATHOLOGY_SPECIMEN_NAME',pic:'',hsh:true}],[{av:'AV8InOutBR_Pathology_SpecimenID',fld:'vINOUTBR_PATHOLOGY_SPECIMENID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV9InOutBR_Pathology_Specimen_Name',fld:'vINOUTBR_PATHOLOGY_SPECIMEN_NAME',pic:''}]];
   this.EnterCtrl = ["vSELECT"];
   this.setVCMap("AV8InOutBR_Pathology_SpecimenID", "vINOUTBR_PATHOLOGY_SPECIMENID", 0, "int", 18, 0);
   this.setVCMap("AV9InOutBR_Pathology_Specimen_Name", "vINOUTBR_PATHOLOGY_SPECIMEN_NAME", 0, "svchar", 100, 0);
   GridContainer.addRefreshingVar(this.GXValidFnc[31]);
   GridContainer.addRefreshingVar(this.GXValidFnc[32]);
   GridContainer.addRefreshingVar(this.GXValidFnc[25]);
   GridContainer.addRefreshingVar(this.GXValidFnc[27]);
   GridContainer.addRefreshingVar(this.GXValidFnc[29]);
   this.Initialize( );
});
gx.createParentObj(br_pathology_specimenprompt);
