/*!   GeneXus C# 16_0_0-127771 on 2/27/2020 12:6:50.24
*/
gx.evt.autoSkip = false;
gx.define('jc_providerprompt', false, function () {
   this.ServerClass =  "jc_providerprompt" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.hasEnterEvent = true;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV8InOutJC_ProviderID=gx.fn.getIntegerValue("vINOUTJC_PROVIDERID",',') ;
      this.AV9InOutJC_ProviderName=gx.fn.getControlValue("vINOUTJC_PROVIDERNAME") ;
   };
   this.e238j2_client=function()
   {
      this.clearMessages();
      this.popupOpenUrl(gx.http.formatLink("wwpbaseobjects.addressdisplay.aspx",[this.A161JC_ProviderAddresss, ""]), []);
      this.refreshOutputs([]);
      return gx.$.Deferred().resolve();
   };
   this.e118j2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEPAGE", false, null, true, true);
   };
   this.e128j2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", false, null, true, true);
   };
   this.e138j2_client=function()
   {
      return this.executeServerEvent("DDO_JC_PROVIDERID.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e148j2_client=function()
   {
      return this.executeServerEvent("DDO_JC_PROVIDERNAME.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e158j2_client=function()
   {
      return this.executeServerEvent("DDO_JC_PROVIDERSHORTNAME.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e168j2_client=function()
   {
      return this.executeServerEvent("DDO_JC_PROVIDERADDRESSS.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e178j2_client=function()
   {
      return this.executeServerEvent("DDO_JC_PROVIDERPHONE.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e188j2_client=function()
   {
      return this.executeServerEvent("DDO_JC_PROVIDERUSER.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e228j2_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e248j2_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,24,25,26,28,30,32,34,36,38,40,41];
   this.GXLastCtrlId =41;
   this.GridContainer = new gx.grid.grid(this, 2,"WbpLvl2",12,"Grid","Grid","GridContainer",this.CmpContext,this.IsMasterPage,"jc_providerprompt",[],false,1,false,true,0,false,false,false,"",0,"px",0,"px","澧炲姞绌虹櫧琛?,true,false,false,null,null,false,"",false,[1,1,1,1],false,0,true,false);
   var GridContainer = this.GridContainer;
   GridContainer.addBitmap("&Select","vSELECT",13,0,"px",17,"px","e228j2_client","","","SelectAttribute ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addSingleLineEdit(87,14,"JC_PROVIDERID","","","JC_ProviderID","int",0,"px",18,18,"right",null,[],87,"JC_ProviderID",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(89,15,"JC_PROVIDERNAME","","","JC_ProviderName","svchar",410,"px",200,80,"left",null,[],89,"JC_ProviderName",true,0,false,false,"Attribute",1,"WWColumn");
   GridContainer.addSingleLineEdit(160,16,"JC_PROVIDERSHORTNAME","","","JC_ProviderShortName","svchar",0,"px",100,80,"left",null,[],160,"JC_ProviderShortName",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(161,17,"JC_PROVIDERADDRESSS","","","JC_ProviderAddresss","svchar",410,"px",1024,80,"left","e238j2_client",[],161,"JC_ProviderAddresss",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(162,18,"JC_PROVIDERPHONE","","","JC_ProviderPhone","char",0,"px",20,20,"left",null,[],162,"JC_ProviderPhone",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(163,19,"JC_PROVIDERUSER","","","JC_ProviderUser","svchar",0,"px",40,40,"left",null,[],163,"JC_ProviderUser",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   this.GridContainer.emptyText = "";
   this.setGrid(GridContainer);
   this.GRIDPAGINATIONBARContainer = gx.uc.getNew(this, 23, 13, "DVelop_DVPaginationBar", "GRIDPAGINATIONBARContainer", "Gridpaginationbar", "GRIDPAGINATIONBAR");
   var GRIDPAGINATIONBARContainer = this.GRIDPAGINATIONBARContainer;
   GRIDPAGINATIONBARContainer.setProp("Enabled", "Enabled", true, "boolean");
   GRIDPAGINATIONBARContainer.setProp("Class", "Class", "PaginationBar", "str");
   GRIDPAGINATIONBARContainer.setProp("ShowFirst", "Showfirst", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowPrevious", "Showprevious", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowNext", "Shownext", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowLast", "Showlast", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("PagesToShow", "Pagestoshow", 5, "num");
   GRIDPAGINATIONBARContainer.setProp("PagingButtonsPosition", "Pagingbuttonsposition", "Right", "str");
   GRIDPAGINATIONBARContainer.setProp("PagingCaptionPosition", "Pagingcaptionposition", "Left", "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridClass", "Emptygridclass", "PaginationBarEmptyGrid", "str");
   GRIDPAGINATIONBARContainer.setProp("SelectedPage", "Selectedpage", "", "char");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageSelector", "Rowsperpageselector", true, "bool");
   GRIDPAGINATIONBARContainer.setDynProp("RowsPerPageSelectedValue", "Rowsperpageselectedvalue", 10, "num");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageOptions", "Rowsperpageoptions", "5:WWP_Rows5,10:WWP_Rows10,20:WWP_Rows20,50:WWP_Rows50", "str");
   GRIDPAGINATIONBARContainer.setProp("First", "First", "First", "str");
   GRIDPAGINATIONBARContainer.setProp("Previous", "Previous", "WWP_PagingPreviousCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Next", "Next", "WWP_PagingNextCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Last", "Last", "Last", "str");
   GRIDPAGINATIONBARContainer.setProp("Caption", "Caption", "<CURRENT_PAGE>椤?<TOTAL_PAGES>椤?璁板綍锛?TOTAL_RECORDS>鏉?, "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridCaption", "Emptygridcaption", "WWP_PagingEmptyGridCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageCaption", "Rowsperpagecaption", "WWP_PagingRowsPerPage", "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV27GridCurrentPage', "vGRIDCURRENTPAGE", 'SetCurrentPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV27GridCurrentPage=UC.GetCurrentPage();gx.fn.setControlValue("vGRIDCURRENTPAGE",UC.ParentObject.AV27GridCurrentPage); });
   GRIDPAGINATIONBARContainer.setProp("PageCount", "Pagecount", '', "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV29GridRecordCount', "vGRIDRECORDCOUNT", 'SetRecordCount');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV29GridRecordCount=UC.GetRecordCount();gx.fn.setControlValue("vGRIDRECORDCOUNT",UC.ParentObject.AV29GridRecordCount); });
   GRIDPAGINATIONBARContainer.addV2CFunction('AV28GridPageSize', "vGRIDPAGESIZE", 'SetPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV28GridPageSize=UC.GetPage();gx.fn.setControlValue("vGRIDPAGESIZE",UC.ParentObject.AV28GridPageSize); });
   GRIDPAGINATIONBARContainer.setProp("Visible", "Visible", true, "bool");
   GRIDPAGINATIONBARContainer.setC2ShowFunction(function(UC) { UC.show(); });
   GRIDPAGINATIONBARContainer.addEventHandler("ChangePage", this.e118j2_client);
   GRIDPAGINATIONBARContainer.addEventHandler("ChangeRowsPerPage", this.e128j2_client);
   this.setUserControl(GRIDPAGINATIONBARContainer);
   this.DDO_JC_PROVIDERIDContainer = gx.uc.getNew(this, 27, 13, "BootstrapDropDownOptions", "DDO_JC_PROVIDERIDContainer", "Ddo_jc_providerid", "DDO_JC_PROVIDERID");
   var DDO_JC_PROVIDERIDContainer = this.DDO_JC_PROVIDERIDContainer;
   DDO_JC_PROVIDERIDContainer.setProp("Class", "Class", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_JC_PROVIDERIDContainer.setProp("Icon", "Icon", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("Caption", "Caption", "", "str");
   DDO_JC_PROVIDERIDContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_JC_PROVIDERIDContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_JC_PROVIDERIDContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_JC_PROVIDERIDContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_JC_PROVIDERIDContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_JC_PROVIDERIDContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_JC_PROVIDERIDContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_JC_PROVIDERIDContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_JC_PROVIDERIDContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_JC_PROVIDERIDContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_JC_PROVIDERIDContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_JC_PROVIDERIDContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_JC_PROVIDERIDContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_JC_PROVIDERIDContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_JC_PROVIDERIDContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_JC_PROVIDERIDContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_JC_PROVIDERIDContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_JC_PROVIDERIDContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_JC_PROVIDERIDContainer.addV2CFunction('AV25DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_JC_PROVIDERIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV25DDO_TitleSettingsIcons); });
   DDO_JC_PROVIDERIDContainer.addV2CFunction('AV13JC_ProviderIDTitleFilterData', "vJC_PROVIDERIDTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_JC_PROVIDERIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV13JC_ProviderIDTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vJC_PROVIDERIDTITLEFILTERDATA",UC.ParentObject.AV13JC_ProviderIDTitleFilterData); });
   DDO_JC_PROVIDERIDContainer.setProp("Visible", "Visible", true, "bool");
   DDO_JC_PROVIDERIDContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_JC_PROVIDERIDContainer.addEventHandler("OnOptionClicked", this.e138j2_client);
   this.setUserControl(DDO_JC_PROVIDERIDContainer);
   this.DDO_JC_PROVIDERNAMEContainer = gx.uc.getNew(this, 29, 28, "BootstrapDropDownOptions", "DDO_JC_PROVIDERNAMEContainer", "Ddo_jc_providername", "DDO_JC_PROVIDERNAME");
   var DDO_JC_PROVIDERNAMEContainer = this.DDO_JC_PROVIDERNAMEContainer;
   DDO_JC_PROVIDERNAMEContainer.setProp("Class", "Class", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_JC_PROVIDERNAMEContainer.setProp("Icon", "Icon", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("Caption", "Caption", "", "str");
   DDO_JC_PROVIDERNAMEContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_JC_PROVIDERNAMEContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_JC_PROVIDERNAMEContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_JC_PROVIDERNAMEContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_JC_PROVIDERNAMEContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_JC_PROVIDERNAMEContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_JC_PROVIDERNAMEContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_JC_PROVIDERNAMEContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_JC_PROVIDERNAMEContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_JC_PROVIDERNAMEContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_JC_PROVIDERNAMEContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_JC_PROVIDERNAMEContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_JC_PROVIDERNAMEContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_JC_PROVIDERNAMEContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_JC_PROVIDERNAMEContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_JC_PROVIDERNAMEContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_JC_PROVIDERNAMEContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_JC_PROVIDERNAMEContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_JC_PROVIDERNAMEContainer.addV2CFunction('AV25DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_JC_PROVIDERNAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV25DDO_TitleSettingsIcons); });
   DDO_JC_PROVIDERNAMEContainer.addV2CFunction('AV15JC_ProviderNameTitleFilterData', "vJC_PROVIDERNAMETITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_JC_PROVIDERNAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV15JC_ProviderNameTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vJC_PROVIDERNAMETITLEFILTERDATA",UC.ParentObject.AV15JC_ProviderNameTitleFilterData); });
   DDO_JC_PROVIDERNAMEContainer.setProp("Visible", "Visible", true, "bool");
   DDO_JC_PROVIDERNAMEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_JC_PROVIDERNAMEContainer.addEventHandler("OnOptionClicked", this.e148j2_client);
   this.setUserControl(DDO_JC_PROVIDERNAMEContainer);
   this.DDO_JC_PROVIDERSHORTNAMEContainer = gx.uc.getNew(this, 31, 28, "BootstrapDropDownOptions", "DDO_JC_PROVIDERSHORTNAMEContainer", "Ddo_jc_providershortname", "DDO_JC_PROVIDERSHORTNAME");
   var DDO_JC_PROVIDERSHORTNAMEContainer = this.DDO_JC_PROVIDERSHORTNAMEContainer;
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("Class", "Class", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("Icon", "Icon", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("Caption", "Caption", "", "str");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_JC_PROVIDERSHORTNAMEContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_JC_PROVIDERSHORTNAMEContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_JC_PROVIDERSHORTNAMEContainer.addV2CFunction('AV25DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_JC_PROVIDERSHORTNAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV25DDO_TitleSettingsIcons); });
   DDO_JC_PROVIDERSHORTNAMEContainer.addV2CFunction('AV17JC_ProviderShortNameTitleFilterData', "vJC_PROVIDERSHORTNAMETITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_JC_PROVIDERSHORTNAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV17JC_ProviderShortNameTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vJC_PROVIDERSHORTNAMETITLEFILTERDATA",UC.ParentObject.AV17JC_ProviderShortNameTitleFilterData); });
   DDO_JC_PROVIDERSHORTNAMEContainer.setProp("Visible", "Visible", true, "bool");
   DDO_JC_PROVIDERSHORTNAMEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_JC_PROVIDERSHORTNAMEContainer.addEventHandler("OnOptionClicked", this.e158j2_client);
   this.setUserControl(DDO_JC_PROVIDERSHORTNAMEContainer);
   this.DDO_JC_PROVIDERADDRESSSContainer = gx.uc.getNew(this, 33, 28, "BootstrapDropDownOptions", "DDO_JC_PROVIDERADDRESSSContainer", "Ddo_jc_provideraddresss", "DDO_JC_PROVIDERADDRESSS");
   var DDO_JC_PROVIDERADDRESSSContainer = this.DDO_JC_PROVIDERADDRESSSContainer;
   DDO_JC_PROVIDERADDRESSSContainer.setProp("Class", "Class", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("Icon", "Icon", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("Caption", "Caption", "", "str");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_JC_PROVIDERADDRESSSContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_JC_PROVIDERADDRESSSContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_JC_PROVIDERADDRESSSContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_JC_PROVIDERADDRESSSContainer.addV2CFunction('AV25DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_JC_PROVIDERADDRESSSContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV25DDO_TitleSettingsIcons); });
   DDO_JC_PROVIDERADDRESSSContainer.addV2CFunction('AV19JC_ProviderAddresssTitleFilterData', "vJC_PROVIDERADDRESSSTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_JC_PROVIDERADDRESSSContainer.addC2VFunction(function(UC) { UC.ParentObject.AV19JC_ProviderAddresssTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vJC_PROVIDERADDRESSSTITLEFILTERDATA",UC.ParentObject.AV19JC_ProviderAddresssTitleFilterData); });
   DDO_JC_PROVIDERADDRESSSContainer.setProp("Visible", "Visible", true, "bool");
   DDO_JC_PROVIDERADDRESSSContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_JC_PROVIDERADDRESSSContainer.addEventHandler("OnOptionClicked", this.e168j2_client);
   this.setUserControl(DDO_JC_PROVIDERADDRESSSContainer);
   this.DDO_JC_PROVIDERPHONEContainer = gx.uc.getNew(this, 35, 28, "BootstrapDropDownOptions", "DDO_JC_PROVIDERPHONEContainer", "Ddo_jc_providerphone", "DDO_JC_PROVIDERPHONE");
   var DDO_JC_PROVIDERPHONEContainer = this.DDO_JC_PROVIDERPHONEContainer;
   DDO_JC_PROVIDERPHONEContainer.setProp("Class", "Class", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_JC_PROVIDERPHONEContainer.setProp("Icon", "Icon", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("Caption", "Caption", "", "str");
   DDO_JC_PROVIDERPHONEContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_JC_PROVIDERPHONEContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_JC_PROVIDERPHONEContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_JC_PROVIDERPHONEContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_JC_PROVIDERPHONEContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_JC_PROVIDERPHONEContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_JC_PROVIDERPHONEContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_JC_PROVIDERPHONEContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_JC_PROVIDERPHONEContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_JC_PROVIDERPHONEContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_JC_PROVIDERPHONEContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_JC_PROVIDERPHONEContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_JC_PROVIDERPHONEContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_JC_PROVIDERPHONEContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_JC_PROVIDERPHONEContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_JC_PROVIDERPHONEContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_JC_PROVIDERPHONEContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_JC_PROVIDERPHONEContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_JC_PROVIDERPHONEContainer.addV2CFunction('AV25DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_JC_PROVIDERPHONEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV25DDO_TitleSettingsIcons); });
   DDO_JC_PROVIDERPHONEContainer.addV2CFunction('AV21JC_ProviderPhoneTitleFilterData', "vJC_PROVIDERPHONETITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_JC_PROVIDERPHONEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV21JC_ProviderPhoneTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vJC_PROVIDERPHONETITLEFILTERDATA",UC.ParentObject.AV21JC_ProviderPhoneTitleFilterData); });
   DDO_JC_PROVIDERPHONEContainer.setProp("Visible", "Visible", true, "bool");
   DDO_JC_PROVIDERPHONEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_JC_PROVIDERPHONEContainer.addEventHandler("OnOptionClicked", this.e178j2_client);
   this.setUserControl(DDO_JC_PROVIDERPHONEContainer);
   this.DDO_JC_PROVIDERUSERContainer = gx.uc.getNew(this, 37, 28, "BootstrapDropDownOptions", "DDO_JC_PROVIDERUSERContainer", "Ddo_jc_provideruser", "DDO_JC_PROVIDERUSER");
   var DDO_JC_PROVIDERUSERContainer = this.DDO_JC_PROVIDERUSERContainer;
   DDO_JC_PROVIDERUSERContainer.setProp("Class", "Class", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_JC_PROVIDERUSERContainer.setProp("Icon", "Icon", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("Caption", "Caption", "", "str");
   DDO_JC_PROVIDERUSERContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_JC_PROVIDERUSERContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_JC_PROVIDERUSERContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_JC_PROVIDERUSERContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_JC_PROVIDERUSERContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_JC_PROVIDERUSERContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_JC_PROVIDERUSERContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_JC_PROVIDERUSERContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_JC_PROVIDERUSERContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_JC_PROVIDERUSERContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_JC_PROVIDERUSERContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_JC_PROVIDERUSERContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_JC_PROVIDERUSERContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_JC_PROVIDERUSERContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_JC_PROVIDERUSERContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_JC_PROVIDERUSERContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_JC_PROVIDERUSERContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_JC_PROVIDERUSERContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_JC_PROVIDERUSERContainer.addV2CFunction('AV25DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_JC_PROVIDERUSERContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV25DDO_TitleSettingsIcons); });
   DDO_JC_PROVIDERUSERContainer.addV2CFunction('AV23JC_ProviderUserTitleFilterData', "vJC_PROVIDERUSERTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_JC_PROVIDERUSERContainer.addC2VFunction(function(UC) { UC.ParentObject.AV23JC_ProviderUserTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vJC_PROVIDERUSERTITLEFILTERDATA",UC.ParentObject.AV23JC_ProviderUserTitleFilterData); });
   DDO_JC_PROVIDERUSERContainer.setProp("Visible", "Visible", true, "bool");
   DDO_JC_PROVIDERUSERContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_JC_PROVIDERUSERContainer.addEventHandler("OnOptionClicked", this.e188j2_client);
   this.setUserControl(DDO_JC_PROVIDERUSERContainer);
   this.WORKWITHPLUSUTILITIES1Container = gx.uc.getNew(this, 39, 28, "DVelop_WorkWithPlusUtilities", "WORKWITHPLUSUTILITIES1Container", "Workwithplusutilities1", "WORKWITHPLUSUTILITIES1");
   var WORKWITHPLUSUTILITIES1Container = this.WORKWITHPLUSUTILITIES1Container;
   WORKWITHPLUSUTILITIES1Container.setProp("Class", "Class", "", "char");
   WORKWITHPLUSUTILITIES1Container.setProp("Enabled", "Enabled", true, "boolean");
   WORKWITHPLUSUTILITIES1Container.setProp("Width", "Width", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Height", "Height", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Visible", "Visible", true, "bool");
   WORKWITHPLUSUTILITIES1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(WORKWITHPLUSUTILITIES1Container);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEMAIN",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"GRIDTABLEWITHPAGINATIONBAR",grid:0};
   GXValidFnc[10]={ id: 10, fld:"",grid:0};
   GXValidFnc[11]={ id: 11, fld:"",grid:0};
   GXValidFnc[13]={ id:13 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vSELECT",gxz:"ZV30Select",gxold:"OV30Select",gxvar:"AV30Select",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV30Select=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV30Select=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vSELECT",row || gx.fn.currentGridRowImpl(12),gx.O.AV30Select,gx.O.AV34Select_GXI)},c2v:function(){gx.O.AV34Select_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV30Select=this.val()},val:function(row){return gx.fn.getGridControlValue("vSELECT",row || gx.fn.currentGridRowImpl(12))},val_GXI:function(row){return gx.fn.getGridControlValue("vSELECT_GXI",row || gx.fn.currentGridRowImpl(12))}, gxvar_GXI:'AV34Select_GXI',nac:gx.falseFn,evt:"e228j2_client",std:"ENTER"};
   GXValidFnc[14]={ id:14 ,lvl:2,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"JC_PROVIDERID",gxz:"Z87JC_ProviderID",gxold:"O87JC_ProviderID",gxvar:"A87JC_ProviderID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A87JC_ProviderID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z87JC_ProviderID=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("JC_PROVIDERID",row || gx.fn.currentGridRowImpl(12),gx.O.A87JC_ProviderID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A87JC_ProviderID=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("JC_PROVIDERID",row || gx.fn.currentGridRowImpl(12),',')},nac:gx.falseFn};
   GXValidFnc[15]={ id:15 ,lvl:2,type:"svchar",len:200,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"JC_PROVIDERNAME",gxz:"Z89JC_ProviderName",gxold:"O89JC_ProviderName",gxvar:"A89JC_ProviderName",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A89JC_ProviderName=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z89JC_ProviderName=Value},v2c:function(row){gx.fn.setGridControlValue("JC_PROVIDERNAME",row || gx.fn.currentGridRowImpl(12),gx.O.A89JC_ProviderName,0)},c2v:function(){if(this.val()!==undefined)gx.O.A89JC_ProviderName=this.val()},val:function(row){return gx.fn.getGridControlValue("JC_PROVIDERNAME",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn};
   GXValidFnc[16]={ id:16 ,lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"JC_PROVIDERSHORTNAME",gxz:"Z160JC_ProviderShortName",gxold:"O160JC_ProviderShortName",gxvar:"A160JC_ProviderShortName",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A160JC_ProviderShortName=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z160JC_ProviderShortName=Value},v2c:function(row){gx.fn.setGridControlValue("JC_PROVIDERSHORTNAME",row || gx.fn.currentGridRowImpl(12),gx.O.A160JC_ProviderShortName,0)},c2v:function(){if(this.val()!==undefined)gx.O.A160JC_ProviderShortName=this.val()},val:function(row){return gx.fn.getGridControlValue("JC_PROVIDERSHORTNAME",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn};
   GXValidFnc[17]={ id:17 ,lvl:2,type:"svchar",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"JC_PROVIDERADDRESSS",gxz:"Z161JC_ProviderAddresss",gxold:"O161JC_ProviderAddresss",gxvar:"A161JC_ProviderAddresss",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.A161JC_ProviderAddresss=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z161JC_ProviderAddresss=Value},v2c:function(row){gx.fn.setGridControlValue("JC_PROVIDERADDRESSS",row || gx.fn.currentGridRowImpl(12),gx.O.A161JC_ProviderAddresss,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A161JC_ProviderAddresss=this.val()},val:function(row){return gx.fn.getGridControlValue("JC_PROVIDERADDRESSS",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn,evt:"e238j2_client"};
   GXValidFnc[18]={ id:18 ,lvl:2,type:"char",len:20,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"JC_PROVIDERPHONE",gxz:"Z162JC_ProviderPhone",gxold:"O162JC_ProviderPhone",gxvar:"A162JC_ProviderPhone",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'tel',v2v:function(Value){if(Value!==undefined)gx.O.A162JC_ProviderPhone=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z162JC_ProviderPhone=Value},v2c:function(row){gx.fn.setGridControlValue("JC_PROVIDERPHONE",row || gx.fn.currentGridRowImpl(12),gx.O.A162JC_ProviderPhone,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A162JC_ProviderPhone=this.val()},val:function(row){return gx.fn.getGridControlValue("JC_PROVIDERPHONE",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn};
   GXValidFnc[19]={ id:19 ,lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"JC_PROVIDERUSER",gxz:"Z163JC_ProviderUser",gxold:"O163JC_ProviderUser",gxvar:"A163JC_ProviderUser",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A163JC_ProviderUser=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z163JC_ProviderUser=Value},v2c:function(row){gx.fn.setGridControlValue("JC_PROVIDERUSER",row || gx.fn.currentGridRowImpl(12),gx.O.A163JC_ProviderUser,0)},c2v:function(){if(this.val()!==undefined)gx.O.A163JC_ProviderUser=this.val()},val:function(row){return gx.fn.getGridControlValue("JC_PROVIDERUSER",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn};
   GXValidFnc[20]={ id: 20, fld:"",grid:0};
   GXValidFnc[21]={ id: 21, fld:"",grid:0};
   GXValidFnc[22]={ id: 22, fld:"HTML_GRIDPAGINATIONBAR",grid:0};
   GXValidFnc[24]={ id: 24, fld:"",grid:0};
   GXValidFnc[25]={ id: 25, fld:"",grid:0};
   GXValidFnc[26]={ id: 26, fld:"HTML_BOTTOMAUXILIARCONTROLS",grid:0};
   GXValidFnc[28]={ id:28 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_JC_PROVIDERIDTITLECONTROLIDTOREPLACE",gxz:"ZV14ddo_JC_ProviderIDTitleControlIdToReplace",gxold:"OV14ddo_JC_ProviderIDTitleControlIdToReplace",gxvar:"AV14ddo_JC_ProviderIDTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV14ddo_JC_ProviderIDTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV14ddo_JC_ProviderIDTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_JC_PROVIDERIDTITLECONTROLIDTOREPLACE",gx.O.AV14ddo_JC_ProviderIDTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV14ddo_JC_ProviderIDTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_JC_PROVIDERIDTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[30]={ id:30 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_JC_PROVIDERNAMETITLECONTROLIDTOREPLACE",gxz:"ZV16ddo_JC_ProviderNameTitleControlIdToReplace",gxold:"OV16ddo_JC_ProviderNameTitleControlIdToReplace",gxvar:"AV16ddo_JC_ProviderNameTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV16ddo_JC_ProviderNameTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV16ddo_JC_ProviderNameTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_JC_PROVIDERNAMETITLECONTROLIDTOREPLACE",gx.O.AV16ddo_JC_ProviderNameTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV16ddo_JC_ProviderNameTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_JC_PROVIDERNAMETITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[32]={ id:32 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_JC_PROVIDERSHORTNAMETITLECONTROLIDTOREPLACE",gxz:"ZV18ddo_JC_ProviderShortNameTitleControlIdToReplace",gxold:"OV18ddo_JC_ProviderShortNameTitleControlIdToReplace",gxvar:"AV18ddo_JC_ProviderShortNameTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV18ddo_JC_ProviderShortNameTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV18ddo_JC_ProviderShortNameTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_JC_PROVIDERSHORTNAMETITLECONTROLIDTOREPLACE",gx.O.AV18ddo_JC_ProviderShortNameTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV18ddo_JC_ProviderShortNameTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_JC_PROVIDERSHORTNAMETITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[34]={ id:34 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_JC_PROVIDERADDRESSSTITLECONTROLIDTOREPLACE",gxz:"ZV20ddo_JC_ProviderAddresssTitleControlIdToReplace",gxold:"OV20ddo_JC_ProviderAddresssTitleControlIdToReplace",gxvar:"AV20ddo_JC_ProviderAddresssTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV20ddo_JC_ProviderAddresssTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV20ddo_JC_ProviderAddresssTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_JC_PROVIDERADDRESSSTITLECONTROLIDTOREPLACE",gx.O.AV20ddo_JC_ProviderAddresssTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV20ddo_JC_ProviderAddresssTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_JC_PROVIDERADDRESSSTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[36]={ id:36 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_JC_PROVIDERPHONETITLECONTROLIDTOREPLACE",gxz:"ZV22ddo_JC_ProviderPhoneTitleControlIdToReplace",gxold:"OV22ddo_JC_ProviderPhoneTitleControlIdToReplace",gxvar:"AV22ddo_JC_ProviderPhoneTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV22ddo_JC_ProviderPhoneTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV22ddo_JC_ProviderPhoneTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_JC_PROVIDERPHONETITLECONTROLIDTOREPLACE",gx.O.AV22ddo_JC_ProviderPhoneTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV22ddo_JC_ProviderPhoneTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_JC_PROVIDERPHONETITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[38]={ id:38 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_JC_PROVIDERUSERTITLECONTROLIDTOREPLACE",gxz:"ZV24ddo_JC_ProviderUserTitleControlIdToReplace",gxold:"OV24ddo_JC_ProviderUserTitleControlIdToReplace",gxvar:"AV24ddo_JC_ProviderUserTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV24ddo_JC_ProviderUserTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV24ddo_JC_ProviderUserTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_JC_PROVIDERUSERTITLECONTROLIDTOREPLACE",gx.O.AV24ddo_JC_ProviderUserTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV24ddo_JC_ProviderUserTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_JC_PROVIDERUSERTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[40]={ id:40 ,lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDBY",gxz:"ZV11OrderedBy",gxold:"OV11OrderedBy",gxvar:"AV11OrderedBy",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV11OrderedBy=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV11OrderedBy=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDBY",gx.O.AV11OrderedBy,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV11OrderedBy=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vORDEREDBY",',')},nac:gx.falseFn};
   GXValidFnc[41]={ id:41 ,lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDDSC",gxz:"ZV12OrderedDsc",gxold:"OV12OrderedDsc",gxvar:"AV12OrderedDsc",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV12OrderedDsc=gx.lang.booleanValue(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV12OrderedDsc=gx.lang.booleanValue(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDDSC",gx.O.AV12OrderedDsc,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV12OrderedDsc=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getControlValue("vORDEREDDSC")},nac:gx.falseFn};
   this.ZV30Select = "" ;
   this.OV30Select = "" ;
   this.Z87JC_ProviderID = 0 ;
   this.O87JC_ProviderID = 0 ;
   this.Z89JC_ProviderName = "" ;
   this.O89JC_ProviderName = "" ;
   this.Z160JC_ProviderShortName = "" ;
   this.O160JC_ProviderShortName = "" ;
   this.Z161JC_ProviderAddresss = "" ;
   this.O161JC_ProviderAddresss = "" ;
   this.Z162JC_ProviderPhone = "" ;
   this.O162JC_ProviderPhone = "" ;
   this.Z163JC_ProviderUser = "" ;
   this.O163JC_ProviderUser = "" ;
   this.AV14ddo_JC_ProviderIDTitleControlIdToReplace = "" ;
   this.ZV14ddo_JC_ProviderIDTitleControlIdToReplace = "" ;
   this.OV14ddo_JC_ProviderIDTitleControlIdToReplace = "" ;
   this.AV16ddo_JC_ProviderNameTitleControlIdToReplace = "" ;
   this.ZV16ddo_JC_ProviderNameTitleControlIdToReplace = "" ;
   this.OV16ddo_JC_ProviderNameTitleControlIdToReplace = "" ;
   this.AV18ddo_JC_ProviderShortNameTitleControlIdToReplace = "" ;
   this.ZV18ddo_JC_ProviderShortNameTitleControlIdToReplace = "" ;
   this.OV18ddo_JC_ProviderShortNameTitleControlIdToReplace = "" ;
   this.AV20ddo_JC_ProviderAddresssTitleControlIdToReplace = "" ;
   this.ZV20ddo_JC_ProviderAddresssTitleControlIdToReplace = "" ;
   this.OV20ddo_JC_ProviderAddresssTitleControlIdToReplace = "" ;
   this.AV22ddo_JC_ProviderPhoneTitleControlIdToReplace = "" ;
   this.ZV22ddo_JC_ProviderPhoneTitleControlIdToReplace = "" ;
   this.OV22ddo_JC_ProviderPhoneTitleControlIdToReplace = "" ;
   this.AV24ddo_JC_ProviderUserTitleControlIdToReplace = "" ;
   this.ZV24ddo_JC_ProviderUserTitleControlIdToReplace = "" ;
   this.OV24ddo_JC_ProviderUserTitleControlIdToReplace = "" ;
   this.AV11OrderedBy = 0 ;
   this.ZV11OrderedBy = 0 ;
   this.OV11OrderedBy = 0 ;
   this.AV12OrderedDsc = false ;
   this.ZV12OrderedDsc = false ;
   this.OV12OrderedDsc = false ;
   this.AV27GridCurrentPage = 0 ;
   this.AV25DDO_TitleSettingsIcons = {Default:"",Default_GXI:"",Filtered:"",Filtered_GXI:"",SortedASC:"",SortedASC_GXI:"",SortedDSC:"",SortedDSC_GXI:"",FilteredSortedASC:"",FilteredSortedASC_GXI:"",FilteredSortedDSC:"",FilteredSortedDSC_GXI:"",OptionSortASC:"",OptionSortASC_GXI:"",OptionSortDSC:"",OptionSortDSC_GXI:"",OptionApplyFilter:"",OptionApplyFilter_GXI:"",OptionFilteringData:"",OptionFilteringData_GXI:"",OptionCleanFilters:"",OptionCleanFilters_GXI:"",SelectedOption:"",SelectedOption_GXI:"",MultiselOption:"",MultiselOption_GXI:"",MultiselSelOption:"",MultiselSelOption_GXI:""} ;
   this.AV14ddo_JC_ProviderIDTitleControlIdToReplace = "" ;
   this.AV16ddo_JC_ProviderNameTitleControlIdToReplace = "" ;
   this.AV18ddo_JC_ProviderShortNameTitleControlIdToReplace = "" ;
   this.AV20ddo_JC_ProviderAddresssTitleControlIdToReplace = "" ;
   this.AV22ddo_JC_ProviderPhoneTitleControlIdToReplace = "" ;
   this.AV24ddo_JC_ProviderUserTitleControlIdToReplace = "" ;
   this.AV11OrderedBy = 0 ;
   this.AV12OrderedDsc = false ;
   this.AV8InOutJC_ProviderID = 0 ;
   this.AV9InOutJC_ProviderName = "" ;
   this.AV30Select = "" ;
   this.A87JC_ProviderID = 0 ;
   this.A89JC_ProviderName = "" ;
   this.A160JC_ProviderShortName = "" ;
   this.A161JC_ProviderAddresss = "" ;
   this.A162JC_ProviderPhone = "" ;
   this.A163JC_ProviderUser = "" ;
   this.Events = {"e118j2_client": ["GRIDPAGINATIONBAR.CHANGEPAGE", true] ,"e128j2_client": ["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", true] ,"e138j2_client": ["DDO_JC_PROVIDERID.ONOPTIONCLICKED", true] ,"e148j2_client": ["DDO_JC_PROVIDERNAME.ONOPTIONCLICKED", true] ,"e158j2_client": ["DDO_JC_PROVIDERSHORTNAME.ONOPTIONCLICKED", true] ,"e168j2_client": ["DDO_JC_PROVIDERADDRESSS.ONOPTIONCLICKED", true] ,"e178j2_client": ["DDO_JC_PROVIDERPHONE.ONOPTIONCLICKED", true] ,"e188j2_client": ["DDO_JC_PROVIDERUSER.ONOPTIONCLICKED", true] ,"e228j2_client": ["ENTER", true] ,"e248j2_client": ["CANCEL", true] ,"e238j2_client": ["JC_PROVIDERADDRESSS.CLICK", false]};
   this.EvtParms["REFRESH"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_JC_ProviderIDTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_JC_ProviderNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_JC_ProviderShortNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERSHORTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_JC_ProviderAddresssTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERADDRESSSTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_JC_ProviderPhoneTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERPHONETITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_JC_ProviderUserTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERUSERTITLECONTROLIDTOREPLACE',pic:''},{ctrl:'GRID',prop:'Rows'}],[{av:'AV13JC_ProviderIDTitleFilterData',fld:'vJC_PROVIDERIDTITLEFILTERDATA',pic:''},{av:'AV15JC_ProviderNameTitleFilterData',fld:'vJC_PROVIDERNAMETITLEFILTERDATA',pic:''},{av:'AV17JC_ProviderShortNameTitleFilterData',fld:'vJC_PROVIDERSHORTNAMETITLEFILTERDATA',pic:''},{av:'AV19JC_ProviderAddresssTitleFilterData',fld:'vJC_PROVIDERADDRESSSTITLEFILTERDATA',pic:''},{av:'AV21JC_ProviderPhoneTitleFilterData',fld:'vJC_PROVIDERPHONETITLEFILTERDATA',pic:''},{av:'AV23JC_ProviderUserTitleFilterData',fld:'vJC_PROVIDERUSERTITLEFILTERDATA',pic:''},{ctrl:'JC_PROVIDERID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERID","Title")',ctrl:'JC_PROVIDERID',prop:'Title'},{ctrl:'JC_PROVIDERNAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERNAME","Title")',ctrl:'JC_PROVIDERNAME',prop:'Title'},{ctrl:'JC_PROVIDERSHORTNAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERSHORTNAME","Title")',ctrl:'JC_PROVIDERSHORTNAME',prop:'Title'},{ctrl:'JC_PROVIDERADDRESSS',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERADDRESSS","Title")',ctrl:'JC_PROVIDERADDRESSS',prop:'Title'},{ctrl:'JC_PROVIDERPHONE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERPHONE","Title")',ctrl:'JC_PROVIDERPHONE',prop:'Title'},{ctrl:'JC_PROVIDERUSER',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERUSER","Title")',ctrl:'JC_PROVIDERUSER',prop:'Title'},{av:'AV27GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV28GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV29GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["START"] = [[{av:'AV33Pgmname',fld:'vPGMNAME',pic:''},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'}],[{av:'gx.fn.getCtrlProperty("TABLEMAIN","Height")',ctrl:'TABLEMAIN',prop:'Height'},{ctrl:'GRID',prop:'Rows'},{av:'this.DDO_JC_PROVIDERIDContainer.TitleControlIdToReplace',ctrl:'DDO_JC_PROVIDERID',prop:'TitleControlIdToReplace'},{av:'AV14ddo_JC_ProviderIDTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERIDTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_JC_PROVIDERIDTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_JC_PROVIDERIDTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_JC_PROVIDERNAMEContainer.TitleControlIdToReplace',ctrl:'DDO_JC_PROVIDERNAME',prop:'TitleControlIdToReplace'},{av:'AV16ddo_JC_ProviderNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_JC_PROVIDERNAMETITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_JC_PROVIDERNAMETITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_JC_PROVIDERSHORTNAMEContainer.TitleControlIdToReplace',ctrl:'DDO_JC_PROVIDERSHORTNAME',prop:'TitleControlIdToReplace'},{av:'AV18ddo_JC_ProviderShortNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERSHORTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_JC_PROVIDERSHORTNAMETITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_JC_PROVIDERSHORTNAMETITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_JC_PROVIDERADDRESSSContainer.TitleControlIdToReplace',ctrl:'DDO_JC_PROVIDERADDRESSS',prop:'TitleControlIdToReplace'},{av:'AV20ddo_JC_ProviderAddresssTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERADDRESSSTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_JC_PROVIDERADDRESSSTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_JC_PROVIDERADDRESSSTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_JC_PROVIDERPHONEContainer.TitleControlIdToReplace',ctrl:'DDO_JC_PROVIDERPHONE',prop:'TitleControlIdToReplace'},{av:'AV22ddo_JC_ProviderPhoneTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERPHONETITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_JC_PROVIDERPHONETITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_JC_PROVIDERPHONETITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_JC_PROVIDERUSERContainer.TitleControlIdToReplace',ctrl:'DDO_JC_PROVIDERUSER',prop:'TitleControlIdToReplace'},{av:'AV24ddo_JC_ProviderUserTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERUSERTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_JC_PROVIDERUSERTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_JC_PROVIDERUSERTITLECONTROLIDTOREPLACE',prop:'Visible'},{ctrl:'FORM',prop:'Caption'},{av:'gx.fn.getCtrlProperty("vORDEREDBY","Visible")',ctrl:'vORDEREDBY',prop:'Visible'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'gx.fn.getCtrlProperty("vORDEREDDSC","Visible")',ctrl:'vORDEREDDSC',prop:'Visible'},{av:'AV25DDO_TitleSettingsIcons',fld:'vDDO_TITLESETTINGSICONS',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}]];
   this.EvtParms["JC_PROVIDERADDRESSS.CLICK"] = [[{av:'A161JC_ProviderAddresss',fld:'JC_PROVIDERADDRESSS',pic:'',hsh:true}],[]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_JC_ProviderIDTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_JC_ProviderNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_JC_ProviderShortNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERSHORTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_JC_ProviderAddresssTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERADDRESSSTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_JC_ProviderPhoneTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERPHONETITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_JC_ProviderUserTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERUSERTITLECONTROLIDTOREPLACE',pic:''},{av:'this.GRIDPAGINATIONBARContainer.SelectedPage',ctrl:'GRIDPAGINATIONBAR',prop:'SelectedPage'}],[]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_JC_ProviderIDTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_JC_ProviderNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_JC_ProviderShortNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERSHORTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_JC_ProviderAddresssTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERADDRESSSTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_JC_ProviderPhoneTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERPHONETITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_JC_ProviderUserTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERUSERTITLECONTROLIDTOREPLACE',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}],[{ctrl:'GRID',prop:'Rows'}]];
   this.EvtParms["DDO_JC_PROVIDERID.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_JC_ProviderIDTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_JC_ProviderNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_JC_ProviderShortNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERSHORTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_JC_ProviderAddresssTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERADDRESSSTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_JC_ProviderPhoneTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERPHONETITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_JC_ProviderUserTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERUSERTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_JC_PROVIDERIDContainer.ActiveEventKey',ctrl:'DDO_JC_PROVIDERID',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_JC_PROVIDERIDContainer.SortedStatus',ctrl:'DDO_JC_PROVIDERID',prop:'SortedStatus'},{av:'AV13JC_ProviderIDTitleFilterData',fld:'vJC_PROVIDERIDTITLEFILTERDATA',pic:''},{av:'AV15JC_ProviderNameTitleFilterData',fld:'vJC_PROVIDERNAMETITLEFILTERDATA',pic:''},{av:'AV17JC_ProviderShortNameTitleFilterData',fld:'vJC_PROVIDERSHORTNAMETITLEFILTERDATA',pic:''},{av:'AV19JC_ProviderAddresssTitleFilterData',fld:'vJC_PROVIDERADDRESSSTITLEFILTERDATA',pic:''},{av:'AV21JC_ProviderPhoneTitleFilterData',fld:'vJC_PROVIDERPHONETITLEFILTERDATA',pic:''},{av:'AV23JC_ProviderUserTitleFilterData',fld:'vJC_PROVIDERUSERTITLEFILTERDATA',pic:''},{ctrl:'JC_PROVIDERID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERID","Title")',ctrl:'JC_PROVIDERID',prop:'Title'},{ctrl:'JC_PROVIDERNAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERNAME","Title")',ctrl:'JC_PROVIDERNAME',prop:'Title'},{ctrl:'JC_PROVIDERSHORTNAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERSHORTNAME","Title")',ctrl:'JC_PROVIDERSHORTNAME',prop:'Title'},{ctrl:'JC_PROVIDERADDRESSS',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERADDRESSS","Title")',ctrl:'JC_PROVIDERADDRESSS',prop:'Title'},{ctrl:'JC_PROVIDERPHONE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERPHONE","Title")',ctrl:'JC_PROVIDERPHONE',prop:'Title'},{ctrl:'JC_PROVIDERUSER',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERUSER","Title")',ctrl:'JC_PROVIDERUSER',prop:'Title'},{av:'AV27GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV28GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV29GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_JC_PROVIDERNAME.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_JC_ProviderIDTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_JC_ProviderNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_JC_ProviderShortNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERSHORTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_JC_ProviderAddresssTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERADDRESSSTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_JC_ProviderPhoneTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERPHONETITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_JC_ProviderUserTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERUSERTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_JC_PROVIDERNAMEContainer.ActiveEventKey',ctrl:'DDO_JC_PROVIDERNAME',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_JC_PROVIDERNAMEContainer.SortedStatus',ctrl:'DDO_JC_PROVIDERNAME',prop:'SortedStatus'},{av:'AV13JC_ProviderIDTitleFilterData',fld:'vJC_PROVIDERIDTITLEFILTERDATA',pic:''},{av:'AV15JC_ProviderNameTitleFilterData',fld:'vJC_PROVIDERNAMETITLEFILTERDATA',pic:''},{av:'AV17JC_ProviderShortNameTitleFilterData',fld:'vJC_PROVIDERSHORTNAMETITLEFILTERDATA',pic:''},{av:'AV19JC_ProviderAddresssTitleFilterData',fld:'vJC_PROVIDERADDRESSSTITLEFILTERDATA',pic:''},{av:'AV21JC_ProviderPhoneTitleFilterData',fld:'vJC_PROVIDERPHONETITLEFILTERDATA',pic:''},{av:'AV23JC_ProviderUserTitleFilterData',fld:'vJC_PROVIDERUSERTITLEFILTERDATA',pic:''},{ctrl:'JC_PROVIDERID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERID","Title")',ctrl:'JC_PROVIDERID',prop:'Title'},{ctrl:'JC_PROVIDERNAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERNAME","Title")',ctrl:'JC_PROVIDERNAME',prop:'Title'},{ctrl:'JC_PROVIDERSHORTNAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERSHORTNAME","Title")',ctrl:'JC_PROVIDERSHORTNAME',prop:'Title'},{ctrl:'JC_PROVIDERADDRESSS',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERADDRESSS","Title")',ctrl:'JC_PROVIDERADDRESSS',prop:'Title'},{ctrl:'JC_PROVIDERPHONE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERPHONE","Title")',ctrl:'JC_PROVIDERPHONE',prop:'Title'},{ctrl:'JC_PROVIDERUSER',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERUSER","Title")',ctrl:'JC_PROVIDERUSER',prop:'Title'},{av:'AV27GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV28GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV29GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_JC_PROVIDERSHORTNAME.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_JC_ProviderIDTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_JC_ProviderNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_JC_ProviderShortNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERSHORTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_JC_ProviderAddresssTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERADDRESSSTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_JC_ProviderPhoneTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERPHONETITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_JC_ProviderUserTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERUSERTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_JC_PROVIDERSHORTNAMEContainer.ActiveEventKey',ctrl:'DDO_JC_PROVIDERSHORTNAME',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_JC_PROVIDERSHORTNAMEContainer.SortedStatus',ctrl:'DDO_JC_PROVIDERSHORTNAME',prop:'SortedStatus'},{av:'AV13JC_ProviderIDTitleFilterData',fld:'vJC_PROVIDERIDTITLEFILTERDATA',pic:''},{av:'AV15JC_ProviderNameTitleFilterData',fld:'vJC_PROVIDERNAMETITLEFILTERDATA',pic:''},{av:'AV17JC_ProviderShortNameTitleFilterData',fld:'vJC_PROVIDERSHORTNAMETITLEFILTERDATA',pic:''},{av:'AV19JC_ProviderAddresssTitleFilterData',fld:'vJC_PROVIDERADDRESSSTITLEFILTERDATA',pic:''},{av:'AV21JC_ProviderPhoneTitleFilterData',fld:'vJC_PROVIDERPHONETITLEFILTERDATA',pic:''},{av:'AV23JC_ProviderUserTitleFilterData',fld:'vJC_PROVIDERUSERTITLEFILTERDATA',pic:''},{ctrl:'JC_PROVIDERID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERID","Title")',ctrl:'JC_PROVIDERID',prop:'Title'},{ctrl:'JC_PROVIDERNAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERNAME","Title")',ctrl:'JC_PROVIDERNAME',prop:'Title'},{ctrl:'JC_PROVIDERSHORTNAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERSHORTNAME","Title")',ctrl:'JC_PROVIDERSHORTNAME',prop:'Title'},{ctrl:'JC_PROVIDERADDRESSS',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERADDRESSS","Title")',ctrl:'JC_PROVIDERADDRESSS',prop:'Title'},{ctrl:'JC_PROVIDERPHONE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERPHONE","Title")',ctrl:'JC_PROVIDERPHONE',prop:'Title'},{ctrl:'JC_PROVIDERUSER',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERUSER","Title")',ctrl:'JC_PROVIDERUSER',prop:'Title'},{av:'AV27GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV28GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV29GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_JC_PROVIDERADDRESSS.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_JC_ProviderIDTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_JC_ProviderNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_JC_ProviderShortNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERSHORTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_JC_ProviderAddresssTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERADDRESSSTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_JC_ProviderPhoneTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERPHONETITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_JC_ProviderUserTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERUSERTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_JC_PROVIDERADDRESSSContainer.ActiveEventKey',ctrl:'DDO_JC_PROVIDERADDRESSS',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_JC_PROVIDERADDRESSSContainer.SortedStatus',ctrl:'DDO_JC_PROVIDERADDRESSS',prop:'SortedStatus'},{av:'AV13JC_ProviderIDTitleFilterData',fld:'vJC_PROVIDERIDTITLEFILTERDATA',pic:''},{av:'AV15JC_ProviderNameTitleFilterData',fld:'vJC_PROVIDERNAMETITLEFILTERDATA',pic:''},{av:'AV17JC_ProviderShortNameTitleFilterData',fld:'vJC_PROVIDERSHORTNAMETITLEFILTERDATA',pic:''},{av:'AV19JC_ProviderAddresssTitleFilterData',fld:'vJC_PROVIDERADDRESSSTITLEFILTERDATA',pic:''},{av:'AV21JC_ProviderPhoneTitleFilterData',fld:'vJC_PROVIDERPHONETITLEFILTERDATA',pic:''},{av:'AV23JC_ProviderUserTitleFilterData',fld:'vJC_PROVIDERUSERTITLEFILTERDATA',pic:''},{ctrl:'JC_PROVIDERID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERID","Title")',ctrl:'JC_PROVIDERID',prop:'Title'},{ctrl:'JC_PROVIDERNAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERNAME","Title")',ctrl:'JC_PROVIDERNAME',prop:'Title'},{ctrl:'JC_PROVIDERSHORTNAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERSHORTNAME","Title")',ctrl:'JC_PROVIDERSHORTNAME',prop:'Title'},{ctrl:'JC_PROVIDERADDRESSS',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERADDRESSS","Title")',ctrl:'JC_PROVIDERADDRESSS',prop:'Title'},{ctrl:'JC_PROVIDERPHONE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERPHONE","Title")',ctrl:'JC_PROVIDERPHONE',prop:'Title'},{ctrl:'JC_PROVIDERUSER',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERUSER","Title")',ctrl:'JC_PROVIDERUSER',prop:'Title'},{av:'AV27GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV28GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV29GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_JC_PROVIDERPHONE.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_JC_ProviderIDTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_JC_ProviderNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_JC_ProviderShortNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERSHORTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_JC_ProviderAddresssTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERADDRESSSTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_JC_ProviderPhoneTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERPHONETITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_JC_ProviderUserTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERUSERTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_JC_PROVIDERPHONEContainer.ActiveEventKey',ctrl:'DDO_JC_PROVIDERPHONE',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_JC_PROVIDERPHONEContainer.SortedStatus',ctrl:'DDO_JC_PROVIDERPHONE',prop:'SortedStatus'},{av:'AV13JC_ProviderIDTitleFilterData',fld:'vJC_PROVIDERIDTITLEFILTERDATA',pic:''},{av:'AV15JC_ProviderNameTitleFilterData',fld:'vJC_PROVIDERNAMETITLEFILTERDATA',pic:''},{av:'AV17JC_ProviderShortNameTitleFilterData',fld:'vJC_PROVIDERSHORTNAMETITLEFILTERDATA',pic:''},{av:'AV19JC_ProviderAddresssTitleFilterData',fld:'vJC_PROVIDERADDRESSSTITLEFILTERDATA',pic:''},{av:'AV21JC_ProviderPhoneTitleFilterData',fld:'vJC_PROVIDERPHONETITLEFILTERDATA',pic:''},{av:'AV23JC_ProviderUserTitleFilterData',fld:'vJC_PROVIDERUSERTITLEFILTERDATA',pic:''},{ctrl:'JC_PROVIDERID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERID","Title")',ctrl:'JC_PROVIDERID',prop:'Title'},{ctrl:'JC_PROVIDERNAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERNAME","Title")',ctrl:'JC_PROVIDERNAME',prop:'Title'},{ctrl:'JC_PROVIDERSHORTNAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERSHORTNAME","Title")',ctrl:'JC_PROVIDERSHORTNAME',prop:'Title'},{ctrl:'JC_PROVIDERADDRESSS',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERADDRESSS","Title")',ctrl:'JC_PROVIDERADDRESSS',prop:'Title'},{ctrl:'JC_PROVIDERPHONE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERPHONE","Title")',ctrl:'JC_PROVIDERPHONE',prop:'Title'},{ctrl:'JC_PROVIDERUSER',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERUSER","Title")',ctrl:'JC_PROVIDERUSER',prop:'Title'},{av:'AV27GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV28GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV29GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_JC_PROVIDERUSER.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_JC_ProviderIDTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_JC_ProviderNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_JC_ProviderShortNameTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERSHORTNAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_JC_ProviderAddresssTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERADDRESSSTITLECONTROLIDTOREPLACE',pic:''},{av:'AV22ddo_JC_ProviderPhoneTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERPHONETITLECONTROLIDTOREPLACE',pic:''},{av:'AV24ddo_JC_ProviderUserTitleControlIdToReplace',fld:'vDDO_JC_PROVIDERUSERTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_JC_PROVIDERUSERContainer.ActiveEventKey',ctrl:'DDO_JC_PROVIDERUSER',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_JC_PROVIDERUSERContainer.SortedStatus',ctrl:'DDO_JC_PROVIDERUSER',prop:'SortedStatus'},{av:'AV13JC_ProviderIDTitleFilterData',fld:'vJC_PROVIDERIDTITLEFILTERDATA',pic:''},{av:'AV15JC_ProviderNameTitleFilterData',fld:'vJC_PROVIDERNAMETITLEFILTERDATA',pic:''},{av:'AV17JC_ProviderShortNameTitleFilterData',fld:'vJC_PROVIDERSHORTNAMETITLEFILTERDATA',pic:''},{av:'AV19JC_ProviderAddresssTitleFilterData',fld:'vJC_PROVIDERADDRESSSTITLEFILTERDATA',pic:''},{av:'AV21JC_ProviderPhoneTitleFilterData',fld:'vJC_PROVIDERPHONETITLEFILTERDATA',pic:''},{av:'AV23JC_ProviderUserTitleFilterData',fld:'vJC_PROVIDERUSERTITLEFILTERDATA',pic:''},{ctrl:'JC_PROVIDERID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERID","Title")',ctrl:'JC_PROVIDERID',prop:'Title'},{ctrl:'JC_PROVIDERNAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERNAME","Title")',ctrl:'JC_PROVIDERNAME',prop:'Title'},{ctrl:'JC_PROVIDERSHORTNAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERSHORTNAME","Title")',ctrl:'JC_PROVIDERSHORTNAME',prop:'Title'},{ctrl:'JC_PROVIDERADDRESSS',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("JC_PROVIDERADDRESSS","Title")',ctrl:'JC_PROVIDERADDRESSS',prop:'Title'},{ctrl:'JC_PROVIDERPHONE',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERPHONE","Title")',ctrl:'JC_PROVIDERPHONE',prop:'Title'},{ctrl:'JC_PROVIDERUSER',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("JC_PROVIDERUSER","Title")',ctrl:'JC_PROVIDERUSER',prop:'Title'},{av:'AV27GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV28GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV29GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["GRID.LOAD"] = [[],[{av:'AV30Select',fld:'vSELECT',pic:''},{av:'gx.fn.getCtrlProperty("vSELECT","Tooltiptext")',ctrl:'vSELECT',prop:'Tooltiptext'}]];
   this.EvtParms["ENTER"] = [[{av:'A87JC_ProviderID',fld:'JC_PROVIDERID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true},{av:'A89JC_ProviderName',fld:'JC_PROVIDERNAME',pic:'',hsh:true}],[{av:'AV8InOutJC_ProviderID',fld:'vINOUTJC_PROVIDERID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV9InOutJC_ProviderName',fld:'vINOUTJC_PROVIDERNAME',pic:''}]];
   this.EnterCtrl = ["vSELECT"];
   this.setVCMap("AV8InOutJC_ProviderID", "vINOUTJC_PROVIDERID", 0, "int", 18, 0);
   this.setVCMap("AV9InOutJC_ProviderName", "vINOUTJC_PROVIDERNAME", 0, "svchar", 200, 0);
   GridContainer.addRefreshingVar(this.GXValidFnc[40]);
   GridContainer.addRefreshingVar(this.GXValidFnc[41]);
   GridContainer.addRefreshingVar(this.GXValidFnc[28]);
   GridContainer.addRefreshingVar(this.GXValidFnc[30]);
   GridContainer.addRefreshingVar(this.GXValidFnc[32]);
   GridContainer.addRefreshingVar(this.GXValidFnc[34]);
   GridContainer.addRefreshingVar(this.GXValidFnc[36]);
   GridContainer.addRefreshingVar(this.GXValidFnc[38]);
   this.Initialize( );
});
gx.createParentObj(jc_providerprompt);
