/*!   GeneXus C# 16_0_0-127771 on 2/27/2020 11:59:2.89
*/
gx.evt.autoSkip = false;
gx.define('xt_definecodeprompt', false, function () {
   this.ServerClass =  "xt_definecodeprompt" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.hasEnterEvent = true;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV8InOutXT_DefineCodeID=gx.fn.getIntegerValue("vINOUTXT_DEFINECODEID",',') ;
      this.AV9InOutXT_DefineCodeName=gx.fn.getControlValue("vINOUTXT_DEFINECODENAME") ;
   };
   this.Valid_Xt_defindcodetypeid=function()
   {
      try {
         if(  gx.fn.currentGridRowImpl(12) ===0) {
            return true;
         }
         var gxballoon = gx.util.balloon.getNew("XT_DEFINDCODETYPEID", gx.fn.currentGridRowImpl(12));
         this.AnyError  = 0;

      }
      catch(e){}
      try {
         if (gxballoon == null) return true; return gxballoon.show();
      }
      catch(e){}
      return true ;
   }
   this.e112h2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEPAGE", false, null, true, true);
   };
   this.e122h2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", false, null, true, true);
   };
   this.e132h2_client=function()
   {
      return this.executeServerEvent("DDO_XT_DEFINECODEID.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e142h2_client=function()
   {
      return this.executeServerEvent("DDO_XT_DEFINECODENAME.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e152h2_client=function()
   {
      return this.executeServerEvent("DDO_XT_DEFINDCODETYPEID.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e162h2_client=function()
   {
      return this.executeServerEvent("DDO_XT_DEFINDCODETYPENAME.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e172h2_client=function()
   {
      return this.executeServerEvent("DDO_XT_DEFINECODEORDER.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e212h2_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e222h2_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,23,24,25,27,29,31,33,35,37,38];
   this.GXLastCtrlId =38;
   this.GridContainer = new gx.grid.grid(this, 2,"WbpLvl2",12,"Grid","Grid","GridContainer",this.CmpContext,this.IsMasterPage,"xt_definecodeprompt",[],false,1,false,true,0,false,false,false,"",0,"px",0,"px","澧炲姞绌虹櫧琛?,true,false,false,null,null,false,"",false,[1,1,1,1],false,0,true,false);
   var GridContainer = this.GridContainer;
   GridContainer.addBitmap("&Select","vSELECT",13,0,"px",17,"px","e212h2_client","","","SelectAttribute ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addSingleLineEdit(167,14,"XT_DEFINECODEID","","","XT_DefineCodeID","int",0,"px",18,18,"right",null,[],167,"XT_DefineCodeID",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(168,15,"XT_DEFINECODENAME","","","XT_DefineCodeName","svchar",0,"px",100,80,"left",null,[],168,"XT_DefineCodeName",true,0,false,false,"Attribute",1,"WWColumn");
   GridContainer.addSingleLineEdit(165,16,"XT_DEFINDCODETYPEID","","","XT_DefindcodeTypeID","int",0,"px",18,18,"right",null,[],165,"XT_DefindcodeTypeID",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(166,17,"XT_DEFINDCODETYPENAME","","","XT_DefindcodeTypeName","svchar",0,"px",40,40,"left",null,[],166,"XT_DefindcodeTypeName",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(171,18,"XT_DEFINECODEORDER","","","XT_DefineCodeOrder","int",0,"px",4,4,"right",null,[],171,"XT_DefineCodeOrder",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   this.GridContainer.emptyText = "";
   this.setGrid(GridContainer);
   this.GRIDPAGINATIONBARContainer = gx.uc.getNew(this, 22, 13, "DVelop_DVPaginationBar", "GRIDPAGINATIONBARContainer", "Gridpaginationbar", "GRIDPAGINATIONBAR");
   var GRIDPAGINATIONBARContainer = this.GRIDPAGINATIONBARContainer;
   GRIDPAGINATIONBARContainer.setProp("Enabled", "Enabled", true, "boolean");
   GRIDPAGINATIONBARContainer.setProp("Class", "Class", "PaginationBar", "str");
   GRIDPAGINATIONBARContainer.setProp("ShowFirst", "Showfirst", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowPrevious", "Showprevious", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowNext", "Shownext", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowLast", "Showlast", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("PagesToShow", "Pagestoshow", 5, "num");
   GRIDPAGINATIONBARContainer.setProp("PagingButtonsPosition", "Pagingbuttonsposition", "Right", "str");
   GRIDPAGINATIONBARContainer.setProp("PagingCaptionPosition", "Pagingcaptionposition", "Left", "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridClass", "Emptygridclass", "PaginationBarEmptyGrid", "str");
   GRIDPAGINATIONBARContainer.setProp("SelectedPage", "Selectedpage", "", "char");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageSelector", "Rowsperpageselector", true, "bool");
   GRIDPAGINATIONBARContainer.setDynProp("RowsPerPageSelectedValue", "Rowsperpageselectedvalue", 10, "num");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageOptions", "Rowsperpageoptions", "5:WWP_Rows5,10:WWP_Rows10,20:WWP_Rows20,50:WWP_Rows50", "str");
   GRIDPAGINATIONBARContainer.setProp("First", "First", "First", "str");
   GRIDPAGINATIONBARContainer.setProp("Previous", "Previous", "WWP_PagingPreviousCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Next", "Next", "WWP_PagingNextCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Last", "Last", "Last", "str");
   GRIDPAGINATIONBARContainer.setProp("Caption", "Caption", "<CURRENT_PAGE>椤?<TOTAL_PAGES>椤?璁板綍锛?TOTAL_RECORDS>鏉?, "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridCaption", "Emptygridcaption", "WWP_PagingEmptyGridCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageCaption", "Rowsperpagecaption", "WWP_PagingRowsPerPage", "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV23GridCurrentPage', "vGRIDCURRENTPAGE", 'SetCurrentPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV23GridCurrentPage=UC.GetCurrentPage();gx.fn.setControlValue("vGRIDCURRENTPAGE",UC.ParentObject.AV23GridCurrentPage); });
   GRIDPAGINATIONBARContainer.setProp("PageCount", "Pagecount", '', "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV25GridRecordCount', "vGRIDRECORDCOUNT", 'SetRecordCount');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV25GridRecordCount=UC.GetRecordCount();gx.fn.setControlValue("vGRIDRECORDCOUNT",UC.ParentObject.AV25GridRecordCount); });
   GRIDPAGINATIONBARContainer.addV2CFunction('AV24GridPageSize', "vGRIDPAGESIZE", 'SetPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV24GridPageSize=UC.GetPage();gx.fn.setControlValue("vGRIDPAGESIZE",UC.ParentObject.AV24GridPageSize); });
   GRIDPAGINATIONBARContainer.setProp("Visible", "Visible", true, "bool");
   GRIDPAGINATIONBARContainer.setC2ShowFunction(function(UC) { UC.show(); });
   GRIDPAGINATIONBARContainer.addEventHandler("ChangePage", this.e112h2_client);
   GRIDPAGINATIONBARContainer.addEventHandler("ChangeRowsPerPage", this.e122h2_client);
   this.setUserControl(GRIDPAGINATIONBARContainer);
   this.DDO_XT_DEFINECODEIDContainer = gx.uc.getNew(this, 26, 13, "BootstrapDropDownOptions", "DDO_XT_DEFINECODEIDContainer", "Ddo_xt_definecodeid", "DDO_XT_DEFINECODEID");
   var DDO_XT_DEFINECODEIDContainer = this.DDO_XT_DEFINECODEIDContainer;
   DDO_XT_DEFINECODEIDContainer.setProp("Class", "Class", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_XT_DEFINECODEIDContainer.setProp("Icon", "Icon", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("Caption", "Caption", "", "str");
   DDO_XT_DEFINECODEIDContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_XT_DEFINECODEIDContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_XT_DEFINECODEIDContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_XT_DEFINECODEIDContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_XT_DEFINECODEIDContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_XT_DEFINECODEIDContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_XT_DEFINECODEIDContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_XT_DEFINECODEIDContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_XT_DEFINECODEIDContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_XT_DEFINECODEIDContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_XT_DEFINECODEIDContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_XT_DEFINECODEIDContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_XT_DEFINECODEIDContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_XT_DEFINECODEIDContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_XT_DEFINECODEIDContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_XT_DEFINECODEIDContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_XT_DEFINECODEIDContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_XT_DEFINECODEIDContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_XT_DEFINECODEIDContainer.addV2CFunction('AV21DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_XT_DEFINECODEIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV21DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV21DDO_TitleSettingsIcons); });
   DDO_XT_DEFINECODEIDContainer.addV2CFunction('AV13XT_DefineCodeIDTitleFilterData', "vXT_DEFINECODEIDTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_XT_DEFINECODEIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV13XT_DefineCodeIDTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vXT_DEFINECODEIDTITLEFILTERDATA",UC.ParentObject.AV13XT_DefineCodeIDTitleFilterData); });
   DDO_XT_DEFINECODEIDContainer.setProp("Visible", "Visible", true, "bool");
   DDO_XT_DEFINECODEIDContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_XT_DEFINECODEIDContainer.addEventHandler("OnOptionClicked", this.e132h2_client);
   this.setUserControl(DDO_XT_DEFINECODEIDContainer);
   this.DDO_XT_DEFINECODENAMEContainer = gx.uc.getNew(this, 28, 27, "BootstrapDropDownOptions", "DDO_XT_DEFINECODENAMEContainer", "Ddo_xt_definecodename", "DDO_XT_DEFINECODENAME");
   var DDO_XT_DEFINECODENAMEContainer = this.DDO_XT_DEFINECODENAMEContainer;
   DDO_XT_DEFINECODENAMEContainer.setProp("Class", "Class", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_XT_DEFINECODENAMEContainer.setProp("Icon", "Icon", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("Caption", "Caption", "", "str");
   DDO_XT_DEFINECODENAMEContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_XT_DEFINECODENAMEContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_XT_DEFINECODENAMEContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_XT_DEFINECODENAMEContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_XT_DEFINECODENAMEContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_XT_DEFINECODENAMEContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_XT_DEFINECODENAMEContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_XT_DEFINECODENAMEContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_XT_DEFINECODENAMEContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_XT_DEFINECODENAMEContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_XT_DEFINECODENAMEContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_XT_DEFINECODENAMEContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_XT_DEFINECODENAMEContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_XT_DEFINECODENAMEContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_XT_DEFINECODENAMEContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_XT_DEFINECODENAMEContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_XT_DEFINECODENAMEContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_XT_DEFINECODENAMEContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_XT_DEFINECODENAMEContainer.addV2CFunction('AV21DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_XT_DEFINECODENAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV21DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV21DDO_TitleSettingsIcons); });
   DDO_XT_DEFINECODENAMEContainer.addV2CFunction('AV15XT_DefineCodeNameTitleFilterData', "vXT_DEFINECODENAMETITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_XT_DEFINECODENAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV15XT_DefineCodeNameTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vXT_DEFINECODENAMETITLEFILTERDATA",UC.ParentObject.AV15XT_DefineCodeNameTitleFilterData); });
   DDO_XT_DEFINECODENAMEContainer.setProp("Visible", "Visible", true, "bool");
   DDO_XT_DEFINECODENAMEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_XT_DEFINECODENAMEContainer.addEventHandler("OnOptionClicked", this.e142h2_client);
   this.setUserControl(DDO_XT_DEFINECODENAMEContainer);
   this.DDO_XT_DEFINDCODETYPEIDContainer = gx.uc.getNew(this, 30, 27, "BootstrapDropDownOptions", "DDO_XT_DEFINDCODETYPEIDContainer", "Ddo_xt_defindcodetypeid", "DDO_XT_DEFINDCODETYPEID");
   var DDO_XT_DEFINDCODETYPEIDContainer = this.DDO_XT_DEFINDCODETYPEIDContainer;
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("Class", "Class", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("Icon", "Icon", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("Caption", "Caption", "", "str");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_XT_DEFINDCODETYPEIDContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_XT_DEFINDCODETYPEIDContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_XT_DEFINDCODETYPEIDContainer.addV2CFunction('AV21DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_XT_DEFINDCODETYPEIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV21DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV21DDO_TitleSettingsIcons); });
   DDO_XT_DEFINDCODETYPEIDContainer.addV2CFunction('AV17XT_DefindcodeTypeIDTitleFilterData', "vXT_DEFINDCODETYPEIDTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_XT_DEFINDCODETYPEIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV17XT_DefindcodeTypeIDTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vXT_DEFINDCODETYPEIDTITLEFILTERDATA",UC.ParentObject.AV17XT_DefindcodeTypeIDTitleFilterData); });
   DDO_XT_DEFINDCODETYPEIDContainer.setProp("Visible", "Visible", true, "bool");
   DDO_XT_DEFINDCODETYPEIDContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_XT_DEFINDCODETYPEIDContainer.addEventHandler("OnOptionClicked", this.e152h2_client);
   this.setUserControl(DDO_XT_DEFINDCODETYPEIDContainer);
   this.DDO_XT_DEFINDCODETYPENAMEContainer = gx.uc.getNew(this, 32, 27, "BootstrapDropDownOptions", "DDO_XT_DEFINDCODETYPENAMEContainer", "Ddo_xt_defindcodetypename", "DDO_XT_DEFINDCODETYPENAME");
   var DDO_XT_DEFINDCODETYPENAMEContainer = this.DDO_XT_DEFINDCODETYPENAMEContainer;
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("Class", "Class", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("Icon", "Icon", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("Caption", "Caption", "", "str");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_XT_DEFINDCODETYPENAMEContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_XT_DEFINDCODETYPENAMEContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_XT_DEFINDCODETYPENAMEContainer.addV2CFunction('AV21DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_XT_DEFINDCODETYPENAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV21DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV21DDO_TitleSettingsIcons); });
   DDO_XT_DEFINDCODETYPENAMEContainer.addV2CFunction('AV19XT_DefindcodeTypeNameTitleFilterData', "vXT_DEFINDCODETYPENAMETITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_XT_DEFINDCODETYPENAMEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV19XT_DefindcodeTypeNameTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vXT_DEFINDCODETYPENAMETITLEFILTERDATA",UC.ParentObject.AV19XT_DefindcodeTypeNameTitleFilterData); });
   DDO_XT_DEFINDCODETYPENAMEContainer.setProp("Visible", "Visible", true, "bool");
   DDO_XT_DEFINDCODETYPENAMEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_XT_DEFINDCODETYPENAMEContainer.addEventHandler("OnOptionClicked", this.e162h2_client);
   this.setUserControl(DDO_XT_DEFINDCODETYPENAMEContainer);
   this.DDO_XT_DEFINECODEORDERContainer = gx.uc.getNew(this, 34, 27, "BootstrapDropDownOptions", "DDO_XT_DEFINECODEORDERContainer", "Ddo_xt_definecodeorder", "DDO_XT_DEFINECODEORDER");
   var DDO_XT_DEFINECODEORDERContainer = this.DDO_XT_DEFINECODEORDERContainer;
   DDO_XT_DEFINECODEORDERContainer.setProp("Class", "Class", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_XT_DEFINECODEORDERContainer.setProp("Icon", "Icon", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("Caption", "Caption", "", "str");
   DDO_XT_DEFINECODEORDERContainer.setProp("Tooltip", "Tooltip", "WWP_TSColumnOptions", "str");
   DDO_XT_DEFINECODEORDERContainer.setProp("Cls", "Cls", "ColumnSettings", "str");
   DDO_XT_DEFINECODEORDERContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_XT_DEFINECODEORDERContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "GridTitleSettings", "str");
   DDO_XT_DEFINECODEORDERContainer.setDynProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_XT_DEFINECODEORDERContainer.setProp("IncludeSortASC", "Includesortasc", true, "bool");
   DDO_XT_DEFINECODEORDERContainer.setProp("IncludeSortDSC", "Includesortdsc", true, "bool");
   DDO_XT_DEFINECODEORDERContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("IncludeFilter", "Includefilter", false, "bool");
   DDO_XT_DEFINECODEORDERContainer.setProp("FilterType", "Filtertype", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("FilterIsRange", "Filterisrange", false, "boolean");
   DDO_XT_DEFINECODEORDERContainer.setProp("IncludeDataList", "Includedatalist", false, "bool");
   DDO_XT_DEFINECODEORDERContainer.setProp("DataListType", "Datalisttype", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", false, "boolean");
   DDO_XT_DEFINECODEORDERContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("DataListProc", "Datalistproc", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", '', "int");
   DDO_XT_DEFINECODEORDERContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_XT_DEFINECODEORDERContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("ColumnsSelectorValues", "Columnsselectorvalues", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("SortASC", "Sortasc", "WWP_TSSortASC", "str");
   DDO_XT_DEFINECODEORDERContainer.setProp("SortDSC", "Sortdsc", "WWP_TSSortDSC", "str");
   DDO_XT_DEFINECODEORDERContainer.setProp("LoadingData", "Loadingdata", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("CleanFilter", "Cleanfilter", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("RangeFilterTo", "Rangefilterto", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("NoResultsFound", "Noresultsfound", "", "char");
   DDO_XT_DEFINECODEORDERContainer.setProp("SearchButtonText", "Searchbuttontext", "WWP_TSSearchButtonCaption", "str");
   DDO_XT_DEFINECODEORDERContainer.setProp("UpdateButtonText", "Updatebuttontext", "Update", "str");
   DDO_XT_DEFINECODEORDERContainer.addV2CFunction('AV21DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_XT_DEFINECODEORDERContainer.addC2VFunction(function(UC) { UC.ParentObject.AV21DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV21DDO_TitleSettingsIcons); });
   DDO_XT_DEFINECODEORDERContainer.addV2CFunction('AV27XT_DefineCodeOrderTitleFilterData', "vXT_DEFINECODEORDERTITLEFILTERDATA", 'SetDropDownOptionsData');
   DDO_XT_DEFINECODEORDERContainer.addC2VFunction(function(UC) { UC.ParentObject.AV27XT_DefineCodeOrderTitleFilterData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vXT_DEFINECODEORDERTITLEFILTERDATA",UC.ParentObject.AV27XT_DefineCodeOrderTitleFilterData); });
   DDO_XT_DEFINECODEORDERContainer.setProp("Visible", "Visible", true, "bool");
   DDO_XT_DEFINECODEORDERContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_XT_DEFINECODEORDERContainer.addEventHandler("OnOptionClicked", this.e172h2_client);
   this.setUserControl(DDO_XT_DEFINECODEORDERContainer);
   this.WORKWITHPLUSUTILITIES1Container = gx.uc.getNew(this, 36, 27, "DVelop_WorkWithPlusUtilities", "WORKWITHPLUSUTILITIES1Container", "Workwithplusutilities1", "WORKWITHPLUSUTILITIES1");
   var WORKWITHPLUSUTILITIES1Container = this.WORKWITHPLUSUTILITIES1Container;
   WORKWITHPLUSUTILITIES1Container.setProp("Class", "Class", "", "char");
   WORKWITHPLUSUTILITIES1Container.setProp("Enabled", "Enabled", true, "boolean");
   WORKWITHPLUSUTILITIES1Container.setProp("Width", "Width", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Height", "Height", "100", "str");
   WORKWITHPLUSUTILITIES1Container.setProp("Visible", "Visible", true, "bool");
   WORKWITHPLUSUTILITIES1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(WORKWITHPLUSUTILITIES1Container);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEMAIN",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"GRIDTABLEWITHPAGINATIONBAR",grid:0};
   GXValidFnc[10]={ id: 10, fld:"",grid:0};
   GXValidFnc[11]={ id: 11, fld:"",grid:0};
   GXValidFnc[13]={ id:13 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vSELECT",gxz:"ZV26Select",gxold:"OV26Select",gxvar:"AV26Select",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV26Select=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV26Select=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vSELECT",row || gx.fn.currentGridRowImpl(12),gx.O.AV26Select,gx.O.AV32Select_GXI)},c2v:function(){gx.O.AV32Select_GXI=this.val_GXI();if(this.val()!==undefined)gx.O.AV26Select=this.val()},val:function(row){return gx.fn.getGridControlValue("vSELECT",row || gx.fn.currentGridRowImpl(12))},val_GXI:function(row){return gx.fn.getGridControlValue("vSELECT_GXI",row || gx.fn.currentGridRowImpl(12))}, gxvar_GXI:'AV32Select_GXI',nac:gx.falseFn,evt:"e212h2_client",std:"ENTER"};
   GXValidFnc[14]={ id:14 ,lvl:2,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"XT_DEFINECODEID",gxz:"Z167XT_DefineCodeID",gxold:"O167XT_DefineCodeID",gxvar:"A167XT_DefineCodeID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A167XT_DefineCodeID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z167XT_DefineCodeID=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("XT_DEFINECODEID",row || gx.fn.currentGridRowImpl(12),gx.O.A167XT_DefineCodeID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A167XT_DefineCodeID=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("XT_DEFINECODEID",row || gx.fn.currentGridRowImpl(12),',')},nac:gx.falseFn};
   GXValidFnc[15]={ id:15 ,lvl:2,type:"svchar",len:100,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"XT_DEFINECODENAME",gxz:"Z168XT_DefineCodeName",gxold:"O168XT_DefineCodeName",gxvar:"A168XT_DefineCodeName",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A168XT_DefineCodeName=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z168XT_DefineCodeName=Value},v2c:function(row){gx.fn.setGridControlValue("XT_DEFINECODENAME",row || gx.fn.currentGridRowImpl(12),gx.O.A168XT_DefineCodeName,0)},c2v:function(){if(this.val()!==undefined)gx.O.A168XT_DefineCodeName=this.val()},val:function(row){return gx.fn.getGridControlValue("XT_DEFINECODENAME",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn};
   GXValidFnc[16]={ id:16 ,lvl:2,type:"int",len:18,dec:0,sign:false,pic:"ZZZZZZZZZZZZZZZZZZ",ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:this.Valid_Xt_defindcodetypeid,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"XT_DEFINDCODETYPEID",gxz:"Z165XT_DefindcodeTypeID",gxold:"O165XT_DefindcodeTypeID",gxvar:"A165XT_DefindcodeTypeID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A165XT_DefindcodeTypeID=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z165XT_DefindcodeTypeID=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("XT_DEFINDCODETYPEID",row || gx.fn.currentGridRowImpl(12),gx.O.A165XT_DefindcodeTypeID,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.A165XT_DefindcodeTypeID=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("XT_DEFINDCODETYPEID",row || gx.fn.currentGridRowImpl(12),',')},nac:gx.falseFn};
   GXValidFnc[17]={ id:17 ,lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"XT_DEFINDCODETYPENAME",gxz:"Z166XT_DefindcodeTypeName",gxold:"O166XT_DefindcodeTypeName",gxvar:"A166XT_DefindcodeTypeName",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A166XT_DefindcodeTypeName=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z166XT_DefindcodeTypeName=Value},v2c:function(row){gx.fn.setGridControlValue("XT_DEFINDCODETYPENAME",row || gx.fn.currentGridRowImpl(12),gx.O.A166XT_DefindcodeTypeName,0)},c2v:function(){if(this.val()!==undefined)gx.O.A166XT_DefindcodeTypeName=this.val()},val:function(row){return gx.fn.getGridControlValue("XT_DEFINDCODETYPENAME",row || gx.fn.currentGridRowImpl(12))},nac:gx.falseFn};
   GXValidFnc[18]={ id:18 ,lvl:2,type:"int",len:4,dec:0,sign:false,pic:"ZZZZ",ro:1,isacc:0,grid:12,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"XT_DEFINECODEORDER",gxz:"Z171XT_DefineCodeOrder",gxold:"O171XT_DefineCodeOrder",gxvar:"A171XT_DefineCodeOrder",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A171XT_DefineCodeOrder=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z171XT_DefineCodeOrder=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("XT_DEFINECODEORDER",row || gx.fn.currentGridRowImpl(12),gx.O.A171XT_DefineCodeOrder,0)},c2v:function(){if(this.val()!==undefined)gx.O.A171XT_DefineCodeOrder=gx.num.intval(this.val())},val:function(row){return gx.fn.getGridIntegerValue("XT_DEFINECODEORDER",row || gx.fn.currentGridRowImpl(12),',')},nac:gx.falseFn};
   GXValidFnc[19]={ id: 19, fld:"",grid:0};
   GXValidFnc[20]={ id: 20, fld:"",grid:0};
   GXValidFnc[21]={ id: 21, fld:"HTML_GRIDPAGINATIONBAR",grid:0};
   GXValidFnc[23]={ id: 23, fld:"",grid:0};
   GXValidFnc[24]={ id: 24, fld:"",grid:0};
   GXValidFnc[25]={ id: 25, fld:"HTML_BOTTOMAUXILIARCONTROLS",grid:0};
   GXValidFnc[27]={ id:27 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_XT_DEFINECODEIDTITLECONTROLIDTOREPLACE",gxz:"ZV14ddo_XT_DefineCodeIDTitleControlIdToReplace",gxold:"OV14ddo_XT_DefineCodeIDTitleControlIdToReplace",gxvar:"AV14ddo_XT_DefineCodeIDTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV14ddo_XT_DefineCodeIDTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV14ddo_XT_DefineCodeIDTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_XT_DEFINECODEIDTITLECONTROLIDTOREPLACE",gx.O.AV14ddo_XT_DefineCodeIDTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV14ddo_XT_DefineCodeIDTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_XT_DEFINECODEIDTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[29]={ id:29 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_XT_DEFINECODENAMETITLECONTROLIDTOREPLACE",gxz:"ZV16ddo_XT_DefineCodeNameTitleControlIdToReplace",gxold:"OV16ddo_XT_DefineCodeNameTitleControlIdToReplace",gxvar:"AV16ddo_XT_DefineCodeNameTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV16ddo_XT_DefineCodeNameTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV16ddo_XT_DefineCodeNameTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_XT_DEFINECODENAMETITLECONTROLIDTOREPLACE",gx.O.AV16ddo_XT_DefineCodeNameTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV16ddo_XT_DefineCodeNameTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_XT_DEFINECODENAMETITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[31]={ id:31 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_XT_DEFINDCODETYPEIDTITLECONTROLIDTOREPLACE",gxz:"ZV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace",gxold:"OV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace",gxvar:"AV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_XT_DEFINDCODETYPEIDTITLECONTROLIDTOREPLACE",gx.O.AV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_XT_DEFINDCODETYPEIDTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[33]={ id:33 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_XT_DEFINDCODETYPENAMETITLECONTROLIDTOREPLACE",gxz:"ZV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace",gxold:"OV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace",gxvar:"AV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_XT_DEFINDCODETYPENAMETITLECONTROLIDTOREPLACE",gx.O.AV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_XT_DEFINDCODETYPENAMETITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[35]={ id:35 ,lvl:0,type:"svchar",len:300,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDDO_XT_DEFINECODEORDERTITLECONTROLIDTOREPLACE",gxz:"ZV28ddo_XT_DefineCodeOrderTitleControlIdToReplace",gxold:"OV28ddo_XT_DefineCodeOrderTitleControlIdToReplace",gxvar:"AV28ddo_XT_DefineCodeOrderTitleControlIdToReplace",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV28ddo_XT_DefineCodeOrderTitleControlIdToReplace=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV28ddo_XT_DefineCodeOrderTitleControlIdToReplace=Value},v2c:function(){gx.fn.setControlValue("vDDO_XT_DEFINECODEORDERTITLECONTROLIDTOREPLACE",gx.O.AV28ddo_XT_DefineCodeOrderTitleControlIdToReplace,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV28ddo_XT_DefineCodeOrderTitleControlIdToReplace=this.val()},val:function(){return gx.fn.getControlValue("vDDO_XT_DEFINECODEORDERTITLECONTROLIDTOREPLACE")},nac:gx.falseFn};
   GXValidFnc[37]={ id:37 ,lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDBY",gxz:"ZV11OrderedBy",gxold:"OV11OrderedBy",gxvar:"AV11OrderedBy",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV11OrderedBy=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV11OrderedBy=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDBY",gx.O.AV11OrderedBy,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV11OrderedBy=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vORDEREDBY",',')},nac:gx.falseFn};
   GXValidFnc[38]={ id:38 ,lvl:0,type:"boolean",len:4,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vORDEREDDSC",gxz:"ZV12OrderedDsc",gxold:"OV12OrderedDsc",gxvar:"AV12OrderedDsc",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV12OrderedDsc=gx.lang.booleanValue(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV12OrderedDsc=gx.lang.booleanValue(Value)},v2c:function(){gx.fn.setControlValue("vORDEREDDSC",gx.O.AV12OrderedDsc,0)},c2v:function(){if(this.val()!==undefined)gx.O.AV12OrderedDsc=gx.lang.booleanValue(this.val())},val:function(){return gx.fn.getControlValue("vORDEREDDSC")},nac:gx.falseFn};
   this.ZV26Select = "" ;
   this.OV26Select = "" ;
   this.Z167XT_DefineCodeID = 0 ;
   this.O167XT_DefineCodeID = 0 ;
   this.Z168XT_DefineCodeName = "" ;
   this.O168XT_DefineCodeName = "" ;
   this.Z165XT_DefindcodeTypeID = 0 ;
   this.O165XT_DefindcodeTypeID = 0 ;
   this.Z166XT_DefindcodeTypeName = "" ;
   this.O166XT_DefindcodeTypeName = "" ;
   this.Z171XT_DefineCodeOrder = 0 ;
   this.O171XT_DefineCodeOrder = 0 ;
   this.AV14ddo_XT_DefineCodeIDTitleControlIdToReplace = "" ;
   this.ZV14ddo_XT_DefineCodeIDTitleControlIdToReplace = "" ;
   this.OV14ddo_XT_DefineCodeIDTitleControlIdToReplace = "" ;
   this.AV16ddo_XT_DefineCodeNameTitleControlIdToReplace = "" ;
   this.ZV16ddo_XT_DefineCodeNameTitleControlIdToReplace = "" ;
   this.OV16ddo_XT_DefineCodeNameTitleControlIdToReplace = "" ;
   this.AV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace = "" ;
   this.ZV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace = "" ;
   this.OV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace = "" ;
   this.AV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace = "" ;
   this.ZV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace = "" ;
   this.OV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace = "" ;
   this.AV28ddo_XT_DefineCodeOrderTitleControlIdToReplace = "" ;
   this.ZV28ddo_XT_DefineCodeOrderTitleControlIdToReplace = "" ;
   this.OV28ddo_XT_DefineCodeOrderTitleControlIdToReplace = "" ;
   this.AV11OrderedBy = 0 ;
   this.ZV11OrderedBy = 0 ;
   this.OV11OrderedBy = 0 ;
   this.AV12OrderedDsc = false ;
   this.ZV12OrderedDsc = false ;
   this.OV12OrderedDsc = false ;
   this.AV23GridCurrentPage = 0 ;
   this.AV21DDO_TitleSettingsIcons = {Default:"",Default_GXI:"",Filtered:"",Filtered_GXI:"",SortedASC:"",SortedASC_GXI:"",SortedDSC:"",SortedDSC_GXI:"",FilteredSortedASC:"",FilteredSortedASC_GXI:"",FilteredSortedDSC:"",FilteredSortedDSC_GXI:"",OptionSortASC:"",OptionSortASC_GXI:"",OptionSortDSC:"",OptionSortDSC_GXI:"",OptionApplyFilter:"",OptionApplyFilter_GXI:"",OptionFilteringData:"",OptionFilteringData_GXI:"",OptionCleanFilters:"",OptionCleanFilters_GXI:"",SelectedOption:"",SelectedOption_GXI:"",MultiselOption:"",MultiselOption_GXI:"",MultiselSelOption:"",MultiselSelOption_GXI:""} ;
   this.AV14ddo_XT_DefineCodeIDTitleControlIdToReplace = "" ;
   this.AV16ddo_XT_DefineCodeNameTitleControlIdToReplace = "" ;
   this.AV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace = "" ;
   this.AV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace = "" ;
   this.AV28ddo_XT_DefineCodeOrderTitleControlIdToReplace = "" ;
   this.AV11OrderedBy = 0 ;
   this.AV12OrderedDsc = false ;
   this.AV8InOutXT_DefineCodeID = 0 ;
   this.AV9InOutXT_DefineCodeName = "" ;
   this.AV26Select = "" ;
   this.A167XT_DefineCodeID = 0 ;
   this.A168XT_DefineCodeName = "" ;
   this.A165XT_DefindcodeTypeID = 0 ;
   this.A166XT_DefindcodeTypeName = "" ;
   this.A171XT_DefineCodeOrder = 0 ;
   this.Events = {"e112h2_client": ["GRIDPAGINATIONBAR.CHANGEPAGE", true] ,"e122h2_client": ["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", true] ,"e132h2_client": ["DDO_XT_DEFINECODEID.ONOPTIONCLICKED", true] ,"e142h2_client": ["DDO_XT_DEFINECODENAME.ONOPTIONCLICKED", true] ,"e152h2_client": ["DDO_XT_DEFINDCODETYPEID.ONOPTIONCLICKED", true] ,"e162h2_client": ["DDO_XT_DEFINDCODETYPENAME.ONOPTIONCLICKED", true] ,"e172h2_client": ["DDO_XT_DEFINECODEORDER.ONOPTIONCLICKED", true] ,"e212h2_client": ["ENTER", true] ,"e222h2_client": ["CANCEL", true]};
   this.EvtParms["REFRESH"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_XT_DefineCodeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_XT_DefineCodeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_XT_DefineCodeOrderTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEORDERTITLECONTROLIDTOREPLACE',pic:''},{ctrl:'GRID',prop:'Rows'}],[{av:'AV13XT_DefineCodeIDTitleFilterData',fld:'vXT_DEFINECODEIDTITLEFILTERDATA',pic:''},{av:'AV15XT_DefineCodeNameTitleFilterData',fld:'vXT_DEFINECODENAMETITLEFILTERDATA',pic:''},{av:'AV17XT_DefindcodeTypeIDTitleFilterData',fld:'vXT_DEFINDCODETYPEIDTITLEFILTERDATA',pic:''},{av:'AV19XT_DefindcodeTypeNameTitleFilterData',fld:'vXT_DEFINDCODETYPENAMETITLEFILTERDATA',pic:''},{av:'AV27XT_DefineCodeOrderTitleFilterData',fld:'vXT_DEFINECODEORDERTITLEFILTERDATA',pic:''},{ctrl:'XT_DEFINECODEID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("XT_DEFINECODEID","Title")',ctrl:'XT_DEFINECODEID',prop:'Title'},{ctrl:'XT_DEFINECODENAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("XT_DEFINECODENAME","Title")',ctrl:'XT_DEFINECODENAME',prop:'Title'},{ctrl:'XT_DEFINDCODETYPEID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINDCODETYPEID","Title")',ctrl:'XT_DEFINDCODETYPEID',prop:'Title'},{ctrl:'XT_DEFINDCODETYPENAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINDCODETYPENAME","Title")',ctrl:'XT_DEFINDCODETYPENAME',prop:'Title'},{ctrl:'XT_DEFINECODEORDER',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINECODEORDER","Title")',ctrl:'XT_DEFINECODEORDER',prop:'Title'},{av:'AV23GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV24GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV25GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["START"] = [[{av:'AV31Pgmname',fld:'vPGMNAME',pic:''},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'}],[{av:'gx.fn.getCtrlProperty("TABLEMAIN","Height")',ctrl:'TABLEMAIN',prop:'Height'},{ctrl:'GRID',prop:'Rows'},{av:'this.DDO_XT_DEFINECODEIDContainer.TitleControlIdToReplace',ctrl:'DDO_XT_DEFINECODEID',prop:'TitleControlIdToReplace'},{av:'AV14ddo_XT_DefineCodeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_XT_DEFINECODEIDTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_XT_DEFINECODEIDTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_XT_DEFINECODENAMEContainer.TitleControlIdToReplace',ctrl:'DDO_XT_DEFINECODENAME',prop:'TitleControlIdToReplace'},{av:'AV16ddo_XT_DefineCodeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_XT_DEFINECODENAMETITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_XT_DEFINECODENAMETITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_XT_DEFINDCODETYPEIDContainer.TitleControlIdToReplace',ctrl:'DDO_XT_DEFINDCODETYPEID',prop:'TitleControlIdToReplace'},{av:'AV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_XT_DEFINDCODETYPEIDTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_XT_DEFINDCODETYPEIDTITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_XT_DEFINDCODETYPENAMEContainer.TitleControlIdToReplace',ctrl:'DDO_XT_DEFINDCODETYPENAME',prop:'TitleControlIdToReplace'},{av:'AV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_XT_DEFINDCODETYPENAMETITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_XT_DEFINDCODETYPENAMETITLECONTROLIDTOREPLACE',prop:'Visible'},{av:'this.DDO_XT_DEFINECODEORDERContainer.TitleControlIdToReplace',ctrl:'DDO_XT_DEFINECODEORDER',prop:'TitleControlIdToReplace'},{av:'AV28ddo_XT_DefineCodeOrderTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEORDERTITLECONTROLIDTOREPLACE',pic:''},{av:'gx.fn.getCtrlProperty("vDDO_XT_DEFINECODEORDERTITLECONTROLIDTOREPLACE","Visible")',ctrl:'vDDO_XT_DEFINECODEORDERTITLECONTROLIDTOREPLACE',prop:'Visible'},{ctrl:'FORM',prop:'Caption'},{av:'gx.fn.getCtrlProperty("vORDEREDBY","Visible")',ctrl:'vORDEREDBY',prop:'Visible'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'gx.fn.getCtrlProperty("vORDEREDDSC","Visible")',ctrl:'vORDEREDDSC',prop:'Visible'},{av:'AV21DDO_TitleSettingsIcons',fld:'vDDO_TITLESETTINGSICONS',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_XT_DefineCodeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_XT_DefineCodeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_XT_DefineCodeOrderTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEORDERTITLECONTROLIDTOREPLACE',pic:''},{av:'this.GRIDPAGINATIONBARContainer.SelectedPage',ctrl:'GRIDPAGINATIONBAR',prop:'SelectedPage'}],[]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_XT_DefineCodeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_XT_DefineCodeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_XT_DefineCodeOrderTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEORDERTITLECONTROLIDTOREPLACE',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}],[{ctrl:'GRID',prop:'Rows'}]];
   this.EvtParms["DDO_XT_DEFINECODEID.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_XT_DefineCodeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_XT_DefineCodeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_XT_DefineCodeOrderTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEORDERTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_XT_DEFINECODEIDContainer.ActiveEventKey',ctrl:'DDO_XT_DEFINECODEID',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_XT_DEFINECODEIDContainer.SortedStatus',ctrl:'DDO_XT_DEFINECODEID',prop:'SortedStatus'},{av:'AV13XT_DefineCodeIDTitleFilterData',fld:'vXT_DEFINECODEIDTITLEFILTERDATA',pic:''},{av:'AV15XT_DefineCodeNameTitleFilterData',fld:'vXT_DEFINECODENAMETITLEFILTERDATA',pic:''},{av:'AV17XT_DefindcodeTypeIDTitleFilterData',fld:'vXT_DEFINDCODETYPEIDTITLEFILTERDATA',pic:''},{av:'AV19XT_DefindcodeTypeNameTitleFilterData',fld:'vXT_DEFINDCODETYPENAMETITLEFILTERDATA',pic:''},{av:'AV27XT_DefineCodeOrderTitleFilterData',fld:'vXT_DEFINECODEORDERTITLEFILTERDATA',pic:''},{ctrl:'XT_DEFINECODEID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("XT_DEFINECODEID","Title")',ctrl:'XT_DEFINECODEID',prop:'Title'},{ctrl:'XT_DEFINECODENAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("XT_DEFINECODENAME","Title")',ctrl:'XT_DEFINECODENAME',prop:'Title'},{ctrl:'XT_DEFINDCODETYPEID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINDCODETYPEID","Title")',ctrl:'XT_DEFINDCODETYPEID',prop:'Title'},{ctrl:'XT_DEFINDCODETYPENAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINDCODETYPENAME","Title")',ctrl:'XT_DEFINDCODETYPENAME',prop:'Title'},{ctrl:'XT_DEFINECODEORDER',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINECODEORDER","Title")',ctrl:'XT_DEFINECODEORDER',prop:'Title'},{av:'AV23GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV24GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV25GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_XT_DEFINECODENAME.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_XT_DefineCodeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_XT_DefineCodeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_XT_DefineCodeOrderTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEORDERTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_XT_DEFINECODENAMEContainer.ActiveEventKey',ctrl:'DDO_XT_DEFINECODENAME',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_XT_DEFINECODENAMEContainer.SortedStatus',ctrl:'DDO_XT_DEFINECODENAME',prop:'SortedStatus'},{av:'AV13XT_DefineCodeIDTitleFilterData',fld:'vXT_DEFINECODEIDTITLEFILTERDATA',pic:''},{av:'AV15XT_DefineCodeNameTitleFilterData',fld:'vXT_DEFINECODENAMETITLEFILTERDATA',pic:''},{av:'AV17XT_DefindcodeTypeIDTitleFilterData',fld:'vXT_DEFINDCODETYPEIDTITLEFILTERDATA',pic:''},{av:'AV19XT_DefindcodeTypeNameTitleFilterData',fld:'vXT_DEFINDCODETYPENAMETITLEFILTERDATA',pic:''},{av:'AV27XT_DefineCodeOrderTitleFilterData',fld:'vXT_DEFINECODEORDERTITLEFILTERDATA',pic:''},{ctrl:'XT_DEFINECODEID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("XT_DEFINECODEID","Title")',ctrl:'XT_DEFINECODEID',prop:'Title'},{ctrl:'XT_DEFINECODENAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("XT_DEFINECODENAME","Title")',ctrl:'XT_DEFINECODENAME',prop:'Title'},{ctrl:'XT_DEFINDCODETYPEID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINDCODETYPEID","Title")',ctrl:'XT_DEFINDCODETYPEID',prop:'Title'},{ctrl:'XT_DEFINDCODETYPENAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINDCODETYPENAME","Title")',ctrl:'XT_DEFINDCODETYPENAME',prop:'Title'},{ctrl:'XT_DEFINECODEORDER',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINECODEORDER","Title")',ctrl:'XT_DEFINECODEORDER',prop:'Title'},{av:'AV23GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV24GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV25GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_XT_DEFINDCODETYPEID.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_XT_DefineCodeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_XT_DefineCodeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_XT_DefineCodeOrderTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEORDERTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_XT_DEFINDCODETYPEIDContainer.ActiveEventKey',ctrl:'DDO_XT_DEFINDCODETYPEID',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_XT_DEFINDCODETYPEIDContainer.SortedStatus',ctrl:'DDO_XT_DEFINDCODETYPEID',prop:'SortedStatus'},{av:'AV13XT_DefineCodeIDTitleFilterData',fld:'vXT_DEFINECODEIDTITLEFILTERDATA',pic:''},{av:'AV15XT_DefineCodeNameTitleFilterData',fld:'vXT_DEFINECODENAMETITLEFILTERDATA',pic:''},{av:'AV17XT_DefindcodeTypeIDTitleFilterData',fld:'vXT_DEFINDCODETYPEIDTITLEFILTERDATA',pic:''},{av:'AV19XT_DefindcodeTypeNameTitleFilterData',fld:'vXT_DEFINDCODETYPENAMETITLEFILTERDATA',pic:''},{av:'AV27XT_DefineCodeOrderTitleFilterData',fld:'vXT_DEFINECODEORDERTITLEFILTERDATA',pic:''},{ctrl:'XT_DEFINECODEID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("XT_DEFINECODEID","Title")',ctrl:'XT_DEFINECODEID',prop:'Title'},{ctrl:'XT_DEFINECODENAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("XT_DEFINECODENAME","Title")',ctrl:'XT_DEFINECODENAME',prop:'Title'},{ctrl:'XT_DEFINDCODETYPEID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINDCODETYPEID","Title")',ctrl:'XT_DEFINDCODETYPEID',prop:'Title'},{ctrl:'XT_DEFINDCODETYPENAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINDCODETYPENAME","Title")',ctrl:'XT_DEFINDCODETYPENAME',prop:'Title'},{ctrl:'XT_DEFINECODEORDER',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINECODEORDER","Title")',ctrl:'XT_DEFINECODEORDER',prop:'Title'},{av:'AV23GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV24GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV25GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_XT_DEFINDCODETYPENAME.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_XT_DefineCodeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_XT_DefineCodeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_XT_DefineCodeOrderTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEORDERTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_XT_DEFINDCODETYPENAMEContainer.ActiveEventKey',ctrl:'DDO_XT_DEFINDCODETYPENAME',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_XT_DEFINDCODETYPENAMEContainer.SortedStatus',ctrl:'DDO_XT_DEFINDCODETYPENAME',prop:'SortedStatus'},{av:'AV13XT_DefineCodeIDTitleFilterData',fld:'vXT_DEFINECODEIDTITLEFILTERDATA',pic:''},{av:'AV15XT_DefineCodeNameTitleFilterData',fld:'vXT_DEFINECODENAMETITLEFILTERDATA',pic:''},{av:'AV17XT_DefindcodeTypeIDTitleFilterData',fld:'vXT_DEFINDCODETYPEIDTITLEFILTERDATA',pic:''},{av:'AV19XT_DefindcodeTypeNameTitleFilterData',fld:'vXT_DEFINDCODETYPENAMETITLEFILTERDATA',pic:''},{av:'AV27XT_DefineCodeOrderTitleFilterData',fld:'vXT_DEFINECODEORDERTITLEFILTERDATA',pic:''},{ctrl:'XT_DEFINECODEID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("XT_DEFINECODEID","Title")',ctrl:'XT_DEFINECODEID',prop:'Title'},{ctrl:'XT_DEFINECODENAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("XT_DEFINECODENAME","Title")',ctrl:'XT_DEFINECODENAME',prop:'Title'},{ctrl:'XT_DEFINDCODETYPEID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINDCODETYPEID","Title")',ctrl:'XT_DEFINDCODETYPEID',prop:'Title'},{ctrl:'XT_DEFINDCODETYPENAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINDCODETYPENAME","Title")',ctrl:'XT_DEFINDCODETYPENAME',prop:'Title'},{ctrl:'XT_DEFINECODEORDER',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINECODEORDER","Title")',ctrl:'XT_DEFINECODEORDER',prop:'Title'},{av:'AV23GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV24GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV25GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["DDO_XT_DEFINECODEORDER.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV14ddo_XT_DefineCodeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV16ddo_XT_DefineCodeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV18ddo_XT_DefindcodeTypeIDTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPEIDTITLECONTROLIDTOREPLACE',pic:''},{av:'AV20ddo_XT_DefindcodeTypeNameTitleControlIdToReplace',fld:'vDDO_XT_DEFINDCODETYPENAMETITLECONTROLIDTOREPLACE',pic:''},{av:'AV28ddo_XT_DefineCodeOrderTitleControlIdToReplace',fld:'vDDO_XT_DEFINECODEORDERTITLECONTROLIDTOREPLACE',pic:''},{av:'this.DDO_XT_DEFINECODEORDERContainer.ActiveEventKey',ctrl:'DDO_XT_DEFINECODEORDER',prop:'ActiveEventKey'}],[{av:'AV11OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV12OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'this.DDO_XT_DEFINECODEORDERContainer.SortedStatus',ctrl:'DDO_XT_DEFINECODEORDER',prop:'SortedStatus'},{av:'AV13XT_DefineCodeIDTitleFilterData',fld:'vXT_DEFINECODEIDTITLEFILTERDATA',pic:''},{av:'AV15XT_DefineCodeNameTitleFilterData',fld:'vXT_DEFINECODENAMETITLEFILTERDATA',pic:''},{av:'AV17XT_DefindcodeTypeIDTitleFilterData',fld:'vXT_DEFINDCODETYPEIDTITLEFILTERDATA',pic:''},{av:'AV19XT_DefindcodeTypeNameTitleFilterData',fld:'vXT_DEFINDCODETYPENAMETITLEFILTERDATA',pic:''},{av:'AV27XT_DefineCodeOrderTitleFilterData',fld:'vXT_DEFINECODEORDERTITLEFILTERDATA',pic:''},{ctrl:'XT_DEFINECODEID',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("XT_DEFINECODEID","Title")',ctrl:'XT_DEFINECODEID',prop:'Title'},{ctrl:'XT_DEFINECODENAME',prop:'Titleformat',hsh:true},{av:'gx.fn.getCtrlProperty("XT_DEFINECODENAME","Title")',ctrl:'XT_DEFINECODENAME',prop:'Title'},{ctrl:'XT_DEFINDCODETYPEID',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINDCODETYPEID","Title")',ctrl:'XT_DEFINDCODETYPEID',prop:'Title'},{ctrl:'XT_DEFINDCODETYPENAME',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINDCODETYPENAME","Title")',ctrl:'XT_DEFINDCODETYPENAME',prop:'Title'},{ctrl:'XT_DEFINECODEORDER',prop:'Titleformat'},{av:'gx.fn.getCtrlProperty("XT_DEFINECODEORDER","Title")',ctrl:'XT_DEFINECODEORDER',prop:'Title'},{av:'AV23GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV24GridPageSize',fld:'vGRIDPAGESIZE',pic:'ZZZZZZZZZ9'},{av:'AV25GridRecordCount',fld:'vGRIDRECORDCOUNT',pic:'ZZZZZZZZZ9'}]];
   this.EvtParms["GRID.LOAD"] = [[],[{av:'AV26Select',fld:'vSELECT',pic:''},{av:'gx.fn.getCtrlProperty("vSELECT","Tooltiptext")',ctrl:'vSELECT',prop:'Tooltiptext'}]];
   this.EvtParms["ENTER"] = [[{av:'A167XT_DefineCodeID',fld:'XT_DEFINECODEID',pic:'ZZZZZZZZZZZZZZZZZZ',hsh:true},{av:'A168XT_DefineCodeName',fld:'XT_DEFINECODENAME',pic:'',hsh:true}],[{av:'AV8InOutXT_DefineCodeID',fld:'vINOUTXT_DEFINECODEID',pic:'ZZZZZZZZZZZZZZZZZZ'},{av:'AV9InOutXT_DefineCodeName',fld:'vINOUTXT_DEFINECODENAME',pic:''}]];
   this.EnterCtrl = ["vSELECT"];
   this.setVCMap("AV8InOutXT_DefineCodeID", "vINOUTXT_DEFINECODEID", 0, "int", 18, 0);
   this.setVCMap("AV9InOutXT_DefineCodeName", "vINOUTXT_DEFINECODENAME", 0, "svchar", 100, 0);
   GridContainer.addRefreshingVar(this.GXValidFnc[37]);
   GridContainer.addRefreshingVar(this.GXValidFnc[38]);
   GridContainer.addRefreshingVar(this.GXValidFnc[27]);
   GridContainer.addRefreshingVar(this.GXValidFnc[29]);
   GridContainer.addRefreshingVar(this.GXValidFnc[31]);
   GridContainer.addRefreshingVar(this.GXValidFnc[33]);
   GridContainer.addRefreshingVar(this.GXValidFnc[35]);
   this.Initialize( );
});
gx.createParentObj(xt_definecodeprompt);
